update MNT_Lookups set Description='Loss of Earning'  where Category='Trancomponent' and Description='LossofEarning'
update MNT_Lookups set Description='Cost of Repairs'  where Category='Trancomponent' and Description='CostofRepairs'
update MNT_Lookups set Description='Loss of Use'  where Category='Trancomponent' and Description='LossofUse'
update MNT_Lookups set Description='Loss of Use'  where Category='Trancomponent' and Description='LossofUseUn'
update MNT_Lookups set Description='Loss of Rental'  where Category='Trancomponent' and Description='LossofRental'
update MNT_Lookups set Description='Excess'  where Category='Trancomponent' and Description='Excess'
update MNT_Lookups set Description='Other Expenses'  where Category='Trancomponent' and Description='OtherExpenses'
update MNT_Lookups set Description='Report Fees'  where Category='Trancomponent' and Description='ReportFees'
update MNT_Lookups set Description='Survey Fee'  where Category='Trancomponent' and Description='SurveyFee'
update MNT_Lookups set Description='Re Survey Fee'  where Category='Trancomponent' and Description='ReSurveyFee'
update MNT_Lookups set Description='LGPolRep Fee'  where Category='Trancomponent' and Description='LGPolRepFee'
update MNT_Lookups set Description='Par LawCost 3rd'  where Category='Trancomponent' and Description='ParLawCost3rd'
update MNT_Lookups set Description='Par LawDisbursements 3rd'  where Category='Trancomponent' and Description='ParLawDisbursements3rd'
update MNT_Lookups set Description='Our Lawyer Cost'  where Category='Trancomponent' and Description='OurLawyerCost'
update MNT_Lookups set Description='Our LawDisbursements'  where Category='Trancomponent' and Description='OurLawDisbursements'
update MNT_Lookups set Description='General Damages'  where Category='Trancomponent' and Description='GeneralDamages'
update MNT_Lookups set Description='Medical Expenses'  where Category='Trancomponent' and Description='MedicalExpenses'
update MNT_Lookups set Description='FutureMedical Expenses'  where Category='Trancomponent' and Description='FutureMedicalExpenses'
update MNT_Lookups set Description='LOGMedical Expenses'  where Category='Trancomponent' and Description='LOGMedicalExpenses'
update MNT_Lookups set Description='Loss ofEarnings Capacity'  where Category='Trancomponent' and Description='LossofEarningsCapacity'
update MNT_Lookups set Description='Loss of Earnings'  where Category='Trancomponent' and Description='LossofEarnings'
update MNT_Lookups set Description='Loss of Future Earnings'  where Category='Trancomponent' and Description='LossofFutureEarnings'
update MNT_Lookups set Description='Transport'  where Category='Trancomponent' and Description='Transport'
update MNT_Lookups set Description='Medical Record'  where Category='Trancomponent' and Description='MedicalRecord'
update MNT_Lookups set Description='Public Trustee Fee'  where Category='Trancomponent' and Description='PublicTrusteeFee'
update MNT_Lookups set Description='Our Professional Expert Fee'  where Category='Trancomponent' and Description='OurProfessionalExpertFee'
update MNT_Lookups set Description='Rate Per Day'  where Category='Trancomponent' and Description='Rateperday'
update MNT_Lookups set Description='Total'  where Category='Trancomponent' and Description='Total'
update MNT_Lookups set Description='Sub Total'  where Category='Trancomponent' and Description='SubTotal'
update MNT_Lookups set Description='No of days'  where Category='Trancomponent' and Description='Noofdays'
update MNT_Lookups set Description='Liability'  where Category='Trancomponent' and Description='Liability'
