update MNT_Lookups set Lookupdesc='Loss of Earning', Description=  'LossofEarning' where Lookupvalue='LOE'
update MNT_Lookups set Lookupdesc='Cost of Repairs', Description=  'CostofRepairs' where Lookupvalue='COR'
update MNT_Lookups set Lookupdesc='Loss of Use', Description=  'LossofUse' where Lookupvalue='LOU'
update MNT_Lookups set Lookupdesc='Loss of Use', Description=  'LossofUseUn' where Lookupvalue='LOUUN'
update MNT_Lookups set Lookupdesc='Loss of Rental', Description=  'LossofRental' where Lookupvalue='LOR'
update MNT_Lookups set Lookupdesc='Excess', Description=  'Excess' where Lookupvalue='Ex'
update MNT_Lookups set Lookupdesc='Other Expenses', Description=  'OtherExpenses' where Lookupvalue='OE'
update MNT_Lookups set Lookupdesc='Report Fees', Description=  'ReportFees' where Lookupvalue='RE'
update MNT_Lookups set Lookupdesc='Survey Fee', Description=  'SurveyFee' where Lookupvalue='SF'
update MNT_Lookups set Lookupdesc='Re Survey Fee', Description=  'ReSurveyFee' where Lookupvalue='RSF'
update MNT_Lookups set Lookupdesc='LG Pol Rep Fee', Description=  'LGPolRepFee' where Lookupvalue='LPRF'
update MNT_Lookups set Lookupdesc='Par Law Cost', Description=  'ParLawCost3rd' where Lookupvalue='PLC'
update MNT_Lookups set Lookupdesc='Par Law Disbursements3rd', Description=  'ParLawDisbursements3rd' where Lookupvalue='PLD'
update MNT_Lookups set Lookupdesc='Our Lawyer Cost', Description=  'OurLawyerCost' where Lookupvalue='OLC'
update MNT_Lookups set Lookupdesc='Our Law Disbursements', Description=  'OurLawDisbursements' where Lookupvalue='OLD'
update MNT_Lookups set Lookupdesc='General Damages', Description=  'GeneralDamages' where Lookupvalue='GD'
update MNT_Lookups set Lookupdesc='Medical Expenses', Description=  'MedicalExpenses' where Lookupvalue='ME'
update MNT_Lookups set Lookupdesc='Future Medical Expenses', Description=  'FutureMedicalExpenses' where Lookupvalue='FME'
update MNT_Lookups set Lookupdesc='LOGMedical Expenses', Description=  'LOGMedicalExpenses' where Lookupvalue='LME'
update MNT_Lookups set Lookupdesc='Loss of Earnings Capacity', Description=  'LossofEarningsCapacity' where Lookupvalue='LEC'
update MNT_Lookups set Lookupdesc='Loss of Earnings', Description=  'LossofEarnings' where Lookupvalue='LOEAR'
update MNT_Lookups set Lookupdesc='Loss of Future Earnings', Description=  'LossofFutureEarnings' where Lookupvalue='LODE'
update MNT_Lookups set Lookupdesc='Transport', Description=  'Transport' where Lookupvalue='TRAN'
update MNT_Lookups set Lookupdesc='Medical Record', Description=  'MedicalRecord' where Lookupvalue='MR'
update MNT_Lookups set Lookupdesc='Public Trustee Fee', Description=  'PublicTrusteeFee' where Lookupvalue='PTF'
update MNT_Lookups set Lookupdesc='Our Professional Expert Fee', Description=  'OurProfessionalExpertFee' where Lookupvalue='OPEF'
update MNT_Lookups set Lookupdesc='Rate Per Day', Description=  'RatePerday' where Lookupvalue='RPD'
update MNT_Lookups set Lookupdesc='Total', Description=  'Total' where Lookupvalue='TOTAL'
update MNT_Lookups set Lookupdesc='Sub Total', Description=  'SubTotal' where Lookupvalue='SubTotal'
update MNT_Lookups set Lookupdesc='No of days', Description=  'Noofdays' where Lookupvalue='NOD'
update MNT_Lookups set Lookupdesc='Liability', Description=  'Liability' where Lookupvalue='Labl'
