CREATE TABLE [dbo].[Claim_Claimant](
	[ClaimantRefNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimRefNo] [nchar](21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CreateDate] [datetime] NULL CONSTRAINT [DF_Claim_Claimant_CreateDate]  DEFAULT (getdate()),
	[CreatedBy] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossLocation] [nchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossDescription] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossTypeCode] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossTypeDesc] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossNatureCode] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossNatureDesc] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantAddress] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CatastropheCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CatastropheDesc] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleRefNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VesselName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Recovery] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Adjuster] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RES_CurrencyCode] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_Claim_Claimant_EXP_CurrencyCode]  DEFAULT (''),
	[RES_ExchangeRate] [decimal](18, 9) NULL CONSTRAINT [DF_Claim_Claimant_EXP_ExchangeRate]  DEFAULT ((0)),
	[RES_ReserveLoc] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_EXP_ReserveLoc]  DEFAULT ((0)),
	[RES_ReserveFor] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_EXP_ReserveFor]  DEFAULT ((0)),
	[RES_NewLoc] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_ReserveLoc1]  DEFAULT ((0)),
	[RES_NewFor] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_ReserveLoc1_1]  DEFAULT ((0)),
	[AdjusterName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdjusterCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Surveyor] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SurveyorCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SurveyorName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SurveyLocation] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Garage] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GarageCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GarageName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GarageReceivedBy] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GarageEnterDate] [datetime] NULL,
	[Excess] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantDispNo] [numeric](18, 0) NULL,
	[Deductible] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ItemNo] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Consult] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UnlistGarage] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateDiary] [datetime] NULL,
	[DiaryDesc] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpExclusion] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecAmount] [decimal](18, 2) NULL,
	[DeductibleAmt] [decimal](18, 2) NULL,
	[TPClaimant] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountDescription] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountDescriptionDet] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DescCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RegNo1] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RegNo2] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RegNo3] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LnkClaimant] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdjusterNumber] [tinyint] NULL CONSTRAINT [DF_Claim_Claimant_AdjusterNumber]  DEFAULT ((1)),
	[SurveyorNumber] [tinyint] NULL CONSTRAINT [DF_Claim_Claimant_SurveyorNumber]  DEFAULT ((1)),
	[ConsultantNumber] [tinyint] NULL CONSTRAINT [DF_Claim_Claimant_ConsultantNumber]  DEFAULT ((1)),
	[StrClaimantDispNo]  AS (('CM'+replicate('0',(4)-len(CONVERT([varchar],[ClaimantDispNo],(0)))))+CONVERT([varchar],[ClaimantDispNo],(0))),
	[ClaimantType] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RES_BaseFor] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_BaseFor]  DEFAULT ((0)),
	[RES_BaseLoc] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_BaseLoc]  DEFAULT ((0)),
	[RES_NewBaseFor] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_NewBaseFor]  DEFAULT ((0)),
	[RES_NewBaseLoc] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_NewBaseLoc]  DEFAULT ((0)),
	[RES_TreatyFor] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_TreatyFor]  DEFAULT ((0)),
	[RES_TreatyLoc] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_TreatyLoc]  DEFAULT ((0)),
	[RES_NewTreatyFor] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_NewTreatyFor]  DEFAULT ((0)),
	[RES_NewTreatyLoc] [decimal](18, 2) NULL CONSTRAINT [DF_Claim_Claimant_RES_NewTreatyLoc]  DEFAULT ((0)),
	[CrestaCountry] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MoveDeductibleAmt] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Claim_Claimant] PRIMARY KEY NONCLUSTERED 
(
	[ClaimantRefNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


