CREATE TABLE [dbo].[Claim_Payment](
	[PaymentRefNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimRefNo] [nchar](21) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Status] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NOT NULL CONSTRAINT [DF_Claim_Payment_CreatedDate]  DEFAULT (getdate()),
	[CreateBy] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[isApprove] [int] NOT NULL CONSTRAINT [DF_Claim_Payment_PaymentStatus]  DEFAULT ((-10)),
	[ApproveDate] [datetime] NULL,
	[ApproveBy] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Type] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Category] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaymentType] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaymentCost] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaymentFee] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaymentDesc] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateIssue] [datetime] NULL,
	[PayeeName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PayeeCode] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PayeeAddress] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Reserve] [decimal](18, 2) NULL,
	[CurrencyCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExchangeRate] [numeric](18, 9) NULL,
	[NettAmountLoc] [decimal](18, 2) NULL,
	[NettAmountFor] [decimal](18, 2) NULL,
	[VAT] [decimal](18, 4) NULL,
	[AmountLoc] [decimal](18, 2) NULL,
	[AmountFor] [decimal](18, 2) NULL,
	[PaymentMode] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaymentDate] [datetime] NULL,
	[CashCall] [nchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_Claim_Payment_CashCall]  DEFAULT ('N'),
	[CashCallDesc] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ChequeResume] [nchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ChequeNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RefPaymentNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantStatus] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Beneficiary] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Bank] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Branch] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccountNo] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WHT] [decimal](18, 2) NULL,
	[AmountForDed] [decimal](18, 2) NULL,
	[AmountLocDed] [decimal](18, 2) NULL,
	[AmountForVAT] [decimal](18, 2) NULL,
	[AmountLocVAT] [decimal](18, 2) NULL,
	[PayeeCodeRef] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantPendingStatus] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[WorkShopRes] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServiceRes] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Suggestion] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Ben] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BankName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BBranch] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccNo] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SwiftCode] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PayDate] [datetime] NULL,
	[AmountForRec] [decimal](18, 2) NULL,
	[AmountLocRec] [decimal](18, 2) NULL,
	[XOLRefNo] [nvarchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GSTType] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GST] [decimal](18, 0) NULL,
	[PushToAccounts] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TotalAmountTreaty] [float] NULL,
 CONSTRAINT [PK_Claim_Payment] PRIMARY KEY NONCLUSTERED 
(
	[PaymentRefNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


