CREATE TABLE [dbo].[ClaimAccidentDetails](
	[AccidentClaimId] [int] IDENTITY(1,1) NOT NULL,
	[PolicyId] [int] NOT NULL,
	[IPNo] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimNo] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BusServiceNo] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleNo] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccidentDate] [datetime] NOT NULL,
	[AccidentTime] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ReportedDate] [datetime] NOT NULL,
	[Facts] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Damages] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateofFinding] [datetime] NULL,
	[InvestStatus] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Results] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BOIResults] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FinalLiability] [int] NULL,
	[DutyIO] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Make] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModelNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DriverEmployeeNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DriverName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DriverNRICNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DriverMobileNo] [numeric](18, 0) NULL,
	[InitialEstimate] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsurerClaim] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MandateReqd] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Organization] [int] NULL,
	[AccidentImage] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossTypeCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossNatureCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPClaimentStatus] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TimePeriod] [int] NULL,
	[BusCaptainFault] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ODAssignmentTranId] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPAssignmentTranId] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TempClaimNo] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedBy] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedDate] [datetime] NULL,
	[IsRecoveryOD] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccidentLoc] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ODStatus] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsRecoveryBI] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsComplete] [int] NULL CONSTRAINT [DF_ClaimAccidentDetails_IsComplete]  DEFAULT ('1'),
	[OperatingHours] [int] NULL,
	[IsReported] [bit] NULL,
	[ReportedRefId] [int] NULL,
	[DateJoined] [datetime] NULL,
	[DateResigned] [datetime] NULL,
	[Interchange] [int] NULL,
	[UploadReportNo] nvarchar(50) NULL,
	[IsReadOnly] [bit] NULL,
	[LinkedAccidentClaimId] [int] NULL,
	[Status] [nvarchar](50) NULL,
	[InitialLiability] [nvarchar](20) NULL,
	[CollisionType] [nvarchar](500) NULL,
 CONSTRAINT [PK_ClaimAccidentDetails] PRIMARY KEY CLUSTERED 
(
	[AccidentClaimId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


