CREATE TABLE [dbo].[CLM_Payment](
	[PaymentId] [int] IDENTITY(1,1) NOT NULL,
	[AccidentClaimId] [int] NOT NULL,
	[PolicyId] [int] NOT NULL,
	[Payee] [int] NULL,
	[AssignedToSupervisor] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossofEarning_D] [decimal](18, 2) NULL,
	[LossofEarning_S] [decimal](18, 2) NULL,
	[CostofRepairs_D] [decimal](18, 2) NULL,
	[CostofRepairs_S] [decimal](18, 2) NULL,
	[LossofUse_D] [decimal](18, 2) NULL,
	[LossofUse_S] [decimal](18, 2) NULL,
	[LossofUseUn_D] [decimal](18, 2) NULL,
	[LossofUseUn_S] [decimal](18, 2) NULL,
	[LossofRental_D] [decimal](18, 2) NULL,
	[LossofRental_S] [decimal](18, 2) NULL,
	[Excess_D] [decimal](18, 2) NULL,
	[Excess_S] [decimal](18, 2) NULL,
	[OtherExpenses_D] [decimal](18, 2) NULL,
	[OtherExpenses_S] [decimal](18, 2) NULL,
	[ReportFees_D] [decimal](18, 2) NULL,
	[ReportFees_S] [decimal](18, 2) NULL,
	[SurveyFee_D] [decimal](18, 2) NULL,
	[SurveyFee_S] [decimal](18, 2) NULL,
	[ReSurveyFee_D] [decimal](18, 2) NULL,
	[ReSurveyFee_S] [decimal](18, 2) NULL,
	[LGPolRepFee_D] [decimal](18, 2) NULL,
	[LGPolRepFee_S] [decimal](18, 2) NULL,
	[ParLawCost3rd_D] [decimal](18, 2) NULL,
	[ParLawCost3rd_S] [decimal](18, 2) NULL,
	[ParLawDisbursements3rd_D] [decimal](18, 2) NULL,
	[ParLawDisbursements3rd_S] [decimal](18, 2) NULL,
	[OurLawyerCost_D] [decimal](18, 2) NULL,
	[OurLawyerCost_S] [decimal](18, 2) NULL,
	[OurLawDisbursements_D] [decimal](18, 2) NULL,
	[OurLawDisbursements_S] [decimal](18, 2) NULL,
	[GeneralDamages_D] [decimal](18, 2) NULL,
	[GeneralDamages_S] [decimal](18, 2) NULL,
	[MedicalExpenses_D] [decimal](18, 2) NULL,
	[MedicalExpenses_S] [decimal](18, 2) NULL,
	[FutureMedicalExpenses_D] [decimal](18, 2) NULL,
	[FutureMedicalExpenses_S] [decimal](18, 2) NULL,
	[LOGMedicalExpenses_D] [decimal](18, 2) NULL,
	[LOGMedicalExpenses_S] [decimal](18, 2) NULL,
	[LossofEarningsCapacity_D] [decimal](18, 2) NULL,
	[LossofEarningsCapacity_S] [decimal](18, 2) NULL,
	[LossofEarnings_D] [decimal](18, 2) NULL,
	[LossofEarnings_S] [decimal](18, 2) NULL,
	[LossofFutureEarnings_D] [decimal](18, 2) NULL,
	[LossofFutureEarnings_S] [decimal](18, 2) NULL,
	[Transport_D] [decimal](18, 2) NULL,
	[Transport_S] [decimal](18, 2) NULL,
	[MedicalRecord_D] [decimal](18, 2) NULL,
	[MedicalRecord_S] [decimal](18, 2) NULL,
	[PublicTrusteeFee_D] [decimal](18, 2) NULL,
	[PublicTrusteeFee_S] [decimal](18, 2) NULL,
	[OurProfessionalExpertFee_D] [decimal](18, 2) NULL,
	[OurProfessionalExpertFee_S] [decimal](18, 2) NULL,
	[Rateperday_D] [decimal](18, 2) NULL,
	[Rateperday_S] [decimal](18, 2) NULL,
	[Total_D] [decimal](18, 2) NULL,
	[Total_S] [decimal](18, 2) NULL,
	[Createddate] [datetime] NULL,
	[Modifieddate] [datetime] NULL,
	[PaymentRequestDate] [datetime] NULL,
	[PaymentDueDate] [datetime] NULL,
	[CreatedBy] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Modifiedby] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Noofdays_D] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Noofdays_S] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AssignedTo] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimType] [int] NULL,
	[IsActive] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF_CLM_Payment_IsActive]  DEFAULT ('Y'),
	[ClaimID] [int] NULL,
	[Address] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Address1] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Address2] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PostalCodes] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CoRemarks] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ApprovePayment] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CLM_Payment_ApprovePayment]  DEFAULT ('N'),
	[SupervisorRemarks] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ApprovedDate] [datetime] NULL,
	[MovementType] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CLM_Payment_MovementType]  DEFAULT ('I'),
	[MandateId] [int] NULL,
	[ReserveId] [int] NULL,
 CONSTRAINT [PK_CLM_Payment] PRIMARY KEY CLUSTERED 
(
	[PaymentId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON),
 CONSTRAINT [FK_CLM_Payment_ClaimAccidentDetails] FOREIGN KEY([AccidentClaimId])
REFERENCES [dbo].[ClaimAccidentDetails] ([AccidentClaimId]),
 CONSTRAINT [FK_CLM_Payment_CLM_Claims] FOREIGN KEY([ClaimID])
REFERENCES [dbo].[CLM_Claims] ([ClaimID]),
 CONSTRAINT [FK_CLM_Payment_CLM_Mandate] FOREIGN KEY([MandateId])
REFERENCES [dbo].[CLM_Mandate] ([MandateId]),
 CONSTRAINT [FK_CLM_Payment_CLM_Reserve] FOREIGN KEY([ReserveId])
REFERENCES [dbo].[CLM_Reserve] ([ReserveId])
)


