CREATE TABLE [dbo].[CLM_Reserve](
	[ReserveId] [int] IDENTITY(1,1) NOT NULL,
	[ClaimantName] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimType] [int] NOT NULL,
	[CostofRepairs_I] [decimal](18, 2) NULL,
	[CostofRepairs_R] [decimal](18, 2) NULL,
	[CostofRepairs_O] [decimal](18, 2) NULL,
	[LossofUse_I] [decimal](18, 2) NULL,
	[LossofUse_R] [decimal](18, 2) NULL,
	[LossofUse_O] [decimal](18, 2) NULL,
	[LossofUseUn_I] [decimal](18, 2) NULL,
	[LossofUseUn_R] [decimal](18, 2) NULL,
	[LossofUseUn_O] [decimal](18, 2) NULL,
	[LossofRental_I] [decimal](18, 2) NULL,
	[LossofRental_R] [decimal](18, 2) NULL,
	[LossofRental_O] [decimal](18, 2) NULL,
	[Excess_I] [decimal](18, 2) NULL,
	[Excess_R] [decimal](18, 2) NULL,
	[Excess_O] [decimal](18, 2) NULL,
	[OtherExpenses_I] [decimal](18, 2) NULL,
	[OtherExpenses_R] [decimal](18, 2) NULL,
	[OtherExpenses_O] [decimal](18, 2) NULL,
	[ReportFees_I] [decimal](18, 2) NULL,
	[ReportFees_R] [decimal](18, 2) NULL,
	[ReportFees_O] [decimal](18, 2) NULL,
	[SurveyFee_I] [decimal](18, 2) NULL,
	[SurveyFee_R] [decimal](18, 2) NULL,
	[SurveyFee_O] [decimal](18, 2) NULL,
	[ReSurveyFee_I] [decimal](18, 2) NULL,
	[ReSurveyFee_R] [decimal](18, 2) NULL,
	[ReSurveyFee_O] [decimal](18, 2) NULL,
	[LGPolRepFee_I] [decimal](18, 2) NULL,
	[LGPolRepFee_R] [decimal](18, 2) NULL,
	[LGPolRepFee_O] [decimal](18, 2) NULL,
	[ParLawCost3rd_I] [decimal](18, 2) NULL,
	[ParLawCost3rd_R] [decimal](18, 2) NULL,
	[ParLawCost3rd_O] [decimal](18, 2) NULL,
	[ParLawDisbursements3rd_I] [decimal](18, 2) NULL,
	[ParLawDisbursements3rd_R] [decimal](18, 2) NULL,
	[ParLawDisbursements3rd_O] [decimal](18, 2) NULL,
	[OurLawyerCost_I] [decimal](18, 2) NULL,
	[OurLawyerCost_R] [decimal](18, 2) NULL,
	[OurLawyerCost_O] [decimal](18, 2) NULL,
	[OurLawDisbursements_I] [decimal](18, 2) NULL,
	[OurLawDisbursements_R] [decimal](18, 2) NULL,
	[OurLawDisbursements_O] [decimal](18, 2) NULL,
	[GeneralDamages_I] [decimal](18, 2) NULL,
	[GeneralDamages_R] [decimal](18, 2) NULL,
	[GeneralDamages_O] [decimal](18, 2) NULL,
	[MedicalExpenses_I] [decimal](18, 2) NULL,
	[MedicalExpenses_R] [decimal](18, 2) NULL,
	[MedicalExpenses_O] [decimal](18, 2) NULL,
	[FutureMedicalExpenses_I] [decimal](18, 2) NULL,
	[FutureMedicalExpenses_R] [decimal](18, 2) NULL,
	[FutureMedicalExpenses_O] [decimal](18, 2) NULL,
	[LOGMedicalExpenses_I] [decimal](18, 2) NULL,
	[LOGMedicalExpenses_R] [decimal](18, 2) NULL,
	[LOGMedicalExpenses_O] [decimal](18, 2) NULL,
	[LossofEarningsCapacity_I] [decimal](18, 2) NULL,
	[LossofEarningsCapacity_R] [decimal](18, 2) NULL,
	[LossofEarningsCapacity_O] [decimal](18, 2) NULL,
	[LossofEarnings_I] [decimal](18, 2) NULL,
	[LossofEarnings_R] [decimal](18, 2) NULL,
	[LossofEarnings_O] [decimal](18, 2) NULL,
	[LossofFutureEarnings_I] [decimal](18, 2) NULL,
	[LossofFutureEarnings_R] [decimal](18, 2) NULL,
	[LossofFutureEarnings_O] [decimal](18, 2) NULL,
	[Transport_I] [decimal](18, 2) NULL,
	[Transport_R] [decimal](18, 2) NULL,
	[Transport_O] [decimal](18, 2) NULL,
	[Noofdays_I] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Noofdays_R] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Noofdays_O] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MedicalRecord_I] [decimal](18, 2) NULL,
	[MedicalRecord_R] [decimal](18, 2) NULL,
	[MedicalRecord_O] [decimal](18, 2) NULL,
	[PublicTrusteeFee_I] [decimal](18, 2) NULL,
	[PublicTrusteeFee_R] [decimal](18, 2) NULL,
	[PublicTrusteeFee_O] [decimal](18, 2) NULL,
	[OurProfessionalExpertFee_I] [decimal](18, 2) NULL,
	[OurProfessionalExpertFee_R] [decimal](18, 2) NULL,
	[OurProfessionalExpertFee_O] [decimal](18, 2) NULL,
	[Rateperday_I] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Rateperday_R] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Rateperday_O] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Total_I] [decimal](18, 2) NOT NULL CONSTRAINT [DF_CLM_Reserve_Total_I]  DEFAULT ((0)),
	[Total_R] [decimal](18, 2) NOT NULL CONSTRAINT [DF_CLM_Reserve_Total_R]  DEFAULT ((0)),
	[Total_O] [decimal](18, 2) NOT NULL CONSTRAINT [DF_CLM_Reserve_Total_O]  DEFAULT ((0)),
	[LOGAmount] [decimal](18, 2) NULL CONSTRAINT [DF_CLM_Reserve_LOGAmount]  DEFAULT ((0.00)),
	[LOGDate] [datetime] NULL CONSTRAINT [DF_CLM_Reserve_LOGDate]  DEFAULT (getdate()),
	[CORemarks] [nvarchar](800) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Createdby] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HospitalName] [int] NOT NULL CONSTRAINT [DF_CLM_Reserve_HospitalName]  DEFAULT ((0)),
	[AssignedTo] [int] NOT NULL CONSTRAINT [DF_CLM_Reserve_AssignedTo]  DEFAULT ((0)),
	[Createddate] [datetime] NULL,
	[Modifiedby] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Modifieddate] [datetime] NULL,
	[AccidentId] [int] NULL,
	[PolicyId] [int] NULL,
	[IsActive] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimID] [int] NULL,
	[ClaimantNameId] [int] NULL,
	[HopitalNameId] [int] NULL,
	[AssignToId] [int] NULL,
	[MovementType] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CLM_Reserve_MovementType]  DEFAULT ('I'),
	[PaymentId] [int] NULL,
	[Finalize] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_CLM_Reserve_Finalize]  DEFAULT ('N'),
	[CostofRepairs_C] [decimal](18, 0) NULL,
	[LossofUse_C] [decimal](18, 0) NULL,
	[LossofUseUn_C] [decimal](18, 0) NULL,
	[LossofRental_C] [decimal](18, 0) NULL,
	[Excess_C] [decimal](18, 0) NULL,
	[OtherExpenses_C] [decimal](18, 0) NULL,
	[ReportFees_C] [decimal](18, 0) NULL,
	[SurveyFee_C] [decimal](18, 0) NULL,
	[ReSurveyFee_C] [decimal](18, 0) NULL,
	[LGPolRepFee_C] [decimal](18, 0) NULL,
	[ParLawCost3rd_C] [decimal](18, 0) NULL,
	[ParLawDisbursements3rd_C] [decimal](18, 0) NULL,
	[OurLawyerCost_C] [decimal](18, 0) NULL,
	[OurLawDisbursements_C] [decimal](18, 0) NULL,
	[GeneralDamages_C] [decimal](18, 0) NULL,
	[MedicalExpenses_C] [decimal](18, 0) NULL,
	[FutureMedicalExpenses_C] [decimal](18, 0) NULL,
	[LOGMedicalExpenses_C] [decimal](18, 0) NULL,
	[LossofEarningsCapacity_C] [decimal](18, 0) NULL,
	[LossofEarnings_C] [decimal](18, 0) NULL,
	[LossofFutureEarnings_C] [decimal](18, 0) NULL,
	[Transport_C] [decimal](18, 0) NULL,
	[MedicalRecord_C] [decimal](18, 0) NULL,
	[PublicTrusteeFee_C] [decimal](18, 0) NULL,
	[OurProfessionalExpertFee_C] [decimal](18, 0) NULL,
	[Total_C] [decimal](18, 0) NULL,
	[Noofdays_C] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Rateperday_C] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_CLM_Reserve] PRIMARY KEY CLUSTERED 
(
	[ReserveId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON),
 CONSTRAINT [FK_CLM_Reserve_ClaimAccidentDetails] FOREIGN KEY([AccidentId])
REFERENCES [dbo].[ClaimAccidentDetails] ([AccidentClaimId]),
 CONSTRAINT [FK_CLM_Reserve_CLM_Claim] FOREIGN KEY([ClaimID])
REFERENCES [dbo].[CLM_Claims] ([ClaimID]),
 CONSTRAINT [FK_CLM_Reserve_CLM_Payment] FOREIGN KEY([PaymentId])
REFERENCES [dbo].[CLM_Payment] ([PaymentId])
)


