CREATE TABLE [dbo].[CLM_Claim](
	[ClaimID] [int] IDENTITY(1,1) NOT NULL,
	[ClaimantName] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimantNRICPPNO] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimantDOB] [datetime] NULL,
	[ClaimantGender] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantType] [int] NOT NULL,
	[ClaimantAddress1] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimantAddress2] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimantAddress3] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[PostalCode] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimantContactNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimantEmail] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleRegnNo] [nvarchar](8) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[VehicleMake] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[VehicleModel] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Isclaimantaninfant] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InfantName] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InfantDOB] [datetime] NULL,
	[InfantGender] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimType] [int] NOT NULL,
	[ClaimRecordNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TimeBarDate] [datetime] NOT NULL,
	[ClaimDate] [datetime] NOT NULL,
	[ClaimsOfficer] [int] NOT NULL,
	[DriverLiablity] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccidentCause] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CaseCategory] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CaseStatus] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimantStatus] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FinalSettleDate] [datetime] NOT NULL,
	[WritIssuedDate] [datetime] NULL,
	[WritNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SensitiveCase] [datetime] NULL,
	[ReopenedDate] [datetime] NULL,
	[RecordReopenedReason] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecordCancellationDate] [datetime] NULL,
	[RecordCancellationReason] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Createdby] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Createddate] [datetime] NOT NULL,
	[Modifiedby] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Modifieddate] [datetime] NULL,
	[AccidentId] [int] NULL,
	[PolicyId] [int] NULL,
	[IsActive] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[MP] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Constituency] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfMpLetter] [datetime] NULL,
	[SeverityReferenceNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportSentToInsurer] [datetime] NULL,
	[ReferredToInsurers] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InformedInsurerOfSettlement] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExcessRecoveredDate] [datetime] NULL,
	[ReferredToInsurersB] [bit] NOT NULL,
	[DateReferredToInsurersB] [datetime] NULL,
	[ClaimStatus] [int] NULL CONSTRAINT [DF__CLM_Claim__Claim__42C2BEC4]  DEFAULT ((1)),
 CONSTRAINT [PK_CLM_Claim] PRIMARY KEY CLUSTERED 
(
	[ClaimID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON),
 CONSTRAINT [FK_CLM_Claim_ClaimAccidentDetails] FOREIGN KEY([AccidentId])
REFERENCES [dbo].[ClaimAccidentDetails] ([AccidentClaimId])
)


