CREATE TABLE [dbo].[CLM_ThirdParty](
	[TPartyId] [int] IDENTITY(1,1) NOT NULL,
	[ClaimId] [int] NOT NULL,
	[OtherPartyType] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CompanyName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Reference] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateAppointed] [datetime] NULL,
	[TPVehicleNo] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPSurname] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPGivenName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPNRICNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPAdd1] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPAdd2] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPCountry] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPPostalCode] [numeric](18, 0) NULL,
	[TPOfficeNo] [numeric](18, 0) NULL,
	[TPMobNo] [numeric](18, 0) NULL,
	[TPFaxNo] [numeric](18, 0) NULL,
	[TPEmailAdd] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaidThisYear] [numeric](18, 0) NULL,
	[PaidToDate] [numeric](18, 0) NULL,
	[RecovThisYear] [numeric](18, 0) NULL,
	[RecovToDate] [numeric](18, 0) NULL,
	[IsActive] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[ModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedDate] [datetime] NULL,
	[VehicleRegnNo] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleMake] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleModel] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossDamageDesc] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPAdjuster] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPLawyer] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPWorkShop] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Remarks] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AttachedFile] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReserveCurr] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReserveExRate] [decimal](18, 9) NULL,
	[ReserveAmt] [decimal](18, 9) NULL,
	[ExpensesCurr] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExpensesExRate] [decimal](18, 9) NULL,
	[ExpensesAmt] [decimal](18, 9) NULL,
	[TotalReserve] [decimal](18, 9) NULL,
	[ClaimAmount] [decimal](18, 9) NULL,
	[PaidDate] [datetime] NULL,
	[BalanceLOG] [numeric](18, 0) NULL,
	[LOGAmount] [numeric](18, 0) NULL,
	[LOURate] [numeric](18, 0) NULL,
	[LOUDays] [numeric](18, 0) NULL,
	[ClaimAmtCurr] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimAmtExRate] [decimal](18, 9) NULL,
	[ClaimAmt] [decimal](18, 9) NULL,
	[PayableTo] [int] NULL,
	[ExpensesAmount] [decimal](18, 9) NULL,
	[ReserveAmount] [decimal](18, 9) NULL,
 CONSTRAINT [PK_CLM_ThirdParty] PRIMARY KEY CLUSTERED 
(
	[TPartyId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON),
 CONSTRAINT [FK_CLM_ThirdParty_CLM_Claims] FOREIGN KEY([ClaimId])
REFERENCES [dbo].[CLM_Claims] ([ClaimID])
)


