CREATE TABLE [dbo].[CLM_Claims](
	[ClaimID] [int] IDENTITY(1,1) NOT NULL,
	[AccidentClaimId] [int] NOT NULL,
	[PolicyId] [int] NOT NULL,
	[ClaimType] [int] NULL,
	[ClaimDate] [datetime] NULL,
	[ClaimOfficer] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FinalSettleDate] [datetime] NULL,
	[ClaimStatus] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TimeBarDate] [datetime] NULL,
	[CaseCategory] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CaseStatus] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DriversLiability] [numeric](18, 0) NULL,
	[ClaimAmount] [decimal](18, 9) NULL,
	[PaidDate] [datetime] NULL,
	[BalanceLOG] [numeric](18, 0) NULL,
	[LOGAmount] [numeric](18, 0) NULL,
	[LOURate] [numeric](18, 0) NULL,
	[LOUDays] [numeric](18, 0) NULL,
	[ReportSentInsurer] [datetime] NULL,
	[ReferredInsurers] [datetime] NULL,
	[InformInsurer] [datetime] NULL,
	[ExcessRecoveredDate] [datetime] NULL,
	[WritIssuedDate] [datetime] NULL,
	[WritNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SenstiveCase] [datetime] NULL,
	[MPLetter] [datetime] NULL,
	[IsActive] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[ModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedDate] [datetime] NULL,
	[ReserveCurr] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReserveExRate] [decimal](18, 9) NULL,
	[ReserveAmt] [decimal](18, 9) NULL,
	[ExpensesCurr] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExpensesExRate] [decimal](18, 9) NULL,
	[TotalReserve] [decimal](18, 9) NULL,
	[AdjusterAppointed] [int] NULL,
	[LawyerAppointed] [int] NULL,
	[SurveyorAppointed] [int] NULL,
	[DepotWorkshop] [int] NULL,
	[ExpensesAmt] [decimal](18, 9) NULL,
	[PayableTo] [int] NULL,
	[ClaimAmountCurr] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimAmtPayout] [decimal](18, 9) NULL,
	[ClaimAmtPayoutExRate] [decimal](18, 9) NULL,
	[ExpensesAmount] [decimal](18, 9) NULL,
	[ReserveAmount] [decimal](18, 9) NULL,
	[RecordDeletionDate] [datetime] NULL,
	[RecordDeletionReason] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantName] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantNRICPPNO] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantDOB] [datetime] NULL,
	[ClaimantGender] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantType] [nvarchar](50) NULL,
	[ClaimantAddress1] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantAddress2] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantAddress3] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PostalCode] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantContactNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantEmail] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleRegnNo] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleMake] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleModel] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Isclaimantaninfant] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InfantName] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InfantDOB] [datetime] NULL,
	[InfantGender] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimRecordNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimsOfficer] [int] NULL,
	[DriverLiablity] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccidentCause] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantStatus] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SensitiveCase] [datetime] NULL,
	[ReopenedDate] [datetime] NULL,
	[RecordReopenedReason] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecordCancellationDate] [datetime] NULL,
	[RecordCancellationReason] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MP] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Constituency] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateOfMpLetter] [datetime] NULL,
	[SeverityReferenceNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReportSentToInsurer] [datetime] NULL,
	[ReferredToInsurers] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InformedInsurerOfSettlement] [nvarchar](250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReferredToInsurersB] [bit] NULL,
	[DateReferredToInsurersB] [datetime] NULL,
	[AccidentId] [int] NULL,
	[ConfirmedAmount] [numeric](18, 2) NULL,
	[LODSentdate] [datetime] NULL,
	[InformedInsurer] [datetime] NULL,
	[EZLinkCardNo] [char](1) NULL,
	[NODNOS] [char](1) NULL,
	[RecoveredtoDate] [decimal](18, 9) NULL,
	[Country] [varchar](5) NULL,
	[City] [nvarchar](50) NULL,
	[State] [nvarchar](100) NULL,
 CONSTRAINT [PK_CLM_Claims] PRIMARY KEY CLUSTERED 
(
	[ClaimID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON),
 CONSTRAINT [FK_CLM_Claims_ClaimAccidentDetails_AccidentClaimId] FOREIGN KEY([AccidentClaimId])
REFERENCES [dbo].[ClaimAccidentDetails] ([AccidentClaimId]),
 CONSTRAINT [FK_CLM_Claims_MNT_Adjusters] FOREIGN KEY([AdjusterAppointed])
REFERENCES [dbo].[MNT_Adjusters] ([AdjusterId]),
 CONSTRAINT [FK_CLM_Claims_MNT_Adjusters1] FOREIGN KEY([LawyerAppointed])
REFERENCES [dbo].[MNT_Adjusters] ([AdjusterId]),
 CONSTRAINT [FK_CLM_Claims_MNT_Adjusters2] FOREIGN KEY([SurveyorAppointed])
REFERENCES [dbo].[MNT_Adjusters] ([AdjusterId]),
 CONSTRAINT [FK_CLM_Claims_MNT_Department] FOREIGN KEY([DepotWorkshop])
REFERENCES [dbo].[MNT_Department] ([DeptId])
)


