CREATE TABLE [dbo].[MIG_IL_VEHICLE_DETAIL](
	[UPLOAD_FILE_ID] [int] NULL,
	[UPLOAD_SERIAL_NO] [int] IDENTITY(1,1) NOT NULL,
	[VEHICLE_REGISTRATION_NO] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_MAKE] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_MODEL] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_CLASS] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MODEL_DESCRIPTION] [nvarchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUS_CAPTAIN] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IMPORT_ACTION] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FileName] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_MIG_IL_VEHICLE_DETAIL] PRIMARY KEY CLUSTERED 
(
	[UPLOAD_SERIAL_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


