CREATE TABLE [dbo].[MIG_ERROR_TYPE_DETAIL](
	[ERROR_TYPE_ID] [int] NOT NULL,
	[TYPE_ID] [int] NOT NULL,
	[ERROR_DESCRIPTION] [nvarchar](150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_ACTIVE] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
 CONSTRAINT [PK_MIG_ERROR_TYPE_DETAIL_ERROR_TYPE_ID] PRIMARY KEY NONCLUSTERED 
(
	[ERROR_TYPE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


