CREATE TABLE [dbo].[MNT_MODULE_MASTER](
	[MM_MODULE_ID] [int] IDENTITY(1,1) NOT NULL,
	[MM_MODULE_NAME] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[MM_IS_ACTIVE] [nchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_MNT_MODULE_MASTER_MM_MODULE_ID] PRIMARY KEY NONCLUSTERED 
(
	[MM_MODULE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


