CREATE TABLE [dbo].[MNT_PACKAGE_TEMPLATES](
	[Package_Template_Id] [int] IDENTITY(1,1) NOT NULL,
	[Package_Id] [int] NOT NULL,
	[Template_Id] [int] NOT NULL,
	[Order_In_Package] [decimal](18, 2) NULL,
	[Has_Attachment] [bit] NULL,
 CONSTRAINT [PK_MNT_PACKAGE_TEMPLATES] PRIMARY KEY CLUSTERED 
(
	[Package_Template_Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON),
 CONSTRAINT [FK_MNT_PACKAGE_TEMPLATES_MNT_PACKAGE_MASTER] FOREIGN KEY([Package_Id])
REFERENCES [dbo].[MNT_PACKAGE_MASTER] ([Package_Id])
)


