CREATE TABLE [dbo].[MNT_VEHICLE_LIST](
	[VEHICLE_REGISTRATION_ID] [int] IDENTITY(1,1) NOT NULL,
	[VEHICLE_REGISTRATION_NO] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_MAKE] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_MODEL] [int] NULL,
	[VEHICLE_CLASS] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MODEL_DESCRIPTION] [nvarchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUS_CAPTAIN] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_ACTIVE] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREATE_BY] [int] NULL,
	[CREATE_DATE] [datetime] NULL,
 CONSTRAINT [PK_VEHICLE_REGISTRATION_ID] PRIMARY KEY CLUSTERED 
(
	[VEHICLE_REGISTRATION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


