CREATE TABLE [dbo].[MNT_LOOKUP_MULTILINGUAL](
	[LOOKUP_ID] [decimal](18, 0) NOT NULL,
	[LOOKUP_DESC] [nvarchar](500) NULL,
	[LANG_ID] [int] NOT NULL,
 CONSTRAINT [PK_MNT_LOOKUP_MULTILINGUAL] PRIMARY KEY CLUSTERED 
(
	[LOOKUP_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ,
CONSTRAINT [FK_MNT_LOOKUP_MULTILINGUAL_MNT_Lookups] FOREIGN KEY([LOOKUP_ID])
REFERENCES [dbo].[MNT_Lookups] ([LookupID])
)