CREATE TABLE [dbo].[MNT_DIARY_MASTER](
	[DIARY_ID] [int] IDENTITY(1,1) NOT NULL,
	[TRIGGER_ID] [int] NOT NULL,
	[DIARY_TYPE_ID] [numeric](18, 0) NOT NULL,
	[ENTITY_ID] [int] NOT NULL,
	[FOLLOWUP_DATE] [datetime] NULL,
	[SUBJECTLINE] [nvarchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRIORITY] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NOTIFICATION_LIST] [numeric](9, 0) NULL,
	[NOTE] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[FOLLOWUP] [numeric](3, 0) NULL,
	[IS_ACTIVE] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[CREATED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
 CONSTRAINT [PK_Diary_Master] PRIMARY KEY CLUSTERED 
(
	[DIARY_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


