CREATE TABLE [dbo].[MNT_LOB_MASTER](
	[LOB_ID] [int] IDENTITY(1,1) NOT NULL,
	[LOB_CODE] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOB_DESC] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOB_CATEGORY] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOB_TYPE] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOB_PKG] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOB_ACORD_STD] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DEF_CLAIMS_TYPE] [nvarchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOB_PREFIX] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOB_SUFFIX] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LOB_SEED] [int] NULL,
	[MAPPING_LOOKUP_ID] [int] NULL,
	[OVERRIDE_LOB_PREFIX] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REWRITE_SEED] [nvarchar](7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SUSEP_LOB_ID] [int] NULL,
	[SUSEP_LOB_CODE] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COMMISSION_LEVEL] [char](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IS_ACTIVE] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[APPLICABLE_COMMISSION] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PRODUCT_TYPE] [int] NULL,
	[MIN_CANCELLATION_DAYS] [smallint] NULL,
	[ADMINISTRATIVE_EXPENSE] [decimal](10, 2) NULL,
	[IOF_PERCENTAGE] [decimal](12, 4) NULL,
	[LOB_POLICY_TYPE] [int] NULL,
 CONSTRAINT [PK_MNT_LOB_MASTER_LOB_ID] PRIMARY KEY CLUSTERED 
(
	[LOB_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


