CREATE TABLE [dbo].[PolicyDetailTrx](
	[TranRefNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskReferenceNo] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskType] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SubClassCode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Occupancy] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Address1] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Address2] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Address3] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BuildingName] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[City] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Province] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Country] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PostalCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConstructionTitle] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PremCalcBase] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConstructionMonth] [int] NULL,
	[ConstructionDay] [int] NULL,
	[ConstructionFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ConstructionTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TestingMonth] [int] NULL,
	[TestingDay] [int] NULL,
	[TestingFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TestingTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MaintMonth] [int] NULL,
	[MaintDay] [int] NULL,
	[MaintFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MaintTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TypeOfMaint] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InterestDesc] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GeoRegion] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DefectsCover] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeductionBrokerage] [decimal](18, 5) NULL,
	[DeductionCommission] [decimal](18, 5) NULL,
	[DeductionLeadFee] [decimal](18, 5) NULL,
	[DeductionTax] [decimal](18, 5) NULL,
	[OccupancyDesc] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PremCalcDays] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtConstructionMonth] [int] NULL,
	[EndtConstructionDay] [int] NULL,
	[EndtConstructionFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtConstructionTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtTestingMonth] [int] NULL,
	[EndtTestingDay] [int] NULL,
	[EndtTestingFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtTestingTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtMaintMonth] [int] NULL,
	[EndtMaintDay] [int] NULL,
	[EndtMaintFrom] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtMaintTo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyPeriodMonth] [int] NULL,
	[PolicyPeriodDays] [int] NULL,
	[PolicyInceptionDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyExpiryDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CommitStartDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CommitEndDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Situation] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InsuredCountry] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtPolicyPeriodMonth] [int] NULL,
	[EndtPolicyPeriodDays] [int] NULL,
	[EndtPolicyInceptionDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtPolicyExpiryDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtCommitStartDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtCommitEndDate] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BenchmarkRate] [decimal](9, 2) NULL,
	[BPI] [decimal](18, 2) NULL,
	[BPIPer] [decimal](18, 2) NULL,
	[CreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[ModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedDate] [datetime] NULL,
	[Tab] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TerritoryLocation] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)


