CREATE TABLE [dbo].[PolicyClassRegTrx](
	[TranRefNo] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskNo] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClassCode] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SubClassCode] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskCurr] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskExRate] [decimal](18, 9) NULL,
	[CStatus] [int] NULL CONSTRAINT [DF_PolicyClassRegTrx_CStatus_1]  DEFAULT ((0)),
	[AccumFlag] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyClassRegTrx_AccumFlag]  DEFAULT ('N'),
	[AccumCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AccumBlockRefNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskUsRate] [decimal](18, 4) NULL,
	[RiskDispNo] [int] NULL CONSTRAINT [DF_PolicyClassRegTrx_RiskDispNo]  DEFAULT ((0)),
	[RiskFolderId] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SumIns] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_SumIns_1]  DEFAULT ((0)),
	[Premium] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_Premium_1]  DEFAULT ((0)),
	[AnnualSumIns] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_AnnualSumIns_1]  DEFAULT ((0)),
	[AnnualPremium] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_AnnualPremium_1]  DEFAULT ((0)),
	[SumIns_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_SumIns_Init_1]  DEFAULT ((0)),
	[Premium_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_Premium_Init_1]  DEFAULT ((0)),
	[SumIns_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_SumIns_Final_1]  DEFAULT ((0)),
	[Premium_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_Premium_Final_1]  DEFAULT ((0)),
	[LiabilityLimit] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossExp] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PML] [decimal](18, 2) NULL,
	[EML] [decimal](18, 2) NULL,
	[CommRate] [decimal](18, 2) NULL,
	[MSubClassCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PhotoSurvey] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyClassRegTrx_PhotoSurvey]  DEFAULT ('N'),
	[NoPhotoReason] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DatePhotoReceived] [datetime] NULL,
	[NoPhotoApproval] [datetime] NULL,
	[Comm2Rate] [decimal](18, 2) NULL,
	[RIOurShare] [decimal](18, 3) NULL,
	[RIComm] [decimal](18, 3) NULL,
	[RIOrComm] [decimal](18, 3) NULL,
	[LGSumIns] [decimal](18, 2) NULL,
	[LGPremium] [decimal](18, 2) NULL,
	[LGSumIns_Init] [decimal](18, 2) NULL,
	[LGPremium_Init] [decimal](18, 2) NULL,
	[LGSumIns_Final] [decimal](18, 2) NULL,
	[LGPremium_Final] [decimal](18, 2) NULL,
	[CountryGroup] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CommAmt] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_CommAmt]  DEFAULT ((0)),
	[CommAmt_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_CommAmt_Init]  DEFAULT ((0)),
	[CommAmt_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_CommAmt_Final]  DEFAULT ((0)),
	[Comm2Amt] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_Comm2Amt]  DEFAULT ((0)),
	[Comm2Amt_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_Comm2Amt_Init]  DEFAULT ((0)),
	[Comm2Amt_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_Comm2Amt_Final]  DEFAULT ((0)),
	[LGCommAmt] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_LGCommAmt]  DEFAULT ((0)),
	[LGCommAmt_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_LGCommAmt_Init]  DEFAULT ((0)),
	[LGCommAmt_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_LGCommAmt_Final]  DEFAULT ((0)),
	[LGComm2Amt] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_LGComm2Amt]  DEFAULT ((0)),
	[LGComm2Amt_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_LGComm2Amt_Init]  DEFAULT ((0)),
	[LGComm2Amt_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_LGComm2Amt_Final]  DEFAULT ((0)),
	[DiscAmt] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_DiscAmt]  DEFAULT ((0)),
	[DiscAmt_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_DiscAmt_Init]  DEFAULT ((0)),
	[DiscAmt_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRegTrx_DiscAmt_Final]  DEFAULT ((0)),
	[ExtraSumIns] [decimal](18, 2) NULL,
	[ExtraPremium] [decimal](18, 2) NULL,
	[ExtraSumIns_Init] [decimal](18, 2) NULL,
	[ExtraPremium_Init] [decimal](18, 2) NULL,
	[ExtraSumIns_Final] [decimal](18, 2) NULL,
	[ExtraPremium_Final] [decimal](18, 2) NULL,
	[ExtraDiscAmt] [decimal](18, 2) NULL,
	[ExtraCommAmt] [decimal](18, 2) NULL,
	[ExtraComm2Amt] [decimal](18, 2) NULL,
	[ExtraDiscAmt_Init] [decimal](18, 2) NULL,
	[ExtraCommAmt_Init] [decimal](18, 2) NULL,
	[ExtraComm2Amt_Init] [decimal](18, 2) NULL,
	[ExtraDiscAmt_Final] [decimal](18, 2) NULL,
	[ExtraCommAmt_Final] [decimal](18, 2) NULL,
	[ExtraComm2Amt_Final] [decimal](18, 2) NULL,
	[CreditNotePer] [decimal](18, 2) NULL,
	[CreditNoteAmt] [decimal](18, 2) NULL,
	[CreditNoteAmt_Init] [decimal](18, 2) NULL,
	[CreditNoteAmt_Final] [decimal](18, 2) NULL,
	[ContractValue] [decimal](18, 2) NULL,
	[PolicyRate] [decimal](18, 5) NULL,
	[EscalationPct] [decimal](18, 2) NULL,
	[EscalationAmt] [decimal](18, 2) NULL,
	[ProfessionalPct] [decimal](18, 2) NULL,
	[ProfessionalAmt] [decimal](18, 2) NULL,
	[RODPct] [decimal](18, 2) NULL,
	[RODAmt] [decimal](18, 2) NULL,
	[PPSIPct] [decimal](18, 2) NULL,
	[PPSIAmt] [decimal](18, 2) NULL,
	[ExpeditingExpensePct] [decimal](18, 2) NULL,
	[ExpeditingExpenseAmt] [decimal](18, 2) NULL,
	[TSIPremCalc] [decimal](18, 2) NULL,
	[SumInsAgg] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TSIPMLCalc] [decimal](18, 2) NULL,
	[EstPrem] [decimal](18, 2) NULL,
	[EstBeazley] [decimal](18, 2) NULL,
	[AOGPct] [decimal](18, 2) NULL,
	[AOGAmt] [decimal](18, 2) NULL,
	[TestingPct] [decimal](18, 2) NULL,
	[TestingAmt] [decimal](18, 2) NULL,
	[DefectsPct] [decimal](18, 2) NULL,
	[DefectsAmt] [decimal](18, 2) NULL,
	[MaintPct] [decimal](18, 2) NULL,
	[MaintAmt] [decimal](18, 2) NULL,
	[ExsistPPPct] [decimal](18, 2) NULL,
	[ExsistPPAmt] [decimal](18, 2) NULL,
	[OthersPct] [decimal](18, 2) NULL,
	[OthersAmt] [decimal](18, 2) NULL,
	[TPLLimit] [decimal](18, 2) NULL,
	[SumInsAggII] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TPPDPct] [decimal](18, 2) NULL,
	[TPPDAmt] [decimal](18, 2) NULL,
	[UndergroundSvcPct] [decimal](18, 2) NULL,
	[UndergroundSvcAmt] [decimal](18, 2) NULL,
	[VRWSPct] [decimal](18, 2) NULL,
	[VRWSAmt] [decimal](18, 2) NULL,
	[OthersIIPct] [decimal](18, 2) NULL,
	[OthersIIAmt] [decimal](18, 2) NULL,
	[PMLExpOri] [decimal](18, 2) NULL,
	[PMLExpTreaty1] [decimal](18, 2) NULL,
	[PMLExpTreaty2] [decimal](18, 2) NULL,
	[ROE] [decimal](18, 9) NULL,
	[CrestaCountry] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Cresta] [char](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TSI] [decimal](18, 2) NULL,
	[LimitOfLiability] [decimal](18, 2) NULL,
	[InterestInsured] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Remarks] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskCurrII] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskExRateII] [decimal](18, 9) NULL,
	[NaturalPerilAmt] [decimal](18, 2) NULL,
	[OthSubLimitDesc1] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OthSubLimit1] [decimal](18, 2) NULL,
	[OthSubLimitAmt1] [decimal](18, 2) NULL,
	[OthSubLimitDesc2] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OthSubLimit2] [decimal](18, 2) NULL,
	[OthSubLimitAmt2] [decimal](18, 2) NULL,
	[OthSubLimitDesc3] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OthSubLimit3] [decimal](18, 2) NULL,
	[OthSubLimitAmt3] [decimal](18, 2) NULL,
	[PARDeductibleName1] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARDeductibleRate1] [decimal](18, 2) NULL,
	[PARDeductibleAmt1] [decimal](18, 2) NULL,
	[PARDeductibleName2] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARDeductibleRate2] [decimal](18, 2) NULL,
	[PARDeductibleAmt2] [decimal](18, 2) NULL,
	[PARDeductibleName3] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARDeductibleRate3] [decimal](18, 2) NULL,
	[PARDeductibleAmt3] [decimal](18, 2) NULL,
	[PARDeductibleName4] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARDeductibleRate4] [decimal](18, 2) NULL,
	[PARDeductibleAmt4] [decimal](18, 2) NULL,
	[PARDeductibleName5] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARDeductibleRate5] [decimal](18, 2) NULL,
	[PARDeductibleAmt5] [decimal](18, 2) NULL,
	[DeductibleName1] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeductibleRate1] [decimal](18, 2) NULL,
	[DeductibleAmt1] [decimal](18, 2) NULL,
	[DeductibleName2] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeductibleRate2] [decimal](18, 2) NULL,
	[DeductibleAmt2] [decimal](18, 2) NULL,
	[DeductibleName3] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeductibleRate3] [decimal](18, 2) NULL,
	[DeductibleAmt3] [decimal](18, 2) NULL,
	[DeductibleName4] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeductibleRate4] [decimal](18, 2) NULL,
	[DeductibleAmt4] [decimal](18, 2) NULL,
	[DeductibleName5] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeductibleRate5] [decimal](18, 2) NULL,
	[DeductibleAmt5] [decimal](18, 2) NULL,
	[BILimitOfLiability] [decimal](18, 2) NULL,
	[BIInterestInsured] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PARLimitOfLiability] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NaturalPeril] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskType] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROEOrgTr] [decimal](18, 9) NULL,
	[TimeExcessDays] [decimal](18, 2) NULL,
	[TimeExcessAmt] [decimal](18, 2) NULL,
	[IndemnityPeriod] [decimal](18, 0) NULL,
	[TypeOfBICover] [nvarchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PMLInclude] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TSIPremEndt] [decimal](25, 9) NULL,
	[TSIPMLEndt] [decimal](25, 9) NULL,
	[EstPremEndt] [decimal](25, 9) NULL,
	[EstBeazleyEndt] [decimal](25, 9) NULL,
	[TSIPremRev] [decimal](25, 9) NULL,
	[TSIPMLRev] [decimal](25, 9) NULL,
	[EstPremRev] [decimal](25, 9) NULL,
	[EstBeazleyRev] [decimal](25, 9) NULL,
	[IsNewEndt] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsOldRisk] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SumInsInitShare] [decimal](25, 9) NULL,
	[SumInsNewShare] [decimal](25, 9) NULL,
	[SumInsRevShare] [decimal](25, 9) NULL,
	[PMLRevShare] [decimal](25, 9) NULL,
	[NewWrittenLine] [decimal](25, 9) NULL,
	[LondonRefNo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BinderRefNo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmorSumIns] [decimal](18, 2) NULL,
	[LineSize] [decimal](18, 2) NULL,
	[DepositPermium] [decimal](18, 2) NULL,
	[MinimumPermium] [decimal](18, 2) NULL,
	[AdjustablePermium] [decimal](18, 2) NULL,
	[PropertyDamage] [decimal](18, 2) NULL,
	[BusinessInterruption] [decimal](18, 2) NULL,
	[Cend] [decimal](18, 2) NULL,
	[Ci] [decimal](18, 2) NULL,
	[DeductiblePct] [decimal](18, 2) NULL,
	[DedPropertyDamage] [decimal](18, 2) NULL,
	[DedBI] [int] NULL,
	[SumInsAggEndt] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepositPermiumEndt] [decimal](18, 2) NULL,
	[MinimumPermiumEndt] [decimal](18, 2) NULL,
	[AdjustablePermiumEndt] [decimal](18, 2) NULL,
	[PropertyDamageEndt] [decimal](18, 2) NULL,
	[BusinessInterruptionEndt] [decimal](18, 2) NULL,
	[CendEndt] [decimal](18, 2) NULL,
	[CiEndt] [decimal](18, 2) NULL,
	[DeductiblePctEndt] [decimal](18, 2) NULL,
	[DedPropertyDamageEndt] [decimal](18, 2) NULL,
	[DedBIEndt] [decimal](18, 2) NULL,
	[SumInsAggRev] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DepositPermiumRev] [decimal](18, 2) NULL,
	[MinimumPermiumRev] [decimal](18, 2) NULL,
	[AdjustablePermiumRev] [decimal](18, 2) NULL,
	[PropertyDamageRev] [decimal](18, 2) NULL,
	[BusinessInterruptionRev] [decimal](18, 2) NULL,
	[CendRev] [decimal](18, 2) NULL,
	[CiRev] [decimal](18, 2) NULL,
	[DeductiblePctRev] [decimal](18, 2) NULL,
	[DedPropertyDamageRev] [decimal](18, 2) NULL,
	[DedBIRev] [decimal](18, 2) NULL,
	[OrigDeductRemarks] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndtDeductRemarks] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CoInsPer] [decimal](18, 2) NULL,
	[PCGInitialSumIns] [decimal](18, 2) NULL,
	[PDPolicyRate] [decimal](18, 5) NULL,
	[BIPolicyRate] [decimal](18, 5) NULL,
	[PDBuildingAmt] [decimal](18, 2) NULL,
	[PDContMachineAmt] [decimal](18, 2) NULL,
	[PDStockAmt] [decimal](18, 2) NULL,
	[BIMaxIndemPeriod] [int] NULL,
	[PDTotalSumIns] [decimal](18, 2) NULL,
	[BITotalSumIns] [decimal](18, 2) NULL,
	[PDEscalationPer] [decimal](18, 2) NULL,
	[PDEscalationAmt] [decimal](18, 2) NULL,
	[BIEscalationPer] [decimal](18, 2) NULL,
	[BIEscalationAmt] [decimal](18, 2) NULL,
	[PDTSIAggrAmt] [decimal](18, 2) NULL,
	[PDSumInsAggr] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BITSIAggrAmt] [decimal](18, 2) NULL,
	[BISumInsAggr] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDEstPremium] [decimal](18, 2) NULL,
	[BIEstPremium] [decimal](18, 2) NULL,
	[PDEstBzPremium] [decimal](18, 2) NULL,
	[BIEstBzPremium] [decimal](18, 2) NULL,
	[PDDeductible] [decimal](18, 2) NULL,
	[BITimeExcessDays] [int] NULL,
	[BITimeExcessAmt] [decimal](18, 2) NULL,
	[EQSubLimitAmt] [decimal](18, 2) NULL,
	[EQDeductibleAmt] [decimal](18, 2) NULL,
	[TNSubLimitAmt] [decimal](18, 2) NULL,
	[TNDeductibleAmt] [decimal](18, 2) NULL,
	[FDSubLimitAmt] [decimal](18, 2) NULL,
	[FDDeductibleAmt] [decimal](18, 2) NULL,
	[MBSubLimitAmt] [decimal](18, 2) NULL,
	[MBDeductibleAmt] [decimal](18, 2) NULL,
	[UD1SubLimitAmt] [decimal](18, 2) NULL,
	[UD1DeductibleAmt] [decimal](18, 2) NULL,
	[UD2SubLimitAmt] [decimal](18, 2) NULL,
	[UD2DeductibleAmt] [decimal](18, 2) NULL,
	[PolicyTopLocation] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NoOfLocation] [int] NULL,
	[PDTopLocSI] [decimal](18, 2) NULL,
	[PDTopLocPMLPer] [decimal](18, 2) NULL,
	[PDTopLocPMLAmt] [decimal](18, 2) NULL,
	[PDTopLocBzShareAmt] [decimal](18, 2) NULL,
	[BITopLocSI] [decimal](18, 2) NULL,
	[BITopLocPMLPer] [decimal](18, 2) NULL,
	[BITopLocPMLAmt] [decimal](18, 2) NULL,
	[BITopLocBzShareAmt] [decimal](18, 2) NULL,
	[TopLocTotalSI] [decimal](18, 2) NULL,
	[TopLocTotalPMLPer] [decimal](18, 2) NULL,
	[TopLocTotalPMLAmt] [decimal](18, 2) NULL,
	[TopLocTotalBzShareAmt] [decimal](18, 2) NULL,
	[TopLocTotalSITtyAmt] [decimal](18, 2) NULL,
	[TopLocTotalPMLTtyPer] [decimal](18, 2) NULL,
	[TopLocTotalPMLTtyAmt] [decimal](18, 2) NULL,
	[TopLocTotalBzShareTtyAmt] [decimal](18, 2) NULL,
	[PMLExpOrgPMLAmt] [decimal](18, 2) NULL,
	[PMLExpOrgBzShareAmt] [decimal](18, 2) NULL,
	[PMLExpTtyPMLAmt] [decimal](18, 2) NULL,
	[PMLExpTtyBzShareAmt] [decimal](18, 2) NULL,
	[PDPolicyRateEndt] [decimal](18, 5) NULL,
	[BIPolicyRateEndt] [decimal](18, 5) NULL,
	[PDBuildingAmtEndt] [decimal](18, 2) NULL,
	[PDContMachineAmtEndt] [decimal](18, 2) NULL,
	[PDStockAmtEndt] [decimal](18, 2) NULL,
	[BIMaxIndemPeriodEndt] [int] NULL,
	[PDTotalSumInsEndt] [decimal](18, 2) NULL,
	[BITotalSumInsEndt] [decimal](18, 2) NULL,
	[PDEscalationPerEndt] [decimal](18, 2) NULL,
	[PDEscalationAmtEndt] [decimal](18, 2) NULL,
	[BIEscalationPerEndt] [decimal](18, 2) NULL,
	[BIEscalationAmtEndt] [decimal](18, 2) NULL,
	[PDTSIAggrAmtEndt] [decimal](18, 2) NULL,
	[PDSumInsAggrEndt] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BITSIAggrAmtEndt] [decimal](18, 2) NULL,
	[BISumInsAggrEndt] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDEstPremiumEndt] [decimal](18, 2) NULL,
	[BIEstPremiumEndt] [decimal](18, 2) NULL,
	[PDEstBzPremiumEndt] [decimal](18, 2) NULL,
	[BIEstBzPremiumEndt] [decimal](18, 2) NULL,
	[PDDeductibleEndt] [decimal](18, 2) NULL,
	[BITimeExcessDaysEndt] [int] NULL,
	[BITimeExcessAmtEndt] [decimal](18, 2) NULL,
	[EQSubLimitAmtEndt] [decimal](18, 2) NULL,
	[EQDeductibleAmtEndt] [decimal](18, 2) NULL,
	[TNSubLimitAmtEndt] [decimal](18, 2) NULL,
	[TNDeductibleAmtEndt] [decimal](18, 2) NULL,
	[FDSubLimitAmtEndt] [decimal](18, 2) NULL,
	[FDDeductibleAmtEndt] [decimal](18, 2) NULL,
	[MBSubLimitAmtEndt] [decimal](18, 2) NULL,
	[MBDeductibleAmtEndt] [decimal](18, 2) NULL,
	[UD1SubLimitAmtEndt] [decimal](18, 2) NULL,
	[UD1DeductibleAmtEndt] [decimal](18, 2) NULL,
	[UD2SubLimitAmtEndt] [decimal](18, 2) NULL,
	[UD2DeductibleAmtEndt] [decimal](18, 2) NULL,
	[PolicyTopLocationEndt] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NoOfLocationEndt] [int] NULL,
	[PDTopLocSIEndt] [decimal](18, 2) NULL,
	[PDTopLocPMLPerEndt] [decimal](18, 2) NULL,
	[PDTopLocPMLAmtEndt] [decimal](18, 2) NULL,
	[PDTopLocBzShareAmtEndt] [decimal](18, 2) NULL,
	[BITopLocSIEndt] [decimal](18, 2) NULL,
	[BITopLocPMLPerEndt] [decimal](18, 2) NULL,
	[BITopLocPMLAmtEndt] [decimal](18, 2) NULL,
	[BITopLocBzShareAmtEndt] [decimal](18, 2) NULL,
	[TopLocTotalSIEndt] [decimal](18, 2) NULL,
	[TopLocTotalPMLPerEndt] [decimal](18, 2) NULL,
	[TopLocTotalPMLAmtEndt] [decimal](18, 2) NULL,
	[TopLocTotalBzShareAmtEndt] [decimal](18, 2) NULL,
	[TopLocTotalSITtyAmtEndt] [decimal](18, 2) NULL,
	[TopLocTotalPMLTtyPerEndt] [decimal](18, 2) NULL,
	[TopLocTotalPMLTtyAmtEndt] [decimal](18, 2) NULL,
	[TopLocTotalBzShareTtyAmtEndt] [decimal](18, 2) NULL,
	[PMLExpOrgPMLAmtEndt] [decimal](18, 2) NULL,
	[PMLExpOrgBzShareAmtEndt] [decimal](18, 2) NULL,
	[PMLExpTtyPMLAmtEndt] [decimal](18, 2) NULL,
	[PMLExpTtyBzShareAmtEndt] [decimal](18, 2) NULL,
	[PMLExpOriEndt] [decimal](18, 2) NULL,
	[PMLExpTreaty2Endt] [decimal](18, 2) NULL,
	[PDPolicyRateRev] [decimal](18, 5) NULL,
	[BIPolicyRateRev] [decimal](18, 5) NULL,
	[PDBuildingAmtRev] [decimal](18, 2) NULL,
	[PDContMachineAmtRev] [decimal](18, 2) NULL,
	[PDStockAmtRev] [decimal](18, 2) NULL,
	[BIMaxIndemPeriodRev] [int] NULL,
	[PDTotalSumInsRev] [decimal](18, 2) NULL,
	[BITotalSumInsRev] [decimal](18, 2) NULL,
	[PDEscalationPerRev] [decimal](18, 2) NULL,
	[PDEscalationAmtRev] [decimal](18, 2) NULL,
	[BIEscalationPerRev] [decimal](18, 2) NULL,
	[BIEscalationAmtRev] [decimal](18, 2) NULL,
	[PDTSIAggrAmtRev] [decimal](18, 2) NULL,
	[PDSumInsAggrRev] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BITSIAggrAmtRev] [decimal](18, 2) NULL,
	[BISumInsAggrRev] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDEstPremiumRev] [decimal](18, 2) NULL,
	[BIEstPremiumRev] [decimal](18, 2) NULL,
	[PDEstBzPremiumRev] [decimal](18, 2) NULL,
	[BIEstBzPremiumRev] [decimal](18, 2) NULL,
	[PDDeductibleRev] [decimal](18, 2) NULL,
	[BITimeExcessDaysRev] [int] NULL,
	[BITimeExcessAmtRev] [decimal](18, 2) NULL,
	[EQSubLimitAmtRev] [decimal](18, 2) NULL,
	[EQDeductibleAmtRev] [decimal](18, 2) NULL,
	[TNSubLimitAmtRev] [decimal](18, 2) NULL,
	[TNDeductibleAmtRev] [decimal](18, 2) NULL,
	[FDSubLimitAmtRev] [decimal](18, 2) NULL,
	[FDDeductibleAmtRev] [decimal](18, 2) NULL,
	[MBSubLimitAmtRev] [decimal](18, 2) NULL,
	[MBDeductibleAmtRev] [decimal](18, 2) NULL,
	[UD1SubLimitAmtRev] [decimal](18, 2) NULL,
	[UD1DeductibleAmtRev] [decimal](18, 2) NULL,
	[UD2SubLimitAmtRev] [decimal](18, 2) NULL,
	[UD2DeductibleAmtRev] [decimal](18, 2) NULL,
	[PolicyTopLocationRev] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NoOfLocationRev] [int] NULL,
	[PDTopLocSIRev] [decimal](18, 2) NULL,
	[PDTopLocPMLPerRev] [decimal](18, 2) NULL,
	[PDTopLocPMLAmtRev] [decimal](18, 2) NULL,
	[PDTopLocBzShareAmtRev] [decimal](18, 2) NULL,
	[BITopLocSIRev] [decimal](18, 2) NULL,
	[BITopLocPMLPerRev] [decimal](18, 2) NULL,
	[BITopLocPMLAmtRev] [decimal](18, 2) NULL,
	[BITopLocBzShareAmtRev] [decimal](18, 2) NULL,
	[TopLocTotalSIRev] [decimal](18, 2) NULL,
	[TopLocTotalPMLPerRev] [decimal](18, 2) NULL,
	[TopLocTotalPMLAmtRev] [decimal](18, 2) NULL,
	[TopLocTotalBzShareAmtRev] [decimal](18, 2) NULL,
	[TopLocTotalSITtyAmtRev] [decimal](18, 2) NULL,
	[TopLocTotalPMLTtyPerRev] [decimal](18, 2) NULL,
	[TopLocTotalPMLTtyAmtRev] [decimal](18, 2) NULL,
	[TopLocTotalBzShareTtyAmtRev] [decimal](18, 2) NULL,
	[PMLExpOrgPMLPerRev] [decimal](18, 2) NULL,
	[PMLExpOrgPMLAmtRev] [decimal](18, 2) NULL,
	[PMLExpOrgBzShareAmtRev] [decimal](18, 2) NULL,
	[PMLExpTtyPMLPerRev] [decimal](18, 2) NULL,
	[PMLExpTtyPMLAmtRev] [decimal](18, 2) NULL,
	[PMLExpTtyBzShareAmtRev] [decimal](18, 2) NULL,
	[PMLExpOriRev] [decimal](18, 2) NULL,
	[PMLExpTreaty2Rev] [decimal](18, 2) NULL,
	[PMLIncludeRev] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PMLIncludeEndt] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CatAccumulation] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDCatAccumulation] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BICatAccumulation] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDCatAccumulationEndt] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BICatAccumulationEndt] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDCatAccumulationRev] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BICatAccumulationRev] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[ModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedDate] [datetime] NULL,
	[Tab] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDContractNo] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDShortRiskDescription] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDBeazleyShareLimit] [decimal](18, 2) NULL,
	[PDRetroactiveDate] [datetime] NULL,
	[PDRetroactiveDesciption] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDTermCondition] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1YN] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2YN] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3YN] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4YN] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5YN] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1SubLimit] [decimal](18, 2) NULL,
	[PDExtension2SubLimit] [decimal](18, 2) NULL,
	[PDExtension3SubLimit] [decimal](18, 2) NULL,
	[PDExtension4SubLimit] [decimal](18, 2) NULL,
	[PDExtension5SubLimit] [decimal](18, 2) NULL,
	[PDExtension1Remarks] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2Remarks] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3Remarks] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4Remarks] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5Remarks] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible1] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount1] [decimal](18, 2) NULL,
	[PDExcessRemarks1] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible2] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount2] [decimal](18, 2) NULL,
	[PDExcessRemarks2] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible3] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount3] [decimal](18, 2) NULL,
	[PDExcessRemarks3] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDContractNoEndt] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDShortRiskDescriptionEndt] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDBeazleyShareLimitEndt] [decimal](18, 2) NULL,
	[PDRetroactiveDateEndt] [datetime] NULL,
	[PDRetroactiveDesciptionEndt] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDTermConditionEndt] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1Endt] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2Endt] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3Endt] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4Endt] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5Endt] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1YNEndt] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2YNEndt] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3YNEndt] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4YNEndt] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5YNEndt] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1SubLimitEndt] [decimal](18, 2) NULL,
	[PDExtension2SubLimitEndt] [decimal](18, 2) NULL,
	[PDExtension3SubLimitEndt] [decimal](18, 2) NULL,
	[PDExtension4SubLimitEndt] [decimal](18, 2) NULL,
	[PDExtension5SubLimitEndt] [decimal](18, 2) NULL,
	[PDExtension1RemarksEndt] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2RemarksEndt] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3RemarksEndt] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4RemarksEndt] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5RemarksEndt] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible1Endt] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount1Endt] [decimal](18, 2) NULL,
	[PDExcessRemarks1Endt] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible2Endt] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount2Endt] [decimal](18, 2) NULL,
	[PDExcessRemarks2Endt] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible3Endt] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount3Endt] [decimal](18, 2) NULL,
	[PDExcessRemarks3Endt] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDContractNoRev] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDShortRiskDescriptionRev] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDBeazleyShareLimitRev] [decimal](18, 2) NULL,
	[PDRetroactiveDateRev] [datetime] NULL,
	[PDRetroactiveDesciptionRev] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDTermConditionRev] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1Rev] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2Rev] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3Rev] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4Rev] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5Rev] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1YNRev] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2YNRev] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3YNRev] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4YNRev] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5YNRev] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension1SubLimitRev] [decimal](18, 2) NULL,
	[PDExtension2SubLimitRev] [decimal](18, 2) NULL,
	[PDExtension3SubLimitRev] [decimal](18, 2) NULL,
	[PDExtension4SubLimitRev] [decimal](18, 2) NULL,
	[PDExtension5SubLimitRev] [decimal](18, 2) NULL,
	[PDExtension1RemarksRev] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension2RemarksRev] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension3RemarksRev] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension4RemarksRev] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExtension5RemarksRev] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible1Rev] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount1Rev] [decimal](18, 2) NULL,
	[PDExcessRemarks1Rev] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible2Rev] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount2Rev] [decimal](18, 2) NULL,
	[PDExcessRemarks2Rev] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessDeductible3Rev] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PDExcessAmount3Rev] [decimal](18, 2) NULL,
	[PDExcessRemarks3Rev] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)


