CREATE TABLE [dbo].[PolicyRegTrx](
	[TranRefNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolRefNo] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyNo] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PrevPolicyNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CoverNoteNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[OpenCoverNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CINo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[QuotationNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MOUNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateIssue] [datetime] NULL,
	[DateCreated] [datetime] NULL CONSTRAINT [DF_PolicyRegTrx_DateCreated]  DEFAULT (getdate()),
	[CreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsLatest] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_IsLatest]  DEFAULT ('Y'),
	[TranType] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_TranType]  DEFAULT ('PL'),
	[PolicyStatus] [tinyint] NULL CONSTRAINT [DF_PolicyRegTrx_PolicyStatus]  DEFAULT ((0)),
	[Status] [smallint] NULL CONSTRAINT [DF_PolicyRegTrx_Status_1]  DEFAULT ((0)),
	[PolicySource] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_PolicySource_1]  DEFAULT ('D'),
	[EntNo] [smallint] NULL,
	[RenNo] [smallint] NULL,
	[IntEntNo] [smallint] NULL CONSTRAINT [DF_PolicyRegTrx_IntEntNo]  DEFAULT ((0)),
	[BizType] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_BizType]  DEFAULT ('D'),
	[BizSource] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SubBizSource] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BranchCode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClientCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClientName] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProducerCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProducerName] [varchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProductType] [varchar](16) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProductCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProductName] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServicerCode] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ServicerName] [nvarchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProfitCentre] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClientOccupation] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CurrencyCode] [varchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExchangeRate] [decimal](18, 9) NULL CONSTRAINT [DF_PolicyRegTrx_ExchangeRate_1]  DEFAULT ((1.00)),
	[SumInsCurrencyCode] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SumInsExRate] [decimal](18, 9) NULL CONSTRAINT [DF_PolicyRegTrx_SumInsExRate_1]  DEFAULT ((1.0000)),
	[POI_Type] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POI_CommenceDate] [datetime] NULL,
	[POI_CommenceTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POI_CommenceTimeTick] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POI_ExpiryDate] [datetime] NULL,
	[POI_ExpiryTime] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POI_PeriodCount] [int] NULL CONSTRAINT [DF_PolicyRegTrx_POI_PeriodCount]  DEFAULT ((0)),
	[POI_MonthCount] [smallint] NULL CONSTRAINT [DF_PolicyRegTrx_POI_MonthCount]  DEFAULT ((0)),
	[POI_PeriodType] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POI_PeriodRemarks] [nvarchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POI_MaintExpiry] [datetime] NULL,
	[POI_MaintCount] [int] NULL,
	[POI_MaintRemarks] [nvarchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POI_ComputeMethod] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POI_ProRate] [decimal](18, 4) NULL,
	[CI_LeaderPolicyNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CI_Leader] [varchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CI_LeaderShare] [decimal](18, 4) NULL,
	[ENT_CommenceDate] [datetime] NULL,
	[ENT_ExpiryDate] [datetime] NULL,
	[ENT_IssueDate] [datetime] NULL,
	[ENT_Type] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENT_Code] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENT_Desc] [nvarchar](1500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENT_EffDate] [datetime] NULL,
	[ENT_MaintExpiry] [datetime] NULL,
	[ENT_MaintRemarks] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENT_ExpiryRemarks] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENT_ComputeMethod] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RenewalType] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REN_CommenceDate] [datetime] NULL,
	[REN_ExpiryDate] [datetime] NULL,
	[REN_Review] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REN_ReviewDate] [datetime] NULL,
	[REN_Reviewer] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REN_PrintNotice] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[REN_Desc] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[JointInsured] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[FinComCode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PremiumPaidStatus] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_PremiumPaidStatus_1]  DEFAULT ((0)),
	[InstFlag] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_InstFlag_1]  DEFAULT ('N'),
	[InstCtr] [smallint] NULL,
	[IsRenListPrint] [tinyint] NULL CONSTRAINT [DF_PolicyRegTrx_IsRenListPrint]  DEFAULT ((0)),
	[ReasonCanCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ReasonCanDesc] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProfitComm] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RateTerm] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DocumentNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DocumentIssueDate] [datetime] NULL,
	[EffPeriodFrom] [datetime] NULL,
	[EffPeriodTo] [datetime] NULL,
	[PremPaidAmt] [decimal](18, 2) NULL,
	[ClaimPaidAmt] [decimal](18, 2) NULL,
	[PremCollName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PremCollAddress] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PremCollPhone] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeliveryName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeliveryAddress] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DeliveryPhone] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpecialAcceptance] [varchar](2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LinkPolicyNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaymentBank] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaymentCCNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PaymentCCExpiryDate] [datetime] NULL,
	[ORSpecialAcceptance] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_ORSpecialAcceptance]  DEFAULT ('N'),
	[IsReadyApproved] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_IsReadyApproved]  DEFAULT ('N'),
	[Producer2Code] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Producer2Name] [varchar](70) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MarCoverNoteNo] [numeric](18, 0) NULL,
	[CedantNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PrevCPolNo] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[HandlingFee] [decimal](18, 2) NULL,
	[HandlingFee_Init] [decimal](18, 2) NULL,
	[HandlingFee_Final] [decimal](18, 2) NULL,
	[SurveyFee] [decimal](18, 2) NULL,
	[SurveyFee_Init] [decimal](18, 2) NULL,
	[SurveyFee_Final] [decimal](18, 2) NULL,
	[HandlingFeeType] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_HandlingFeeType]  DEFAULT ('A'),
	[SurveyFeeType] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_SurveyFeeType]  DEFAULT ('A'),
	[RIRequired] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_RIRequired]  DEFAULT ('N'),
	[HandlingFeeAmt] [decimal](18, 2) NULL,
	[SurveyFeeAmt] [decimal](18, 2) NULL,
	[HandlingFeeAmt_Init] [decimal](18, 2) NULL,
	[SurveyFeeAmt_Init] [decimal](18, 2) NULL,
	[HandlingFeeAmt_Final] [decimal](18, 2) NULL,
	[SurveyFeeAmt_Final] [decimal](18, 2) NULL,
	[RISrc] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[INTreaty] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BrdRefNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ENT_POI_ExpiryDate] [datetime] NULL,
	[CNAgentCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MOU] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsPolicyNoGenerated] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TempPolicyNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsFacApproved] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyRegTrx_IsFacApproved]  DEFAULT (N'N'),
	[FleetPolicy] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AbbName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyEntryTypeID] [int] NULL,
	[PolicyEntrySubID] [int] NULL,
	[LloydCode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DebitNoteNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CedentCoName] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[preview_completed] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndorsementNo] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyNo_Renewal] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Domicile] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Exposure] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskReferenceNo] [varchar](12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BusinessType] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskStatus] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateSeen] [datetime] NULL,
	[ProportionalXOL] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskGroupCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TerritoryCode] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CopyRisk] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CedantCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CedantName] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BrokerCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BrokerName] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LeadOffice] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UWYear] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateWritten] [datetime] NULL,
	[BinderYear] [char](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BinderRefNo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Prospect] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Probability] [decimal](18, 5) NULL,
	[PipelinePremium] [decimal](18, 2) NULL,
	[PendingLine] [decimal](18, 2) NULL,
	[WrittenLine] [decimal](18, 6) NULL,
	[Remarks] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XOLLayerNo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XOLLimit] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[InExcess] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[XOL_Premium] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AnnualAggrLimit] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EngineeringFee] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GrossLossRatio] [decimal](18, 2) NULL,
	[approve] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[approveby] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[approvedate] [datetime] NULL,
	[EstSign] [decimal](18, 5) NULL,
	[ActSign] [decimal](18, 5) NULL,
	[XOLCurrency] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ROE] [decimal](18, 9) NULL,
	[MemoPrint] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateSurveyed] [datetime] NULL,
	[DateDiary] [datetime] NULL,
	[DiaryStatus] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DiaryDesc] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Underwriter] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[NewRiskWritten] [datetime] NULL,
	[PremiumRemarks] [varchar](300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsWrittenLineChanged] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClintCode] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClintName] [varchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PremiumDueDate] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[COBCode] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SlipPolicyNo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CountryCode] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[IsPolDeclineOrNTU] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskTypeCode] [varchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedDate] [datetime] NULL,
	[Tab] [varchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MemoCreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MemoCreatedDate] [datetime] NULL,
	[MemoModifiedDate] [datetime] NULL,
	[MemoModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyCompletedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PolicyCompletedDate] [datetime] NULL,
	[EndorsementCreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndorsementCreatedDate] [datetime] NULL,
	[EndorsementModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EndorsementModifiedDate] [datetime] NULL,
	[RenewalCreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RenewalCreatedDate] [datetime] NULL,
	[RenewalModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RenewalModifiedDate] [datetime] NULL,
	[RemarksCreatedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RemarksCreatedDate] [datetime] NULL,
	[RemarksModifiedBy] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RemarksModifiedDate] [datetime] NULL,
	[LondonRefNo] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)


