CREATE TABLE [dbo].[PolicyClassRiskItemTrx](
	[TranRefNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RiskNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RIRefNo] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RIDispNo] [smallint] NULL,
	[Description] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Excess] [nvarchar](4000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LoadFactor] [decimal](18, 4) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_LoadFactor_1]  DEFAULT ((0)),
	[Rate] [decimal](18, 4) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_Rate_1]  DEFAULT ((0)),
	[AgentTxAmount] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_AgentTxAmount_1]  DEFAULT ((0)),
	[SumIns] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_SumIns_1]  DEFAULT ((0)),
	[Premium] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_Premium_1]  DEFAULT ((0)),
	[AnnualSumIns] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_AnnualSumIns_1]  DEFAULT ((0)),
	[AnnualPremium] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_AnnualPremium_1]  DEFAULT ((0)),
	[SumIns_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_SumIns_Init_1]  DEFAULT ((0)),
	[Premium_Init] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_Premium_Init_1]  DEFAULT ((0)),
	[SumIns_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_SumIns_Final_1]  DEFAULT ((0)),
	[Premium_Final] [decimal](18, 2) NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_Premium_Final_1]  DEFAULT ((0)),
	[StockDeclaration] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_StockDeclaration]  DEFAULT ('N'),
	[StockRate] [decimal](18, 2) NULL,
	[DiscRate] [decimal](18, 3) NULL,
	[DiscAmt] [decimal](18, 2) NULL,
	[DiscAmt_Init] [decimal](18, 2) NULL,
	[DiscAmt_Final] [decimal](18, 2) NULL,
	[DescCode] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CPremium] [decimal](18, 2) NULL,
	[CAnnualPremium] [decimal](18, 2) NULL,
	[CedantSumIns] [decimal](18, 2) NULL,
	[RIOurShare] [decimal](18, 3) NULL,
	[CDiscAmt] [decimal](18, 2) NULL,
	[DiscRate_Init] [decimal](18, 4) NULL,
	[DiscRate_Final] [decimal](18, 4) NULL,
	[IncludeSI] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_PolicyClassRiskItemTrx_IncludeSI]  DEFAULT ('Y')
)


