CREATE TABLE [dbo].[SQL Server Destination](
	[VEHICLE_REGISTRATION_NO] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_MAKE] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_MODEL] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VEHICLE_CLASS] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[MODEL_DESCRIPTION] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[BUS_CAPTAIN] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
)


