CREATE TABLE [dbo].[TClaim_Claimant](
	[ClaimantRefNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimRefNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreateDate] [datetime] NULL CONSTRAINT [DF_TClaim_Claimant_CreateDate]  DEFAULT (getdate()),
	[CreatedBy] [char](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossLocation] [nchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossDescription] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossTypeCode] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossTypeDesc] [nvarchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossNatureCode] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LossNatureDesc] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantAddress] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CatastropheCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CatastropheDesc] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VehicleRefNo] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[VesselName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Recovery] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Adjuster] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RES_CurrencyCode] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_TClaim_Claimant_RES_CurrencyCode]  DEFAULT (''),
	[RES_ExchangeRate] [decimal](18, 9) NULL CONSTRAINT [DF_TClaim_Claimant_RES_ExchangeRate]  DEFAULT ((0)),
	[RES_ReserveLoc] [decimal](18, 2) NULL CONSTRAINT [DF_TClaim_Claimant_RES_ReserveLoc]  DEFAULT ((0)),
	[RES_ReserveFor] [decimal](18, 2) NULL CONSTRAINT [DF_TClaim_Claimant_RES_ReserveFor]  DEFAULT ((0)),
	[RES_NewLoc] [decimal](18, 2) NULL CONSTRAINT [DF_TClaim_Claimant_RES_NewLoc]  DEFAULT ((0)),
	[RES_NewFor] [decimal](18, 2) NULL CONSTRAINT [DF_TClaim_Claimant_RES_NewFor]  DEFAULT ((0)),
	[AdjusterName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AdjusterCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Surveyor] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SurveyorCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SurveyorName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SurveyLocation] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Garage] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GarageCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GarageName] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GarageReceivedBy] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[GarageEnterDate] [datetime] NULL,
	[Excess] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ClaimantDispNo] [numeric](18, 0) NULL,
	[Deductible] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ItemNo] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Consult] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[UnlistGarage] [nvarchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateDiary] [datetime] NULL,
	[DiaryDesc] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SpExclusion] [nvarchar](5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RecAmount] [decimal](18, 2) NULL,
	[DeductibleAmt] [decimal](18, 2) NULL,
	[TPClaimant] [nvarchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountDescription] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[AmountDescriptionDet] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DescCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RegNo1] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RegNo2] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RegNo3] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_TClaim_Claimant] PRIMARY KEY CLUSTERED 
(
	[ClaimantRefNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


