CREATE TABLE [dbo].[TClaim_Registration](
	[TempClaimRefNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ClaimRefNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DateNotification] [datetime] NULL,
	[DateAccident] [datetime] NULL,
	[DateDiary] [datetime] NULL,
	[DiaryDesc] [nvarchar](500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Remarks] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Status] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[trx_status] [int] NULL CONSTRAINT [DF_TClaim_Registration_trx_status]  DEFAULT ((0)),
	[CreatedDate] [datetime] NULL CONSTRAINT [DF_TClaim_Registration_CreatedDate]  DEFAULT (getdate()),
	[CreatedBy] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[isApprove] [int] NOT NULL CONSTRAINT [DF_TClaim_Registration_isApprove]  DEFAULT ((0)),
	[ApproveDate] [datetime] NULL,
	[ApproveBy] [varchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CashCall_Remarks] [nvarchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[isCashCall] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_TClaim_Registration_isCashCall]  DEFAULT ('N'),
	[RES_ReserveLoc] [numeric](18, 2) NULL CONSTRAINT [DF_TClaim_Registration_RES_ReserveLoc]  DEFAULT ((0)),
	[RES_ReserveFor] [numeric](18, 2) NULL CONSTRAINT [DF_TClaim_Registration_RES_ReserveFor]  DEFAULT ((0)),
	[EXP_CurrencyCode] [nvarchar](6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EXP_ExchangeRate] [decimal](18, 9) NULL CONSTRAINT [DF_TClaim_Registration_EXP_ExchangeRate]  DEFAULT ((0)),
	[EXP_ReserveLoc] [decimal](18, 2) NULL CONSTRAINT [DF_TClaim_Registration_EXP_ReserveLoc]  DEFAULT ((0)),
	[EXP_ReserveFor] [decimal](18, 2) NULL CONSTRAINT [DF_TClaim_Registration_EXP_ReserveFor]  DEFAULT ((0)),
	[PAY_TotalLoc] [decimal](18, 2) NULL CONSTRAINT [DF_TClaim_Registration_PAY_TotalLoc]  DEFAULT ((0)),
	[POL_TranRefNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[POL_PolRefNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_EntNo] [int] NULL,
	[POL_RenNo] [int] NULL,
	[POL_DateCommence] [datetime] NULL,
	[POL_DateExpiry] [datetime] NULL,
	[POL_BranchCode] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_CurrencyCode] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_InsuredCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_InsuredName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_ProducerCode] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_ProducerName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_PolicyStatus] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_PremiumStatus] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_ProductCode] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_ProductName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_RiskID] [nvarchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_TClaim_Registration_POL_RiskID]  DEFAULT ((1)),
	[POL_RiskNo] [nchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_ClassCode] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_TClaim_Registration_POL_ClassCode]  DEFAULT (''),
	[POL_SubClassCode] [nchar](10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_SubClassName] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_SharePer] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_POL_SharePer]  DEFAULT ((0)),
	[RES_ObligatoryPer] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_RES_ObligatoryPer]  DEFAULT ((0)),
	[RES_FacRIPer] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_RES_FacRIPer]  DEFAULT ((0)),
	[RES_FacOblPer] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_RES_FacOblPer]  DEFAULT ((0)),
	[RES_SurplusPer] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_RES_SurplusPer]  DEFAULT ((0)),
	[RES_Surplus2Per] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_RES_Surplus2Per]  DEFAULT ((0)),
	[RES_GrossPer] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_RES_GrossPer]  DEFAULT ((0)),
	[RES_QuotaSharePer] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_RES_QuotaSharePer]  DEFAULT ((0)),
	[RES_XOLPer] [decimal](18, 4) NULL CONSTRAINT [DF_TClaim_Registration_RES_XOLPer]  DEFAULT ((0)),
	[ReportedBy] [varchar](80) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Converted] [tinyint] NULL CONSTRAINT [DF_TClaim_Registration_Converted]  DEFAULT ((0)),
	[RES_Surplus3Per] [decimal](18, 4) NULL,
	[RES_Surplus4Per] [decimal](18, 4) NULL,
	[RES_Surplus5Per] [decimal](18, 4) NULL,
	[Accepted] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF_TClaim_Registration_Accepted]  DEFAULT (N'N'),
	[Comments] [nvarchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TimeAccident] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Reason] [nvarchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_CI_Leader] [nvarchar](3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POL_CI_LeaderShare] [decimal](18, 4) NULL,
 CONSTRAINT [PK_TClaim_Registration] PRIMARY KEY CLUSTERED 
(
	[TempClaimRefNo] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


