CREATE TABLE [dbo].[TODODIARYLIST](
	[LISTID] [bigint] IDENTITY(1,1) NOT NULL,
	[RECBYSYSTEM] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[RECDATE] [datetime] NULL,
	[FOLLOWUPDATE] [datetime] NULL,
	[LISTTYPEID] [varchar](max) NOT NULL,
	[POLICYBROKERID] [numeric](8, 0) NULL,
	[SUBJECTLINE] [nvarchar](512) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LISTOPEN] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SYSTEMFOLLOWUPID] [numeric](18, 0) NULL,
	[PRIORITY] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[TOUSERID] [numeric](18, 0) NULL,
	[FROMUSERID] [numeric](18, 0) NULL,
	[STARTTIME] [datetime] NULL,
	[ENDTIME] [datetime] NULL,
	[NOTE] [nvarchar](2000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[PROPOSALVERSION] [numeric](18, 0) NULL,
	[QUOTEID] [numeric](18, 0) NULL,
	[CLAIMID] [int] NULL,
	[CLAIMMOVEMENTID] [numeric](18, 0) NULL,
	[TOENTITYID] [numeric](10, 0) NULL,
	[FROMENTITYID] [int] NULL,
	[CUSTOMER_ID] [int] NULL,
	[APP_ID] [int] NULL,
	[APP_VERSION_ID] [smallint] NULL,
	[POLICY_ID] [int] NULL,
	[POLICY_VERSION_ID] [smallint] NULL,
	[RULES_VERIFIED] [smallint] NULL,
	[PROCESS_ROW_ID] [int] NULL,
	[MODULE_ID] [int] NULL,
	[INSURERNAME] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[POLICYNO] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CLAIMNO] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ExpectedPaymentDate] [datetime] NULL,
	[ReminderBeforeCompletion] [int] NULL,
	[Escalation] [varchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EscalationTo] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[EmailBody] [nvarchar](max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedBy] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [nvarchar](25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ModifiedDate] [datetime] NULL,
	[UserId] [int] NULL,
	[ReassignedDiary] [nvarchar](4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL CONSTRAINT [DF__TODODIARY__Reass__3E3313D1]  DEFAULT ('No'),
	[ReassignedDiaryDate] [datetime] NULL,
	[AccidentId] [int] NULL,
	[MovementType] [nvarchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ParentId] [int] NULL,
	[IsActive] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_TODODIARYLIST_LISTID] PRIMARY KEY NONCLUSTERED 
(
	[LISTID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON),
 CONSTRAINT [FK_TODODIARYLIST_ClaimAccidentDetails] FOREIGN KEY([AccidentId])
REFERENCES [dbo].[ClaimAccidentDetails] ([AccidentClaimId])
)


