CREATE TABLE [dbo].[TODODIARYLISTTYPES_MULTILINGUAL](
	[TYPEID] [numeric](18, 0) NOT NULL,
	[TYPEDESC] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LANG_ID] [int] NOT NULL,
 CONSTRAINT [PK_TODODIARYLISTTYPES_MULTILINGUAL_TYPEID_LANG_ID] PRIMARY KEY CLUSTERED 
(
	[TYPEID] ASC,
	[LANG_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


