CREATE TABLE [dbo].[TODODIARYLISTTYPES](
	[TYPEID] [int] NOT NULL,
	[TYPEDESC] [nvarchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[SYSDEFAULT] [numeric](8, 0) NULL,
	[TYPE_FLAG] [nchar](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_TODODIARYLISTTYPES_TYPEID] PRIMARY KEY CLUSTERED 
(
	[TYPEID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
)


