//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAS.Web.Objects.Resources.ClaimRegProcPCNTX {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceProviderCrTx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceProviderCrTx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCAS.Web.Objects.Resources.ClaimRegProcPCNTX.ServiceProviderCrTx", typeof(ServiceProviderCrTx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Insurer.
        /// </summary>
        public static string AddInsurer {
            get {
                return ResourceManager.GetString("AddInsurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Lawyer.
        /// </summary>
        public static string AddLawyer {
            get {
                return ResourceManager.GetString("AddLawyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address1.
        /// </summary>
        public static string Address1 {
            get {
                return ResourceManager.GetString("Address1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address2.
        /// </summary>
        public static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address3.
        /// </summary>
        public static string Address3 {
            get {
                return ResourceManager.GetString("Address3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Surveyor.
        /// </summary>
        public static string AddSurveyor {
            get {
                return ResourceManager.GetString("AddSurveyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Workshop.
        /// </summary>
        public static string AddWorkshop {
            get {
                return ResourceManager.GetString("AddWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment Date.
        /// </summary>
        public static string AppointmentDate {
            get {
                return ResourceManager.GetString("AppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claims Registration.
        /// </summary>
        public static string ClaimsRegistration {
            get {
                return ResourceManager.GetString("ClaimsRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Type.
        /// </summary>
        public static string ClaimType {
            get {
                return ResourceManager.GetString("ClaimType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1st Contact Name.
        /// </summary>
        public static string ContactName1 {
            get {
                return ResourceManager.GetString("ContactName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2nd Contact Name.
        /// </summary>
        public static string ContactName2 {
            get {
                return ResourceManager.GetString("ContactName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string EmailAddress2 {
            get {
                return ResourceManager.GetString("EmailAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax No.
        /// </summary>
        public static string FaxNo {
            get {
                return ResourceManager.GetString("FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax No.
        /// </summary>
        public static string FaxNo2 {
            get {
                return ResourceManager.GetString("FaxNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer.
        /// </summary>
        public static string Insurer {
            get {
                return ResourceManager.GetString("Insurer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MobileNo {
            get {
                return ResourceManager.GetString("MobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No.
        /// </summary>
        public static string MobileNo2 {
            get {
                return ResourceManager.GetString("MobileNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3rd Party / Own Service Provider Information.
        /// </summary>
        public static string NewServiceProviderEntry {
            get {
                return ResourceManager.GetString("NewServiceProviderEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office No.
        /// </summary>
        public static string OfficeNo {
            get {
                return ResourceManager.GetString("OfficeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office No.
        /// </summary>
        public static string OfficeNo2 {
            get {
                return ResourceManager.GetString("OfficeNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type.
        /// </summary>
        public static string PartyType {
            get {
                return ResourceManager.GetString("PartyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref No.
        /// </summary>
        public static string ReferenceNo {
            get {
                return ResourceManager.GetString("ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add 3rd Party / Own Service Provider.
        /// </summary>
        public static string ServiceProviderEntry {
            get {
                return ResourceManager.GetString("ServiceProviderEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider Type.
        /// </summary>
        public static string ServiceProviderType {
            get {
                return ResourceManager.GetString("ServiceProviderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TP Vehicle No.
        /// </summary>
        public static string TPVehicleNo {
            get {
                return ResourceManager.GetString("TPVehicleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle No.
        /// </summary>
        public static string VehicleNo {
            get {
                return ResourceManager.GetString("VehicleNo", resourceCulture);
            }
        }
    }
}
