//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAS.Web.Objects.Resources.AdjusterMasters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Surveyor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Surveyor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCAS.Web.Objects.Resources.AdjusterMasters.Surveyor", typeof(Surveyor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        internal static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuster Code.
        /// </summary>
        internal static string AdjusterCode {
            get {
                return ResourceManager.GetString("AdjusterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuster History.
        /// </summary>
        internal static string AdjusterHistory {
            get {
                return ResourceManager.GetString("AdjusterHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuster Master.
        /// </summary>
        internal static string AdjusterMaster {
            get {
                return ResourceManager.GetString("AdjusterMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuster Master Details.
        /// </summary>
        internal static string AdjusterMasterDetails {
            get {
                return ResourceManager.GetString("AdjusterMasterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuster Name.
        /// </summary>
        internal static string AdjusterName {
            get {
                return ResourceManager.GetString("AdjusterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjuster Type.
        /// </summary>
        internal static string AdjusterType {
            get {
                return ResourceManager.GetString("AdjusterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Master.
        /// </summary>
        internal static string HospitalMaster {
            get {
                return ResourceManager.GetString("HospitalMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurer Master.
        /// </summary>
        internal static string InsurerMaster {
            get {
                return ResourceManager.GetString("InsurerMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lawyer Master.
        /// </summary>
        internal static string LawyerMaster {
            get {
                return ResourceManager.GetString("LawyerMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        internal static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Screen.
        /// </summary>
        internal static string SearchScreen {
            get {
                return ResourceManager.GetString("SearchScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Provider Master.
        /// </summary>
        internal static string ServiceProviderMaster {
            get {
                return ResourceManager.GetString("ServiceProviderMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor Code.
        /// </summary>
        internal static string SurveyorCode {
            get {
                return ResourceManager.GetString("SurveyorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor Master.
        /// </summary>
        internal static string SurveyorMaster {
            get {
                return ResourceManager.GetString("SurveyorMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor Master Details.
        /// </summary>
        internal static string SurveyorMasterDetails {
            get {
                return ResourceManager.GetString("SurveyorMasterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor Name.
        /// </summary>
        internal static string SurveyorName {
            get {
                return ResourceManager.GetString("SurveyorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveyor Type.
        /// </summary>
        internal static string SurveyorType {
            get {
                return ResourceManager.GetString("SurveyorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin.
        /// </summary>
        internal static string SystemAdmin {
            get {
                return ResourceManager.GetString("SystemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        internal static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workshop/Depot Master.
        /// </summary>
        internal static string WorkshopDepotMaster {
            get {
                return ResourceManager.GetString("WorkshopDepotMaster", resourceCulture);
            }
        }
    }
}
