IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'clm_claim' AND [COLUMN_NAME] = 'ClaimStatus')
BEGIN
ALTER TABLE [dbo].[clm_claim] ADD [ClaimStatus] [int] NULL DEFAULT 1
END