IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantName')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantName nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantNRICPPNO')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantNRICPPNO nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantDOB')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantDOB datetime NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantGender')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantGender nvarchar(10) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantType')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantType int NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantAddress1')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantAddress1 nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantAddress2')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantAddress2 nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantAddress3')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantAddress3 nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'PostalCode')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD PostalCode nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantContactNo')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantContactNo nvarchar(20) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantEmail')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantEmail nvarchar(100) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'VehicleRegnNo')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD VehicleRegnNo nvarchar(8) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'VehicleMake')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD VehicleMake nvarchar(150) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'VehicleModel')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD VehicleModel nvarchar(150) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'Isclaimantaninfant')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD Isclaimantaninfant nvarchar(5) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'InfantName')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD InfantName nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'InfantDOB')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD InfantDOB datetime NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'InfantGender')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD InfantGender nvarchar(10) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimRecordNo')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimRecordNo nvarchar(50) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimsOfficer')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimsOfficer int NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'DriverLiablity')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD DriverLiablity nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'AccidentCause')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD AccidentCause nvarchar(100) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ClaimantStatus')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ClaimantStatus nvarchar(10) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'SensitiveCase')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD SensitiveCase datetime NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ReopenedDate')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ReopenedDate datetime NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'RecordReopenedReason')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD RecordReopenedReason nvarchar(150) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'RecordCancellationDate')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD RecordCancellationDate datetime NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'RecordCancellationReason')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD RecordCancellationReason nvarchar(150) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'AccidentId')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD AccidentId int NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'MP')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD MP nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'Constituency')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD Constituency nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'DateOfMpLetter')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD DateOfMpLetter datetime NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'SeverityReferenceNo')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD SeverityReferenceNo nvarchar(50) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ReportSentToInsurer')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ReportSentToInsurer datetime NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ReferredToInsurers')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ReferredToInsurers nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'InformedInsurerOfSettlement')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD InformedInsurerOfSettlement nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'ReferredToInsurersB')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD ReferredToInsurersB bit NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'DateReferredToInsurersB')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD DateReferredToInsurersB datetime NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'Createdby')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD Createdby nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'Createddate')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD Createddate datetime null
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'Modifiedby')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD Modifiedby nvarchar(250) NULL
END
IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'Modifieddate')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD Modifieddate datetime NULL
END