IF NOT EXISTS (SELECT TOP 1* FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'MNT_Lookups' AND [COLUMN_NAME] = 'IsActive')
BEGIN
  ALTER TABLE [dbo].[MNT_Lookups] ADD IsActive char(1) NULL
END

IF NOT EXISTS (SELECT TOP 1* FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'MNT_Lookups' AND [COLUMN_NAME] = 'lookupCode')
BEGIN
  ALTER TABLE [dbo].[MNT_Lookups] ADD lookupCode varchar(10) NULL
END
IF NOT EXISTS (SELECT TOP 1* FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'MNT_Lookups' AND [COLUMN_NAME] = 'CreateDate')
BEGIN
  ALTER TABLE [dbo].[MNT_Lookups] ADD CreateDate datetime NULL
END
IF NOT EXISTS (SELECT TOP 1* FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'MNT_Lookups' AND [COLUMN_NAME] = 'CreateBy')
BEGIN
  ALTER TABLE [dbo].[MNT_Lookups] ADD CreateBy nvarchar(20) NULL
END
