IF NOT EXISTS (SELECT TOP 1* FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'MNT_BusCaptain' AND [COLUMN_NAME] = 'DateJoined')
BEGIN
  ALTER TABLE [dbo].[MNT_BusCaptain] ADD DateJoined datetime NULL
END

IF NOT EXISTS (SELECT TOP 1* FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'MNT_BusCaptain' AND [COLUMN_NAME] = 'DateResigned')
BEGIN
  ALTER TABLE [dbo].[MNT_BusCaptain] ADD DateResigned datetime NULL
END