IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = '[MNT_SYS_PARAMS]'
  AND [COLUMN_NAME] = 'FileServerPath')
BEGIN
  ALTER TABLE [dbo].MNT_SYS_PARAMS ADD [FileServerPath] [nvarchar](150)
END




IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = '[STG_TAC_IP]'
  AND [COLUMN_NAME] = 'HistoryId')
BEGIN
  ALTER TABLE [dbo].STG_TAC_IP ADD [HistoryId] [int] NULL
END




IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = '[STG_TAC_ACC_REP]'
  AND [COLUMN_NAME] = 'HistoryId')
BEGIN
  ALTER TABLE [dbo].STG_TAC_ACC_REP ADD [HistoryId] [int] NULL
END



IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = '[STG_TAC_IP_BUS]'
  AND [COLUMN_NAME] = 'HistoryId')
BEGIN
  ALTER TABLE [dbo].STG_TAC_IP_BUS ADD [HistoryId] [int] NULL
END


IF NOT EXISTS (SELECT TOP 1
    1
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = '[STG_UploadedFileData]'
  AND [COLUMN_NAME] = 'HistoryIds')
BEGIN
  ALTER TABLE [dbo].STG_UploadedFileData ADD [HistoryIds] [varchar](20) NULL
END



