IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_Reserve' AND [COLUMN_NAME] = 'ClaimantNameId')
BEGIN
ALTER TABLE [dbo].[CLM_Reserve] ADD ClaimantNameId int null
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_Reserve' AND [COLUMN_NAME] = 'HopitalNameId')
BEGIN
ALTER TABLE [dbo].[CLM_Reserve] ADD HopitalNameId int null
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_Reserve' AND [COLUMN_NAME] = 'AssignToId')
BEGIN
ALTER TABLE [dbo].[CLM_Reserve] ADD AssignToId int null
END