IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_Payment' AND [COLUMN_NAME] = 'MandateId')
BEGIN
ALTER TABLE [dbo].CLM_Payment ADD MandateId int null
END

IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_Payment' AND [COLUMN_NAME] = 'ReserveId')
BEGIN
ALTER TABLE [dbo].CLM_Payment ADD ReserveId int null
END

IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_Reserve' AND [COLUMN_NAME] = 'PaymentId')
BEGIN
ALTER TABLE [dbo].CLM_Reserve ADD PaymentId int null
END

IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_Mandate' AND [COLUMN_NAME] = 'PaymentId')
BEGIN
ALTER TABLE [dbo].CLM_Mandate ADD PaymentId int null
END

IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'Clm_MandateTransactionHistory' AND [COLUMN_NAME] = 'PaymentId')
BEGIN
ALTER TABLE [dbo].Clm_MandateTransactionHistory ADD PaymentId int null
END


IF NOT EXISTS(SELECT TOP 1 * FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_Reserve' AND [COLUMN_NAME] = 'Finalize')
BEGIN
ALTER TABLE [dbo].CLM_Reserve ADD Finalize char(1) null
END