-----Alter table add column

IF NOT EXISTS (SELECT
    *
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE table_name = 'MIG_IL_VEHICLE_DETAIL'
  AND column_name = 'FileName')

BEGIN

  ALTER TABLE MIG_IL_VEHICLE_DETAIL

  ADD FileName nvarchar(200)

END
-----End

-----Alter table change column VEHICLE_MODEL datatype

ALTER TABLE MIG_IL_VEHICLE_DETAIL ALTER COLUMN VEHICLE_MODEL varchar(100)
-----End


-----Alter table change column IMPORT_ACTION datatype

ALTER TABLE MIG_IL_VEHICLE_DETAIL ALTER COLUMN IMPORT_ACTION varchar(50)
-----End


-----Drop CONSTRAINT
IF EXISTS (SELECT
    *
  FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS
  WHERE CONSTRAINT_NAME = 'PK_MIG_IL_VEHICLE_DETAIL')

  ALTER TABLE MIG_IL_VEHICLE_DETAIL DROP CONSTRAINT PK_MIG_IL_VEHICLE_DETAIL
-----End


-----Add CONSTRAINT
ALTER TABLE MIG_IL_VEHICLE_DETAIL
ADD CONSTRAINT [PK_MIG_IL_VEHICLE_DETAIL]
PRIMARY KEY CLUSTERED
(
[UPLOAD_SERIAL_NO] ASC
)
-----End