CREATE TABLE dbo.MNT_VEHICLE_LIST
(

VEHICLE_REGISTRATION_ID INT IDENTITY(1,1) NOT NULL,
VEHICLE_REGISTRATION_NO nvarchar(100) null,
VEHICLE_MAKE nvarchar(50) null,
VEHICLE_MODEL INT null,
 VEHICLE_CLASS nvarchar(50) null,
 MODEL_DESCRIPTION nvarchar(2000) null,
 BUS_CAPTAIN nvarchar(50) null,
 [IS_ACTIVE] varchar(1) null,
 [CREATE_BY] INT NULL,
 [CREATE_DATE] DATETIME NULL,
 constraint [PK_VEHICLE_REGISTRATION_ID] primary key clustered
 (VEHICLE_REGISTRATION_ID)
);
