/****** Object:  Table [dbo].[MNT_VehicleListingUpload]    Script Date: 07/10/2014 11:02:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MNT_VEHICLELISTINGUPLOAD](
	[UPLOAD_FILE_ID] [int] IDENTITY(1,1) NOT NULL,
	[UPLOAD_FILE_REF_NO] [nvarchar](50) NOT NULL,
	[UPLOAD_FILE_NAME] [nvarchar](100) NOT NULL,
	[UPLOADED_DATE] [datetime] NOT NULL,
	[TOTAL_RECORDS] [int] NULL,
	[UPLODED_SUCCESS] [int] NULL,
	[UPLOADED_FAILED] [int] NULL,
	[STATUS] [nvarchar](50) NULL,
	[IS_PROCESSED] varchar(1) null,
	[PROCESSED_DATE] datetime null,
	[IS_ACTIVE] varchar(1) null,
	[HASERROR] varchar(50),
 CONSTRAINT [PK_MNT_VehicleListingUpload] PRIMARY KEY CLUSTERED 
(
	[UPLOAD_FILE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



