IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_ServiceProvider' AND [COLUMN_NAME] = 'PostalCode')
BEGIN
  ALTER TABLE CLM_ServiceProvider
    ALTER COLUMN PostalCode nvarchar(30) not null
END

IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_ServiceProvider' AND [COLUMN_NAME] = 'OfficeNo')
BEGIN
  ALTER TABLE CLM_ServiceProvider
    ALTER COLUMN OfficeNo nvarchar(30)
END

IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_ServiceProvider' AND [COLUMN_NAME] = 'Mobile')
BEGIN
  ALTER TABLE CLM_ServiceProvider
    ALTER COLUMN Mobile nvarchar(30)
END

IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_ServiceProvider' AND [COLUMN_NAME] = 'Fax')
BEGIN
  ALTER TABLE CLM_ServiceProvider
    ALTER COLUMN Fax nvarchar(30)
END

IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_ServiceProvider' AND [COLUMN_NAME] = 'OfficeNo2nd')
BEGIN
  ALTER TABLE CLM_ServiceProvider
    ALTER COLUMN OfficeNo2nd nvarchar(30)
END

IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_ServiceProvider' AND [COLUMN_NAME] = 'Mobile2nd')
BEGIN
  ALTER TABLE CLM_ServiceProvider
    ALTER COLUMN Mobile2nd nvarchar(30)
END

IF EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_ServiceProvider' AND [COLUMN_NAME] = 'Fax2nd')
BEGIN
  ALTER TABLE CLM_ServiceProvider
    ALTER COLUMN Fax2nd nvarchar(30)
END