--SELECT * FROM dbo.TODODIARYLIST

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'TODODIARYLIST' AND [COLUMN_NAME] = 'ExpectedPaymentDate')
BEGIN
ALTER TABLE [dbo].[TODODIARYLIST] ADD ExpectedPaymentDate DateTime
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'TODODIARYLIST' AND [COLUMN_NAME] = 'ReminderBeforeCompletion')
BEGIN
ALTER TABLE [dbo].[TODODIARYLIST] ADD ReminderBeforeCompletion INT
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'TODODIARYLIST' AND [COLUMN_NAME] = 'Escalation')
BEGIN
ALTER TABLE [dbo].[TODODIARYLIST] ADD Escalation VARCHAR(1)
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'TODODIARYLIST' AND [COLUMN_NAME] = 'EscalationTo')
BEGIN
ALTER TABLE [dbo].[TODODIARYLIST] ADD EscalationTo NVARCHAR(100)
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'TODODIARYLIST' AND [COLUMN_NAME] = 'EmailBody')
BEGIN
ALTER TABLE [dbo].[TODODIARYLIST] ADD EmailBody NVARCHAR(Max)
END