
IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLM_ClaimReserve' AND [COLUMN_NAME] = 'ClaimantType')
BEGIN
ALTER TABLE [dbo].[CLM_ClaimReserve] ADD ClaimantType VARCHAR(20)
END

