IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLAIMACCIDENTDETAILS' AND [COLUMN_NAME] = 'CreatedDate')
BEGIN
ALTER TABLE [dbo].[CLAIMACCIDENTDETAILS] ADD CreatedDate DateTime
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLAIMACCIDENTDETAILS' AND [COLUMN_NAME] = 'CreatedBy')
BEGIN
ALTER TABLE [dbo].[CLAIMACCIDENTDETAILS] ADD CreatedBy NVARCHAR(25)
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLAIMACCIDENTDETAILS' AND [COLUMN_NAME] = 'ModifiedBy')
BEGIN
ALTER TABLE [dbo].[CLAIMACCIDENTDETAILS] ADD ModifiedBy NVARCHAR(25)
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLAIMACCIDENTDETAILS' AND [COLUMN_NAME] = 'ModifiedDate')
BEGIN
ALTER TABLE [dbo].[CLAIMACCIDENTDETAILS] ADD ModifiedDate DateTime
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLAIMACCIDENTDETAILS' AND [COLUMN_NAME] = 'IsRecovery')
BEGIN
ALTER TABLE [dbo].[CLAIMACCIDENTDETAILS] ADD IsRecovery VARCHAR(1)
END

IF NOT EXISTS(SELECT TOP 1 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'CLAIMACCIDENTDETAILS' AND [COLUMN_NAME] = 'AccidentLoc')
BEGIN
ALTER TABLE [dbo].[CLAIMACCIDENTDETAILS] ADD AccidentLoc NVARCHAR(250)
END