    IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
              WHERE TABLE_NAME = 'ACT_POLICY_REIN_INSTALLMENT_DETAILS' 
                    AND COLUMN_NAME ='REIN_INSTALLMENT_NO') 
              BEGIN
                    ALTER TABLE ACT_POLICY_REIN_INSTALLMENT_DETAILS
                    ADD REIN_INSTALLMENT_NO VARCHAR(100)
               END    