IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_PERILS' AND COLUMN_NAME ='EXCEEDED_PREMIUM') 
BEGIN
ALTER TABLE POL_PERILS
ADD EXCEEDED_PREMIUM INT
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO' AND COLUMN_NAME ='EXCEEDED_PREMIUM') 
BEGIN
ALTER TABLE POL_PRODUCT_LOCATION_INFO
ADD EXCEEDED_PREMIUM INT
END


IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_MARITIME' AND COLUMN_NAME ='EXCEEDED_PREMIUM') 
BEGIN
ALTER TABLE POL_MARITIME
ADD EXCEEDED_PREMIUM INT
END


IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_PERSONAL_ACCIDENT_INFO' AND COLUMN_NAME ='EXCEEDED_PREMIUM') 
BEGIN
ALTER TABLE POL_PERSONAL_ACCIDENT_INFO
ADD EXCEEDED_PREMIUM INT
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_CIVIL_TRANSPORT_VEHICLES' AND COLUMN_NAME ='EXCEEDED_PREMIUM') 
BEGIN
ALTER TABLE POL_CIVIL_TRANSPORT_VEHICLES
ADD EXCEEDED_PREMIUM INT
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_COMMODITY_INFO' AND COLUMN_NAME ='EXCEEDED_PREMIUM') 
BEGIN
ALTER TABLE POL_COMMODITY_INFO
ADD EXCEEDED_PREMIUM INT
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_PASSENGERS_PERSONAL_ACCIDENT_INFO' AND COLUMN_NAME ='EXCEEDED_PREMIUM') 
BEGIN
ALTER TABLE POL_PASSENGERS_PERSONAL_ACCIDENT_INFO
ADD EXCEEDED_PREMIUM INT
END

IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_PENHOR_RURAL_INFO' AND COLUMN_NAME ='EXCEEDED_PREMIUM') 
BEGIN
ALTER TABLE POL_PENHOR_RURAL_INFO
ADD EXCEEDED_PREMIUM INT
END

     

