   IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'POL_REINSURANCE_INFO' 
        AND COLUMN_NAME ='MAX_NO_INSTALLMENT') 
  BEGIN
        ALTER TABLE POL_REINSURANCE_INFO
        ADD MAX_NO_INSTALLMENT INT
   END
   
   IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'POL_REINSURANCE_INFO' 
        AND COLUMN_NAME ='RISK_ID') 
  BEGIN
        ALTER TABLE POL_REINSURANCE_INFO
        ADD RISK_ID INT
   END