
IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
                  WHERE TABLE_NAME = 'MNT_SYSTEM_PARAMS' 
                        AND COLUMN_NAME ='MAXIMUM_LIMIT') 
                  BEGIN
                        ALTER TABLE MNT_SYSTEM_PARAMS
                        ADD MAXIMUM_LIMIT DECIMAL(12,2)
                   END
                   
                   
   IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'MNT_SYSTEM_PARAMS' 
        AND COLUMN_NAME ='FEES_PERCENTAGE') 
  BEGIN
        ALTER TABLE MNT_SYSTEM_PARAMS
        ADD FEES_PERCENTAGE DECIMAL(12,2)
   END
   
   
   IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'MNT_LOB_MASTER' 
        AND COLUMN_NAME ='IOF_PERCENTAGE') 
  BEGIN
        ALTER TABLE MNT_LOB_MASTER
        ADD IOF_PERCENTAGE DECIMAL(12,4)
   END


  
