
IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_LOCATIONS' AND COLUMN_NAME = 'LOC_NUM')
BEGIN
      ALTER TABLE POL_LOCATIONS  
	  ALTER COLUMN LOC_NUM BIGINT

 END
GO
IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'POL_LOCATIONS' AND COLUMN_NAME = 'SOURCE_LOCATION_ID')
BEGIN
      ALTER TABLE POL_LOCATIONS  
	  ALTER COLUMN SOURCE_LOCATION_ID BIGINT

 END
GO
