  IF NOT EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
  WHERE TABLE_NAME = 'MNT_REINSURANCE_CONTRACT' 
        AND COLUMN_NAME ='MAX_NO_INSTALLMENT') 
  BEGIN
        ALTER TABLE MNT_REINSURANCE_CONTRACT
        ADD MAX_NO_INSTALLMENT INT
   END