IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'MNT_CONTACT_LIST' AND COLUMN_NAME = 'CONTACT_FNAME')
 BEGIN
     ALTER TABLE MNT_CONTACT_LIST  
	 ALTER COLUMN CONTACT_FNAME NVARCHAR(200) NULL
 END
Go


 