IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
                  WHERE TABLE_NAME = 'MNT_SYSTEM_PARAMS' 
                        AND COLUMN_NAME ='MAXIMUM_LIMIT') 
                  BEGIN
ALTER TABLE MNT_SYSTEM_PARAMS ALTER COLUMN MAXIMUM_LIMIT DECIMAL(12,4)
END


IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
                  WHERE TABLE_NAME = 'MNT_SYSTEM_PARAMS' 
                        AND COLUMN_NAME ='MAXIMUM_LIMIT') 
                  BEGIN
ALTER TABLE MNT_SYSTEM_PARAMS ALTER COLUMN FEES_PERCENTAGE DECIMAL(12,4)
END
