 

IF NOT EXISTS 
(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
      WHERE TABLE_NAME = 'POL_CUSTOMER_POLICY_LIST' AND COLUMN_NAME = 'IL_DOCUMENT_GENERATED')
 BEGIN
      ALTER TABLE POL_CUSTOMER_POLICY_LIST  
      ADD  IL_DOCUMENT_GENERATED  BIT
        CONSTRAINT DF_POL_IL_POLICY_BOLETO_DETAILS_IL_DOCUMENT_GENERATED DEFAULT '0'  
 END
 GO
 