
IF NOT EXISTS (SELECT  * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='536')
BEGIN
INSERT INTO MNT_SCREEN_LIST(SCREEN_ID, SCREEN_DESC,SCREEN_PATH, SCREEN_READ, SCREEN_WRITE, SCREEN_DELETE, SCREEN_EXECUTE, IS_ACTIVE)
VALUES
('536', 'Susep Reports', '/cms/Reports/Aspx/Susep_Reports.aspx', 1, 1, 1, 1, 'Y')
END	


IF NOT EXISTS (SELECT  * FROM MNT_SCREEN_LIST_MULTILINGUAL WHERE SCREEN_ID='536')
BEGIN
INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL(SCREEN_ID, SCREEN_DESC,LANG_ID)VALUES('536','Susep Reports', 2)
END

