If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=100 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Contábil' where ACTIVITY_ID=100 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=501 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Sinistro Fechado' where ACTIVITY_ID=501 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=500 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Sinistro Processado' where ACTIVITY_ID=500 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=502 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Reserva de Sinistro atualizado pelo Índice Monetário' where ACTIVITY_ID=502 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=200 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Apólice Processada' where ACTIVITY_ID=200 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=200 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Apólice Processada' where ACTIVITY_ID=200 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=10 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Gerenciamento de Serviços' where ACTIVITY_ID=10 and LANG_ID=2 
END




if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=990)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Documento rejeitado pelo Pagnet-Retornou para Ebix'
where INTERFACE_CODE=990

if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=991)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Documento rejeitado pelo Pagnet-Esperando por correção no Pagnet'
where INTERFACE_CODE=991