
IF NOT EXISTS(SELECT * FROM MNT_COUNTRY_LIST WHERE COUNTRY_ID=7)
BEGIN

INSERT INTO dbo.MNT_COUNTRY_LIST 
select 7,
'SG',
'Singapore',
COUNTRY_DESC,
CREATED_BY,
CREATED_DATETIME,
MODIFIED_BY,
LAST_UPDATED_DATETIME,
DISPLAY_ALL,
IS_ACTIVE from MNT_COUNTRY_LIST where COUNTRY_ID = 1

END
--select * from MNT_LOOKUP_TABLES where LOOKUP_ID = 1361
--select * from MNT_LOOKUP_VALUES where LOOKUP_ID = 1361--LOOKUP_UNIQUE_ID = 14546

--select MAX(LOOKUP_UNIQUE_ID)+1 from MNT_LOOKUP_VALUES

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=114301)
BEGIN


INSERT INTO dbo.MNT_LOOKUP_VALUES
select 114301,
LOOKUP_ID,
3,
'SGDS',
'SG Dollar',
3,
IS_ACTIVE,
LAST_UPDATED_DATETIME,
LOOKUP_FRAME_OR_MASONRY,
Type,
NSS_VALUE_CODE from MNT_LOOKUP_VALUES where LOOKUP_UNIQUE_ID = 14546


END