IF NOT EXISTS(SELECT * FROM MNT_COVERAGE where COV_ID = '10101')
BEGIN
INSERT INTO [dbo].[MNT_COVERAGE]
           ([COV_ID]
           ,[COV_REF_CODE]
           ,[COV_CODE]
           ,[COV_DES]
           ,[STATE_ID]
           ,[LOB_ID]
           ,[IS_ACTIVE]
           ,[IS_DEFAULT]
           ,[TYPE]
           ,[PURPOSE]
           ,[LIMIT_TYPE]
           ,[DEDUCTIBLE_TYPE]
           ,[IsLimitApplicable]
           ,[IsDeductApplicable]
           ,[IS_MANDATORY]
           ,[INCLUDED]
           ,[COVERAGE_TYPE]
           ,[RANK]
           ,[EFFECTIVE_FROM_DATE]
           ,[EFFECTIVE_TO_DATE]
           ,[DISABLED_DATE]
           ,[ISADDDEDUCTIBLE_APP]
           ,[ADDDEDUCTIBLE_TYPE]
           ,[COMPONENT_CODE]
           ,[FORM_NUMBER]
           ,[EDITION_DATE]
           ,[NSS_VALUE_CODE]
           ,[NSS_SUBLINE_CODE]
           ,[NSS_LOSSTYPE_CODE]
           ,[REINSURANCE_LOB]
           ,[REINSURANCE_COV]
           ,[ASLOB]
           ,[REINSURANCE_CALC]
           ,[COMM_VEHICLE]
           ,[COMM_REIN_COV_CAT]
           ,[REIN_ASLOB]
           ,[COMM_CALC]
           ,[REIN_REPORT_BUCK]
           ,[REIN_REPORT_BUCK_COMM]
           ,[SHOW_ACT_PREMIUM]
           ,[IS_SYSTEM_GENERAED]
           ,[MANDATORY_DATE]
           ,[NON_MANDATORY_DATE]
           ,[DEFAULT_DATE]
           ,[NON_DEFAULT_DATE]
           ,[DISPLAY_ON_CLAIM]
           ,[CLAIM_RESERVE_APPLY]
           ,[IS_MAIN]
           ,[SUB_LOB_ID]
           ,[CARRIER_COV_CODE]
           ,[CLM_PAYMENT_TYPE]
           ,[COV_TYPE_ABBR]
           ,[SUSEP_COV_CODE])
     VALUES
           (10101
           ,''
           ,'SGCOM'
           ,'Comprehensive'
           ,0
           ,-99
           ,'Y'
           ,0
           ,1
           ,1
           ,3
           ,3
           ,0
           ,0
           ,0
           ,NULL
           ,'QQ'
           ,NULL
           ,'1985-01-01 00:00:00.000'
           ,'2999-01-01 00:00:00.000'
           ,'2999-01-01 00:00:00.000'
           ,''
           ,''
           ,'SGCOM'
           ,''
           ,NULL
           ,''
           ,''
           ,''
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,''
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,0
           ,1
           ,1
           ,NULL
           ,NULL
           ,NULL)
           
END
GO

IF NOT EXISTS(SELECT * FROM MNT_COVERAGE where COV_ID = '10102')
BEGIN
INSERT INTO [dbo].[MNT_COVERAGE]
           ([COV_ID]
           ,[COV_REF_CODE]
           ,[COV_CODE]
           ,[COV_DES]
           ,[STATE_ID]
           ,[LOB_ID]
           ,[IS_ACTIVE]
           ,[IS_DEFAULT]
           ,[TYPE]
           ,[PURPOSE]
           ,[LIMIT_TYPE]
           ,[DEDUCTIBLE_TYPE]
           ,[IsLimitApplicable]
           ,[IsDeductApplicable]
           ,[IS_MANDATORY]
           ,[INCLUDED]
           ,[COVERAGE_TYPE]
           ,[RANK]
           ,[EFFECTIVE_FROM_DATE]
           ,[EFFECTIVE_TO_DATE]
           ,[DISABLED_DATE]
           ,[ISADDDEDUCTIBLE_APP]
           ,[ADDDEDUCTIBLE_TYPE]
           ,[COMPONENT_CODE]
           ,[FORM_NUMBER]
           ,[EDITION_DATE]
           ,[NSS_VALUE_CODE]
           ,[NSS_SUBLINE_CODE]
           ,[NSS_LOSSTYPE_CODE]
           ,[REINSURANCE_LOB]
           ,[REINSURANCE_COV]
           ,[ASLOB]
           ,[REINSURANCE_CALC]
           ,[COMM_VEHICLE]
           ,[COMM_REIN_COV_CAT]
           ,[REIN_ASLOB]
           ,[COMM_CALC]
           ,[REIN_REPORT_BUCK]
           ,[REIN_REPORT_BUCK_COMM]
           ,[SHOW_ACT_PREMIUM]
           ,[IS_SYSTEM_GENERAED]
           ,[MANDATORY_DATE]
           ,[NON_MANDATORY_DATE]
           ,[DEFAULT_DATE]
           ,[NON_DEFAULT_DATE]
           ,[DISPLAY_ON_CLAIM]
           ,[CLAIM_RESERVE_APPLY]
           ,[IS_MAIN]
           ,[SUB_LOB_ID]
           ,[CARRIER_COV_CODE]
           ,[CLM_PAYMENT_TYPE]
           ,[COV_TYPE_ABBR]
           ,[SUSEP_COV_CODE])
     VALUES
           (10102
           ,''
           ,'SGTHP'
           ,'Third party'
           ,0
           ,-99
           ,'Y'
           ,0
           ,1
           ,1
           ,3
           ,3
           ,0
           ,0
           ,0
           ,NULL
           ,'QQ'
           ,NULL
           ,'1985-01-01 00:00:00.000'
           ,'2999-01-01 00:00:00.000'
           ,'2999-01-01 00:00:00.000'
           ,''
           ,''
           ,'SGTHP'
           ,''
           ,NULL
           ,''
           ,''
           ,''
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,''
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,0
           ,1
           ,1
           ,NULL
           ,NULL
           ,NULL)
           
END
GO

IF NOT EXISTS(SELECT * FROM MNT_COVERAGE where COV_ID = '10103')
BEGIN
INSERT INTO [dbo].[MNT_COVERAGE]
           ([COV_ID]
           ,[COV_REF_CODE]
           ,[COV_CODE]
           ,[COV_DES]
           ,[STATE_ID]
           ,[LOB_ID]
           ,[IS_ACTIVE]
           ,[IS_DEFAULT]
           ,[TYPE]
           ,[PURPOSE]
           ,[LIMIT_TYPE]
           ,[DEDUCTIBLE_TYPE]
           ,[IsLimitApplicable]
           ,[IsDeductApplicable]
           ,[IS_MANDATORY]
           ,[INCLUDED]
           ,[COVERAGE_TYPE]
           ,[RANK]
           ,[EFFECTIVE_FROM_DATE]
           ,[EFFECTIVE_TO_DATE]
           ,[DISABLED_DATE]
           ,[ISADDDEDUCTIBLE_APP]
           ,[ADDDEDUCTIBLE_TYPE]
           ,[COMPONENT_CODE]
           ,[FORM_NUMBER]
           ,[EDITION_DATE]
           ,[NSS_VALUE_CODE]
           ,[NSS_SUBLINE_CODE]
           ,[NSS_LOSSTYPE_CODE]
           ,[REINSURANCE_LOB]
           ,[REINSURANCE_COV]
           ,[ASLOB]
           ,[REINSURANCE_CALC]
           ,[COMM_VEHICLE]
           ,[COMM_REIN_COV_CAT]
           ,[REIN_ASLOB]
           ,[COMM_CALC]
           ,[REIN_REPORT_BUCK]
           ,[REIN_REPORT_BUCK_COMM]
           ,[SHOW_ACT_PREMIUM]
           ,[IS_SYSTEM_GENERAED]
           ,[MANDATORY_DATE]
           ,[NON_MANDATORY_DATE]
           ,[DEFAULT_DATE]
           ,[NON_DEFAULT_DATE]
           ,[DISPLAY_ON_CLAIM]
           ,[CLAIM_RESERVE_APPLY]
           ,[IS_MAIN]
           ,[SUB_LOB_ID]
           ,[CARRIER_COV_CODE]
           ,[CLM_PAYMENT_TYPE]
           ,[COV_TYPE_ABBR]
           ,[SUSEP_COV_CODE])
     VALUES
           (10103
           ,''
           ,'SGTHPFT'
           ,'Third Party Fire and Theft'
           ,0
           ,-99
           ,'Y'
           ,0
           ,1
           ,1
           ,3
           ,3
           ,0
           ,0
           ,0
           ,NULL
           ,'QQ'
           ,NULL
           ,'1985-01-01 00:00:00.000'
           ,'2999-01-01 00:00:00.000'
           ,'2999-01-01 00:00:00.000'
           ,''
           ,''
           ,'SGTHPFT'
           ,''
           ,NULL
           ,''
           ,''
           ,''
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,''
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,0
           ,1
           ,1
           ,NULL
           ,NULL
           ,NULL)
END
           
GO

