IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'ACT_BANK_INFORMATION' AND COLUMN_NAME = 'ADD_NUMBER')
 BEGIN
     ALTER TABLE ACT_BANK_INFORMATION  
     Add ADD_NUMBER NVARCHAR(40) NULL
 END
 go
  IF NOT EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'ACT_BANK_INFORMATION' AND COLUMN_NAME = 'BANK_TYPE')
 BEGIN
     ALTER TABLE ACT_BANK_INFORMATION  
	 ADD BANK_TYPE Int NULL
 END
 go

