IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'MNT_DIV_LIST' AND COLUMN_NAME = 'DIV_NAME')
 BEGIN
     ALTER TABLE MNT_DIV_LIST  
	 ALTER COLUMN DIV_NAME NVARCHAR(200) NULL
 END
 go
