IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MNT_RATING_LIST_LOG') AND type in (N'U'))
DROP TABLE dbo.MNT_RATING_LIST_LOG
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO


CREATE TABLE dbo.MNT_RATING_LIST_LOG
(
      RATING_LOG_ID INT NOT NULL,
      RATING_ID INT NOT NULL,
      AGENCY_ID INT NULL,
      RATED nvarchar (6) NULL,
      EFFECTIVE_YEAR INT NULL,
      IS_ACTIVE BIT,
      CREATED_BY INT NULL,
      CREATED_DATETIME datetime NULL,
      MODIFIED_BY INT NULL,
      LAST_UPDATED_DATETIME datetime NULL   
) 
GO

ALTER TABLE dbo.MNT_RATING_LIST_LOG ADD CONSTRAINT PK_MNT_RATING_LIST_LOG_LIST_RATING_ID PRIMARY KEY
      CLUSTERED
      (
            RATING_LOG_ID ASC

      )     WITH
      (
            PAD_INDEX = OFF
            ,STATISTICS_NORECOMPUTE = OFF
            ,IGNORE_DUP_KEY = OFF
            ,ALLOW_ROW_LOCKS = ON
            ,ALLOW_PAGE_LOCKS = ON
      ) 
GO

ALTER TABLE dbo.MNT_RATING_LIST_LOG ADD CONSTRAINT FK_MNT_RATING_LIST_LOG_LIST FOREIGN KEY
      (
            RATING_ID     
	  )
      REFERENCES dbo.MNT_CURRENT_RATING_LIST
      (
            RATING_ID
      ) 
GO
 EXEC Proc_AddExtendedProperty MNT_RATING_LIST_LOG
GO