IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'MNT_DEPT_LIST' AND COLUMN_NAME = 'DEPT_NAME')
 BEGIN
     ALTER TABLE MNT_DEPT_LIST  
	 ALTER COLUMN DEPT_NAME NVARCHAR(200) NULL
 END
 go
 