


SELECT REC_ID=IDENTITY(INT,9 ,1),* INTO #TEMPTABLE  FROM
 (
SELECT 
 B.AGENCY_ID AS AGENCY_ID
 ,B.DIV_ID AS DIV_ID
 ,B.DEPT_ID AS DEPT_ID , 
 (SELECT MAX(MDPM.PC_ID)FROM MNT_DEPT_PC_MAPPING MDPM WITH(NOLOCK) WHERE MDPM.DEPT_ID =B.DEPT_ID) AS PC_ID 
 
 FROM  
 ( 
     SELECT AGENCY_ID
     ,DIV_ID,
     (SELECT MAX(DEPT_ID) FROM MNT_DIV_DEPT_MAPPING MDDM WITH(NOLOCK) WHERE MDDM.DIV_ID= A.DIV_ID)DEPT_ID
 FROM 
     ( SELECT MAL.AGENCY_ID AS AGENCY_ID, MDL.DIV_ID AS DIV_ID
       FROM MNT_AGENCY_LIST MAL with(nolock) 
       JOIN MNT_DIV_LIST MDL WITH(NOLOCK) ON CAST (MAL.NUM_AGENCY_CODE 
       AS NVARCHAR(20))=MDL.DIV_CODE) A)B)C
 
 INSERT INTO MNT_DEFAULT_HIERARCHY 
   ( REC_ID, AGENCY_ID,DIV_ID,DEPT_ID,PC_ID,IS_ACTIVE,CREATED_BY,CREATED_DATETIME,MODIFIED_BY,
     LAST_UPDATED_DATETIME )
 SELECT *,'Y','248',GETDATE(),'248',GETDATE() FROM #TEMPTABLE

  DROP TABLE #TEMPTABLE
  

 
 

