IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='MIG_IL_POLICY_RISK_DETAILS' AND COLUMN_NAME='RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE MIG_IL_POLICY_RISK_DETAILS
ALTER COLUMN RISK_ID_LINK_WITH_CLAIM nvarchar(100)
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POL_PERILS' AND COLUMN_NAME='IL_RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE POL_PERILS
ADD IL_RISK_ID_LINK_WITH_CLAIM NVARCHAR(100)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POL_PRODUCT_LOCATION_INFO' AND COLUMN_NAME='IL_RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE POL_PRODUCT_LOCATION_INFO
ADD IL_RISK_ID_LINK_WITH_CLAIM NVARCHAR(100)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POL_MARITIME' AND COLUMN_NAME='IL_RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE POL_MARITIME
ADD IL_RISK_ID_LINK_WITH_CLAIM NVARCHAR(100)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POL_PERSONAL_ACCIDENT_INFO' AND COLUMN_NAME='IL_RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE POL_PERSONAL_ACCIDENT_INFO
ADD IL_RISK_ID_LINK_WITH_CLAIM NVARCHAR(100)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POL_CIVIL_TRANSPORT_VEHICLES' AND COLUMN_NAME='IL_RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE POL_CIVIL_TRANSPORT_VEHICLES
ADD IL_RISK_ID_LINK_WITH_CLAIM NVARCHAR(100)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POL_COMMODITY_INFO' AND COLUMN_NAME='IL_RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE POL_COMMODITY_INFO
ADD IL_RISK_ID_LINK_WITH_CLAIM NVARCHAR(100)
END


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POL_PASSENGERS_PERSONAL_ACCIDENT_INFO' AND COLUMN_NAME='IL_RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE POL_PASSENGERS_PERSONAL_ACCIDENT_INFO
ADD IL_RISK_ID_LINK_WITH_CLAIM NVARCHAR(100)
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='POL_PENHOR_RURAL_INFO' AND COLUMN_NAME='IL_RISK_ID_LINK_WITH_CLAIM')
BEGIN
ALTER TABLE POL_PENHOR_RURAL_INFO
ADD IL_RISK_ID_LINK_WITH_CLAIM NVARCHAR(100)
END



IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='MIG_IL_POLICY_REMUNERATION_DETAILS' AND COLUMN_NAME='NAME')
BEGIN
ALTER TABLE MIG_IL_POLICY_REMUNERATION_DETAILS
ALTER COLUMN NAME nvarchar(20)
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='MIG_IL_POLICY_DETAILS' AND COLUMN_NAME='BROKER')
BEGIN
ALTER TABLE MIG_IL_POLICY_DETAILS
ALTER COLUMN BROKER nvarchar(20)
END


IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL WHERE ERROR_TYPE_ID=136)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL (ERROR_TYPE_ID,TYPE_ID,ERROR_DESCRIPTION,IS_ACTIVE,CREATED_BY,CREATED_DATETIME,MODIFIED_BY,LAST_UPDATED_DATETIME) 
                  VALUES(136,1,'Uploaded file has less columns than defined standard format.','Y',NULL,NULL,NULL,NULL)                                             
END

IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL WHERE ERROR_TYPE_ID=137)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL (ERROR_TYPE_ID,TYPE_ID,ERROR_DESCRIPTION,IS_ACTIVE,CREATED_BY,CREATED_DATETIME,MODIFIED_BY,LAST_UPDATED_DATETIME) 
                  VALUES(137,1,'Uploaded file has more columns than defined standard format.','Y',NULL,NULL,NULL,NULL)                                             
END

IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL_MULTILINGUAL WHERE ERROR_TYPE_ID=136)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL_MULTILINGUAL (ERROR_TYPE_ID,TYPE_DESC,LANG_ID) VALUES(136,'Arquivo enviado tem colunas menos de formato definido pelo padrão',2)
END

IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL_MULTILINGUAL WHERE ERROR_TYPE_ID=137)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL_MULTILINGUAL (ERROR_TYPE_ID,TYPE_DESC,LANG_ID) VALUES(137,'Arquivo enviado tem mais colunas do que formato definido pelo padrão',2)
END


IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL WHERE ERROR_TYPE_ID=249)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL (ERROR_TYPE_ID,TYPE_ID,ERROR_DESCRIPTION,IS_ACTIVE,CREATED_BY,CREATED_DATETIME,MODIFIED_BY,LAST_UPDATED_DATETIME) 
                  VALUES(249,1,'Victim does not exists','Y',NULL,NULL,NULL,NULL)                                              
END

IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL WHERE ERROR_TYPE_ID=250)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL (ERROR_TYPE_ID,TYPE_ID,ERROR_DESCRIPTION,IS_ACTIVE,CREATED_BY,CREATED_DATETIME,MODIFIED_BY,LAST_UPDATED_DATETIME) 
                  VALUES(250,1,'Payee already exists.','Y',NULL,NULL,NULL,NULL)                                               
END


IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL_MULTILINGUAL WHERE ERROR_TYPE_ID=249)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL_MULTILINGUAL (ERROR_TYPE_ID,TYPE_DESC,LANG_ID) VALUES(249,'Vítima não existe.',2)
END

IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL_MULTILINGUAL WHERE ERROR_TYPE_ID=250)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL_MULTILINGUAL (ERROR_TYPE_ID,TYPE_DESC,LANG_ID) VALUES(250,'Cobertura não pode inserir porque a atividade já está criado.',2)
END


IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POL_PERILS' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE POL_PERILS
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POL_PRODUCT_LOCATION_INFO' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE POL_PRODUCT_LOCATION_INFO
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POL_PERSONAL_ACCIDENT_INFO' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE POL_PERSONAL_ACCIDENT_INFO
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POL_CIVIL_TRANSPORT_VEHICLES' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE POL_CIVIL_TRANSPORT_VEHICLES
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POL_COMMODITY_INFO' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE POL_COMMODITY_INFO
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POL_PENHOR_RURAL_INFO' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE POL_PENHOR_RURAL_INFO
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POL_MARITIME' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE POL_MARITIME
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='POL_PASSENGERS_PERSONAL_ACCIDENT_INFO' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE POL_PASSENGERS_PERSONAL_ACCIDENT_INFO
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS  WHERE TABLE_NAME='CLM_INSURED_PRODUCT' AND COLUMN_NAME='IL_RISK_ID')
BEGIN
ALTER TABLE CLM_INSURED_PRODUCT
ALTER COLUMN IL_RISK_ID NVARCHAR(100) NULL 
END



IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL WHERE ERROR_TYPE_ID=213)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL (ERROR_TYPE_ID,TYPE_ID,ERROR_DESCRIPTION,IS_ACTIVE,CREATED_BY,CREATED_DATETIME,MODIFIED_BY,LAST_UPDATED_DATETIME) 
                  VALUES(213,1,'Risk is not exists for given customer.','Y',NULL,NULL,NULL,NULL)                                           
END  

IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL WHERE ERROR_TYPE_ID=214)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL (ERROR_TYPE_ID,TYPE_ID,ERROR_DESCRIPTION,IS_ACTIVE,CREATED_BY,CREATED_DATETIME,MODIFIED_BY,LAST_UPDATED_DATETIME) 
                  VALUES(214,1,'Beneficiary name is already exists for given customer.','Y',NULL,NULL,NULL,NULL)                                           
END  

IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL_MULTILINGUAL WHERE ERROR_TYPE_ID=213)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL_MULTILINGUAL (ERROR_TYPE_ID,TYPE_DESC,LANG_ID) VALUES(213,'Risco não é existe para determinado cliente.',2)
END


IF NOT EXISTS(SELECT * FROM MIG_ERROR_TYPE_DETAIL_MULTILINGUAL WHERE ERROR_TYPE_ID=214)
BEGIN
INSERT INTO MIG_ERROR_TYPE_DETAIL_MULTILINGUAL (ERROR_TYPE_ID,TYPE_DESC,LANG_ID) VALUES(214,'Nome beneficiário já existe para determinado cliente.',2)
END

