--Insert Script For TimeZone Lists Multilingual
IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=13 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(13,'ATST','Hora do Atlântico(Canadá)',2)
End

IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=14 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(14,'EST','Hora do Leste',2)
End

IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=15 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(15,'IEST','Hora do Leste da Índia',2)
End


IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=16 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(16,'CST','Hora Central',2)
End

IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=17 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(17,'AZST','Arizona',2)
End

IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=18 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(18,'MST','Hora das Montanhas',2)
End

IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=19 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(19,'PST','Hora do Pacífico',2)
End

IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=20 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(20,'AKST','Hora do Alasca',2)
End

IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=21 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(21,'AST','Hora das Ilhas Aleutian',2)
End

IF NOT EXISTS(Select * from MNT_TIME_ZONE_LIST_MULTILINGUAL where TIME_ID=22 and LANG_ID=2)
Begin
Insert into MNT_TIME_ZONE_LIST_MULTILINGUAL(TIME_ID,TIME_CODE,TIME_DESC,LANG_ID)values(22,'HST','Hora do Havaí',2)
End
