IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_ID=1447 AND LOOKUP_UNIQUE_ID=14974)
BEGIN
      INSERT INTO MNT_LOOKUP_VALUES
      (
            LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,IS_ACTIVE
      )
      VALUES
      (
            14974,1447,1,'S&P','S&P','Y'
      )
END
GO

IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_ID=1447 AND LOOKUP_UNIQUE_ID=14975)
BEGIN

      INSERT INTO MNT_LOOKUP_VALUES
      (
            LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,IS_ACTIVE
      )
      VALUES
      (
            14975,1447,2,'FCH','FITCH','Y'
      )
END
GO

IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_ID=1447 AND LOOKUP_UNIQUE_ID=14973)
BEGIN
	INSERT INTO MNT_LOOKUP_VALUES
	(
		LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,IS_ACTIVE
	)
	VALUES
	(
		14973,1447,3,'AMBEST','AM Best','Y'
	)
 END
GO
