SELECT * FROM POL_RISK_DETAIL
INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(9,'0196','LOCATION,ADDRESS,NUMBER','POL_PERILS','PERIL_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(10,'0116','LOCATION','POL_PRODUCT_LOCATION_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(11,'0118','LOCATION','POL_PRODUCT_LOCATION_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(12,'0351','LOCATION','POL_PRODUCT_LOCATION_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(13,'0433','VESSEL_NUMBER,NAME_OF_VESSEL','POL_MARITIME','MARITIME_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(14,'0171','LOCATION','POL_PRODUCT_LOCATION_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(15,'0981','CODE,STATE_ID','POL_PERSONAL_ACCIDENT_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(16,'0115','LOCATION','POL_PRODUCT_LOCATION_INFO','VEHICLE_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(17,'0553','VEHICLE_NUMBER,FIPE_CODE,MAKE_MODEL','POL_CIVIL_TRANSPORT_VEHICLES','VEHICLE_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(18,'0523','VEHICLE_NUMBER,FIPE_CODE,MAKE_MODEL','POL_CIVIL_TRANSPORT_VEHICLES','VEHICLE_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(19,'0114','LOCATION','POL_PRODUCT_LOCATION_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(20,'0621','COMMODITY_NUMBER,COMMODITY,CONVEYANCE','POL_COMMODITY_INFO','COMMODITY_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(21,'0982','CODE,STATE_ID','POL_PERSONAL_ACCIDENT_INFO','PERSONAL_INFO_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(22,'0520','NUMBER_OF_PASSENGERS','POL_PASSENGERS_PERSONAL_ACCIDENT_INFO','PERSONAL_ACCIDENT_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(23,'0622','COMMODITY_NUMBER,COMMODITY,CONVEYANCE','POL_COMMODITY_INFO','COMMODITY_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(25,'0111','LOCATION','POL_PRODUCT_LOCATION_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(26,'0167','LOCATION,ADDRESS,NUMBER','POL_PERILS','PERIL_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(27,'0173','LOCATION','POL_PRODUCT_LOCATION_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(28,'0435','VEHICLE_NUMBER,FIPE_CODE,MAKE_MODEL','POL_CIVIL_TRANSPORT_VEHICLES','VEHICLE_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(29,'0531','VEHICLE_NUMBER,FIPE_CODE,MAKE_MODEL','POL_CIVIL_TRANSPORT_VEHICLES','VEHICLE_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(30,'0589','VEHICLE_NUMBER,FIPE_CODE,MAKE_MODEL','POL_CIVIL_TRANSPORT_VEHICLES','VEHICLE_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(31,'0654','VEHICLE_NUMBER,FIPE_CODE,MAKE_MODEL','POL_CIVIL_TRANSPORT_VEHICLES','VEHICLE_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(32,'0750','LOCATION','POL_PRODUCT_LOCATION_INFO','PRODUCT_RISK_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(33,'0977','CODE,STATE_ID','POL_PERSONAL_ACCIDENT_INFO','PERSONAL_INFO_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(34,'0993','CODE,STATE_ID','POL_PERSONAL_ACCIDENT_INFO','PERSONAL_INFO_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(35,'1163','ITEM_NUMBER,FESR_COVERAGE,MODE','POL_PENHOR_RURAL_INFO','PENHOR_RURAL_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(36,'0588','VEHICLE_NUMBER,FIPE_CODE,MAKE_MODEL','POL_CIVIL_TRANSPORT_VEHICLES','VEHICLE_ID')

INSERT INTO POL_RISK_DETAIL
(LOB_ID,SUSEP_LOB_CODE,DISPLAY_COLUMN_NAME,TABLE_NAME,RISK_ID)
VALUES
(37,'0746','ITEM_NUMBER,FESR_COVERAGE,MODE','POL_PENHOR_RURAL_INFO','PENHOR_RURAL_ID')
