---script to insert the missing value in POL_PROCESS_MASTER_MULTILINGUAL for langid =3


IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=2 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (2,'Cancel Policy','CANCEL','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=3 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (3,'Endorsement','ENDORSE','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=4 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (4,'Reinstate','REINST','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=5 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (5,'Renewal','RENEWAL','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=6 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (6,'Non-Renew','NRENEW','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=7 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (7,'Negate',	'NEGT','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=8 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (8,'Corrective User Process','CORUSER','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=9 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (9,'Commit Corrective User Process','CCORUSER','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=10 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (10,'Rollback Corrective User Process','RCORUSER','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=12 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (12,'Commit Cancellation Process','CCANCEL','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=13 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (13,'Rollback Cancellation Process','RCANCEL','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=14 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (14,'Commit Endorsement Process','CENDORSE','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=15 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (15,'Rollback Endorsement Process','RENDORSE','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=16 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (16,'Commit Reinstate Process','CREINST','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=17 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (17,'Rollback Reinstate Process','RREINST','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=18 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (18,'Commit Renewal Process','CRENEWAL','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=19 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (19,'Rollback Renewal Process','RRENEWAL','Y',3)
END
IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=20 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (20,'Commit Non-Renewal Process','CNRENEW','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=21 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (21,'Rollback Non-Renewal Process','RNRENEW','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=22 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (22,'Commit Negate Process','CNEGT','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=23 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (23,'Rollback Negate Process','RNEGT','Y',3)
END
	
IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=24 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (24,'New Business','NBUS','Y',3)
END
IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=25 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (25,'Commit New Business','CNBUS','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=26 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (26,'Reject New Business','RNBUS','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=27 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (27,'Policy Decline','DECPOL','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=31 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (31,'Rewrite','REWRTE','Y',3)
END
IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=32 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (32,'Commit Rewrite Process','CREWRTE','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=33 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (33,'Rollback Rewrite Process','RREWRTE','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=35 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (35,'Un Do Endorsement','REVERT','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=36 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (36,'Rollback Un Do Endorsement','RREVERT','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=37 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (37,'Commit Un Do Endorsement','CREVERT','Y',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=28 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (28,'Rescind Process','DECPOL','N',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=29 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (29,'Commit Rescind Process','CDECPOL','N',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=30 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (30,'Rollback Rescind Process','RDECPOL','N',3)
END

IF NOT EXISTS (SELECT * FROM POL_PROCESS_MASTER_MULTILINGUAL WHERE PROCESS_ID=34 AND LANG_ID=3)
BEGIN
INSERT INTO POL_PROCESS_MASTER_MULTILINGUAL (PROCESS_ID,PROCESS_DESC,PROCESS_SHORTNAME,IS_ACTIVE,LANG_ID)
	VALUES (34,'Endorsement in Suspense','SENDORSE','N',3)
END
