
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('APURACAO DE RESULTADO OPERACIONAL',  'SP_POLICY','Excel', 'Y',14955)

INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ( 'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE','SP_INSTALLMENTS', 'Excel', 'Y',14955)

INSERT  INTO MNT_SUSEP_REPORTS_LIST VALUES ('DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE','SP_BROKER_INSTALLMENTS', 'Excel', 'Y',14955)

INSERT  INTO MNT_SUSEP_REPORTS_LIST VALUES ('DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE','SP_CLAIM',  'Excel', 'Y',14955)

INSERT  INTO MNT_SUSEP_REPORTS_LIST VALUES ( 'REPORT_CLAIM_DETAIL', 'SP_CLAIM_DETAILS', 'Excel', 'Y',14955)