 IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14945 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14945,'ramo',2)
	 END
 GO
 
 
  IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14946 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14946,'ramo-corretor',2)
	 END
 GO
 
 
  IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14947 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14947,'ramo-orgao',2)
	 END
 GO
 
 
   IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14948 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14948,'orgao',2)
	 END
 GO
 
 
    IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14949 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14949,'orgao-corretor',2)
	 END
 GO
 
 
     IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14950 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14950,'orgao-ramo',2)
	 END
 GO
 
 
      IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14951 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14951,'corretor',2)
	 END
 GO
 
 
       IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14952 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14952,'corretor-orgao',2)
	 END
 GO
 
 
        IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14953 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (14953,'corretor-ramo',2)
	 END
 GO