--begin tran 
--select * from MNT_LOOKUP_VALUES where LOOKUP_ID=1442 and IS_ACTIVE='y'
--select * from MIG_IL_LAYOUT_COLUMNS where COLUMN_NAME='é desativar'--COLUMN_TYPE=15008 
 
--risk, --15008 
--0196
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0196')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0196')
END    
GO
--0654
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0654')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0654')
END    
GO
--0171
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0171')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0171')
END    
GO
--0167
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0167')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0167')
END    
GO
--0589
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0589')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0589')
END    
GO
--0993
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0993')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0993')
END    
GO
--0173
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0173')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0173')
END    
GO
--1163
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='1163')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','1163')
END    
GO
--0621
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0621')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0621')
END    
GO
--0523
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0523')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0523')
END    
GO
--0746
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0746')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0746')
END    
GO
--0982
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0982')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0982')
END    
GO
--0553
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0553')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0553')
END    
GO
--0435
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0435')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0435')
END    
GO
--0115
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0115')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0115')
END    
GO
--0116
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0116')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0116')
END    
GO
--0622
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0622')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0622')
END    
GO
--0588
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0588')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0588')
END    
GO
--0118
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0118')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0118')
END    
GO
--0531
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0531')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0531')
END    
GO
--9821
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='9821')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','9821')
END    
GO
--0997
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0997')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0997')
END    
GO
--0750
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0750')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0750')
END    
GO
--0111
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0111')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0111')
END    
GO
--0433
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0433')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0433')
END    
GO
--0351
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0351')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0351')
END    
GO
--0114
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0114')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0114')
END    
GO
--0981
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=15008 AND COLUMN_NAME='é desativar' and SUSEP_LOB_CODE='0981')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 15008,'é desativar','Y','0981')
END    
GO

--clauses, --14962
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=14962 AND COLUMN_NAME='é desativar')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 14962,'é desativar','Y',NULL)
END    
GO
--remuneration,--14940 
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=14940 AND COLUMN_NAME='é desativar')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 14940,'é desativar','Y',NULL)
END    
GO
--coverages, --14968
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=14968 AND COLUMN_NAME='é desativar')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 14968,'é desativar','Y',NULL)
END    
GO
--location, --14960
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=14960 AND COLUMN_NAME='é desativar')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 14960,'é desativar','Y',NULL)
END    
GO
--policy discount, --14963
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=14963 AND COLUMN_NAME='é desativar')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 14963,'é desativar','Y',NULL)
END    
GO
--risk discount, --14966
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=14966 AND COLUMN_NAME='é desativar')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 14966,'é desativar','Y',NULL)
END    
GO
--beneficiary -- 14967
IF NOT EXISTS(SELECT 1 FROM MIG_IL_LAYOUT_COLUMNS WHERE COLUMN_TYPE=14967 AND COLUMN_NAME='é desativar')
BEGIN
INSERT INTO MIG_IL_LAYOUT_COLUMNS(COLUMN_TYPE,COLUMN_NAME,IS_ACTIVE,SUSEP_LOB_CODE)
     VALUES( 14967,'é desativar','Y',NULL)
END    
GO
--select * from MIG_IL_LAYOUT_COLUMNS where COLUMN_NAME='é desativar'
--rollback tran