
IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MNT_BANK_INFO_MASTER')
BEGIN 
CREATE TABLE MNT_BANK_INFO_MASTER
( 
BANK_ID INT IDENTITY(1,1),
BANK_NUMBER NVARCHAR(10),
BANK_BRANCH_NUMBER NVARCHAR(10),
BANK_NAME NVARCHAR(200),
DISCARD NVARCHAR(100),
BANK_BRANCH_NAME NVARCHAR(100),
BANK_BRANCH_VERIFIER_DIGIT CHAR(1)
CONSTRAINT [MNT_BANK_INFO_MASTER_BANK_ID] PRIMARY KEY NONCLUSTERED 
(
	[BANK_ID] ASC
	
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END
GO
 