
--Insert into TRANSACTIONTYPELIST 
If not exists (Select TRANS_TYPE_ID from TRANSACTIONTYPELIST where TRANS_TYPE_ID=448)
BEGIN 
Insert into TRANSACTIONTYPELIST (TRANS_TYPE_ID,TRANS_TYPE_NAME,TRANS_TYPE_DESC,TRANS_LEVEL,IS_ACTIVE) 
VALUES(448,'Invalid Record','Invalid Record','ACCOUNTING','Y')
END 
GO
 --Insert into TRANSACTIONTYPELIST 
If not exists (Select TRANS_TYPE_ID from TRANSACTIONTYPELIST_MULTILINGUAL where TRANS_TYPE_ID=448)
BEGIN 
Insert into TRANSACTIONTYPELIST_MULTILINGUAL (TRANS_TYPE_ID,TRANS_TYPE_NAME,LANG_ID) 
VALUES(448,'Registro inválido',2)
END 
GO

 