
IF EXISTS (SELECT * FROM  MNT_SUSEP_LOB_MASTER_MULTILINGUAL WHERE SUSEP_LOB_ID = 100 )
update MNT_SUSEP_LOB_MASTER_MULTILINGUAL  set SUSEP_LOB_DESC = '0746-Fiança Locatícia'  
where SUSEP_LOB_ID = 100


IF EXISTS (SELECT * FROM  MNT_SUSEP_LOB_MASTER WHERE SUSEP_LOB_ID = 100 )
Update MNT_SUSEP_LOB_MASTER set  SUSEP_LOB_CODE = '0746' ,SUSEP_LOB_DESC = '0746-Rental Surety'
where SUSEP_LOB_ID = 100