--begin tran

IF NOT  EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST  where REPORT_NAME='PPNG' AND ITRACK_NO='1663')
 BEGIN
     
     insert into MNT_SUSEP_REPORTS_LIST (REPORT_NAME,PROC_NAME,OUTPUT_FORMAT,IS_ACTIVE,REPORT_TYPE,FILE_NAME,ITRACK_NO) values('PPNG','PROC_PPNG_REPORT','Excel','Y',14954,'PPNG.XLS','1663')
  
 END
IF NOT  EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST  where REPORT_NAME='RVNE' AND ITRACK_NO='1664')
 BEGIN
     
     insert into MNT_SUSEP_REPORTS_LIST (REPORT_NAME,PROC_NAME,OUTPUT_FORMAT,IS_ACTIVE,REPORT_TYPE,FILE_NAME,ITRACK_NO) values('RVNE','PROC_RVNE_REPORT','Excel','Y',14954,'RVNE.XLS','1664')
  
 END

 IF NOT  EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST  where REPORT_NAME='IBNR' AND ITRACK_NO='1664')
 BEGIN
     
     insert into MNT_SUSEP_REPORTS_LIST (REPORT_NAME,PROC_NAME,OUTPUT_FORMAT,IS_ACTIVE,REPORT_TYPE,FILE_NAME,ITRACK_NO) values('IBNR','PROC_IBNR_REPORT','Excel','Y',14954,'IBNR.XLS','1664')
  
 END
 
  IF NOT  EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST  where REPORT_NAME='Sin_Ret_e_PG' AND ITRACK_NO='1664')
 BEGIN
     
     insert into MNT_SUSEP_REPORTS_LIST (REPORT_NAME,PROC_NAME,OUTPUT_FORMAT,IS_ACTIVE,REPORT_TYPE,FILE_NAME,ITRACK_NO) values('Sin_Ret_e_PG','PROC_REL_SIN_RET_EPG','Excel','Y',14954,'Sin_Ret_e_PG.XLS','1664')
  
 END

--ROLLBACK TRAN