 
/****** Script for INSERT SCREEN_ID into MNT_SCREEN_LIST table For Deposit Validation ******/
IF NOT EXISTS (SELECT SCREEN_ID FROM MNT_SCREEN_LIST WHERE SCREEN_ID='187_0_4')
BEGIN

INSERT INTO MNT_SCREEN_LIST
           (SCREEN_ID,SCREEN_DESC,SCREEN_PATH,SCREEN_READ,SCREEN_WRITE,SCREEN_DELETE,SCREEN_EXECUTE,IS_ACTIVE)
			VALUES( '187_0_4','Deposit Validation Details','/cms/Account/Aspx/DepositMessageDetails.aspx',1,1,1,1,'Y')
END
GO
 
 
 ----For the MNT_SCREEN_LIST_MULTILINGUAL

IF NOT EXISTS (SELECT SCREEN_ID FROM MNT_SCREEN_LIST_MULTILINGUAL WHERE SCREEN_ID='187_0_4')
BEGIN
INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL (SCREEN_ID,SCREEN_DESC,LANG_ID)VALUES( '187_0_4','Deposit Validation Details',2)
END
GO
 