
---itrack-1530
IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14701')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Corretor' WHERE  LOOKUP_UNIQUE_ID = '14701'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14702')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Angariador' WHERE  LOOKUP_UNIQUE_ID = '14702'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '11733')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Isento-Federal ID' WHERE  LOOKUP_UNIQUE_ID = '11733'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '11734')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Incorporado - Federal ID' WHERE  LOOKUP_UNIQUE_ID = '11734'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '11735')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Outro - Federal ID' WHERE  LOOKUP_UNIQUE_ID = '11735'
END



IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14123')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Outro - Federal ID' WHERE  LOOKUP_UNIQUE_ID = '14123'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14525')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Isento-SSN' WHERE  LOOKUP_UNIQUE_ID = '14525'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14526')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Outros-SSN' WHERE  LOOKUP_UNIQUE_ID = '14526'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14527')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Incorporado-SSN' WHERE  LOOKUP_UNIQUE_ID = '14527'
END



