
IF EXISTS (SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID =14931)
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL 
SET LOOKUP_VALUE_DESC ='Contas à Pagar'
WHERE LOOKUP_UNIQUE_ID=14931
END

IF EXISTS (SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID =14932)
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL 
SET LOOKUP_VALUE_DESC ='Contas à Receber'
WHERE LOOKUP_UNIQUE_ID=14932
END

