begin tran 
--For itrack 1303
DECLARE @BANK_ID INT
DECLARE @BRAZIL_BANK_ID INT
--Get brazil bank id 
SELECT @BRAZIL_BANK_ID=BANK_ID FROM ACT_BANK_INFORMATION WHERE BANK_NUMBER='001'

--Get the test (3400) bank id which have been added meintenance 
SELECT @BANK_ID=BANK_ID FROM ACT_BANK_INFORMATION WHERE BANK_NUMBER='3400'

--Update ACT_CURRENT_DEPOSITS's ACCOUNT_ID to brazil bank id 
UPDATE ACT_CURRENT_DEPOSITS SET ACCOUNT_ID=@BRAZIL_BANK_ID WHERE ACCOUNT_ID=@BANK_ID
--Update ACT_ACCOUNTS_POSTING_DETAILS's ACCOUNT_ID to brazil bank id 
UPDATE ACT_ACCOUNTS_POSTING_DETAILS  SET ACCOUNT_ID=@BRAZIL_BANK_ID WHERE ACCOUNT_ID=@BANK_ID
--Delete test bank id which have been added meintenance 
DELETE FROM ACT_BANK_INFORMATION WHERE BANK_ID=@BANK_ID
rollback tran 