IF NOT Exists(select * from TRANSACTIONTYPELIST where TRANS_TYPE_ID=438)
Begin
insert into TRANSACTIONTYPELIST(TRANS_TYPE_ID,TRANS_TYPE_NAME,TRANS_TYPE_DESC,TRANS_LEVEL,IS_ACTIVE,ADD_BY,ADD_DATE,MODIFIED_BY,MODIFIED_DATE,IS_DELETED,DELETED_DATE)Values(438,'Process Commit-Open Items','Renewal Premium.','POLICY','Y',null,null,null,null,null,null)
End


IF NOT Exists(select * from TRANSACTIONTYPELIST where TRANS_TYPE_ID=439)
Begin
insert into TRANSACTIONTYPELIST(TRANS_TYPE_ID,TRANS_TYPE_NAME,TRANS_TYPE_DESC,TRANS_LEVEL,IS_ACTIVE,ADD_BY,ADD_DATE,MODIFIED_BY,MODIFIED_DATE,IS_DELETED,DELETED_DATE)Values(439,'Process Commit-Open Items','Renewal Intrest.','POLICY','Y',null,null,null,null,null,null)
End



IF NOT Exists(select * from TRANSACTIONTYPELIST where TRANS_TYPE_ID=440)
Begin
insert into TRANSACTIONTYPELIST(TRANS_TYPE_ID,TRANS_TYPE_NAME,TRANS_TYPE_DESC,TRANS_LEVEL,IS_ACTIVE,ADD_BY,ADD_DATE,MODIFIED_BY,MODIFIED_DATE,IS_DELETED,DELETED_DATE)Values(440,'Process Commit-Open Items','Renewal Fees.','POLICY','Y',null,null,null,null,null,null)
End


IF NOT Exists(select * from TRANSACTIONTYPELIST where TRANS_TYPE_ID=441)
Begin
insert into TRANSACTIONTYPELIST(TRANS_TYPE_ID,TRANS_TYPE_NAME,TRANS_TYPE_DESC,TRANS_LEVEL,IS_ACTIVE,ADD_BY,ADD_DATE,MODIFIED_BY,MODIFIED_DATE,IS_DELETED,DELETED_DATE)Values(441,'Process Commit-Open Items','Renewal Taxes.','POLICY','Y',null,null,null,null,null,null)
End





IF NOT Exists(select * from TRANSACTIONTYPELIST_MULTILINGUAL where TRANS_TYPE_ID=438)
Begin
insert into TRANSACTIONTYPELIST_MULTILINGUAL(TRANS_TYPE_ID,TRANS_TYPE_NAME,LANG_ID)Values(438,'Renovação Premio',2)
End

IF NOT Exists(select * from TRANSACTIONTYPELIST_MULTILINGUAL where TRANS_TYPE_ID=439)
Begin
insert into TRANSACTIONTYPELIST_MULTILINGUAL(TRANS_TYPE_ID,TRANS_TYPE_NAME,LANG_ID)Values(439,'Intrests renovação.',2)
End


IF NOT Exists(select * from TRANSACTIONTYPELIST_MULTILINGUAL where TRANS_TYPE_ID=440)
Begin
insert into TRANSACTIONTYPELIST_MULTILINGUAL(TRANS_TYPE_ID,TRANS_TYPE_NAME,LANG_ID)Values(440,'Taxas de renovação.',2)
End

IF NOT Exists(select * from TRANSACTIONTYPELIST_MULTILINGUAL where TRANS_TYPE_ID=441)
Begin
insert into TRANSACTIONTYPELIST_MULTILINGUAL(TRANS_TYPE_ID,TRANS_TYPE_NAME,LANG_ID)Values(441,'Impostos renovação.',2)
End