
 
/****** Script for INSERT SCREEN_ID into MNT_SCREEN_LIST table For SUSEP LOB Code  ******/

--For the Index Page 
 
BEGIN
INSERT INTO MNT_SCREEN_LIST
           (SCREEN_ID,SCREEN_DESC,SCREEN_PATH,SCREEN_READ,SCREEN_WRITE,SCREEN_DELETE,SCREEN_EXECUTE,IS_ACTIVE)
			VALUES( '502_1','Product SUSEP Code Details','/cms/cmsweb/maintenance/ProductSusepCodeMasterIndex.aspx',1,1,1,1,'Y')
END
GO

IF NOT EXISTS (SELECT SCREEN_ID FROM MNT_SCREEN_LIST WHERE SCREEN_ID='502_2')
BEGIN
INSERT INTO MNT_SCREEN_LIST
           (SCREEN_ID,SCREEN_DESC,SCREEN_PATH,SCREEN_READ,SCREEN_WRITE,SCREEN_DELETE,SCREEN_EXECUTE,IS_ACTIVE)
			VALUES( '502_2','Product SUSEP Code Details info','/cms/cmsweb/maintenance/ProductSusepCodeMasterDetails.aspx',1,1,1,1,'Y')
END
GO
 
 ----For the MNT_SCREEN_LIST_MULTILINGUAL

IF NOT EXISTS (SELECT SCREEN_ID FROM MNT_SCREEN_LIST_MULTILINGUAL WHERE SCREEN_ID='502_1')
BEGIN
INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL (SCREEN_ID,SCREEN_DESC,LANG_ID)VALUES( '502_1','Product SUSEP Code Details',2)
END
GO
IF NOT EXISTS (SELECT SCREEN_ID FROM MNT_SCREEN_LIST_MULTILINGUAL WHERE SCREEN_ID='502_2')
BEGIN
INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL (SCREEN_ID,SCREEN_DESC,LANG_ID)VALUES( '502_2','Product SUSEP Code Details info',2)
END
GO
 