
/****** Script for Add LOOKUP in MNT_LOOKUP_TABLES table , MNT_LOOKUP_VALUES and  MNT_LOOKUP_VALUES_MULTILINGUAL FOR COMMISSION TYPE   ******/
--SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID=1381 
---SELECT max(LOOKUP_ID) FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID=1378 AND LOOKUP_NAME='COMMTYP'

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID=1447 AND LOOKUP_NAME='INTTYP')
BEGIN
INSERT INTO MNT_LOOKUP_TABLES
(LOOKUP_ID,LOOKUP_NAME,LOOKUP_DESC,LOOKUP_TYPE,LOOKUP_TBL_EDIT,LOOKUP_CODE_WIDTH,LOOKUP_DISPLAY_FORMAT,LOOKUP_DESC_WIDTH,LOOKUP_LEVEL)
VALUES
(1447,'INTTYP','Interest Type','H','Y',null,null,null,null)
END
GO

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_TABLES_MULTILINGUAL WHERE LOOKUP_ID=1447)
BEGIN
INSERT INTO MNT_LOOKUP_TABLES_MULTILINGUAL
(LOOKUP_ID,LOOKUP_DESC,LANG_ID)
VALUES
(1447,'Tipo de juros',2)
END





-----------MNT_LOOKUP_VALUES------------------------
--select max(LOOKUP_UNIQUE_ID) FROM MNT_LOOKUP_VALUES 

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15009 and LOOKUP_ID=1447)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type
		 ,NSS_VALUE_CODE)
		 VALUES
		 (15009,1447,1,'FIFD','First Installment for Future Date',null,'Y',null,null,null,null)
	 END
 GO
 
IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15010 and LOOKUP_ID=1447)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type
		 ,NSS_VALUE_CODE)
		 VALUES
		 (15010,1447,1,'FIC','First Installment in Cash',null,'Y',null,null,null,null)
	END
GO


-----------For MNT_LOOKUP_VALUES_MULTILINGUAL Table---------------
  
 IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15009 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (15009,'Data primeira parcela de Futuro',2)
	 END
 GO
 
 IF NOT EXISTS(SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15010 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (15010,'Primeira parcela em dinheiro',2)
	 END
 GO
 
 
 
 
 