

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID=1445 AND LOOKUP_NAME='MGTRPT')
BEGIN
INSERT INTO MNT_LOOKUP_TABLES
(LOOKUP_ID,LOOKUP_NAME,LOOKUP_DESC,LOOKUP_TYPE,LOOKUP_TBL_EDIT,LOOKUP_CODE_WIDTH,LOOKUP_DISPLAY_FORMAT,LOOKUP_DESC_WIDTH,LOOKUP_LEVEL)
VALUES
(1444,'MGTRPT','Management Report','H','Y',null,null,null,null)
end
   IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14945 and LOOKUP_ID=1444)

	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14945,1444,1,'PERDIV','Per Division',null,'Y',null,null,null,null)
	 END

	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14946 and LOOKUP_ID=1444)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14946,1444,2,'PERDIVBRO','Per Division and Broker',null,'Y',null,null,null,null)
	 END
	 
	 
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14947 and LOOKUP_ID=1444)
	BEGIN
	
	  insert into  MNT_LOOKUP_VALUES
		  (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14947,1444,3,'PERDIVSUSP','Per Division and Susep Accounting LOB',null,'Y',null,null,null,null)
	 END
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14948 and LOOKUP_ID=1444)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14948,1444,4,'PERSUSPACCLOB','Per Susep Accounting LOB',null,'Y',null,null,null,null)
	 END
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14949 and LOOKUP_ID=1444)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14949,1444,5,'PERSUSPACCLOBBRO','Per Susep Accounting LOB and Broker',null,'Y',null,null,null,null)
	 END
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14950 and LOOKUP_ID=1444)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14950,1444,6,'PERSUSPACCLOBDIV','Per Susep Accounting LOB and Division',null,'Y',null,null,null,null)
	 END
	 
	 
	  IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14951 and LOOKUP_ID=1444)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14951,1444,7,'PERBRO','Per Broker',null,'Y',null,null,null,null)
	 END
	 
	 
	  IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14952 and LOOKUP_ID=1444)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14952,1444,8,'PERBROSUSEPACCLOB','Per Broker and Susep Accounting LOB',null,'Y',null,null,null,null)
	 END
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14954 and LOOKUP_ID=1444)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14953,1444,9,'PERBRODIV','Per broker and  Division',null,'Y',null,null,null,null)
	 END
	 



--SuSep REPORT
IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID=1445 AND LOOKUP_NAME='REPTYP')
BEGIN
INSERT INTO MNT_LOOKUP_TABLES
(LOOKUP_ID,LOOKUP_NAME,LOOKUP_DESC,LOOKUP_TYPE,LOOKUP_TBL_EDIT,LOOKUP_CODE_WIDTH,LOOKUP_DISPLAY_FORMAT,LOOKUP_DESC_WIDTH,LOOKUP_LEVEL)
VALUES
(1445,'REPTYP','Report Type','H','Y',null,null,null,null)
end
IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14954 and LOOKUP_ID=1445)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14954,1445,1,'SUSRPT','Susep Report',null,'Y',null,null,null,null)
	 END

	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=14955 and LOOKUP_ID=1445)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
		 VALUES(14955,1445,2,'MGRPT','Management Report',null,'Y',null,null,null,null)
	 END

GO

