--For Customer type
UPDATE MNT_LOOKUP_VALUES SET LOOKUP_VALUE_DESC ='Corporate' where LOOKUP_UNIQUE_ID=11109
UPDATE MNT_LOOKUP_VALUES SET LOOKUP_VALUE_DESC ='Individual' where LOOKUP_UNIQUE_ID=11110


--FOR AGENCY TYPES
UPDATE MNT_LOOKUP_VALUES SET LOOKUP_VALUE_DESC='Broker' where LOOKUP_UNIQUE_ID=14701
UPDATE MNT_LOOKUP_VALUES SET LOOKUP_VALUE_DESC='Agency' where LOOKUP_UNIQUE_ID=14702
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,IS_ACTIVE) VALUES ((select MAX(LOOKUP_UNIQUE_ID)+1 from MNT_LOOKUP_VALUES),1397,3,'CORP','Corporate','Y')

INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,IS_ACTIVE) VALUES ((select MAX(LOOKUP_UNIQUE_ID)+1 from MNT_LOOKUP_VALUES),1397,4,'INDV','Individual','Y')
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,IS_ACTIVE) VALUES ((select MAX(LOOKUP_UNIQUE_ID)+1 from MNT_LOOKUP_VALUES),1397,5,'CORP','Facultative Inwards','Y')
