
IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'CLT_CUSTOMER_LIST' AND COLUMN_NAME = 'CUSTOMER_FIRST_NAME')
 BEGIN
     ALTER TABLE CLT_CUSTOMER_LIST  
     alter  column  CUSTOMER_FIRST_NAME  NVARCHAR(200)
     
   
 END
 go
 
 
 
 IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'CLT_APPLICANT_LIST' AND COLUMN_NAME = 'FIRST_NAME')
 BEGIN
     ALTER TABLE CLT_APPLICANT_LIST  
     alter  column  FIRST_NAME  NVARCHAR(200)
     
   
 END
 go
