IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST WHERE MENU_ID = 556)

BEGIN

INSERT INTO MNT_MENU_LIST Values(556,13,'Rule Collection','/cms/cmsweb/maintenance/RuleCollection.aspx',null,2,22,0,null,null,null,null,null,null,null,null,null,'Y')

END

update MNT_MENU_LIST set MENU_LINK ='/cms/cmsweb/maintenance/RuleCollection.aspx'  where MENU_ID = 556

IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST_MULTILINGUAL WHERE MENU_ID = 556)

BEGIN

INSERT INTO MNT_MENU_LIST_MULTILINGUAL Values(556,'Colecção regra',2)

END



IF NOT EXISTS (SELECT * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='556')
BEGIN 
  INSERT INTO MNT_SCREEN_LIST (SCREEN_ID,SCREEN_DESC,SCREEN_PATH,SCREEN_READ,SCREEN_WRITE,SCREEN_DELETE,SCREEN_EXECUTE,IS_ACTIVE) 
		VALUES('556','Rule Collection','/cms/cmsweb/maintenance/RuleCollection.aspx','1','1','1','1','Y')
END
		
IF NOT EXISTS (SELECT * FROM MNT_SCREEN_LIST_MULTILINGUAL  WHERE SCREEN_ID='556')
BEGIN 
  INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL (SCREEN_ID,SCREEN_DESC,LANG_ID) 
		VALUES('556','Colecção regra',2)
END		

IF NOT EXISTS (SELECT * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='556_0')
BEGIN 
  INSERT INTO MNT_SCREEN_LIST (SCREEN_ID,SCREEN_DESC,SCREEN_PATH,SCREEN_READ,SCREEN_WRITE,SCREEN_DELETE,SCREEN_EXECUTE,IS_ACTIVE) 
		VALUES('556_0','Add Rule Collection','/cms/cmsweb/maintenance/AddRuleCollectionDetail.aspx','1','1','1','1','Y')
END
		
IF NOT EXISTS (SELECT * FROM MNT_SCREEN_LIST_MULTILINGUAL  WHERE SCREEN_ID='556_0')
BEGIN 
  INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL (SCREEN_ID,SCREEN_DESC,LANG_ID) 
		VALUES('556_0','Adicionar coleção de regras',2)
END	


