IF NOT EXISTS (SELECT * FROM MNT_MENU_LIST WHERE MENU_ID=563)
		BEGIN
			INSERT INTO MNT_MENU_LIST (MENU_ID,PARENT_ID,MENU_NAME,MENU_LINK,MENU_TOOLTIP,NESTLEVEL,MENU_ORDER,HASCHILD,SHOWTYPE,HIDESTATUS,ISSECURITY,LANGID,MENU_IMAGE,DEFAULT_PAGE,MODULE_NAME,AGENCY_LEVEL,LOB_CODE,IS_ACTIVE)
								VALUES(563,524,'Rates Tab','/Cms/CmsWeb/maintenance/RatesTab.aspx',NULL,3,1,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y')
		END
	
	
IF NOT EXISTS (SELECT * FROM MNT_MENU_LIST_MULTILINGUAL WHERE MENU_ID=563)
	BEGIN
		INSERT INTO MNT_MENU_LIST_MULTILINGUAL (MENU_ID,MENU_NAME,LANG_ID) VALUES(563,'Rates Tab',2)
	END
	
	
