
IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MNT_LOB_SUSEPCODE_MASTER')
BEGIN 
CREATE TABLE MNT_LOB_SUSEPCODE_MASTER
( 
LOB_SUSEPCODE_ID INT NOT NULL,
LOB_ID SMALLINT NOT NULL,
EFFECTIVE_FROM DATETIME, 
EFFECTIVE_TO DATETIME ,
SUSEP_LOB_CODE NVARCHAR(10),
CREATED_BY INT,
CREATED_DATETIME DATETIME,
MODIFIED_BY INT,
LAST_UPDATED_DATETIME DATETIME,
 
CONSTRAINT [MNT_LOB_SUSEPCODE_MASTER_LOB_SUSEPCODE_ID] PRIMARY KEY NONCLUSTERED 
(
	[LOB_SUSEPCODE_ID] ASC
	
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
Alter TABLE [dbo].[MNT_LOB_SUSEPCODE_MASTER]  WITH NOCHECK ADD  CONSTRAINT [FK_MNT_LOB_SUSEPCODE_MASTER_LOB_ID] FOREIGN KEY([LOB_ID])
REFERENCES [dbo].[MNT_LOB_MASTER] ([LOB_ID])
END
GO
