UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Exhibitions' WHERE ACTIVITY_ID = 	106
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cassava Flour and Derivatives' WHERE ACTIVITY_ID = 	107
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pharmacies and Drugstores' WHERE ACTIVITY_ID = 	108
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Rail - Construction, Installation and Repair of Motor Vehicles' WHERE ACTIVITY_ID = 	109
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fibers - Artificial' WHERE ACTIVITY_ID = 	110
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fibers - Natural' WHERE ACTIVITY_ID = 	111
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Philately' WHERE ACTIVITY_ID = 	112
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Tapes and Films - Production' WHERE ACTIVITY_ID = 	113
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Flowers - Trade' WHERE ACTIVITY_ID = 	114
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fireworks' WHERE ACTIVITY_ID = 	115
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Photos - Articles and Studies' WHERE ACTIVITY_ID = 	116
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Refrigerators' WHERE ACTIVITY_ID = 	117
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fruits - Processing and Trade' WHERE ACTIVITY_ID = 	118
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Smoke - Processing' WHERE ACTIVITY_ID = 	119
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Smoking - Manufacture of cigarettes, cigars and Derivatives' WHERE ACTIVITY_ID = 	120
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Smoke - Shops' WHERE ACTIVITY_ID = 	121
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Garages and Parking' WHERE ACTIVITY_ID = 	122
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fuel Gases - Distribution and Retail' WHERE ACTIVITY_ID = 	123
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fuel Gases - Production' WHERE ACTIVITY_ID = 	124
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ice - Manufacture' WHERE ACTIVITY_ID = 	125
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Horticultural' WHERE ACTIVITY_ID = 	126
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hospitals' WHERE ACTIVITY_ID = 	127
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hotels' WHERE ACTIVITY_ID = 	128
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Churches' WHERE ACTIVITY_ID = 	129
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Real estate' WHERE ACTIVITY_ID = 	130
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Properties in Cleaning and Maintenance' WHERE ACTIVITY_ID = 	131
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Informatica - Equipment Rental' WHERE ACTIVITY_ID = 	132
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Informatica - Articles and Parts Stores' WHERE ACTIVITY_ID = 	133
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Inforematica - Review and Repairs' WHERE ACTIVITY_ID = 	134
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Musical Instruments - Manufacturing' WHERE ACTIVITY_ID = 	135
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Musical Instruments - Shops' WHERE ACTIVITY_ID = 	136
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Zoos' WHERE ACTIVITY_ID = 	137
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Electronic Games' WHERE ACTIVITY_ID = 	138
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Labs Research and Analysis' WHERE ACTIVITY_ID = 	139
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Dairy' WHERE ACTIVITY_ID = 	140
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Laundry and Dry Cleaning' WHERE ACTIVITY_ID = 	141
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Auctioneers' WHERE ACTIVITY_ID = 	142
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bookshops and Stationers' WHERE ACTIVITY_ID = 	143
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Department Stores' WHERE ACTIVITY_ID = 	144
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Masonry' WHERE ACTIVITY_ID = 	145
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Timber, Joinery and carpentry' WHERE ACTIVITY_ID = 	146
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Typewriters and Calculators - Shops' WHERE ACTIVITY_ID = 	147
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Typewriters and Calculators - Workshops' WHERE ACTIVITY_ID = 	148
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Marmoaria' WHERE ACTIVITY_ID = 	149
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pasta - Manufacturing' WHERE ACTIVITY_ID = 	150
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Slaughterhouses' WHERE ACTIVITY_ID = 	151
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Building Materials, Hardware and Tools' WHERE ACTIVITY_ID = 	152
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Marked Public' WHERE ACTIVITY_ID = 	153
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Precious and semiprecious metals - Stoning' WHERE ACTIVITY_ID = 	154
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Metallurgical' WHERE ACTIVITY_ID = 	155
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ores - Extraction' WHERE ACTIVITY_ID = 	156
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Mills' WHERE ACTIVITY_ID = 	157
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Motels' WHERE ACTIVITY_ID = 	158
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = '-Furniture Manufacture' WHERE ACTIVITY_ID = 	159
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Furniture-Shops' WHERE ACTIVITY_ID = 	160
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Museums' WHERE ACTIVITY_ID = 	161
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Oils - Manufacture' WHERE ACTIVITY_ID = 	162
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Orphanages' WHERE ACTIVITY_ID = 	163
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Optical' WHERE ACTIVITY_ID = 	164
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bakeries, Confectioneries and Delicatessen' WHERE ACTIVITY_ID = 	165
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pulp and Paper - Manufacture' WHERE ACTIVITY_ID = 	166
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Precious and semiprecious stones - Stoning' WHERE ACTIVITY_ID = 	167
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fishmongers' WHERE ACTIVITY_ID = 	168
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Penitentiaries' WHERE ACTIVITY_ID = 	169
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Petroleum - Refinery' WHERE ACTIVITY_ID = 	170
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Petroleum and Related Services' WHERE ACTIVITY_ID = 	171
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Batteries and Electric accumulators - Manufacturing' WHERE ACTIVITY_ID = 	172
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Plastics - Manufacturing' WHERE ACTIVITY_ID = 	173
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Plastics - Shops' WHERE ACTIVITY_ID = 	174
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Grit' WHERE ACTIVITY_ID = 	175
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Gas stations and Services' WHERE ACTIVITY_ID = 	176
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Health center' WHERE ACTIVITY_ID = 	177
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cabins and Hostels' WHERE ACTIVITY_ID = 	178
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Agricultural and Veterinary Products - Trade' WHERE ACTIVITY_ID = 	179
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Farmaceiticos Products - Manufacturing and Deposit' WHERE ACTIVITY_ID = 	180
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Chemicals - Manufacture and Deposit' WHERE ACTIVITY_ID = 	181
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Advertising - Companies' WHERE ACTIVITY_ID = 	182
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Barracks' WHERE ACTIVITY_ID = 	183
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Soft drinks - Manufacture' WHERE ACTIVITY_ID = 	184
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Watches - Manufacturing' WHERE ACTIVITY_ID = 	185
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Watches - Shops' WHERE ACTIVITY_ID = 	186
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Watches - Workshops' WHERE ACTIVITY_ID = 	187
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Public Offices' WHERE ACTIVITY_ID = 	188
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Clothing - Manufacturing' WHERE ACTIVITY_ID = 	189
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Clothing - Shops' WHERE ACTIVITY_ID = 	190
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Soaps, soaps and cleaning products - Manufacturing' WHERE ACTIVITY_ID = 	191
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sanatoriums' WHERE ACTIVITY_ID = 	192
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Insurers' WHERE ACTIVITY_ID = 	193
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Metalworking' WHERE ACTIVITY_ID = 	194
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Shopping Center' WHERE ACTIVITY_ID = 	195
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Steel' WHERE ACTIVITY_ID = 	196
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ice Cream' WHERE ACTIVITY_ID = 	197
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Scrap' WHERE ACTIVITY_ID = 	198
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Supermarkets' WHERE ACTIVITY_ID = 	199
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Tapestries' WHERE ACTIVITY_ID = 	200
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Theatres and other artistic and literary activities' WHERE ACTIVITY_ID = 	201
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Textiles - Manufacturing' WHERE ACTIVITY_ID = 	202
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fabrics - Shops' WHERE ACTIVITY_ID = 	203
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Telephony - Distributors' WHERE ACTIVITY_ID = 	204
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Telephony - Shops' WHERE ACTIVITY_ID = 	205
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Telephony - Apparatus Workshops' WHERE ACTIVITY_ID = 	206
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Paints and Solvents - Manufacture' WHERE ACTIVITY_ID = 	207
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Paints and Solvents - Shops' WHERE ACTIVITY_ID = 	208
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Printers' WHERE ACTIVITY_ID = 	209
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Universities and Colleges' WHERE ACTIVITY_ID = 	210
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sugar Mills' WHERE ACTIVITY_ID = 	211
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ethanol Plants' WHERE ACTIVITY_ID = 	212
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Asphalt Plants' WHERE ACTIVITY_ID = 	213
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Glazing' WHERE ACTIVITY_ID = 	214
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Wineries' WHERE ACTIVITY_ID = 	215
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Electricity Plants' WHERE ACTIVITY_ID = 	216
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Clubs Insurance' WHERE ACTIVITY_ID = 	217
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Foundations' WHERE ACTIVITY_ID = 	218
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Associations' WHERE ACTIVITY_ID = 	219
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Livestock' WHERE ACTIVITY_ID = 	220
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Real estate lessors' WHERE ACTIVITY_ID = 	221
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'EMPLOYEE SERVICES ADMINISTRATION, PRESERVATION AND MAINTENANCE OF BUILDINGS' WHERE ACTIVITY_ID = 	15514
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'WORKER HEALTH SERVICES' WHERE ACTIVITY_ID = 	15515
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'EMPLOYEE SERVICES PERSONAL CARE AND BEAUTY' WHERE ACTIVITY_ID = 	15516
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SERVICES WORKER PROTECTION AND SAFETY (EXCEPT MILITARY)' WHERE ACTIVITY_ID = 	15517
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'DRIVER DRIVER AND PASSENGER TRANSPORT (TAXI DRIVER, BUS, ETC SMALL CRAFT)' WHERE ACTIVITY_ID = 	15518
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'OTHER BUSINESS SERVICES WORKERS' WHERE ACTIVITY_ID = 	15519
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'VENDOR AND SERVICE PROVIDER OF COMMERCE, peddlers, traveling salesmen and Camel' WHERE ACTIVITY_ID = 	16529
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PRODUCER OPERATION IN AGRICULTURE' WHERE ACTIVITY_ID = 	17610
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'AGRICULTURAL WORKER AT THE FARM' WHERE ACTIVITY_ID = 	17620
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fishermen, hunters and EXTRACTIVE FOREST' WHERE ACTIVITY_ID = 	17630
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MACHINE OPERATOR OF AGRICULTURE AND FORESTRY' WHERE ACTIVITY_ID = 	17640
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'WORKER mining and construction' WHERE ACTIVITY_ID = 	18710
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'WORKER OF METALS AND COMPOSITES TRANSFORMATION' WHERE ACTIVITY_ID = 	18720
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Manufacturing jobs and wiring-ELECTRONICS' WHERE ACTIVITY_ID = 	18730
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'ASSEMBLER OF APPLIANCES AND ACCURACY OF MUSICAL' WHERE ACTIVITY_ID = 	18740
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Jeweler, glass, CERAMICS AND RELATED' WHERE ACTIVITY_ID = 	18750
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'WORKER OF TEXTILE INDUSTRY, THE TANNING, CLOTHING AND GRAPHIC ARTS' WHERE ACTIVITY_ID = 	18760
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'WORKER OF INDUSTRY AND WOOD FURNITURE' WHERE ACTIVITY_ID = 	18770
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'DRIVER AND OPERATOR OF ROBOTS, VEHICLE EQUIPMENT CARGO HANDLING AND RELATED' WHERE ACTIVITY_ID = 	18780
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'EMPLOYEE OF THE CHEMICAL, PETROCHEMICAL, RUBBER AND PLASTIC AND SIMILAR' WHERE ACTIVITY_ID = 	18810
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Steel plants WORKER AND BUILDING MATERIALS' WHERE ACTIVITY_ID = 	18820
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'WORKER MACHINERY MANUFACTURING FACILITIES AND PULP AND PAPER' WHERE ACTIVITY_ID = 	18830
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'CONSTRUCTION WORKER FOOD, DRINK, SMOKE and agribusiness' WHERE ACTIVITY_ID = 	18840
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'FACILITY OPERATOR PRODUCTION AND DISTRIBUTION OF ENERGY' WHERE ACTIVITY_ID = 	18860
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'OTHER FACILITIES WORKER agribusiness' WHERE ACTIVITY_ID = 	18870
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'REPAIR AND MAINTENANCE WORKER' WHERE ACTIVITY_ID = 	19900
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MILITARY AIRCRAFT' WHERE ACTIVITY_ID = 	20010
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MILITARY ARMY' WHERE ACTIVITY_ID = 	20020
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MILITARY NAVY' WHERE ACTIVITY_ID = 	20030
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MILITARY POLICE' WHERE ACTIVITY_ID = 	20040
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MILITARY FIREMAN' WHERE ACTIVITY_ID = 	20050
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Other occupations nes' WHERE ACTIVITY_ID = 	21000
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'ENGINEER, ARCHITECT AND RELATED' WHERE ACTIVITY_ID = 	3214
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PILOT AIRCRAFT, VESSELS AND COMMANDER OFFICIAL MACHINERY' WHERE ACTIVITY_ID = 	3215
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'BIOLOGY, BIOMEDICAL AND RELATED' WHERE ACTIVITY_ID = 	4221
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'AGRONOMY AND RELATED' WHERE ACTIVITY_ID = 	4222
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PROFESSIONAL PHYSICAL EDUCATION (EXCEPT TEACHER)' WHERE ACTIVITY_ID = 	4224
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'DOCTOR' WHERE ACTIVITY_ID = 	4225
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'DENTISTS' WHERE ACTIVITY_ID = 	4226
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'NURSE HIGHER, nutritionists, pharmacists AND RELATED' WHERE ACTIVITY_ID = 	4227
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'VETERINARY, Pathologist (VET) AND ZOOTECHNICAL' WHERE ACTIVITY_ID = 	4228
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Speech therapist, physiotherapist, occupational therapist AND RELATED' WHERE ACTIVITY_ID = 	4229
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'LAWYER' WHERE ACTIVITY_ID = 	5241
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sociologists and political scientists' WHERE ACTIVITY_ID = 	5250
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Anthropology and Archaeology' WHERE ACTIVITY_ID = 	5251
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Economic, administrative, accountants, auditors and RELATED' WHERE ACTIVITY_ID = 	5252
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PROFESSIONAL MARKETING, ADVERTISING AND MARKETING' WHERE ACTIVITY_ID = 	5253
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Psychologists and psychiatrists' WHERE ACTIVITY_ID = 	5255
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'GEOGRAPHY' WHERE ACTIVITY_ID = 	5256
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'HISTORIAN' WHERE ACTIVITY_ID = 	5257
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'HOME ECONOMIST AND SOCIAL WORKER' WHERE ACTIVITY_ID = 	5258
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PHILOSOPHER' WHERE ACTIVITY_ID = 	5259
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Journalist and reporter' WHERE ACTIVITY_ID = 	6261
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PRIEST OR MEMBER OF ORDERS OR RELIGIOUS SECTS' WHERE ACTIVITY_ID = 	6263
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TRANSLATOR, INTERPRETER, Philology' WHERE ACTIVITY_ID = 	6264
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Librarian, documentary, archival, Museology' WHERE ACTIVITY_ID = 	6265
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Writers, critics, EDITOR' WHERE ACTIVITY_ID = 	6266
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'ANNOUNCER, commentators' WHERE ACTIVITY_ID = 	6271
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'ACTOR, DIRECTOR OF SHOWS' WHERE ACTIVITY_ID = 	6272
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SINGER AND COMPOSER' WHERE ACTIVITY_ID = 	6273
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Musician, arranger, conductor or Coral' WHERE ACTIVITY_ID = 	6274
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'INDUSTRIAL DESIGNER (DESIGNER), SCULPTOR, PAINTER AND RELATED ART' WHERE ACTIVITY_ID = 	6275
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Set designer, interior decorator' WHERE ACTIVITY_ID = 	6276
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MANAGER AND PRODUCER OF SHOWS' WHERE ACTIVITY_ID = 	6277
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'OTHER PROFESSIONALS IN THE SHOW AND THE ARTS' WHERE ACTIVITY_ID = 	6279
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TEACHER IN EARLY CHILDHOOD EDUCATION' WHERE ACTIVITY_ID = 	7290
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Elementary school teacher' WHERE ACTIVITY_ID = 	7291
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'High School teacher' WHERE ACTIVITY_ID = 	7292
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Vocational teachers' WHERE ACTIVITY_ID = 	7293
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TEACHER OF HIGHER EDUCATION' WHERE ACTIVITY_ID = 	7294
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'INSTRUCTOR AND FREE SCHOOL TEACHER' WHERE ACTIVITY_ID = 	7295
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Teacher, Guidance Counselor' WHERE ACTIVITY_ID = 	7296
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICIAN CHEMICAL AND PHYSICAL SCIENCES' WHERE ACTIVITY_ID = 	8311
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICIAN CONSTRUCTION OF BUILDINGS AND WORKS FOR INFRASTRUCTURE' WHERE ACTIVITY_ID = 	8312
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Electricians, electronics and photonics' WHERE ACTIVITY_ID = 	8313
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICIAN METALMECHANICAL' WHERE ACTIVITY_ID = 	8314
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL IN MINERALOGY AND GEOLOGY' WHERE ACTIVITY_ID = 	8316
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'COMPUTER TECHNICIAN' WHERE ACTIVITY_ID = 	8317
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'DESIGNER techniques and models' WHERE ACTIVITY_ID = 	8318
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'OTHER TECHNICAL HIGH SCHOOL OF PHYSICAL SCIENCES, CHEMICAL, ENGINEERING AND ASSOCIATED' WHERE ACTIVITY_ID = 	8319
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICIAN BIOLOGY' WHERE ACTIVITY_ID = 	9320
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL PRODUCTION AGRICULTURE' WHERE ACTIVITY_ID = 	9321
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL SCIENCE OF HUMAN HEALTH' WHERE ACTIVITY_ID = 	9322
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SCIENCE TECHNICIAN ANIMAL HEALTH' WHERE ACTIVITY_ID = 	9323
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Laboratory technician, X-RAY AND OTHER EQUIPMENT AND TOOLS FOR DIAGNOSIS' WHERE ACTIVITY_ID = 	9324
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL BIOCHEMISTRY AND BIOTECHNOLOGY' WHERE ACTIVITY_ID = 	9325
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL CONSERVATION, and stuffed DISSECTION OF BODIES' WHERE ACTIVITY_ID = 	9328
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICIAN AIR NAVIGATION, waterborne and subway-railroad' WHERE ACTIVITY_ID = 	10341
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TRANSPORTATION TECHNICIAN (LOGISTICS)' WHERE ACTIVITY_ID = 	10342
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'ADMINISTRATIVE AND TECHNICAL SCIENCES ACCOUNTING' WHERE ACTIVITY_ID = 	11351
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL INSPECTION, SUPERVISION AND ADMINISTRATIVE COORDINATION' WHERE ACTIVITY_ID = 	11352
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'AGENT OF STOCK EXCHANGE, EXCHANGE AND OTHER FINANCIAL SERVICES' WHERE ACTIVITY_ID = 	11353
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TRADE REPRESENTATIVE AND AGENT, BROKER, AUCTIONEER AND RELATED' WHERE ACTIVITY_ID = 	11354
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL SERVICES CULTURAL' WHERE ACTIVITY_ID = 	12371
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cameramen, photographers and other OPERATION IN TECHNICAL DATA PROCESSING MACHINES' WHERE ACTIVITY_ID = 	12372
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL OPERATION OF RADIO AND TELEVISION STATIONS' WHERE ACTIVITY_ID = 	12373
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'TECHNICAL EQUIPMENT IN OPERATION SOUND, AND PROJECTION SCENOGRAPHY' WHERE ACTIVITY_ID = 	12374
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'DECORATOR and Vitrine' WHERE ACTIVITY_ID = 	12375
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PRESENTER, ARTISTS AND MODELS OF POPULAR ARTS' WHERE ACTIVITY_ID = 	12376
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'ATHLETE, SPORTS AND RELATED' WHERE ACTIVITY_ID = 	12377
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'OTHER TECHNICAL HIGH SCHOOL' WHERE ACTIVITY_ID = 	13391
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Banking, Savings, clerk, SECRETARY, AND AUXILIARY ADMINISTRATIVE ASSISTANT' WHERE ACTIVITY_ID = 	14410
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PUBLIC SERVICE WORKER, BOX, dispatchers, censuses and AFIN' WHERE ACTIVITY_ID = 	14420
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'STEWARD, GUIDE SERVICES, AND RELATED TRAVEL AGENT' WHERE ACTIVITY_ID = 	15511
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'DOMESTIC WORKER OF GENERAL SERVICES' WHERE ACTIVITY_ID = 	15512
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'EMPLOYEE SERVICES FOOD AND HOSPITALITY' WHERE ACTIVITY_ID = 	15513
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'RECOL Assoc Classes' WHERE ACTIVITY_ID = 	823
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Newspapers and Magazines' WHERE ACTIVITY_ID = 	824
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Several lives and Fines' WHERE ACTIVITY_ID = 	825
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Other Expenses' WHERE ACTIVITY_ID = 	826
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Transportation vouchers' WHERE ACTIVITY_ID = 	827
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Mat Imprint' WHERE ACTIVITY_ID = 	851
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Photocopies / Other' WHERE ACTIVITY_ID = 	852
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Phone' WHERE ACTIVITY_ID = 	853
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Energy, Water and Gas' WHERE ACTIVITY_ID = 	854
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Own property' WHERE ACTIVITY_ID = 	856
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Third Party Property' WHERE ACTIVITY_ID = 	857
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Prem. Campaigns' WHERE ACTIVITY_ID = 	858
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pouches / Matching' WHERE ACTIVITY_ID = 	859
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Donations' WHERE ACTIVITY_ID = 	860
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Exp C / Vehicles' WHERE ACTIVITY_ID = 	861
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fund-Fixed' WHERE ACTIVITY_ID = 	862
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Shares subscription' WHERE ACTIVITY_ID = 	864
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Travel Expenses / km Shot' WHERE ACTIVITY_ID = 	865
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Loose (Various)' WHERE ACTIVITY_ID = 	866
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Honorary' WHERE ACTIVITY_ID = 	867
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fix / Repair' WHERE ACTIVITY_ID = 	868
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sin DPVAT' WHERE ACTIVITY_ID = 	869
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Personnel' WHERE ACTIVITY_ID = 	891
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Alliance in Brazil' WHERE ACTIVITY_ID = 	892
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Vila Real' WHERE ACTIVITY_ID = 	893
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Resco Contract' WHERE ACTIVITY_ID = 	894
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cpab' WHERE ACTIVITY_ID = 	895
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cpd / Equipment' WHERE ACTIVITY_ID = 	896
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Supervisor of Inspection' WHERE ACTIVITY_ID = 	900
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Representation' WHERE ACTIVITY_ID = 	902
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Consulting' WHERE ACTIVITY_ID = 	903
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Broker' WHERE ACTIVITY_ID = 	904
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Insurance Brokerage' WHERE ACTIVITY_ID = 	905
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Claims handling' WHERE ACTIVITY_ID = 	906
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Previous inspection' WHERE ACTIVITY_ID = 	907
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Meal and Food Vouchers' WHERE ACTIVITY_ID = 	908
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Advisory' WHERE ACTIVITY_ID = 	909
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Other' WHERE ACTIVITY_ID = 	910
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'The' WHERE ACTIVITY_ID = 	911
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'The' WHERE ACTIVITY_ID = 	912
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'The' WHERE ACTIVITY_ID = 	913
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'General Services' WHERE ACTIVITY_ID = 	914
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'The' WHERE ACTIVITY_ID = 	915
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'The' WHERE ACTIVITY_ID = 	916
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Staff' WHERE ACTIVITY_ID = 	917
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Adrecor' WHERE ACTIVITY_ID = 	918
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Maria Emilia Foundation' WHERE ACTIVITY_ID = 	919
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Alimony' WHERE ACTIVITY_ID = 	920
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Assistance Instruction' WHERE ACTIVITY_ID = 	921
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Housing (SFH)' WHERE ACTIVITY_ID = 	922
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Shares' WHERE ACTIVITY_ID = 	923
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Salary' WHERE ACTIVITY_ID = 	924
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cia Insurance Alliance of Bahia' WHERE ACTIVITY_ID = 	925
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Auditing' WHERE ACTIVITY_ID = 	926
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Building' WHERE ACTIVITY_ID = 	927
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Legal services' WHERE ACTIVITY_ID = 	928
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Reviews' WHERE ACTIVITY_ID = 	929
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Provisional - to Costing' WHERE ACTIVITY_ID = 	998
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ativ.Provisoria for Settlement Cost' WHERE ACTIVITY_ID = 	999
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MEMBER OF THE EXECUTIVE (President, VICE PRESIDENT OF THE REPUBLIC, THE MINISTER OF STATE, GOVERNOR, DEPUTY GOVERNOR, MAYOR,' WHERE ACTIVITY_ID = 	1101
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'STATE OF THE JUDICIARY (ministers, judges and a judge) AND COURT OF AUDITORS (minister and adviser)' WHERE ACTIVITY_ID = 	1102
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Members of the legislature (senators, Federal, State and councilors)' WHERE ACTIVITY_ID = 	1103
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Prosecutors (ATTORNEY AND PROMOTER)' WHERE ACTIVITY_ID = 	1104
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Senior managers of public administration (in positions of DIRECTION, LEADERSHIP, ASSISTANCE AND SPECIAL NATURE), INCLUDING THE FUND OF' WHERE ACTIVITY_ID = 	1105
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'DIPLOMAT AND RELATED' WHERE ACTIVITY_ID = 	1106
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SERVER POWER OF LEGISLATIVE RACES' WHERE ACTIVITY_ID = 	1107
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SERVER''S CAREER PROSECUTOR' WHERE ACTIVITY_ID = 	1108
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SERVER CAREER OF THE JUDICIARY, bailiff, AUXILIARY, AND ASSISTANT LEGAL ANALYST' WHERE ACTIVITY_ID = 	1109
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PUBLIC SECTOR LAWYER, PROSECUTOR OF FINANCE, LEGAL ADVISOR, ATTORNEY FOR MUNICIPALITIES AND FOUNDATIONS PUBLIC PUBLIC DEFENDER' WHERE ACTIVITY_ID = 	1110
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'CAREER SERVER AUDIT AND TAX AUDIT' WHERE ACTIVITY_ID = 	1111
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SERVER CENTRAL BANK OF CAREER, AND CVM SUSEP' WHERE ACTIVITY_ID = 	1112
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Chief of Police and other servers CAREER OF POLICE, MILITARY EXCEPT' WHERE ACTIVITY_ID = 	1113
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SERVER MANAGEMENT CAREERS OF GOVERNMENT, ANALYST, PLANNING AND TECHNICAL MANAGER' WHERE ACTIVITY_ID = 	1114
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SERVER OF CAREERS IN SCIENCE AND TECHNOLOGY' WHERE ACTIVITY_ID = 	1115
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'SERVER OF PUBLIC ADMINISTRATION CAREERS OTHER DIRECT, autonomous agencies and foundations' WHERE ACTIVITY_ID = 	1116
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'HOLDER OF REGISTRY' WHERE ACTIVITY_ID = 	1117
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Managers or officers of political parties, employers organization, trade union, altruistic, and religious' WHERE ACTIVITY_ID = 	1118
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MANAGER, PRESIDENT AND DIRECTOR OF INDUSTRIAL COMPANY, BUSINESS OR SERVICE PROVIDER' WHERE ACTIVITY_ID = 	2120
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PRESIDENT AND DIRECTOR OF PUBLIC ENTERPRISE AND SOCIETY OF MIXED ECONOMY' WHERE ACTIVITY_ID = 	2121
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MANAGER OR SUPERVISOR INDUSTRIAL COMPANY, BUSINESS OR SERVICE PROVIDER' WHERE ACTIVITY_ID = 	2130
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'MANAGER OR SUPERVISOR PUBLIC WORKS AND SOCIETY OF MIXED ECONOMY' WHERE ACTIVITY_ID = 	2131
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'PRESIDENT, DIRECTOR, OFFICE MANAGER AND SUPERVISOR AND INTERNATIONAL NON-GOVERNMENTAL ORGANIZATION' WHERE ACTIVITY_ID = 	2140
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Mathematics, Statistics, Actuarial and RELATED' WHERE ACTIVITY_ID = 	3211
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Systems Analyst, Software Developer, network administrators and DATABASES AND OTHER EXPERTS IN COMPUTER (EXCEPT TECN' WHERE ACTIVITY_ID = 	3212
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Physics, chemistry, meteorology, geology, oceanography and RELATED' WHERE ACTIVITY_ID = 	3213
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Parking' WHERE ACTIVITY_ID = 	222
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Assistance Administrator' WHERE ACTIVITY_ID = 	223
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Assistance 24 Hours' WHERE ACTIVITY_ID = 	224
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Several trade' WHERE ACTIVITY_ID = 	225
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Temporary employment agencies and' WHERE ACTIVITY_ID = 	226
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Credit Analysis' WHERE ACTIVITY_ID = 	227
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Carrier' WHERE ACTIVITY_ID = 	228
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Importer Under Animal Products and Plant' WHERE ACTIVITY_ID = 	229
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Passenger Transp - Company' WHERE ACTIVITY_ID = 	230
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Machinery and Equipment - Manufacturing' WHERE ACTIVITY_ID = 	231
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pharmacies' WHERE ACTIVITY_ID = 	232
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Farms (Textiles)' WHERE ACTIVITY_ID = 	233
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hardware' WHERE ACTIVITY_ID = 	234
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fibers' WHERE ACTIVITY_ID = 	235
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Philately' WHERE ACTIVITY_ID = 	236
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ribbons, Lace and Embroidery' WHERE ACTIVITY_ID = 	237
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Flowers' WHERE ACTIVITY_ID = 	238
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fireworks' WHERE ACTIVITY_ID = 	239
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ship Suppliers' WHERE ACTIVITY_ID = 	240
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fodder' WHERE ACTIVITY_ID = 	241
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fosforos' WHERE ACTIVITY_ID = 	242
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Photos' WHERE ACTIVITY_ID = 	243
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Refrigerators' WHERE ACTIVITY_ID = 	244
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fruits' WHERE ACTIVITY_ID = 	245
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Smoke, Cigars and Cigarettes' WHERE ACTIVITY_ID = 	246
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Funeral articles' WHERE ACTIVITY_ID = 	247
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Garages' WHERE ACTIVITY_ID = 	260
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fuel Gases' WHERE ACTIVITY_ID = 	261
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ice' WHERE ACTIVITY_ID = 	262
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Furniture Guard' WHERE ACTIVITY_ID = 	263
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Carbon Dioxide' WHERE ACTIVITY_ID = 	264
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hydrogen' WHERE ACTIVITY_ID = 	279
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hydrotherapy, Establishments' WHERE ACTIVITY_ID = 	280
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hospitals' WHERE ACTIVITY_ID = 	281
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hotels Hotels and Residences' WHERE ACTIVITY_ID = 	282
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Churches' WHERE ACTIVITY_ID = 	290
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Immunizing' WHERE ACTIVITY_ID = 	291
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Flammable' WHERE ACTIVITY_ID = 	292
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Jewelers' WHERE ACTIVITY_ID = 	300
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Newspapers and Magazines' WHERE ACTIVITY_ID = 	301
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Labs Research and Analysis' WHERE ACTIVITY_ID = 	321
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Seal' WHERE ACTIVITY_ID = 	322
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Tiles' WHERE ACTIVITY_ID = 	323
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Perfume-Lanka' WHERE ACTIVITY_ID = 	324
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Lapis' WHERE ACTIVITY_ID = 	325
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Dairy' WHERE ACTIVITY_ID = 	326
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Laundries' WHERE ACTIVITY_ID = 	327
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Auctioneers' WHERE ACTIVITY_ID = 	328
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Firewood' WHERE ACTIVITY_ID = 	329
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sewing thread' WHERE ACTIVITY_ID = 	331
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bookstores' WHERE ACTIVITY_ID = 	332
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sandpaper' WHERE ACTIVITY_ID = 	333
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Canvas' WHERE ACTIVITY_ID = 	334
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Crazy' WHERE ACTIVITY_ID = 	335
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Madeira' WHERE ACTIVITY_ID = 	364
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bags' WHERE ACTIVITY_ID = 	365
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Maltaria' WHERE ACTIVITY_ID = 	366
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Machines' WHERE ACTIVITY_ID = 	367
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Marble' WHERE ACTIVITY_ID = 	368
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pasta' WHERE ACTIVITY_ID = 	369
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Slaughterhouses' WHERE ACTIVITY_ID = 	370
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Materials for Construction' WHERE ACTIVITY_ID = 	371
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Socks' WHERE ACTIVITY_ID = 	372
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Public Markets' WHERE ACTIVITY_ID = 	373
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Metal' WHERE ACTIVITY_ID = 	374
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Mining' WHERE ACTIVITY_ID = 	375
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Mills Cereals' WHERE ACTIVITY_ID = 	377
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Frames' WHERE ACTIVITY_ID = 	378
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Townhouses and Apart-Hotels' WHERE ACTIVITY_ID = 	379
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Furniture' WHERE ACTIVITY_ID = 	380
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Museums' WHERE ACTIVITY_ID = 	381
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Music' WHERE ACTIVITY_ID = 	382
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Potteries' WHERE ACTIVITY_ID = 	400
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Oilcloths' WHERE ACTIVITY_ID = 	401
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Mineral Oils' WHERE ACTIVITY_ID = 	402
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Vegetable Oils and Oilseeds' WHERE ACTIVITY_ID = 	403
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Orthopedic appliances' WHERE ACTIVITY_ID = 	404
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bones, horns and the like' WHERE ACTIVITY_ID = 	405
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Optics' WHERE ACTIVITY_ID = 	406
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Oxygen' WHERE ACTIVITY_ID = 	407
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bakeries' WHERE ACTIVITY_ID = 	420
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Toothpicks' WHERE ACTIVITY_ID = 	421
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Paper' WHERE ACTIVITY_ID = 	422
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Stationery' WHERE ACTIVITY_ID = 	423
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Precious stones and Semi-Precious' WHERE ACTIVITY_ID = 	424
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pisces' WHERE ACTIVITY_ID = 	425
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pawnshop, Houses' WHERE ACTIVITY_ID = 	426
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hostels' WHERE ACTIVITY_ID = 	427
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Perfumes and Toiletries' WHERE ACTIVITY_ID = 	428
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Paintings' WHERE ACTIVITY_ID = 	429
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pyrethrum, Flower' WHERE ACTIVITY_ID = 	430
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Piro woody' WHERE ACTIVITY_ID = 	431
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Plantations' WHERE ACTIVITY_ID = 	432
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Plastic' WHERE ACTIVITY_ID = 	433
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Feathers' WHERE ACTIVITY_ID = 	434
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Grit' WHERE ACTIVITY_ID = 	435
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Service Stations' WHERE ACTIVITY_ID = 	436
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pharmaceuticals' WHERE ACTIVITY_ID = 	437
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Chemicals' WHERE ACTIVITY_ID = 	438
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Barracks' WHERE ACTIVITY_ID = 	450
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Greengrocers' WHERE ACTIVITY_ID = 	451
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Radio and TV' WHERE ACTIVITY_ID = 	471
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Clothing' WHERE ACTIVITY_ID = 	472
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Soap' WHERE ACTIVITY_ID = 	490
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sacks of vegetable fibers' WHERE ACTIVITY_ID = 	491
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Salt' WHERE ACTIVITY_ID = 	492
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Concert Halls' WHERE ACTIVITY_ID = 	493
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sanitary, Articles' WHERE ACTIVITY_ID = 	494
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Scouring' WHERE ACTIVITY_ID = 	495
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Grocery' WHERE ACTIVITY_ID = 	496
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sericulture' WHERE ACTIVITY_ID = 	498
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Steel' WHERE ACTIVITY_ID = 	499
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Soybean' WHERE ACTIVITY_ID = 	500
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Clogs' WHERE ACTIVITY_ID = 	520
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Tannin' WHERE ACTIVITY_ID = 	521
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cooperages' WHERE ACTIVITY_ID = 	522
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Carpets' WHERE ACTIVITY_ID = 	523
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Theatres and Circuses' WHERE ACTIVITY_ID = 	524
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Telephones and Telegraphs' WHERE ACTIVITY_ID = 	525
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Timbo' WHERE ACTIVITY_ID = 	526
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Paints' WHERE ACTIVITY_ID = 	527
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Construction Materials' WHERE ACTIVITY_ID = 	528
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Printers' WHERE ACTIVITY_ID = 	529
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Glasses' WHERE ACTIVITY_ID = 	540
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Wicker, Rattan, brushes and Similar' WHERE ACTIVITY_ID = 	541
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Vinegar' WHERE ACTIVITY_ID = 	542
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Wines' WHERE ACTIVITY_ID = 	543
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Issuance Docs Below Threshold' WHERE ACTIVITY_ID = 	700
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Advance' WHERE ACTIVITY_ID = 	800
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Commission' WHERE ACTIVITY_ID = 	801
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Sinister' WHERE ACTIVITY_ID = 	802
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Third Pg' WHERE ACTIVITY_ID = 	803
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Alliance Hosp' WHERE ACTIVITY_ID = 	804
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Award Restored' WHERE ACTIVITY_ID = 	805
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'BNH Gatherings' WHERE ACTIVITY_ID = 	806
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Irb Gatherings' WHERE ACTIVITY_ID = 	807
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Taxes / Charges' WHERE ACTIVITY_ID = 	808
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Coinsurance' WHERE ACTIVITY_ID = 	809
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Advance Billing Awards' WHERE ACTIVITY_ID = 	810
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Deposits' WHERE ACTIVITY_ID = 	811
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Expenses Operacioinais' WHERE ACTIVITY_ID = 	812
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Alliance Construction' WHERE ACTIVITY_ID = 	813
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Inst Capital' WHERE ACTIVITY_ID = 	814
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ch Reissue Cancelled' WHERE ACTIVITY_ID = 	815
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Social Representation' WHERE ACTIVITY_ID = 	816
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Expenses with Medical and Pharmacy' WHERE ACTIVITY_ID = 	817
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Help with Meals' WHERE ACTIVITY_ID = 	818
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Marmoaria' WHERE ACTIVITY_ID = 	819
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Shipping & Reels' WHERE ACTIVITY_ID = 	820
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cleaning / Conservation / Reform' WHERE ACTIVITY_ID = 	821
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Driving and Pass Urban' WHERE ACTIVITY_ID = 	822
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Butchers' WHERE ACTIVITY_ID = 	3
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Fertilizers and Fertilizer' WHERE ACTIVITY_ID = 	4
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Aircraft - Construcaoes, Assemblies and Workshops' WHERE ACTIVITY_ID = 	5
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Orders Agencies' WHERE ACTIVITY_ID = 	6
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Travel and Tourism Agencies' WHERE ACTIVITY_ID = 	7
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Lottery Agencies' WHERE ACTIVITY_ID = 	8
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Agriculture, Livestock and Related Activities' WHERE ACTIVITY_ID = 	9
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Water and Sewer Distribution and Trtamento-' WHERE ACTIVITY_ID = 	10
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cotton - Deposit' WHERE ACTIVITY_ID = 	11
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cotton - Processing Plants' WHERE ACTIVITY_ID = 	12
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Live Animals - Commerce' WHERE ACTIVITY_ID = 	13
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Antiques - Shops' WHERE ACTIVITY_ID = 	14
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Photographic and cinematographic apparatus' WHERE ACTIVITY_ID = 	15
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Armarinhos' WHERE ACTIVITY_ID = 	16
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Arms and Ammunition' WHERE ACTIVITY_ID = 	17
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'General Lease' WHERE ACTIVITY_ID = 	18
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Perfume and beauty products - Manufacturing' WHERE ACTIVITY_ID = 	19
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Perfumes and toiletries - Shops' WHERE ACTIVITY_ID = 	20
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Funeral supplies - manufacturing and trade' WHERE ACTIVITY_ID = 	21
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Medical and Dental Articles' WHERE ACTIVITY_ID = 	22
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Homes' WHERE ACTIVITY_ID = 	23
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Automobiles and Motorcycles - Agencies' WHERE ACTIVITY_ID = 	24
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Automobiles and Motorcycles - Rent' WHERE ACTIVITY_ID = 	25
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Automobiles and Motorcycles - Dealers' WHERE ACTIVITY_ID = 	26
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Automobiles and Motorcycles - Workshops' WHERE ACTIVITY_ID = 	27
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Automobiles and Motorcycles - Parts and Accessories' WHERE ACTIVITY_ID = 	28
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Banks and Other Financial Institutions' WHERE ACTIVITY_ID = 	29
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bars, Restaurants and Coffee shops' WHERE ACTIVITY_ID = 	30
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Beverages - Trade' WHERE ACTIVITY_ID = 	31
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bicycles - Manufacture' WHERE ACTIVITY_ID = 	32
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Public Libraries and Archives' WHERE ACTIVITY_ID = 	33
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bicycles - Retail & Workshops' WHERE ACTIVITY_ID = 	34
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Nightclubs' WHERE ACTIVITY_ID = 	35
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bombonieres and confectionery' WHERE ACTIVITY_ID = 	36
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Tire' WHERE ACTIVITY_ID = 	37
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Rubber - Manufacture' WHERE ACTIVITY_ID = 	38
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Toys - Fabrication' WHERE ACTIVITY_ID = 	39
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Toys - Shops' WHERE ACTIVITY_ID = 	40
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hairdressing and other beauty treatments' WHERE ACTIVITY_ID = 	41
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Hunting, Fishing and Sport - Commerce' WHERE ACTIVITY_ID = 	42
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cocoa - Manufacture of Derivatives' WHERE ACTIVITY_ID = 	43
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cafe - roasting and grinding' WHERE ACTIVITY_ID = 	44
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Shoes - Manufacturing' WHERE ACTIVITY_ID = 	45
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Shoes - Shops' WHERE ACTIVITY_ID = 	46
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Notaries' WHERE ACTIVITY_ID = 	47
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Coal - extraction and Trade' WHERE ACTIVITY_ID = 	48
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Charcoal - Extraction and Trade' WHERE ACTIVITY_ID = 	49
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Theater' WHERE ACTIVITY_ID = 	50
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Holiday Games' WHERE ACTIVITY_ID = 	51
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Central Supplies' WHERE ACTIVITY_ID = 	52
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Spiritist Centers' WHERE ACTIVITY_ID = 	53
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ceramics and pottery' WHERE ACTIVITY_ID = 	54
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cereals' WHERE ACTIVITY_ID = 	55
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cereals - Processing Plants and Derivatives' WHERE ACTIVITY_ID = 	56
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cement - Manufacturing' WHERE ACTIVITY_ID = 	57
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Cinemas' WHERE ACTIVITY_ID = 	58
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Clinics and Medical-Dental' WHERE ACTIVITY_ID = 	59
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Clubs and associations' WHERE ACTIVITY_ID = 	60
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Mattresses - Commerce' WHERE ACTIVITY_ID = 	61
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Mattresses - Factories' WHERE ACTIVITY_ID = 	62
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Concrete - Concrete and Similar Articles' WHERE ACTIVITY_ID = 	63
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Condominiums Commercial and Mixed' WHERE ACTIVITY_ID = 	64
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Residential Condominiums' WHERE ACTIVITY_ID = 	65
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Canned Animal' WHERE ACTIVITY_ID = 	66
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Construction' WHERE ACTIVITY_ID = 	67
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Convents' WHERE ACTIVITY_ID = 	68
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Credit Cooperatives' WHERE ACTIVITY_ID = 	69
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Copiers' WHERE ACTIVITY_ID = 	70
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Ropes' WHERE ACTIVITY_ID = 	71
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Post and Telecommunications' WHERE ACTIVITY_ID = 	72
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Poultry' WHERE ACTIVITY_ID = 	73
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Tanneries' WHERE ACTIVITY_ID = 	74
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Pesticides, Feed and Fertilizer' WHERE ACTIVITY_ID = 	75
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Public Deposits' WHERE ACTIVITY_ID = 	76
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Disks and Tapes - Trade' WHERE ACTIVITY_ID = 	77
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Publishing and Printing Newspapers and Magazines' WHERE ACTIVITY_ID = 	78
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Publishers of Books' WHERE ACTIVITY_ID = 	79
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Electricity - articles of commerce' WHERE ACTIVITY_ID = 	80
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Electricity - Distributors' WHERE ACTIVITY_ID = 	81
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Electricity - Items Workshops' WHERE ACTIVITY_ID = 	82
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Appliances - Manufacturing' WHERE ACTIVITY_ID = 	83
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Appliances - Shops' WHERE ACTIVITY_ID = 	84
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Vessels - Manufacture and repair' WHERE ACTIVITY_ID = 	85
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Vessels - Guard' WHERE ACTIVITY_ID = 	86
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Engineering - Projects Office and' WHERE ACTIVITY_ID = 	87
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Machinery and Equipment - Rental' WHERE ACTIVITY_ID = 	88
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Equipment and Machinery - Dealers' WHERE ACTIVITY_ID = 	89
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Equipment and Machines - Workshops' WHERE ACTIVITY_ID = 	90
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Equipment and Machines - Parts and Accessories' WHERE ACTIVITY_ID = 	91
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Schools and Colleges' WHERE ACTIVITY_ID = 	92
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Brushes, Brooms and Brushes - Production' WHERE ACTIVITY_ID = 	93
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Law firm' WHERE ACTIVITY_ID = 	94
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Offices - Manufacture of Goods' WHERE ACTIVITY_ID = 	95
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Offices - Stores Articles' WHERE ACTIVITY_ID = 	96
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Accounting Offices' WHERE ACTIVITY_ID = 	97
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'General office' WHERE ACTIVITY_ID = 	98
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Stations Aeroporturias' WHERE ACTIVITY_ID = 	99
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Radio and TV' WHERE ACTIVITY_ID = 	100
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Railway stations' WHERE ACTIVITY_ID = 	101
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Maritime stations' WHERE ACTIVITY_ID = 	102
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Bus stations' WHERE ACTIVITY_ID = 	103
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Tow - Manufacturing' WHERE ACTIVITY_ID = 	104
UPDATE MNT_ACTIVITY_MASTER SET ACTIVITY_DESC = 'Explosives' WHERE ACTIVITY_ID = 	105
