
-- STRART FIRST SCRIPT
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=1 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(1,'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE GLOBAL DA COMPANHIA POR CORRETOR VALORES EXPRESSOS EM REAIS',3,'DEMO_PRO_SIN_COM_COR_VAL_EXP',14951)
END


-------------------------------------------------------------------------------------------------------------



IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=2 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(2,
'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE POR CORRETOR-ORGAO VALORES EXPRESSOS EM REAIS',3,'DEMO_PRO_SIN_COR_ORG_VAL_EXP',14952)
END


-------------------------------------------------------------------------------------------------------------


IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=3 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(3,
'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE POR CORRETOR-RAMO VALORES EXPRESSOS EM REAIS',3,'DEMO_PRO_SIN_COR_RAM_VAL_EXP',14953)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=4 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(4,
'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE GLOBAL DA COMPANHIA POR ORGAO VALORES EXPRESSOS EM REAIS
',3,'DEMO_PRO_SIN_COM_ORG_VAL_EXP',14948)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=5 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(5,
'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE POR ORGAO-CORRETOR VALORES EXPRESSOS EM REAIS',3,'DEMO_PRO_SIN_ORG_COR_VAL_EXP',14949)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=6 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(6,
'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE POR ORGAO-RAMO VALORES EXPRESSOS EM REAIS',3,'DEMO_PRO_SIN_ORG_RAM_VAL_EXP',14950)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=7 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(7,
'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE GLOBAL DA COMPANHIA POR RAMO VALORES EXPRESSOS EM REAIS
',3,'DEMO_PRO_SIN_COM_RAM_VAL_EXP',14945)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=8 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(8,
'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE POR RAMO-CORRETOR VALORES EXPRESSOS EM REAIS',3,'DEMO_PRO_SIN_RAM_COR_VAL_EXP',14946)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=9 AND REPORT_TYPE_ID=3)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(9,
'DEMONSTRATIVO DA PRODUCAO E SINISTRALIDADE POR RAMO-ORGAO VALORES EXPRESSOS EM REAIS',3,'DEMO_PRO_SIN_RAM_ORG_VAL_EXP',14947)
END


-------------------------------------------------------------------------------------------------------------
--- START SECOND SCRIPT



IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=10 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(10,
'APURACAO DE RESULTADO OPERACIONAL GLOBAL DA COMPANHIA POR CORRETOR VALORES EXPRESSOS EM REAIS',1,'APUR_RES_OPER_COM_COR_VAL_EXP',14951)
END


-------------------------------------------------------------------------------------------------------------



IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=11 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(11,
'APURACAO DE RESULTADO OPERACIONAL POR CORRETOR-ORGAO VALORES EXPRESSOS EM REAIS',1,
'APUR_RES_OPER_COR_ORG_VAL_EXP',14952)
END


-------------------------------------------------------------------------------------------------------------


IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=12 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(12,
'APURACAO DE RESULTADO OPERACIONAL POR CORRETOR-RAMO VALORES EXPRESSOS EM REAIS',1,
'APUR_RES_OPER_COR_RAM_VAL_EXP',14953)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=13 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(13,
'APURACAO DE RESULTADO OPERACIONAL GLOBAL DA COMPANHIA POR ORGAO VALORES EXPRESSOS EM REAIS',1,'APUR_RES_OPER_COM_ORG_VAL_EXP',14948)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=14 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(14,
'APURACAO DE RESULTADO OPERACIONAL POR ORGAO-CORRETOR VALORES EXPRESSOS EM REAIS',1,'APUR_RES_OPER_ORG_COR_VAL_EXP',14949)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=15 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(15,
'APURACAO DE RESULTADO OPERACIONAL POR ORGAO-RAMO VALORES EXPRESSOS EM REAIS',1,
'APUR_RES_OPER_ORG_RAM_VAL_EXP',14950)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=16 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(16,
'APURACAO DE RESULTADO OPERACIONAL GLOBAL DA COMPANHIA POR RAMO VALORES EXPRESSOS EM REAIS',1,'APUR_RES_OPER_COM_RAM_VAL_EXP',14945)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=17 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(17,
'APURACAO DE RESULTADO OPERACIONAL POR RAMO-CORRETOR VALORES EXPRESSOS EM REAIS',1,'APUR_RES_OPER_RAM_COR_VAL_EXP',14946)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=18 AND REPORT_TYPE_ID=1)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(18,
'APURACAO DE RESULTADO OPERACIONAL POR RAMO-ORGAO VALORES EXPRESSOS EM REAIS',1,
'APUR_RES_OPER_RAM_ORG_VAL_EXP',14947)
END


-------------------------------------------------------------------------------------------------------------

-- STRART THIRD SCRIPT

IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=19 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(19,'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE GLOBAL DA COMPANHIA POR CORRETOR VALORES EXPRESSOS EM REAIS',2,'DEMO_PRO_COR_SIN_COM_COR_VAL_EXP',14951)
END


-------------------------------------------------------------------------------------------------------------



IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=20 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(20,
'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE POR CORRETOR-ORGAO VALORES EXPRESSOS EM REAIS
',2,'DEMO_PRO_COR_SIN_COR_ORG_VAL_EXP',14952)
END


-------------------------------------------------------------------------------------------------------------


IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=21 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(21,
'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE POR CORRETOR-RAMO VALORES EXPRESSOS EM REAIS
',2,'DEMO_PRO_COR_SIN_COR_RAM_VAL_EXP',14953)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=22 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(22,
'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE GLOBAL DA COMPANHIA POR ORGAO VALORES EXPRESSOS EM REAIS
',2,'DEMO_PRO_COR_SIN_COM_ORG_VAL_EXP',14948)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=23 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(23,
'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE POR ORGAO-CORRETOR VALORES EXPRESSOS EM REAIS
',2,'DEMO_PRO_COR_SIN_ORG_COR_VAL_EXP',14949)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=24 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(24,
'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE POR ORGAO-RAMO VALORES EXPRESSOS EM REAIS
',2,'DEMO_PRO_COR_SIN_ORG_RAM_VAL_EXP',14950)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=25 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(25,
'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE GLOBAL DA COMPANHIA POR RAMO VALORES EXPRESSOS EM REAIS
',2,'DEMO_PRO_COR_SIN_COM_RAM_VAL_EXP',14945)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=26 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(26,
'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE POR RAMO-CORRETOR VALORES EXPRESSOS EM REAIS
',2,'DEMO_PRO_COR_SIN_RAM_COR_VAL_EXP',14946)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=27 AND REPORT_TYPE_ID=2)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(27,
'DEMONSTRATIVO DA PRODUCAO COBRADA E SINISTRALIDADE POR RAMO-ORGAO VALORES EXPRESSOS EM REAIS
',2,'DEMO_PRO_COR_SIN_RAM_ORG_VAL_EXP',14947)
END


-------------------------------------------------------------------------------------------------------------
-- STRART FOURTH SCRIPT
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=28 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(28,'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE GLOBAL DA COMPANHIA POR CORRETOR VALORES EXPRESSOS EM REAIS',4,'DEMO_PRO_EMIT_SIN_COM_COR_VAL_EXP',14951)
END


-------------------------------------------------------------------------------------------------------------



IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=29 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(29,
'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE POR CORRETOR-ORGAO VALORES EXPRESSOS EM REAIS',4,'DEMO_PRO_EMIT_SIN_COR_ORG_VAL_EXP',14952)
END


-------------------------------------------------------------------------------------------------------------


IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=30 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(30,
'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE POR CORRETOR-RAMO VALORES EXPRESSOS EM REAIS',4,'DEMO_PRO_EMIT_SIN_COR_RAM_VAL_EXP',14953)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=31 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(31,
'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE GLOBAL DA COMPANHIA POR ORGAO VALORES EXPRESSOS EM REAIS
',4,'DEMO_PRO_EMIT_SIN_COM_ORG_VAL_EXP',14948)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=32 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(32,
'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE POR ORGAO-CORRETOR VALORES EXPRESSOS EM REAIS',4,'DEMO_PRO_EMIT_SIN_ORG_COR_VAL_EXP',14949)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=33 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(33,
'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE POR ORGAO-RAMO VALORES EXPRESSOS EM REAIS',4,'DEMO_PRO_EMIT_SIN_ORG_RAM_VAL_EXP',14950)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=34 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(34,
'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE GLOBAL DA COMPANHIA POR RAMO VALORES EXPRESSOS EM REAIS
',4,'DEMO_PRO_EMIT_SIN_COM_RAM_VAL_EXP',14945)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=35 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(35,
'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE POR RAMO-CORRETOR VALORES EXPRESSOS EM REAIS',4,'DEMO_PRO_EMIT_SIN_RAM_COR_VAL_EXP',14946)
END


-------------------------------------------------------------------------------------------------------------
IF NOT EXISTS(SELECT * FROM MNT_MANAGEMENT_REPORTS WHERE REPORT_ID=36 AND REPORT_TYPE_ID=4)
BEGIN
INSERT INTO MNT_MANAGEMENT_REPORTS(REPORT_ID,RDL_NAME,REPORT_TYPE_ID,RDL_SHORT_NAME,GROUP_ID) 
VALUES(36,
'DEMONSTRATIVO DA PRODUCAO EMITIDA E SINISTRALIDADE POR RAMO-ORGAO VALORES EXPRESSOS EM REAIS',4,'DEMO_PRO_EMIT_SIN_RAM_ORG_VAL_EXP',14947)
END


-------------------------------------------------------------------------------------------------------------

