
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
                   WHERE TABLE_NAME = 'PRINT_JOBS' AND (COLUMN_NAME = 'PICKED_BY')
                   )
	BEGIN
			ALTER TABLE PRINT_JOBS 
			ADD PICKED_BY NVARCHAR(20) NULL
    END
