----------------------------------------------------------------------------------
--  ***********			REBUILD INDEXES QUERY			**************************
--**********************************************************************************

-- CREATED_BY: ATUL KUMAR SINGH
-- PURPOSE : REBUILD INDEXES

-- AUTOMATION PROCESS

-- THERE IS SQL JOB RUNNING AFTER EVERY 2 MONTHS EXECUTED THIS QYERY
--**********************************************************************************


DECLARE @TABLENAME VARCHAR(255)

DECLARE TABLECURSOR CURSOR FOR
-- SELECT ALL TABLES
SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE'

OPEN TABLECURSOR

FETCH NEXT FROM TABLECURSOR INTO @TABLENAME
WHILE @@FETCH_STATUS = 0
BEGIN
--REBUILD ALL INDEXES FOR LOOP TABLE WITH FILL FACTOR 0

DBCC DBREINDEX (@TABLENAME,' ',0)

FETCH NEXT FROM TABLECURSOR INTO @TABLENAME
END

CLOSE TABLECURSOR

DEALLOCATE TABLECURSOR
GO