
IF NOT EXISTS (SELECT * FROM MNT_MENU_LIST WHERE MENU_ID=554)
BEGIN
	INSERT INTO MNT_MENU_LIST (MENU_ID,PARENT_ID,MENU_NAME,MENU_LINK,MENU_TOOLTIP,NESTLEVEL,MENU_ORDER,HASCHILD,SHOWTYPE,HIDESTATUS,ISSECURITY,LANGID,MENU_IMAGE,DEFAULT_PAGE,MODULE_NAME,AGENCY_LEVEL,LOB_CODE,IS_ACTIVE)
									VALUES(554,199,'UWRuleTestBed','/Cms/Account/Aspx/UWRuleTestBed.aspx',NULL,2,11,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
END



IF NOT EXISTS (SELECT * FROM MNT_MENU_LIST_MULTILINGUAL WHERE MENU_ID=554)
BEGIN
	INSERT INTO MNT_MENU_LIST_MULTILINGUAL (MENU_ID,MENU_NAME,LANG_ID) VALUES(554,'UWTestBedregra',2)
END	

		
IF NOT EXISTS (SELECT * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='554_0')
BEGIN 
  INSERT INTO MNT_SCREEN_LIST (SCREEN_ID,SCREEN_DESC,SCREEN_PATH,SCREEN_READ,SCREEN_WRITE,SCREEN_DELETE,SCREEN_EXECUTE,IS_ACTIVE) 
		VALUES('554_0','UWRuleTestBed','/Cms/Account/Aspx/UWRuleTestBed.aspx','1','1','1','1','Y')
END
		
IF NOT EXISTS (SELECT * FROM MNT_SCREEN_LIST_MULTILINGUAL  WHERE SCREEN_ID='554_0')
BEGIN 
  INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL (SCREEN_ID,SCREEN_DESC,LANG_ID) 
		VALUES('554_0','UWTestBedregra',2)
END			

