

 IF EXISTS( SELECT * FROM  MNT_MENU_LIST WHERE IS_ACTIVE IS NULL )
   BEGIN
   UPDATE  MNT_MENU_LIST SET IS_ACTIVE='Y' WHERE IS_ACTIVE IS NULL
   END



-- SCRIPT TO ADD NEW SCREEN ID IN DATABASE

--SELECT * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='552'


IF(NOT EXISTS (SELECT  * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='552'))
BEGIN
			INSERT INTO MNT_SCREEN_LIST
			(
			 SCREEN_ID, SCREEN_DESC,SCREEN_PATH, SCREEN_READ, SCREEN_WRITE, SCREEN_DELETE, SCREEN_EXECUTE, IS_ACTIVE
			 )
			 VALUES
			 (
			 '552', 'Carrier Menu Setup', '/Cms/CmsWeb/maintenance/CarrierMenuSetup.aspx', 1, 1, 1, 1, 'Y'			 
			)
END			
------------------------------------------------------------------------------------------------------------------

--- MNT_SCREEN_LIST_MULTILINGUAL--------------

--  select * from MNT_SCREEN_LIST_MULTILINGUAL	WHERE SCREEN_ID='552'

IF NOT EXISTS( SELECT * FROM MNT_SCREEN_LIST_MULTILINGUAL WHERE SCREEN_ID='552')
BEGIN 
INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL 
(SCREEN_ID,SCREEN_DESC,LANG_ID) VALUES ('552','Configuração menu transportadora','2')
END

