
--Scripts for itrack-1422
If Exists(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID='168')
BEGIN
Update CLM_TYPE_DETAIL_MULTILINGUAL
set TYPE_DESC='Reabertura de Reserva' where DETAIL_TYPE_ID='168'
END


IF EXISTS (SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=14887)
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL 
SET LOOKUP_VALUE_DESC='Nro. Sinistro'
WHERE LOOKUP_UNIQUE_ID =14887
END
