---The Script for Tfs id-1783 
 IF EXISTS(Select * from POL_PROCESS_MASTER_MULTILINGUAL where PROCESS_ID=6 and LANG_ID=2)
 BEGIN
 Update POL_PROCESS_MASTER_MULTILINGUAL
 set PROCESS_DESC='Não Renovar' where PROCESS_ID=6 and LANG_ID=2
 END
 
 IF EXISTS(Select * from POL_PROCESS_MASTER_MULTILINGUAL where PROCESS_ID=28 and LANG_ID=2)
 BEGIN
 Update POL_PROCESS_MASTER_MULTILINGUAL
 set PROCESS_DESC='Reverter' where PROCESS_ID=28 and LANG_ID=2
 END

 IF EXISTS(Select * from POL_PROCESS_MASTER_MULTILINGUAL where PROCESS_ID=24 and LANG_ID=2)
 BEGIN
 Update POL_PROCESS_MASTER_MULTILINGUAL
 set PROCESS_DESC='Seguro Novo' where PROCESS_ID=24 and LANG_ID=2
 END




