--Script for itrack-1693
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=11736)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Regulador de Sinistro Interno' where LOOKUP_UNIQUE_ID=11736
 END
 
  IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=11737)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Regulador de Sinistro Externo' where LOOKUP_UNIQUE_ID=11737
 END
 
  IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=11738)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Regulador de Sinistro de Terceiros' where LOOKUP_UNIQUE_ID=11738
 END
 