BEGIN TRANSACTION ABHI
----Script for issue 1405
If exists(Select * from MNT_MENU_LIST_MULTILINGUAL where MENU_ID=533)
Begin
Update MNT_MENU_LIST_MULTILINGUAL
set MENU_NAME='Relatório de Emissão'
where MENU_ID=533
End

If exists(Select * from MNT_MENU_LIST_MULTILINGUAL where MENU_ID=530)
Begin
Update MNT_MENU_LIST_MULTILINGUAL
set MENU_NAME='Relatórios de Resseguro e Cosseguro'
where MENU_ID=530
End

If exists(Select * from MNT_MENU_LIST_MULTILINGUAL where MENU_ID=536)
Begin
Update MNT_MENU_LIST_MULTILINGUAL
set MENU_NAME='Relatórios SUSEP'
where MENU_ID=536
End

If exists(Select * from MNT_MENU_LIST_MULTILINGUAL where MENU_ID=416)
Begin
Update MNT_MENU_LIST_MULTILINGUAL
set MENU_NAME='Log dos Processos EOD'
where MENU_ID=416
End

If exists(Select * from MNT_MENU_LIST_MULTILINGUAL where MENU_ID=537)
Begin
Update MNT_MENU_LIST_MULTILINGUAL
set MENU_NAME='Gestão de Interfaces'
where MENU_ID=537
End



----interface management

if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=990)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Documento Rejeitado pelo Pagnet-Retornou para Ebix'
where INTERFACE_CODE=990

if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=991)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Documento Rejeitado pelo Pagnet-Esperando por Correção no Pagnet'
where INTERFACE_CODE=991


if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=007 and ROW_ID=459)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Pagamento Cancelado pelo Banco(Observações)'
where INTERFACE_CODE=007 and ROW_ID=459


if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=011 and ROW_ID=461)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Pagamento Cancelado pelo Banco(Observações)'
where INTERFACE_CODE=011 and ROW_ID=461

if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=005 and ROW_ID=470)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Pagamento Cancelado pelo Banco(Observações)'
where INTERFACE_CODE=005 and ROW_ID=470


if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=005 and ROW_ID=457)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Pagamento Efetuado no Pagnet'
where INTERFACE_CODE=005 and ROW_ID=457

if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=010 and ROW_ID=460)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Pagamento Efetuado no Pagnet'
where INTERFACE_CODE=010 and ROW_ID=460

if exists(Select * from PAGNET_INTERFACE_CODES where INTERFACE_CODE=003 and ROW_ID=468)
update PAGNET_INTERFACE_CODES
set PORT_DESCRIPTION='Pagamento Efetuado no Pagnet'
where INTERFACE_CODE=003 and ROW_ID=468



--- Script for management report dropdown



 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14945)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Por Divisão' where LOOKUP_UNIQUE_ID=14945
 END
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14946)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Por Divisão e Corretor' where LOOKUP_UNIQUE_ID=14946
 END
  IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14947)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Por Divisão e Ramo Contábil' where LOOKUP_UNIQUE_ID=14947
 END
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14948)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Por Ramo Contábil' where LOOKUP_UNIQUE_ID=14948
 END
 IF EXISTS(select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14949)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Por Ramo Contábil e Corretor' where LOOKUP_UNIQUE_ID=14949
 END
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14950)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Por Ramo Contábil e Divisão' where LOOKUP_UNIQUE_ID=14950
 END
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14951)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Por Corretor - Por Corretor e Divisão' where LOOKUP_UNIQUE_ID=14951
 END
 IF EXISTS(Select * from MNT_LOOKuP_VALUES where LOOKUP_UNIQUE_ID=14952)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Por Corretor e Ramo Contábil' where LOOKUP_UNIQUE_ID=14952
 END
 IF EXISTS(Select * from MNT_LOOKUP_VALUES where LOOKUP_UNIQUE_ID=14953)
 BEGIN
 Update MNT_LOOKUP_VALUES
 set IS_ACTIVE='N'where LOOKUP_UNIQUE_ID=14953
 END
 
 
 
 ----Script for Eod Activity list
 
 If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=106 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Declaração de Corretor Regular' where ACTIVITY_ID=106 and LANG_ID=2 
END
If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=107 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Declaração de Corretor Adicional' where ACTIVITY_ID=107 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=101 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Informações Bancárias' where ACTIVITY_ID=101 and LANG_ID=2 
END


If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=301 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Envio para Banco' where ACTIVITY_ID=301 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=204 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Criar Acompanhamento' where ACTIVITY_ID=204 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=103 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Pre Pagamento Normal' where ACTIVITY_ID=103 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=104 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Aviso de Criação de Prêmio' where ACTIVITY_ID=104 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=102 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Lançamentos Recorrentes' where ACTIVITY_ID=102 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=207 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Acompanhamento de Renovação' where ACTIVITY_ID=207 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=108 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Compor Balancete' where ACTIVITY_ID=108 and LANG_ID=2 
END


If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=11 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Acompanhamento de Envios' where ACTIVITY_ID=11 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=300 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Envio de Documento' where ACTIVITY_ID=300 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=502 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Reserva de Sinistro Atualizado pelo Índice Monetário' where ACTIVITY_ID=502 and LANG_ID=2 
END
 
ROLLBACK TRANSACTION ABHI
 














