 
 ----itrack Expert Service Provider
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=11960)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Não Enviado' where LOOKUP_UNIQUE_ID=11960
 END
 
 
 ---
 
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=11771)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Veículo do Segurado' where LOOKUP_UNIQUE_ID=11771
 END
 
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=11772)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Veículo de Terceiros' where LOOKUP_UNIQUE_ID=11772
 END

------
IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14525)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Isento-SSN' where LOOKUP_UNIQUE_ID=14525
 END
 
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14526)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Outros-SSN' where LOOKUP_UNIQUE_ID=14526
 END
 
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14527)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Incorporado-SSN' where LOOKUP_UNIQUE_ID=14527
 END
 
 -----
 
 IF EXISTS(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=160)
 BEGIN
 Update CLM_TYPE_DETAIL_MULTILINGUAL
 set TYPE_DESC='Procurador do Segurado' where DETAIL_TYPE_ID=160
 END
 
 IF EXISTS(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=161)
 BEGIN
 Update CLM_TYPE_DETAIL_MULTILINGUAL
 set TYPE_DESC='Procurador da Seguradora' where DETAIL_TYPE_ID=161
 END
 
 IF EXISTS(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=23)
 BEGIN
 Update CLM_TYPE_DETAIL_MULTILINGUAL
 set TYPE_DESC='Especialistas' where DETAIL_TYPE_ID=23
 END
 
  IF EXISTS(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=24)
 BEGIN
 Update CLM_TYPE_DETAIL_MULTILINGUAL
 set TYPE_DESC='Advogado do Segurado' where DETAIL_TYPE_ID=24
 END
 
   IF EXISTS(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=191)
 BEGIN
 Update CLM_TYPE_DETAIL_MULTILINGUAL
 set TYPE_DESC='Outros' where DETAIL_TYPE_ID=191
 END
 
   IF EXISTS(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=162)
 BEGIN
 Update CLM_TYPE_DETAIL_MULTILINGUAL
 set TYPE_DESC='Prestadores de Serviços' where DETAIL_TYPE_ID=162
 END
 
    IF EXISTS(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=22)
 BEGIN
 Update CLM_TYPE_DETAIL_MULTILINGUAL
 set TYPE_DESC='TPA''s' where DETAIL_TYPE_ID=22
 END
 
