--THE SCRIPT FOR ISSUE 1814
--BEGIN TRANSACTION ABHI
IF EXISTS(Select * from MNT_SUSEP_LOB_MASTER where SUSEP_LOB_ID>=1 and SUSEP_LOB_ID<=99)
BEGIN
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0111 - INCÊNDIO TRADICIONAL 'WHERE SUSEP_LOB_ID=1
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0112 - INCÊNDIO-BILHETES 'WHERE SUSEP_LOB_ID=2
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0113 - VIDROS 'WHERE SUSEP_LOB_ID=3
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0114 - COMPREENSIVO RESIDENCIAL 'WHERE SUSEP_LOB_ID=4
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0115 - ROUBO 'WHERE SUSEP_LOB_ID=5
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0116 - COMPREESIVO CONDOMÍNIO'WHERE SUSEP_LOB_ID=6
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0117 - TUMULTOS 'WHERE SUSEP_LOB_ID=7
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0118 - COMPREENSIVO EMPRESARIAL 'WHERE SUSEP_LOB_ID=8
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0141 - LUCROS CESSANTES 'WHERE SUSEP_LOB_ID=9
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0142 - LUCROS CESSANTES COBERTURA SIMPLES 'WHERE SUSEP_LOB_ID=10
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0143 - FIDELIDADE 'WHERE SUSEP_LOB_ID=11
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0167 - RISCOS DE ENGENHARIA 'WHERE SUSEP_LOB_ID=12
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0171 - RISCOS DIVERSOS 'WHERE SUSEP_LOB_ID=13
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0173 - GLOBAL DE BANCOS 'WHERE SUSEP_LOB_ID=14
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0176 - RISCOS DIVERSOS-PLANOS CONJUGADOS 'WHERE SUSEP_LOB_ID=15
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0195 - Extensão de Garantia-Patrimonial 'WHERE SUSEP_LOB_ID=16
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0196 - Riscos Nomeados e Operacionais 'WHERE SUSEP_LOB_ID=17
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0234 - RISCOS DE PETRÓLEO 'WHERE SUSEP_LOB_ID=18
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0272 - RISCOS NUCLEARES 'WHERE SUSEP_LOB_ID=19
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0274 - SATÉLITES 'WHERE SUSEP_LOB_ID=20
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0310 - R.C.DE ADM.E DIRETORES (D&O) 'WHERE SUSEP_LOB_ID=21
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0351 - RESPONSABILIDADE CIVIL GERAL 'WHERE SUSEP_LOB_ID=22
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0378 - R.C.PROFISSIONAL 'WHERE SUSEP_LOB_ID=23
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0433 - MARÍTIMOS 'WHERE SUSEP_LOB_ID=24
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0435 - AERONÁUTICOS 'WHERE SUSEP_LOB_ID=25
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0437 - RESPONSABILIDADE CIVIL HANGAR 'WHERE SUSEP_LOB_ID=26
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0457 - D.P.E.M. 'WHERE SUSEP_LOB_ID=27
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0484 - AERONÁUTICOS-BILHETE 'WHERE SUSEP_LOB_ID=28
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0520 - ACIDENTES PESSOAIS DE PASSAGEIROS  'WHERE SUSEP_LOB_ID=29
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0523 - RCT.ROD.INTEREST.EINTERNAC 'WHERE SUSEP_LOB_ID=30
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0524 - EXTENSÃO DE GARANTIA-AUTOMÓVEL 'WHERE SUSEP_LOB_ID=31
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0525 - CARTA VERDE 'WHERE SUSEP_LOB_ID=32
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0526 - SEGURO POPULAR DE AUTOMÓVEL 'WHERE SUSEP_LOB_ID=33
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0531 - AUTOMÓVEIS 'WHERE SUSEP_LOB_ID=34
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0544 - R.C.T.VIAGEM INTER-PES TRANS OU Ñ 'WHERE SUSEP_LOB_ID=35
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0553 - RESP.CIVIL FACULTATIVA 'WHERE SUSEP_LOB_ID=36
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0583 - DPVAT EXTINTO 'WHERE SUSEP_LOB_ID=37
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0588 - DPVAT(TODAS CATEG).A PARTIR JAN 05 'WHERE SUSEP_LOB_ID=38
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0589 - DPVAT RUN OFF 'WHERE SUSEP_LOB_ID=39
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0621 - TRANSPORTE NACIONAL 'WHERE SUSEP_LOB_ID=40
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0622 - TRANSPORTE INTERNACIONAL 'WHERE SUSEP_LOB_ID=41
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0627 - RESP. CIVIL DO TRANSP. INTERMODAL 'WHERE SUSEP_LOB_ID=42
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0632 - RC DO TRANAS. VIAGEM INTERNAC CARGA'WHERE SUSEP_LOB_ID=43
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0638 - RC DO TRANSP. FERROVIÁRIO CARGA'WHERE SUSEP_LOB_ID=44
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0652 - RESP.CIVIL DO TRANSP.AÉREO CARGA 'WHERE SUSEP_LOB_ID=45
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0654 - RESP.C.TRANSPORTADOR RODOV.- CARGA 'WHERE SUSEP_LOB_ID=46
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0655 - RESP.CIVIL DESVIO DE CARGA 'WHERE SUSEP_LOB_ID=47
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0656 - RESP.CIVIL ARMADOR 'WHERE SUSEP_LOB_ID=48
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0658 - RESP.CIVIL OP.TRANSP.MULTIMODAL 'WHERE SUSEP_LOB_ID=49
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0739 - GARANTIA FINANCEIRA 'WHERE SUSEP_LOB_ID=50
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0740 - GARANTIA DE OBRIGAÇÕES PRIVADAS 'WHERE SUSEP_LOB_ID=51
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0745 - GARANTIA DE OBRIGAÇÕES PÚBLICAS 'WHERE SUSEP_LOB_ID=52
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0746 - FIANÇA LOCATÍCIA 'WHERE SUSEP_LOB_ID=53
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0747-Garantia de Concessões Públicas 'WHERE SUSEP_LOB_ID=54
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0750 - GARANTIA JUDICIAL 'WHERE SUSEP_LOB_ID=55
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0775 - GARANTIA 'WHERE SUSEP_LOB_ID=56
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0819 - CRÉDITO À EXP. RISCO COMERCIAL 'WHERE SUSEP_LOB_ID=57
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0848 - CRÉDITO INTERNO 'WHERE SUSEP_LOB_ID=58
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0849 - CRÉDITO A EXPORTAÇÃO 'WHERE SUSEP_LOB_ID=59
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0859 - CRÉDITO À EXPORTAÇÃO RISCO POLÍTICO 'WHERE SUSEP_LOB_ID=60
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0860 - CRÉDITO DOMÉSTICO RISCO COMERCIAL 'WHERE SUSEP_LOB_ID=61
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0870 - CRÉDITO DOMÉSTICO RISCO P. FÍSICA 'WHERE SUSEP_LOB_ID=62
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0936 - P.C.H.V 'WHERE SUSEP_LOB_ID=63
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0969 - TURÍSTICO 'WHERE SUSEP_LOB_ID=64
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0977 - PRESTAMISTA 'WHERE SUSEP_LOB_ID=65
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0980 - SEGURO EDUCACIONAL 'WHERE SUSEP_LOB_ID=66
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0981 - ACIDENTES PESSOAIS INDIVIDUAL 'WHERE SUSEP_LOB_ID=67
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0982 - ACIDENTES PESSOAIS COLETIVO 'WHERE SUSEP_LOB_ID=68
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0990 - RENDA DE EVENTOS ALEATÓRIOS 'WHERE SUSEP_LOB_ID=69
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0991 - VIDA INDIVIDUAL 'WHERE SUSEP_LOB_ID=70
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0992 - VGBL/VAGP/VRGP/VRSA/PRI INDIVIDUAL 'WHERE SUSEP_LOB_ID=71
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0993 - VIDA EM GRUPO 'WHERE SUSEP_LOB_ID=7
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0994 - VGBL/VAGP/VRGP/VRSA/PRI COLETIVO'WHERE SUSEP_LOB_ID=73
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0997 - VG/APC 'WHERE SUSEP_LOB_ID=74
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1066 - HABITACIONAL-SFH 'WHERE SUSEP_LOB_ID=75
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1068 - HABITACIONAL-FORA DO SFH 'WHERE SUSEP_LOB_ID=76
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1101 - SEGURO AGRÍCOLA SEM COB. DO FESR 'WHERE SUSEP_LOB_ID=77
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1102 - SEGURO AGRÍCOLA COM COB. DO FESR 'WHERE SUSEP_LOB_ID=78
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1103 - SEGURO PECUÁRIO SEM COB. DO FESR  'WHERE SUSEP_LOB_ID=79
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1104 - SEGURO PECUÁRIO COM COB. DO FESR 'WHERE SUSEP_LOB_ID=80
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1105 - SEGURO AQUÍCOLA SEM COB. DO FESR  'WHERE SUSEP_LOB_ID=81
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1106 - SEGURO AQUÍCOLA COM COB. DO FESR 'WHERE SUSEP_LOB_ID=82
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1107 - SEGURO FLORESTAS SEM COB. DO FESR  'WHERE SUSEP_LOB_ID=83
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1108 - SEGURO FLORESTAS COM COB. DO FESR 'WHERE SUSEP_LOB_ID=84
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1109 - SEGURO DA CÉLULA DO PRODUTO RURAL 'WHERE SUSEP_LOB_ID=85
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1128 - PECUÁRIO 'WHERE SUSEP_LOB_ID=86
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1129 - AQUÍCOLA 'WHERE SUSEP_LOB_ID=87
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1130 - BENFEITORIAS E PROD.AGROPECUÁRIOS 'WHERE SUSEP_LOB_ID=88
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1161 - AGRÍCOLA 'WHERE SUSEP_LOB_ID=89
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1162 - PENHOR RURAL INSTIT. FIN. PRIV  'WHERE SUSEP_LOB_ID=90
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1163 - PENHOR RURAL INSTIT. FIN. PUB 'WHERE SUSEP_LOB_ID=91
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1164 - ANIMAIS 'WHERE SUSEP_LOB_ID=92
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1165 - COMPREENSIVO DE FLORESTAS 'WHERE SUSEP_LOB_ID=93
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1198 - SEGURO DE VIDA DO PRODUTOR RURAL 'WHERE SUSEP_LOB_ID=94
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1279 - SEGUROS NO EXTERIOR'WHERE SUSEP_LOB_ID=95
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1285 - SAÚDE 'WHERE SUSEP_LOB_ID=96
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1286 - SAÚDE INDIVIDUAL 'WHERE SUSEP_LOB_ID=97
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1287 - SAÚDE GRUPAL 'WHERE SUSEP_LOB_ID=98
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='1299 - SUCURSAIS NO EXTERIOR 'WHERE SUSEP_LOB_ID=99
END
--select * from  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
--ROLLBACK TRANSACTION ABHI


IF EXISTS(SELECT * FROM MNT_SUSEP_LOB_MASTER_MULTILINGUAL WHERE SUSEP_LOB_ID=100)
BEGIN
UPDATE  MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0746 - FIANÇA LOCATÍCIA'
WHERE SUSEP_LOB_ID=100 
END