BEGIN TRANSACTION ABHI
IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID=1448)
BEGIN
INSERT INTO MNT_LOOKUP_TABLES (LOOKUP_ID,LOOKUP_NAME,LOOKUP_DESC,LOOKUP_TYPE,LOOKUP_TBL_EDIT,LOOKUP_CODE_WIDTH,LOOKUP_DISPLAY_FORMAT,LOOKUP_DESC_WIDTH,LOOKUP_LEVEL)
						VALUES(1448,'%SALU','SALUTATION','H','Y','4','N',225,'D')
END

IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_TABLES_MULTILINGUAL WHERE LOOKUP_ID=1448)
BEGIN 
INSERT INTO MNT_LOOKUP_TABLES_MULTILINGUAL (LOOKUP_ID,LOOKUP_DESC,LANG_ID)VALUES(1448,'SALUTATION',2)
END

IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15011)
BEGIN 
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE) 
						VALUES(15011,1448,1,'Mr','Mr.',1,'Y',NULL,NULL,NULL,NULL)
END

IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15012)
BEGIN
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
						VALUES(15012,1448,2,'Miss','Miss.',2,'Y',NULL,NULL,NULL,NULL)
END

IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15013)
BEGIN
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
						VALUES(15013,1448,2,'Mrs','Mrs.',3,'Y',NULL,NULL,NULL,NULL)
END


IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15011)
BEGIN
INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL (LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
									 VALUES(15011,'Sr.',2)
END

IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15012)
BEGIN
INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL (LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
									 VALUES(15012,'Senhorita',2)
END

IF NOT EXISTS (SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15013)
BEGIN
INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL (LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
									 VALUES(15013,'Senhora',2)
END
ROLLBACK TRANSACTION ABHI
