-----------MNT_MENU_LIST------------------------
--select MAX(MENU_ID) from MNT_MENU_LIST 
--SELECT * FROM MNT_MENU_LIST WHERE PARENT_ID=13 and MENU_ID=456

 IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST WHERE MENU_ID=564 and PARENT_ID=199)
	BEGIN
		INSERT INTO MNT_MENU_LIST
		(MENU_ID,PARENT_ID,MENU_NAME,MENU_LINK,MENU_TOOLTIP,NESTLEVEL,MENU_ORDER,HASCHILD,SHOWTYPE,HIDESTATUS
		 ,ISSECURITY,LANGID,MENU_IMAGE,DEFAULT_PAGE,MODULE_NAME,AGENCY_LEVEL,LOB_CODE,IS_ACTIVE)
		 VALUES
		 (564,199,'Reinsurance Installment Detail','/Cms/Account/Aspx/ReinsuranceInstallmentDetails.aspx',NULL,2,15,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL)
	 END
 GO
 


 IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST_MULTILINGUAL WHERE MENU_ID=564)
	BEGIN
		INSERT INTO MNT_MENU_LIST_MULTILINGUAL
		(MENU_ID,MENU_NAME,LANG_ID)
		 VALUES
		 (564,'Detalhe Parcelamento de resseguro',2)
	 END


IF NOT EXISTS (SELECT  * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='564_0')
BEGIN
			INSERT INTO MNT_SCREEN_LIST
			(
			 SCREEN_ID, SCREEN_DESC,SCREEN_PATH, SCREEN_READ, SCREEN_WRITE, SCREEN_DELETE, SCREEN_EXECUTE, IS_ACTIVE
			 )
			 VALUES
			 (
			 '564_0', 'Reinsurance Installment Detail', '/Cms/Account/Aspx/ReinsuranceInstallmentDetails.aspx', 1, 1, 1, 1, 'Y'			 
			)
END	




IF(NOT EXISTS (SELECT  * FROM MNT_SCREEN_LIST_MULTILINGUAL WHERE SCREEN_ID='564_0'))
BEGIN
			INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL 
			(
			 SCREEN_ID, SCREEN_DESC,LANG_ID
			 )
			 VALUES
			 (
			 '564_0', 'Detalhe Parcelamento de resseguro',2		 
			)
END	




