
 
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14706)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Apólice' where LOOKUP_UNIQUE_ID=14706
 END
 
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14705)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Risco do Objeto' where LOOKUP_UNIQUE_ID=14705
 END
 
 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14639)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Dedutíveis' where LOOKUP_UNIQUE_ID=14639
 END

IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14641)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Múltiplas Franquias' where LOOKUP_UNIQUE_ID=14641
 END

IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=14698)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Agravo' where LOOKUP_UNIQUE_ID=14698
 END
 
 
 ---Menu

IF EXISTS(Select * from MNT_MENU_LIST_MULTILINGUAL where MENU_ID=456)
 BEGIN
 Update MNT_MENU_LIST_MULTILINGUAL
 set MENU_NAME='Desconto/Agravo' where MENU_ID=456
 END
 
 



 


