
IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '13046')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Não Aplicável' WHERE  LOOKUP_UNIQUE_ID = '13046'
END
IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14891')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Cobertura de Endosso' WHERE  LOOKUP_UNIQUE_ID = '14891'
END
IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14892')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Cobertura de Resseguro' WHERE  LOOKUP_UNIQUE_ID = '14892'
END
IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14656')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Solicitação de Seguro Novo' WHERE  LOOKUP_UNIQUE_ID = '14656'
END
IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14657')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Solicitação de Renovação' WHERE  LOOKUP_UNIQUE_ID = '14657'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '11296')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Seção II' WHERE  LOOKUP_UNIQUE_ID = '11296'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '11295')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Seção I ' WHERE  LOOKUP_UNIQUE_ID = '11295'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '11331')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Interior Marinho' WHERE  LOOKUP_UNIQUE_ID = '11331'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '11768')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Política de Nível de Apólice' WHERE  LOOKUP_UNIQUE_ID = '11768'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14648')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Plano' WHERE  LOOKUP_UNIQUE_ID = '14648'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14650')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Somente Leitura' WHERE  LOOKUP_UNIQUE_ID = '14650'
END



IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14652')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Plano' WHERE  LOOKUP_UNIQUE_ID = '14652'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14654')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Somente Leitura' WHERE  LOOKUP_UNIQUE_ID = '14654'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14699')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Seguro Novo/Renovação' WHERE  LOOKUP_UNIQUE_ID = '14699'
END


------

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14202')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Não Aplicável' WHERE  LOOKUP_UNIQUE_ID = '14202'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14201')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Responsabilidade da Embarcação' WHERE  LOOKUP_UNIQUE_ID = '14201'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14199')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Passageiro Individual Auto Comp' WHERE  LOOKUP_UNIQUE_ID = '14199'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14198')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Responsabilidade (CSL, BI, MP)' WHERE  LOOKUP_UNIQUE_ID = '14198'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14197')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Motocicleta Comp.' WHERE  LOOKUP_UNIQUE_ID = '14197'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14196')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Proprietário Seção II' WHERE  LOOKUP_UNIQUE_ID = '14196'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14195')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Proprietário Seção I' WHERE  LOOKUP_UNIQUE_ID = '14195'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14194')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Interior Marinho' WHERE  LOOKUP_UNIQUE_ID = '14194'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14193')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Linhas Aliadas' WHERE  LOOKUP_UNIQUE_ID = '14193'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14191')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Comercial Auto Comp.' WHERE  LOOKUP_UNIQUE_ID = '14191'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14190')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto/Ciclo UM,UIM - Unip. passageiro' WHERE  LOOKUP_UNIQUE_ID = '14190'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14189')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto /Ciclo PIP -Unip.passageiro' WHERE  LOOKUP_UNIQUE_ID = '14189'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14188')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto Ciclo CSL/-Unip.Passageiro' WHERE  LOOKUP_UNIQUE_ID = '14188'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14187')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto/Ciclo PD,PPI-Unip. passageiro' WHERE  LOOKUP_UNIQUE_ID = '14187'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14186')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto/Ciclo de BI,MP -Unip.passageiro' WHERE  LOOKUP_UNIQUE_ID = '14186'
END




----AsLOB
IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14335')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'ASLOB Inválida' WHERE  LOOKUP_UNIQUE_ID = '14335'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14334')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Proprietário Taxas de Estatística' WHERE  LOOKUP_UNIQUE_ID = '14334'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14333')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Aluguel Taxas de Estatística' WHERE  LOOKUP_UNIQUE_ID = '14334'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14266')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Responsabilidade da Motocicleta Taxas de Estatística' WHERE  LOOKUP_UNIQUE_ID = '14266'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14265')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto Comercial Taxas de Estatística' WHERE  LOOKUP_UNIQUE_ID = '14265'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14263')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'PPA Taxas de Estatística' WHERE  LOOKUP_UNIQUE_ID = '14263'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14179')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Responsabilidade da Motocicleta' WHERE  LOOKUP_UNIQUE_ID = '14179'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14178')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto Comercial Danos Físicos' WHERE  LOOKUP_UNIQUE_ID = '14178'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14176')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto Comercial Outras Responsabilidades' WHERE  LOOKUP_UNIQUE_ID = '14176'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14175')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Auto Comercial Sem Culpa (Proteção Danos Pessoais)' WHERE  LOOKUP_UNIQUE_ID = '14175'
END


IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14173')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'PPA Sem Culpa PIP' WHERE  LOOKUP_UNIQUE_ID = '14173'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14172')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'PPA Outras Responsabilidades' WHERE  LOOKUP_UNIQUE_ID = '14172'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14171')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Outras Responsabilidades' WHERE  LOOKUP_UNIQUE_ID = '14171'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14170')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Interior Marinho' WHERE  LOOKUP_UNIQUE_ID = '14170'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14169')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Proprietário de Múltiplos Perigos' WHERE  LOOKUP_UNIQUE_ID = '14169'
END

IF EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = '14167')
BEGIN
UPDATE MNT_LOOKUP_VALUES_MULTILINGUAL SET LOOKUP_VALUE_DESC = 'Linhas Alidadas' WHERE  LOOKUP_UNIQUE_ID = '14167'
END



--Menu Script

IF EXISTS(SELECT * FROM MNT_MENU_LIST_MULTILINGUAL where MENU_ID='493')
BEGIN
UPDATE MNT_MENU_LIST_MULTILINGUAL SET MENU_NAME = 'Cláusulas' WHERE  MENU_ID='493'
END

IF EXISTS(SELECT * FROM MNT_MENU_LIST_MULTILINGUAL where MENU_ID='492')
BEGIN
UPDATE MNT_MENU_LIST_MULTILINGUAL SET MENU_NAME = 'Coberturas' WHERE  MENU_ID='492'
END









