
-------Reinsurance contract
IF EXISTS(SELECT  COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
                  WHERE TABLE_NAME = 'MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL' 
                        AND COLUMN_NAME ='CONTRACT_TYPE_DESC') 
                  BEGIN
                        ALTER TABLE MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL
                        ALTER COLUMN CONTRACT_TYPE_DESC nvarchar(60) not null
                        
                   END
                 GO


if not exists(select * from  MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL where CONTRACTTYPEID=1)
Begin
insert into MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL(CONTRACTTYPEID,CONTRACT_TYPE_DESC,IS_ACTIVE,LANG_ID)Values(1,'Compartilhar(Co-Participação)','Y',2)
End
if not exists(select * from  MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL where CONTRACTTYPEID=2)
Begin
insert into MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL(CONTRACTTYPEID,CONTRACT_TYPE_DESC,IS_ACTIVE,LANG_ID)Values(2,'Excedente','Y',2)
End
if not exists(select * from  MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL where CONTRACTTYPEID=3)
Begin
insert into MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL(CONTRACTTYPEID,CONTRACT_TYPE_DESC,IS_ACTIVE,LANG_ID)Values(3,'XOL por Acidente','Y',2)
End
if not exists(select * from  MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL where CONTRACTTYPEID=4)
Begin
insert into MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL(CONTRACTTYPEID,CONTRACT_TYPE_DESC,IS_ACTIVE,LANG_ID)Values(4,'XOL por Risco','Y',2)
End
if not exists(select * from  MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL where CONTRACTTYPEID=45)
Begin
insert into MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL(CONTRACTTYPEID,CONTRACT_TYPE_DESC,IS_ACTIVE,LANG_ID)Values(45,'XOL','Y',2)
End
if not exists(select * from  MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL where CONTRACTTYPEID=47)
Begin
insert into MNT_REINSURANCE_CONTRACT_TYPE_MULTILINGUAL(CONTRACTTYPEID,CONTRACT_TYPE_DESC,IS_ACTIVE,LANG_ID)Values(47,'Facultative','Y',2)
End



 IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=11563)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Ganhos de Prêmio' where LOOKUP_UNIQUE_ID=11563
 END   
 
  IF EXISTS(Select * from MNT_LOOKUP_VALUES_MULTILINGUAL where LOOKUP_UNIQUE_ID=11562)
 BEGIN
 Update MNT_LOOKUP_VALUES_MULTILINGUAL
 set LOOKUP_VALUE_DESC='Ganhos de Contrato' where LOOKUP_UNIQUE_ID=11562
 END    