BEGIN TRAN 
IF NOT  EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'MNT_SUSEP_REPORTS_LIST' AND COLUMN_NAME = 'FILE_NAME')
 BEGIN
     ALTER TABLE MNT_SUSEP_REPORTS_LIST  
     add    FILE_NAME NVARCHAR(20)
     
  
 END
 
 
 
 IF NOT  EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'MNT_SUSEP_REPORTS_LIST' AND COLUMN_NAME = 'ITRACK_NO')
 BEGIN
     ALTER TABLE MNT_SUSEP_REPORTS_LIST  
     add    ITRACK_NO NVARCHAR(20)
     
  
 END
 
 ROLLBACK TRAN