
begin tran

IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_SINPAG_PAID_CLAIMS_DIRECT_POLICIES')
 begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SINPAG',  'PROC_SUSEP_SINPAG_PAID_CLAIMS_DIRECT_POLICIES','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_SINPAGAC_PAID_CLAIMS_INWARDS_COINSURANCE_POLICIES')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SINPAGAC',  'PROC_SUSEP_SINPAGAC_PAID_CLAIMS_INWARDS_COINSURANCE_POLICIES','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_PREMAC_ISSUED_CANCELLED_INWARD_COINSURANCE_PREMIUMS')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('PREMAC',  'PROC_SUSEP_PREMAC_ISSUED_CANCELLED_INWARD_COINSURANCE_PREMIUMS','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_PREMRECEC_PREMIUM_RECEIVED_CHECKOUT_INSURER')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('PREMRECEC',  'PROC_SUSEP_PREMRECEC_PREMIUM_RECEIVED_CHECKOUT_INSURER','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_SINPEND_PENDING_CLAIMS_DIRECT_POLICIES')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SINPEND',  'PROC_SUSEP_SINPEND_PENDING_CLAIMS_DIRECT_POLICIES','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_SINAV_CLAIM_MOVEMENT_OF_DIRECT_POLICIES')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SINAV',  'PROC_SUSEP_SINAV_CLAIM_MOVEMENT_OF_DIRECT_POLICIES','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_STATISTICS_RISK_INSURANCE')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('STATISTICS',  'PROC_SUSEP_STATISTICS_RISK_INSURANCE','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_RURAL_ANIMALS_INSURENCE')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SUSEP_RURAL',  'PROC_SUSEP_RURAL_ANIMALS_INSURENCE','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_DIRECT_PREMIUM')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SUSEP_DIRECT',  'PROC_SUSEP_DIRECT_PREMIUM','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_S_DPVAT_Table_II')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SUSEP_S_DPVAT',  'PROC_SUSEP_S_DPVAT_Table_II','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_R_RURAL')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SUSEP_R_RURAL',  'PROC_SUSEP_R_RURAL','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_ISSUED_CANCELLED_OUTWARDS_COINSURANCE_PREMIUMS')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('ISSUED_CANCELLED',  'PROC_SUSEP_ISSUED_CANCELLED_OUTWARDS_COINSURANCE_PREMIUMS','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_PREMRECAC_INWARD_COINSURANCE_PREMIUMS_RECEIVED')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('PREMRECAC',  'PROC_SUSEP_PREMRECAC_INWARD_COINSURANCE_PREMIUMS_RECEIVED','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_AT_MOR_INSURED_PARTY_ACTIVE_DEATH_COVER')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SUSEP_AT_MOR_INSURED',  'PROC_SUSEP_AT_MOR_INSURED_PARTY_ACTIVE_DEATH_COVER','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_PREMRECEB_PREMIUM_RECEIVED_BY_BANK')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('PREMRECEB',  'PROC_SUSEP_PREMRECEB_PREMIUM_RECEIVED_BY_BANK','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_COINSURENCE_PREMIUM')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SUSEP_COINSURENCE',  'PROC_SUSEP_COINSURENCE_PREMIUM','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_PREMREC_DIRECT_PREMIUMS_RECEIVED')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('PREMREC',  'PROC_SUSEP_PREMREC_DIRECT_PREMIUMS_RECEIVED','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_SINPENDAC_PENDING_CLAIMS_INWARDS_COINSURANCE_POLICIES')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SINPENDAC',  'PROC_SUSEP_SINPENDAC_PENDING_CLAIMS_INWARDS_COINSURANCE_POLICIES','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_TRACSACTIONS_LEGAL_CLAIM')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SINJUDAV',  'PROC_SUSEP_TRACSACTIONS_LEGAL_CLAIM','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_CORRETAGEN_COMMISSION_PAID')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('CORRETAGEN',  'PROC_SUSEP_CORRETAGEN_COMMISSION_PAID','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_R_COMP')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('72A R_COMP',  'PROC_SUSEP_R_COMP','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_SINAVAC_CLAIM_RESERVE_MOVEMENT_OF_INWARD_COI_POLICY')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SINAVAC',  'PROC_SUSEP_SINAVAC_CLAIM_RESERVE_MOVEMENT_OF_INWARD_COI_POLICY','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_ISSUED_AND_CANCELLED_DIRECT_PREMIUMS')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('PREMIT',  'PROC_SUSEP_ISSUED_AND_CANCELLED_DIRECT_PREMIUMS','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='Proc_SUSEP_Report')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('APURACAO DE RESULTADO OPERACIONAL',  'Proc_SUSEP_Report','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_STATISTICS_OF_CLAIMS')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('Quadro270',  'PROC_SUSEP_STATISTICS_OF_CLAIMS','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_R_DPVAT')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('R_DPVAT',  'PROC_SUSEP_R_DPVAT','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_S_COMP_CLAIM_DATA_COMPREENSIVE_INSURANCE')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SUSEP_S_COMP_CLAIM',  'PROC_SUSEP_S_COMP_CLAIM_DATA_COMPREENSIVE_INSURANCE','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_RESPREMC_INWARD_COINSURANCE_PREMIUM_RESERVE')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('RESPREMC',  'PROC_SUSEP_RESPREMC_INWARD_COINSURANCE_PREMIUM_RESERVE','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_AT_INV_INSURER_PARTICIPANT_INVALIDITY')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('AT_INV_Insured',  'PROC_SUSEP_AT_INV_INSURER_PARTICIPANT_INVALIDITY','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_SA_INV_OUTPUT_INSURED_PARTY_WITH_COVER_INVALIDITY')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('SA_INV_Output',  'PROC_SUSEP_SA_INV_OUTPUT_INSURED_PARTY_WITH_COVER_INVALIDITY','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_STATISTICS_GROUPLIFE_OUTSTANDING_CLAIM_TEMP')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('STATISTICS_GROUPLIFE',  'PROC_SUSEP_STATISTICS_GROUPLIFE_OUTSTANDING_CLAIM_TEMP','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_STATISTICS_OUTSTANDING_CLAIM_TEAMP')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('STATISTICS_OUTSTANDING',  'PROC_SUSEP_STATISTICS_OUTSTANDING_CLAIM_TEAMP','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_PREMCED_ISSUED_CANCELLED_OUTWARDS_COINSURANCE_PREMIUMS')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('PREMCED',  'PROC_SUSEP_PREMCED_ISSUED_CANCELLED_OUTWARDS_COINSURANCE_PREMIUMS','Excel', 'Y',14954)
end
IF  NOT EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST where PROC_NAME='PROC_SUSEP_PREMIUM_RELATED_POLICY_TRAN')
begin
INSERT  INTO MNT_SUSEP_REPORTS_LIST  VALUES ('PREMIUM_RELATED',  'PROC_SUSEP_PREMIUM_RELATED_POLICY_TRAN','Excel', 'Y',14954)
end
rollback tran

