
IF EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'MNT_SUSEP_REPORTS_LIST' AND COLUMN_NAME = 'REPORT_TYPE')
 BEGIN
     ALTER TABLE MNT_SUSEP_REPORTS_LIST  
     Add    REPORT_TYPE int
     
   
 END
 go
 --SP_HELP 'CLT_CUSTOMER_LIST'
 --rollback tran
 
 --begin tran 
IF  EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'MNT_SUSEP_REPORTS_LIST' AND COLUMN_NAME = 'REPORT_TYPE')
 BEGIN
     update  MNT_SUSEP_REPORTS_LIST  
     set     REPORT_TYPE =14954 where REPORT_ID<23     
   
 END
 
 IF  EXISTS (SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
 WHERE TABLE_NAME = 'MNT_SUSEP_REPORTS_LIST' AND COLUMN_NAME = 'REPORT_TYPE')
 BEGIN
     update  MNT_SUSEP_REPORTS_LIST  
     set     REPORT_TYPE =14955 where REPORT_ID>13     
   
 END
 go
  --select * from MNT_SUSEP_REPORTS_LIST WITH(NOLOCK)
  -- rollback tran
  
