IF NOT EXISTS(SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME='MNT_INTEREST_RATES')
BEGIN 
CREATE TABLE [dbo].MNT_INTEREST_RATES(
	[INTEREST_RATE_ID] [int] NOT NULL,
	[RATE_EFFECTIVE_DATE] [datetime] NOT NULL,
	[NO_OF_INSTALLMENTS] [int] NOT NULL,
	[INTEREST_TYPE] NVARCHAR(200) NOT NULL,	
	[INTEREST_RATE] DECIMAL(12,4) NOT NULL,
	[SUSEP_LOB_CODE] NVARCHAR(10) NULL,
	[IS_ACTIVE] [char](1) NOT NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
    [LAST_UPDATED_DATETIME] [datetime] NULL,
 CONSTRAINT [PK_MNT_INTEREST_RATES_INTEREST_RATE_ID] PRIMARY KEY NONCLUSTERED 
(
	INTEREST_RATE_ID ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

END



