--menu ID


IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST WHERE MENU_ID = 558)

BEGIN

INSERT INTO MNT_MENU_LIST Values(558,261,'Retention Limit','/cms/cmsweb/maintenance/RetentionLimitListIndex.aspx',null,3,4,0,null,null,null,null,null,null,null,null,null,'Y')


END


IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST_MULTILINGUAL WHERE MENU_ID = 558)

BEGIN


INSERT INTO MNT_MENU_LIST_MULTILINGUAL Values(558,'limite de retenção',2)

END

--screen id
IF NOT EXISTS (SELECT * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='558')
BEGIN 
  INSERT INTO MNT_SCREEN_LIST (SCREEN_ID,SCREEN_DESC,SCREEN_PATH,SCREEN_READ,SCREEN_WRITE,SCREEN_DELETE,SCREEN_EXECUTE,IS_ACTIVE) 
		VALUES('558','Retention Limit','/cms/cmsweb/maintenance/RetentionLimitListIndex.aspx','1','1','1','1','Y')
END
		
IF NOT EXISTS (SELECT * FROM MNT_SCREEN_LIST_MULTILINGUAL  WHERE SCREEN_ID='558')
BEGIN 
  INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL (SCREEN_ID,SCREEN_DESC,LANG_ID) 
		VALUES('558','Limite de Retenção',2)
END		

