IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'MNT_SYSTEM_PARAMS'
					AND COLUMN_NAME = 'SYS_NAVIGATION')
	ALTER TABLE  MNT_SYSTEM_PARAMS
	ADD  SYS_NAVIGATION NVARCHAR(50)

---for Insurar 
UPDATE MNT_SYSTEM_PARAMS SET SYS_NAVIGATION = 'TREENAVIGATION'