

  


-----------MNT_MENU_LIST------------------------
--select MAX(MENU_ID)+1 from MNT_MENU_LIST  where MENU_ID not in (5000,5001,5002)
--SELECT * FROM MNT_MENU_LIST WHERE PARENT_ID=123 and MENU_ID=566


IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST WHERE MENU_ID=566 and PARENT_ID=123)
	BEGIN
		INSERT INTO MNT_MENU_LIST
		(MENU_ID,PARENT_ID,MENU_NAME,MENU_LINK,MENU_TOOLTIP,NESTLEVEL,MENU_ORDER,HASCHILD,SHOWTYPE,HIDESTATUS
		 ,ISSECURITY,LANGID,MENU_IMAGE,DEFAULT_PAGE,MODULE_NAME,AGENCY_LEVEL,LOB_CODE,IS_ACTIVE)
		 VALUES
		 (566,123,'RI Interface','/cms/cmsweb/Accounting/RIInterface.aspx',NULL,3,8,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y')
	 END
 GO
 

 
 

 -----------For MNT_MENU_LIST_MULTILINGUAL Table---------------
 --select MAX(MENU_ID)+1 from MNT_MENU_LIST_MULTILINGUAL where MENU_ID not in (5000,5001,5002)
  --SELECT * FROM MNT_MENU_LIST_MULTILINGUAL WHERE  MENU_ID=566
 
 IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST_MULTILINGUAL WHERE MENU_ID=566 AND LANG_ID=2)
	BEGIN
		INSERT INTO MNT_MENU_LIST_MULTILINGUAL
		(MENU_ID,MENU_NAME,LANG_ID)
		 VALUES
		 (566,'Interface de RI',2)
	 END
 GO


----------------------------------------------------------------------------------------------------------------

-- SCRIPT TO ADD NEW SCREEN ID IN DATABASE
--delete FROM MNT_SCREEN_LIST WHERE SCREEN_ID='566'
--update MNT_SCREEN_LIST set MENU_ID='566' where SCREEN_ID='566'
--SELECT * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='566'
IF(NOT EXISTS (SELECT  * FROM MNT_SCREEN_LIST WHERE SCREEN_ID='566'))
BEGIN
			INSERT INTO MNT_SCREEN_LIST
			(
			 SCREEN_ID, SCREEN_DESC,SCREEN_PATH, SCREEN_READ, SCREEN_WRITE, SCREEN_DELETE, SCREEN_EXECUTE, IS_ACTIVE,MENU_ID
			 )
			 VALUES
			 (
			 '566', 'RI Interface', '/cms/cmsweb/Accounting/RIInterface.aspx', 1, 1, 1, 1, 'Y'	,'566'		 
			)
END	
go
----------------------------------------------------------------------------------------------------------------------

--- MNT_SCREEN_LIST_MULTILINGUAL--------------

--  select * from MNT_SCREEN_LIST_MULTILINGUAL	WHERE SCREEN_ID='552'

IF NOT EXISTS( SELECT * FROM MNT_SCREEN_LIST_MULTILINGUAL WHERE SCREEN_ID='566')
BEGIN 
INSERT INTO MNT_SCREEN_LIST_MULTILINGUAL 
(SCREEN_ID,SCREEN_DESC,LANG_ID) VALUES ('566','Interface de RI','2')
END




