--select MAX(LOOKUP_ID) from MNT_LOOKUP_TABLES

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID=1450 AND LOOKUP_NAME='FLNME')
BEGIN
INSERT INTO MNT_LOOKUP_TABLES
(LOOKUP_ID,LOOKUP_NAME,LOOKUP_DESC,LOOKUP_TYPE,LOOKUP_TBL_EDIT,LOOKUP_CODE_WIDTH,LOOKUP_DISPLAY_FORMAT,LOOKUP_DESC_WIDTH,LOOKUP_LEVEL)
VALUES
(1450,'FLNME','File Name','H','Y',null,null,null,null)
END
GO

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_TABLES_MULTILINGUAL WHERE LOOKUP_ID=1450 AND LANG_ID=2)
BEGIN
INSERT INTO MNT_LOOKUP_TABLES_MULTILINGUAL
(LOOKUP_ID,LOOKUP_DESC,LANG_ID)
VALUES
(1450,'Nome do arquivo',2)
END
GO

-----------MNT_LOOKUP_VALUES------------------------
--select * FROM MNT_LOOKUP_VALUES order by LOOKUP_UNIQUE_ID asc

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15016 and LOOKUP_ID=1450)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type
		 ,NSS_VALUE_CODE)
		 VALUES
		 (15016,1450,1,'SIN','SIN',null,'Y',null,null,null,null)
	 END
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15017 and LOOKUP_ID=1450)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type
		 ,NSS_VALUE_CODE)
		 VALUES
		 (15017,1450,2,'MRSS','MRSS',null,'Y',null,null,null,null)
	 END
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15018 and LOOKUP_ID=1450)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type
		 ,NSS_VALUE_CODE)
		 VALUES
		 (15018,1450,3,'MO-I','MO-I',null,'Y',null,null,null,null)
	 END
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15019 and LOOKUP_ID=1450)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type
		 ,NSS_VALUE_CODE)
		 VALUES
		 (15019,1450,4,'MO-II','MO-II',null,'Y',null,null,null,null)
	 END
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=15020 and LOOKUP_ID=1450)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES
		(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type
		 ,NSS_VALUE_CODE)
		 VALUES
		 (15020,1450,5,'MO-III','MO-III',null,'Y',null,null,null,null)
	 END
	 
 

-----------For MNT_LOOKUP_VALUES_MULTILINGUAL Table---------------
  
 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15016 and LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (15016,'SIN',2)
	 END
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15017 and LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (15017,'MRSS',2)
	 END
	 
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15018 and LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (15018,'MO-I',2)
	 END
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15019 and LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (15019,'MO-II',2)
	 END
	 IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID=15020 and LANG_ID=2)
	BEGIN
		INSERT INTO MNT_LOOKUP_VALUES_MULTILINGUAL
		(LOOKUP_UNIQUE_ID,LOOKUP_VALUE_DESC,LANG_ID)
		 VALUES
		 (15020,'MO-III',2)
	 END
	 
 