IF exists(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=1)
BEGIN
Update CLM_TYPE_DETAIL_MULTILINGUAL
set TYPE_DESC='Tempestade de Granizo' where DETAIL_TYPE_ID=1
End


IF exists(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=3)
BEGIN
Update CLM_TYPE_DETAIL_MULTILINGUAL
set TYPE_DESC='Inundação' where DETAIL_TYPE_ID=3
End

IF exists(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=2)
BEGIN
Update CLM_TYPE_DETAIL_MULTILINGUAL
set TYPE_DESC='Tumulto e Distúrbios' where DETAIL_TYPE_ID=2
End

IF exists(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=5)
BEGIN
Update CLM_TYPE_DETAIL_MULTILINGUAL
set TYPE_DESC='Tempestade de Gelo' where DETAIL_TYPE_ID=5
End

IF exists(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=6)
BEGIN
Update CLM_TYPE_DETAIL_MULTILINGUAL
set TYPE_DESC='Tempestade de Neve' where DETAIL_TYPE_ID=6
End

IF exists(Select * from CLM_TYPE_DETAIL_MULTILINGUAL where DETAIL_TYPE_ID=7)
BEGIN
Update CLM_TYPE_DETAIL_MULTILINGUAL
set TYPE_DESC='Tornado' where DETAIL_TYPE_ID=7
End