
IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=10)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(10,'Gestão Serviços',null,2)
END
IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=11)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(11,'Spool Thread','10',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=12)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(12,'Acompanhamento de Atividades','10',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=100)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(100,'Gestão Interfaces',null,2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=101)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(101,'EFT','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=102)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(102,'Recurring Journal Entries','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=103)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(103,'Pre Bill to Normal','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=104)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(104,'Premium Notice Generation','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=105)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(105,'Credit Card','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=106)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(106,'Agency Statement Regular','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=107)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(107,'Agency Statement Additional','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=108)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(108,'Small Balance Write Off','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=109)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(109,'Processamento de Prêmio Ganho','100',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=200)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(200,'Processo de Apólice',null,2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=201)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(201,'Iniciar Cancelamento','200',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=202)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(202,'Reversão de Cancelamento','200',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=203)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(203,'Emissão de Cancelamento','200',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=204)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(204,'Criação de Follow-up','200',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=205)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(205,'Iniciar Renovação','200',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=206)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(206,'Emissão de Renovação','200',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=207)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(207,'Follow-up de Renovação','200',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=300)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(300,'Spooling',null,2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=301)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(301,'EFT Spooling','300',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=302)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(302,'Credit Card Spooling','300',2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=500)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(500,'Processamento de Sinistro',null,2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=501)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(501,'Encerramento de Sinistro',null,2)
END

IF not exists (select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=502)
BEGIN
Insert into EOD_ACTIVITY_MASTER_MULTILINGUAL(ACTIVITY_ID,ACTIVITY_DESCRIPTION,PARENT_ACTIVITY_ID,LANG_ID)values(502,'Atualização de Reserva por Correção Monetária',null,2)
END