

If exists(Select * from MNT_SUSEP_LOB_MASTER_MULTILINGUAL where SUSEP_LOB_ID=7 and LANG_ID=2)
Begin
Update MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0117-TUMULTOS' where 
SUSEP_LOB_ID=7 and LANG_ID=2
End

If exists(Select * from MNT_SUSEP_LOB_MASTER_MULTILINGUAL where SUSEP_LOB_ID=100)
Begin
Update MNT_SUSEP_LOB_MASTER
set SUSEP_LOB_DESC='' where SUSEP_LOB_ID=100
END

If exists(Select * from MNT_SUSEP_LOB_MASTER_MULTILINGUAL where SUSEP_LOB_ID=100)
Begin
Update MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='' where SUSEP_LOB_ID=100
END


If exists(Select * from MNT_SUSEP_LOB_MASTER_MULTILINGUAL where SUSEP_LOB_ID=54 and LANG_ID=2)
Begin
Update MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0747 - GARANTIA DE CONCESSÕES PÚBLICAS' where 
SUSEP_LOB_ID=54 and LANG_ID=2
End

If exists(Select * from MNT_SUSEP_LOB_MASTER_MULTILINGUAL where SUSEP_LOB_ID=16 and LANG_ID=2)
Begin
Update MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0195 - EXTENSÃO DE GARANTIA - PATRIMONIAL' where 
SUSEP_LOB_ID=16 and LANG_ID=2
End


If exists(Select * from MNT_SUSEP_LOB_MASTER_MULTILINGUAL where SUSEP_LOB_ID=17 and LANG_ID=2)
Begin
Update MNT_SUSEP_LOB_MASTER_MULTILINGUAL
set SUSEP_LOB_DESC='0196 - RISCOS NOMEADOS E OPERACIONAIS' where 
SUSEP_LOB_ID=17 and LANG_ID=2
End
