
IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST WHERE MENU_ID=557 and PARENT_ID=123)
BEGIN
INSERT INTO MNT_MENU_LIST
(MENU_ID,PARENT_ID,MENU_NAME,MENU_LINK,MENU_TOOLTIP,NESTLEVEL,MENU_ORDER,HASCHILD,SHOWTYPE,HIDESTATUS,ISSECURITY,LANGID,MENU_IMAGE,DEFAULT_PAGE,MODULE_NAME,AGENCY_LEVEL,LOB_CODE,IS_ACTIVE)
VALUES
(557,123,'Fund Types','/Cms/CmsWeb/Aspx/FundTypes.aspx',NULL,2,7,0,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'Y')
END

IF NOT EXISTS(SELECT * FROM MNT_MENU_LIST_MULTILINGUAL WHERE MENU_ID=557 AND LANG_ID=3)
BEGIN
INSERT INTO MNT_MENU_LIST_MULTILINGUAL(MENU_ID,MENU_NAME,LANG_ID)
VALUES
(557,'Fund Types',3)
END

delete from MNT_MENU_LIST_MULTILINGUAL where MENU_ID=557