---THE SCRIPT FOR TRANLATION UPDATION OF EOD ACTIVITY MASTER MULTILINGUAL

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=11 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Tópico spool' where ACTIVITY_ID=11 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=102 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Recorrente Lançamentos' where ACTIVITY_ID=102 and LANG_ID=2 
END


If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=103 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='De Bill pré para Normal' where ACTIVITY_ID=103 and LANG_ID=2 
END



If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=104 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Aviso prêmio Geração de' where ACTIVITY_ID=104 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=105 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Cartão de Crédito' where ACTIVITY_ID=105 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=106 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Declaração de agência regulares' where ACTIVITY_ID=106 and LANG_ID=2 
END


If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=107 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Declaração de agência adicionais' where ACTIVITY_ID=107 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=108 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Balanço pequena Escreva Off' where ACTIVITY_ID=108 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=300 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='spooling' where ACTIVITY_ID=300 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=301 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Spooling EFT' where ACTIVITY_ID=301 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=301 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='EFT Spooling' where ACTIVITY_ID=301 and LANG_ID=2 
END

If Exists(Select * from EOD_ACTIVITY_MASTER_MULTILINGUAL where ACTIVITY_ID=302 and LANG_ID=2)
BEGIN
Update EOD_ACTIVITY_MASTER_MULTILINGUAL
set ACTIVITY_DESCRIPTION='Cartão de crédito Spooling' where ACTIVITY_ID=302 and LANG_ID=2 
END