
IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 1)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ CORRESPONDENTE AS DESPESAS COM #### DO SINISTROEM REFERENCIA. COM O RECEBIMENTO DA IMPORTANCIA SUPRA,OUTORGO(AMOS) PELO PRESENTE PLENA, GERAL E IRREVOGAVEL QUITACAO, NADA MAIS PODENDO RECLAMAR A ESSA SEGURADORA, EM JUIZO OU FORA DELE, EM RELACAO AS DESPESAS ACIMA CITADAS.' 
	WHERE TEXT_ID = 1 
END	

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 2)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE  PAGAMENTO DA  INDENIZACAO A  QUE  FACO(FAZEMOS)  JUS, AO AMPARO DAS GARANTIAS  DA  APOLICE/BILHETE  SUPRA,  EM  DECORRENCIA DO SINISTRO OCORRIDO EM ####. COM O RECEBIMENTO  DA IMPORTANCIA SUPRA, OUTORGO(AMOS) PELO PRESENTE, PLENA,GERAL E IRREVOGAVEL QUITACAO, NADA MAIS PODENDO RECLAMAR A ESSA SEGURADORA, RELATIVAMENTE AO  REFERIDO  SINISTRO,  EM  JUIZO  OU FORA DELE, SUBROGANDO-LHE  TODOS OS  DIREITOS  E ACOES,  DE  ACORDO  COM A LEGISLACAO EM VIGOR.' 
	WHERE TEXT_ID = 2 
END	

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 3)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE ADIANTAMENTO DA  INDENIZACAO A QUE FACO(FAZEMOS)  JUS, AO AMPARO DAS GARANTIAS  DA  APOLICE/BILHETE  SUPRA,  EM  DECORRENCIA DO SINISTRO OCORRIDO EM ####. COM O RECEBIMENTO DA IMPORTANCIA SUPRA,  OUTORGO(AMOS) PELO PRESENTE, PLENA, GERAL E IRREVOGAVEL QUITACAO, NADA MAIS PODENDO RECLAMAR A ESSA SEGURADORA,RELATIVAMENTE A IMPORTANCIA SUPRA, EM JUIZO OU FORA  DELE, SUBROGANDO-LHE TODOS OS DIREITOS E  ACOES, DE ACORDO COM A LEGISLACAO EM VIGOR.' 
	WHERE TEXT_ID = 3 
END	

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 4)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE PAGAMENTO DA INDENIZACAO A QUE FACO  JUS, NA QUALIDADE DE BENEFICIARIO DA APOLICE/BILHETE, PELA MORTE DE #### OCORRIDO EM ####. COM O RECEBIMENTO DA IMPORTANCIA SUPRA, OUTORGO PELO PRESENTE, PLENA, GERAL E IRREVOGAVEL  QUITACAO,  NADA  MAIS  PODENDO  RECLAMAR  A ESSA SEGURADORA,RELATIVAMENTE A IMPORTANCIA SUPRA, EM JUIZO OU FORA  DELE.' 
	WHERE TEXT_ID = 4 
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 6)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE  PAGAMENTO DA  INDENIZACAO A  QUE  FACO(FAZEMOS)  JUS, EM DECORRENCIA DA RECLAMACAO QUE LHE FORMALIZEI(AMOS) POR PREJUIZOS  RE-SULTANTE DE ####, QUE NOS FORAM CAUSADOS POR####, NO ACIDENTE OCOR-RIDO EM ####. COM O RECEBIMENTO DA IMPORTANCIA SUPRA,  OUTORGO(AMOS) PELO PRESENTE, PLENA,GERAL E IRREVOGAVEL QUITACAO, NADA MAIS PODENDO RECLAMAR A ESSA SEGURADORA  E A  ####,RELATIVAMENTE AO REFERIDO ACIDENTE, EM JUIZO OU FORA DELE, SUBROGANDO-LHE TODOS OS DIREITOS E ACOES, DE  ACORDO COM A LEGISLACAO EM VIGOR.' 
	WHERE TEXT_ID = 6 
END


IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 7)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE PAGAMENTO DA INDENIZACAO A QUE FACO(FAZEMOS) JUS,AO AMPARO DAS GARANTIAS DA APOLICE SUPRA  EM  DECORRENCIA DO SINISTRO OCORRIDO EM ####, E  QUE  RESULTOU  EM  PERDA   TOTAL   DO   VEICULO  MARCA####, PLACA ####, CHASSI #### DE NOSSA PROPRIEDADE. COM O RECEBIMENTO DA IMPORTANCIA SUPRA,  OUTORGO(AMOS) PELO PRESENTE, PLENA,GERAL E IRREVOGAVEL QUITACAO, NADA MAIS PODENDO RECLAMAR A ESSA SEGURADORA,RELATIVAMENTE AO REFERIDO SINISTRO, EM JUIZO OU FORA DELE, SUBROGANDO-LHE TODOS OS DIREITOS E  ACOES, DE ACORDO COM A LEGISLACAO EM VIGOR.' 
	WHERE TEXT_ID = 7 
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 8)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE PAGAMENTO DA INDENIZACAO  A QUE FAZ(EM)  JUS O(S) BENEFI-CIARIO(S) DO ESPOLIO DE ####EM CURSO PERANTE A ####, EM DECORRENCIA DO SINISTRO OCORRIDO EM ####. ASSIM,TENDO RECEBIDO A IMPORTANCIA SUPRA, ATRAVES DA GUIA DE DEPOSITO JUDICIAL EM ANEXO, OUTORGO(AMOS) PLENA QUITACAO A SEGURADORA, RELATI-VAMENTE  A IMPORTANCIA DEPOSITADA,  SALIENTANDO  QUE A MESMA  FICARA A DISPOSICAO  DO  JUIZO  DE  DIREITO   SUPRA,  SEM   POSSIBILIDADE   DE RECUPERACAO.' 
	WHERE TEXT_ID = 8 
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 9)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ REFERENTE  A   PENHORA  DOS  AUTOS   DE  EXECUCAO  QUE   LHE  MOVE(M)####, REFERENTE AO SINISTRO OCORRIDO EM #### QUE RESULTOU EM #### DO SEGURADO. ASSIM,TENDO RECEBIDO A IMPORTANCIA SUPRA, ATRAVES DA GUIA DE DEPOSITO JUDICIAL EM ANEXO, OUTORGO(AMOS) PLENA QUITACAO A SEGURADORA, RELATI-VAMENTE A IMPORTANCIA DEPOSITADA, RESSALVANDO A POSSIBILIDADE DA MESMA VIR A RECUPERAR O VALOR  DADO  EM  PENHORA,  ATRAVES  DE LEVANTAMENTO JUDICIAL  NOS AUTOS EM  EPIGRAFE.' 
	WHERE TEXT_ID = 9 
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 10)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE PAGAMENTO DA INDENIZACAO A QUE FAZ(EM) JUS O(S) MENOR(ES)####, NA QUALIDADE DE BE-NEFICIARIO(S),  EM DECORRENCIA DO SINISTRO OCORRIDO EM  #### E QUE RESULTOU NO FALECIMENTO DE #### ASSIM,ESTANDO DEVIDAMENTE LEGITIMADO(A) A REPRESENTAR O(S) REFERIDO(S) BENEFICIARIO(S),DE ACORDO COM O DISPOSTO NO ART. 385 DO CODIGO CIVIL; E TENDO RECEBIDO A IMPORTANCIA SUPRA, OUTORGO, PELO PRESENTE, PLENA, GERAL E IRREVOGAVEL QUITACAO A SEGURADORA, PARA NADA MAIS RECLAMAR,EM JUIZO OU FORA DELE, RELATIVAMENTE A IMPORTANCIA ACIMA.' 
	WHERE TEXT_ID = 10 
END


IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 11)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A  TITULO    DE    REEMBOLSO   DA    INDENIZACAO   QUE    PAGAMOS   A####, EM DECORRENCIA DO  SINISTRO   OCORRIDO  EM  ####,  AO  AMPARO DAS GARANTIAS DA APOLICE SUPRA E QUE RESULTOU EM ####. ASSIM, TENDO RECEBIDO A IMPORTANCIA SUPRA,  OUTORGAMOS PELO PRESENTE, PLENA, GERAL E IRREVOGAVEL  QUITACAO A ESSA COSSEGURADORA,  PARA NADA MAIS RECLAMAR, EM JUIZO OU FORA DELE,RELATIVAMENTE AO REFERIDO VALOR, SUBROGANDO-LHE TODOS OS DIREITOS E ACOES, DE ACORDO COM  A LEGISLACAO EM VIGOR.' 
	WHERE TEXT_ID = 11 
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 12)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE REEMBOLSO DA INDENIZACAO QUE PAGAMOS AO(S) BENEFICIARIO(S) ####, EM DECORRENCIA DO SINISTRO OCORRIDO EM ####, COBERTO PELA APOLICE SUPRA E QUE RESULTOU EM ####, ANEXANDO AINDA,  COPIA DO RECIBO COLETIVO  ENVIADO PELO(S) BENEFICIA-RIO(S) ACIMA CITADO(S). ASSIM,TENDO RECEBIDO A IMPORTANCIA SUPRA,OUTORGO(AMOS) PELO PRESENTE, PLENA, GERAL  E IRREVOGAVEL QUITACAO.' 
	WHERE TEXT_ID = 12
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 13)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE PAGAMENTO DE INDENIZACAO A QUE FACO(FAZEMOS) JUS,AO AMPAR) DAS GARANTIAS DA APOLICE SUPRA, EM DECORRENCIA DO SINISTRO OCORRIDOEM ####, QUE ATINGIU BENS DO MUTUARIO,  VINCULADOS AO  CONTRATO DE EMPRESTIMO NUM.#### E SEGURADOS PELOS DOCUMENTOS SUPRA CITADOS. ASSIM,TENDO RECEBIDO A IMPORTANCIA SUPRA,E NADA MAIS PODENDO RECLAMAR A ESTA SEGURADORA,  EM JUIZO OU FORA DELE,  RELATIVAMENTE AO REFERIDO SINISTRO, OUTORGO(AMOS)  PELO PRESENTE,  PLENA,  GERAL  E IRREVOGAVEL QUITACAO.' 
	WHERE TEXT_ID = 13
END


IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 14)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE PAGAMENTO DE INDENIZACAO A QUE FAZ(EM) JUS O(S) MENOR(ES)#### NA QUALIDADE DE BENEFICIARIO(S), EM DECORRENCIA DO SINISTRO  OCORRIDO EM #### E QUE RESULTOU NO FALECIMENTO DE ####. OUTROSSIM, ESTAMOS CIENTES QUE A QUANTIA, SO PODERA SER SACADA, QUANDO DA MAIORIDADE DO(S) MENOR(ES)' 
	WHERE TEXT_ID = 14
END


IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 15)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE PAGAMENTO DE INDENIZACAO A QUE FACO JUZ, NA QUALIDADE DE BENEFICIARIO DA APOLICE/BILHETE SUPRA,PELA MORTE DE #### , OCORRIDA EM ####. COM O RECEBIMENTO DA IMPORTANCIA SUPRA, OUTORGO PELO PRESENTE, ASSISTIDO POR #### PLENA, GERAL E IRREVOGAVEL QUITACAO A SEGURADORA, PARA NADA MAIS  RE-CLAMAR EM JUIZO OU FORA DELE, RELATIVAMENTE A IMPORTANCIA ACIMA.' 
	WHERE TEXT_ID = 15
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 20)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A  TITULO   DE   NOSSA   PARTICIPACAO   NA(O)  #### REFERENTE AO  SINISTRO  SUPRA,  OCORRIDO  EM #### , INDENIZADO  A#### ASSIM, TENDO RECEBIDO A IMPORTANCIA SUPRA,  OUTORGAMOS PELO PRESENTE, PLENA, GERAL E IRREVOGAVEL  QUITACAO  A  ESSA  SEGURADORA,  PARA NADA MAIS RECLAMAR,EM JUIZO OU FORA DELE, RELATIVAMENTE AO REFERIDO VALOR.' 
	WHERE TEXT_ID = 20
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 21)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ A TITULO DE INDENIZACAO (DEVIDA PELO CONVENIO) EM DECORRENCIA DO SINISTRO OCORRIDO EM #### DE ####  DE ####  CAUSADO POR #### COBERTO PELA APOLICE E/OU BILHETE SUPRA  CITADO  E  QUE  RESULTOU  EM#### ASSIM,TENDO RECEBIDO A IMPORTANCIA,ACIMA INDICADA,E NADA MAIS PODENDO RECLAMAR, EM JUIZO, OU FORA DELE, CONTRA ESSA COMPANHIA E/OU QUALQUER OUTRA SEGURADORA PARTICIPANTE DO CONVENIO-DPVAT, RELATIVAMENTE     AO SINISTRO EM APRECO, DOU-LHES, PELO PRESENTE INSTRUMENTO,  FIRMADO  EM 4 VIAS, PARA UM SO EFEITO, PLENA, GERAL E IRREVOGAVEL QUITACAO.' 
	WHERE TEXT_ID = 21
END

IF EXISTS(SELECT TEXT_ID FROM CLM_PAYMENT_TEXT WHERE TEXT_ID = 22)
BEGIN
	UPDATE CLM_PAYMENT_TEXT SET [DESCRIPTION] = 'RECEBI(EMOS) DA(E) COMPANHIA DE SEGUROS ALIANÇA DA BAHIIA A IMPORTANCIA DE $$$$ CORRESPONDENTE AS DESPESAS COM #### DO SINISTRO EM REFERENCIA,COM O RECEBIMENTO DA IMPORTANCIA SUPRA,OUTORGO(AMOS) PELO PRESENTE,PLENA, GERAL E IRREVOGAVEL QUITACAO, NADA MAIS PODENDO RECLAMAR A ESSA SEGURADORA,EM JUIZO OU FORA DELE,(INCLUIR) SOB QUAISQUER TITULOS,TAIS COMO:LUCROS CESSANTES E/OU EMERGENTES,DESPESAS MEDICAS,DANOS PESSOAIS E/OU MORAIS, INCAPACIDADE PERMANENTE,TOTAL OU PARCIAL,PRESENTES E/OU FUTURAS,QUALQUER OUTRO PAGAMENTO,REEMBOLSO E/OU INDENIZACAO COM BASE NA SUPRA  CITADA  OCORRENCIA.' 
	WHERE TEXT_ID = 22
END






















































































