IF EXISTS (SELECT * FROM MNT_MENU_LIST WHERE MENU_ID=560)
BEGIN
UPDATE MNT_MENU_LIST SET IS_ACTIVE = 'N' WHERE MENU_ID=560
END

IF EXISTS (SELECT * FROM MNT_MENU_LIST WHERE MENU_ID=561)
BEGIN
UPDATE MNT_MENU_LIST SET IS_ACTIVE = 'N' WHERE MENU_ID=561
END

IF EXISTS (SELECT * FROM MNT_MENU_LIST WHERE MENU_ID=562)
BEGIN
UPDATE MNT_MENU_LIST SET IS_ACTIVE = 'N' WHERE MENU_ID=562
END