UPDATE POL_REINSURANCE_INFO SET MAX_NO_INSTALLMENT = 5

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID = 15)
BEGIN
UPDATE POL_RISK_DETAIL SET RISK_ID = 'PERSONAL_INFO_ID' WHERE LOB_ID= 15
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID = 16)
BEGIN
UPDATE POL_RISK_DETAIL SET RISK_ID = 'PRODUCT_RISK_ID' WHERE LOB_ID= 16
END