
-- FOR ITRACK 1263  
      
IF EXISTS (SELECT CLAIM_ID FROM CLM_PARTIES WHERE [STATE]=0 AND PARTY_TYPE_ID=618 AND SOURCE_PARTY_ID=1)
BEGIN

UPDATE CLM_PARTIES SET  [STATE]=71 WHERE [STATE]=0 AND PARTY_TYPE_ID=618 AND SOURCE_PARTY_ID=1

END
