
--BEGIN TRAN 
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 5)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1053' WHERE REPORT_ID = 5
END
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 6)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1055' WHERE REPORT_ID = 6
END
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 7)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1056' WHERE REPORT_ID = 7
END
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 8)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1057' WHERE REPORT_ID = 8
END
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 9)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1058' WHERE REPORT_ID = 9
END
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 10)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1060' WHERE REPORT_ID = 10
END
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 11)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1061' WHERE REPORT_ID = 11
END
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 12)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1063' WHERE REPORT_ID = 12
END
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 13)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1064' WHERE REPORT_ID = 13
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 37)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1059' WHERE REPORT_ID = 37
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 32)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET  ITRACK_NO='1078' WHERE REPORT_ID = 32
END


-----------
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 14)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'CADASTRO.DBF', ITRACK_NO='1065' WHERE REPORT_ID = 14
END


IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 33)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'CORRETAGEN.DBF',ITRACK_NO='1066' WHERE REPORT_ID = 33
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 17)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'PREMAC.DBF',ITRACK_NO='1067' WHERE REPORT_ID = 17
END


IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 25)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'PREMCED.DBF',ITRACK_NO='1068' WHERE REPORT_ID = 25
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 36)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'PREMIT.DBF',ITRACK_NO='1069' WHERE REPORT_ID = 36
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 18)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'PREMRECEC.DBF',ITRACK_NO='1071' WHERE REPORT_ID = 18
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 22)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'RESPREM.DBF' ,ITRACK_NO='1072' WHERE REPORT_ID = 22
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 29)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'RESPREMC.DBF',ITRACK_NO='1073'  WHERE REPORT_ID = 29
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 20)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'SINAV.DBF' ,ITRACK_NO='1074'  WHERE REPORT_ID = 20
END

---
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 28)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'PREMRECEB.DBF'  ,ITRACK_NO='1075' WHERE REPORT_ID = 28
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 38)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'R_DPVAT.DBF'  ,ITRACK_NO='1076' WHERE REPORT_ID = 38
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 35)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'SINAVAC.DBF'  ,ITRACK_NO='1077' WHERE REPORT_ID = 35
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 15)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'SINPAG.DBF' ,ITRACK_NO='1079'  WHERE REPORT_ID = 15
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 16)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'SINPAGAC.DBF'  ,ITRACK_NO='1080' WHERE REPORT_ID = 16
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 19)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'SINPEND.DBF'  ,ITRACK_NO='1081' WHERE REPORT_ID = 19
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 31)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'SINPENDAC.DBF' ,ITRACK_NO='1082'  WHERE REPORT_ID = 31
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 23)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'S_DPVAT.DBF'  ,ITRACK_NO='1239' WHERE REPORT_ID = 23
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 40)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'AT_INV.DBF'  ,ITRACK_NO='1241' WHERE REPORT_ID = 40
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 41)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'SA_INV.DBF' ,ITRACK_NO='1242'  WHERE REPORT_ID = 41
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 34)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'R_COMP.DBF'  ,ITRACK_NO='1243' WHERE REPORT_ID = 34
END
----------

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 39)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'S_COMP.DBF'  ,ITRACK_NO='1244' WHERE REPORT_ID = 39
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 24)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'R_RURAL.DB' ,ITRACK_NO='1245'  WHERE REPORT_ID = 24
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 21)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'S_RURAL.DBF' ,ITRACK_NO='1246'  WHERE REPORT_ID = 21
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 30)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'PREMREC.DBF'  ,ITRACK_NO='1247' WHERE REPORT_ID = 30
END

IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 27)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'SALRESAC.DBF'  ,ITRACK_NO='1240' WHERE REPORT_ID = 27
END


IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 26)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET FILE_NAME = 'PREMRECAC.DBF'  ,ITRACK_NO='1070' WHERE REPORT_ID = 26
END
---WRONG EXTENSION MENTIONED
IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 37)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET OUTPUT_FORMAT = 'Txt'   WHERE REPORT_ID = 37
END


IF EXISTS (SELECT * FROM MNT_SUSEP_REPORTS_LIST WHERE REPORT_ID = 14)
BEGIN
UPDATE MNT_SUSEP_REPORTS_LIST SET OUTPUT_FORMAT = 'DBF' WHERE REPORT_ID = 14
END
--SELECT * FROM MNT_SUSEP_REPORTS_LIST
--ROLLBACK TRAN 