
--select * from ACT_GL_ACCOUNTS order by ACC_DISP_NUMBER
--Back of Table : ACT_GL_ACCOUNTS_BK


UPDATE ACT_GL_ACCOUNTS set CATEGORY_TYPE = 14455 where CATEGORY_TYPE = 1
UPDATE ACT_GL_ACCOUNTS set CATEGORY_TYPE = 14456 where CATEGORY_TYPE = 2