IF EXISTS(SELECT * FROM MNT_PRODUCT_SUSEP_PROCESS_NUMBER WHERE LOB_ID=22 AND  SUSEP_PROCESS_ID=195 )
BEGIN
	UPDATE MNT_PRODUCT_SUSEP_PROCESS_NUMBER SET SUBLOB_ID=3 WHERE LOB_ID=22 AND  SUSEP_PROCESS_ID=195 
END	

IF EXISTS(SELECT * FROM MNT_PRODUCT_SUSEP_PROCESS_NUMBER WHERE LOB_ID=31 AND  SUSEP_PROCESS_ID=188 )
BEGIN
	UPDATE MNT_PRODUCT_SUSEP_PROCESS_NUMBER SET SUBLOB_ID=1 WHERE LOB_ID=31 AND  SUSEP_PROCESS_ID=188 
END

IF EXISTS(SELECT * FROM MNT_PRODUCT_SUSEP_PROCESS_NUMBER WHERE LOB_ID=31 AND  SUSEP_PROCESS_ID=189 )
BEGIN
	UPDATE MNT_PRODUCT_SUSEP_PROCESS_NUMBER SET SUBLOB_ID=1 WHERE LOB_ID=31 AND  SUSEP_PROCESS_ID=189 
END	

IF EXISTS(SELECT * FROM MNT_PRODUCT_SUSEP_PROCESS_NUMBER WHERE LOB_ID=31 AND  SUSEP_PROCESS_ID=190)
BEGIN
	UPDATE MNT_PRODUCT_SUSEP_PROCESS_NUMBER SET SUBLOB_ID=1 WHERE LOB_ID=31 AND  SUSEP_PROCESS_ID=190
END


IF EXISTS(SELECT * FROM MNT_PRODUCT_SUSEP_PROCESS_NUMBER WHERE LOB_ID=31 AND  SUSEP_PROCESS_ID=191)
BEGIN
	UPDATE MNT_PRODUCT_SUSEP_PROCESS_NUMBER SET SUBLOB_ID=1 WHERE LOB_ID=31 AND  SUSEP_PROCESS_ID=191
END


IF EXISTS(SELECT * FROM MNT_PRODUCT_SUSEP_PROCESS_NUMBER WHERE LOB_ID=33 AND  SUSEP_PROCESS_ID=192)
BEGIN
	UPDATE MNT_PRODUCT_SUSEP_PROCESS_NUMBER SET SUBLOB_ID=1 WHERE LOB_ID=33 AND  SUSEP_PROCESS_ID=192
END


