
if exists ( SELECT TRANS_TYPE_ID FROM TRANSACTIONTYPELIST_MULTILINGUAL WHERE TRANS_TYPE_ID = 405)
begin
update TRANSACTIONTYPELIST_MULTILINGUAL set TRANS_TYPE_NAME = 'Recebimento de Cosseguro Adicionado com Sucesso' where TRANS_TYPE_ID = 405 
end


if exists ( SELECT TRANS_TYPE_ID FROM TRANSACTIONTYPELIST_MULTILINGUAL WHERE TRANS_TYPE_ID = 404)
begin
update TRANSACTIONTYPELIST_MULTILINGUAL set TRANS_TYPE_NAME = 'Número de Apólice Líder inválido.' where TRANS_TYPE_ID = 404 
end

if exists ( SELECT LOOKUP_UNIQUE_ID FROM MNT_LOOKUP_VALUES_MULTILINGUAL WHERE LOOKUP_UNIQUE_ID = 14902)
begin
update MNT_LOOKUP_VALUES_MULTILINGUAL set LOOKUP_VALUE_DESC = 'Cosseguro e Resseguro' where LOOKUP_UNIQUE_ID = 14902 
end
