 IF EXISTS (SELECT POLICY_STATUS_CODE FROM POL_POLICY_STATUS_MASTER_MULTILINGUAL WHERE POLICY_STATUS_CODE ='REFERRED')
 BEGIN
 UPDATE POL_POLICY_STATUS_MASTER_MULTILINGUAL SET POLICY_DESCRIPTION = 'Forçar Envio' WHERE POLICY_STATUS_CODE ='REFERRED'
 END