IF EXISTS(SELECT COLUMN_NAME FROM INFORMATION_SCHEMA.COLUMNS 
                  WHERE TABLE_NAME = 'POL_RISK_DETAIL' 
                        AND COLUMN_NAME ='TABLE_NAME') 
                  BEGIN
ALTER  TABLE POL_RISK_DETAIL ALTER COLUMN TABLE_NAME NVARCHAR(MAX)
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =10)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 10
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =10)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 10
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =11)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 11
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =11)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 11
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =12)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 12
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =12)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 12
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =14)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 14
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =14)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 14
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =16)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 16
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =16)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 16
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =19)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 19
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =19)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 19
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =25)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 25
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =25)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 25
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =27)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 27
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =27)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 27
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =32)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PRODUCT_LOCATION_INFO RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 32
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =32)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 32
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =15)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='INDIVIDUAL_NAME,CODE'
WHERE LOB_ID = 15
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =21)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='INDIVIDUAL_NAME,CODE'
WHERE LOB_ID = 21
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =33)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='INDIVIDUAL_NAME,CODE'
WHERE LOB_ID = 33
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =34)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='INDIVIDUAL_NAME,CODE'
WHERE LOB_ID = 34
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =22)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.NUMBER_OF_PASSENGERS,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 22
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =22)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PASSENGERS_PERSONAL_ACCIDENT_INFO RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 22
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =9)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PERILS RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND   PL.POLICY_ID = RISK.POLICY_ID AND   PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND   PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 9
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =9)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 9
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =26)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PERILS RISK JOIN POL_LOCATIONS PL WITH(NOLOCK)  ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND   PL.POLICY_ID = RISK.POLICY_ID AND   PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID AND   PL.LOCATION_ID = RISK.LOCATION'
WHERE LOB_ID = 26
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =26)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 26
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =37)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PENHOR_RURAL_INFO RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 37
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =37)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 37
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =35)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PENHOR_RURAL_INFO RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 35
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =35)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.ITEM_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 35
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =20)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_COMMODITY_INFO RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 20
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =20)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.COMMODITY_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 20
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =23)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_COMMODITY_INFO RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 23
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =23)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.COMMODITY_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 23
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =17)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_CIVIL_TRANSPORT_VEHICLES RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 17
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =17)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.VEHICLE_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 17
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =18)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_CIVIL_TRANSPORT_VEHICLES RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 18
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =18)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.VEHICLE_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 18
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =28)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_CIVIL_TRANSPORT_VEHICLES RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 28
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =28)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.VEHICLE_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 28
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =29)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_CIVIL_TRANSPORT_VEHICLES RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 29
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =29)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.VEHICLE_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 29
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =30)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_CIVIL_TRANSPORT_VEHICLES RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 30
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =30)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.VEHICLE_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 30
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =31)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_CIVIL_TRANSPORT_VEHICLES RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 31
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =31)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.VEHICLE_NUMBER,PL.LOC_NUM,PL.LOC_ADD1'
WHERE LOB_ID = 31
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =36)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_CIVIL_TRANSPORT_VEHICLES RISK WITH(NOLOCK) JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID'
WHERE LOB_ID = 36
END


IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =36)
BEGIN
UPDATE POL_RISK_DETAIL SET DISPLAY_COLUMN_NAME ='RISK.VEHICLE_NUMBER,PL.LOC_NUM,PL.LOC_ADD1' WHERE LOB_ID = 36
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =13)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_MARITIME RISK'
WHERE LOB_ID = 13
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =15)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PERSONAL_ACCIDENT_INFO RISK'
WHERE LOB_ID = 15
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =21)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PERSONAL_ACCIDENT_INFO RISK'
WHERE LOB_ID = 21
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =33)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PERSONAL_ACCIDENT_INFO RISK'
WHERE LOB_ID = 33
END

IF EXISTS (SELECT LOB_ID FROM POL_RISK_DETAIL WHERE LOB_ID =34)
BEGIN
UPDATE POL_RISK_DETAIL SET TABLE_NAME = 'POL_PERSONAL_ACCIDENT_INFO RISK'
WHERE LOB_ID = 34
END


