IF EXISTS (SELECT * FROM MNT_REINSURANCE_COVERAGE_CATEGORY WHERE COVERAGE_CATEGORY_ID=7 AND IS_ACTIVE='Y')
BEGIN
Update MNT_REINSURANCE_COVERAGE_CATEGORY SET IS_ACTIVE='N' WHERE COVERAGE_CATEGORY_ID=7 AND IS_ACTIVE='Y' 
END
