IF EXISTS ( SELECT * FROM MIG_ERROR_TYPE_DETAIL_MULTILINGUAL WHERE ERROR_TYPE_ID = 34)
BEGIN
UPDATE MIG_ERROR_TYPE_DETAIL_MULTILINGUAL SET TYPE_DESC = 'Arquivo não pôde ser processada porque tem arquivo enviado dados incorretos.' WHERE ERROR_TYPE_ID = 34 
END
