  
-- =============================================  
-- AUTHOR:  <SHUBHANSHU PANDEY>  
-- CREATE DATE: <2011-09-30>  
-- DESCRIPTION: <VALIDATE FILE DATA [FILE 'CLAIM NOTIFICATION']>  
-- =============================================  
  
CREATE PROCEDURE [dbo].[PROC_MIG_IL_CLAIM_NOTIFICATION_VALIDATE_DATA]   
  
--------------------------------- INPUT PARAMETER  
@IMPORT_REQUEST_ID  INT  
-------------------------------------------------  
    
AS  
BEGIN  

   
-------------------------------- DECLARATION PART  
----------------------------------------------------------------------------------------  
DECLARE @ERROR_NUMBER    INT    
DECLARE @ERROR_SEVERITY  INT    
DECLARE @ERROR_STATE     INT    
DECLARE @ERROR_PROCEDURE VARCHAR(512)    
DECLARE @ERROR_LINE    INT    
DECLARE @ERROR_MESSAGE   NVARCHAR(MAX)    
  
  
DECLARE @LOOP_POLICY_NUMBER NVARCHAR(50)       
DECLARE @LOOP_POLICY_SEQUANCE_NO INT      
DECLARE @LOOP_END_SEQUANCE_NO INT      
DECLARE @LOOP_IMPORT_SERIAL_NO INT      
DECLARE @COUNTER INT  =1    
DECLARE @MAX_RECORD_COUNT INT     
DECLARE @ERROR_NO INT=0    
DECLARE @IMPORT_SERIAL_NO INT   



DECLARE @AM_PM INT  
DECLARE @LITIGATION_FILE INT
DECLARE @ADJUSTER INT  
DECLARE @REPORTED_TO NVARCHAR(100)
DECLARE @CATASTROPHE_EVENT_CODE  INT  
DECLARE @CLAIMANT_PARTY INT
DECLARE @CLAIM_STATUS INT  
DECLARE @CLAIM_STATUS_UNDER INT
DECLARE @REINSURANCE_TYPE INT  
DECLARE @IS_VICTIM_CLAIM INT


 -- VALIDATION FOR AM/PM, FILE IN LITIGATION, ADJUSTER, REPORTED TO, CATASTROPHE EVENT CODE,CLAIMANT PARTY, 
 -- CLAIM STATUS, CLAIM STATUS UNDER, REINSURANCE TYPE, IS VICTIM CLAIM.

  BEGIN TRY  
-------------------------------- CREATE TEMP TABLE FOR THOSE RECORDS NEEDS TO BE PROCESSED  
-----------------------------------------------------------------------------------------  
    
     CREATE TABLE #TEMP_POLICY    
     (    
		ID INT IDENTITY(1,1),    
		IMPORT_SERIAL_NO BIGINT,    
      
     )    
  
  
  
  INSERT INTO #TEMP_POLICY    
     (    
		IMPORT_SERIAL_NO  
     )  
     ( 
     SELECT IMPORT_SERIAL_NO  
     FROM   MIG_IL_CLAIM_NOTIFICATION_DETAILS WITH(NOLOCK)    
     WHERE  IMPORT_REQUEST_ID = @IMPORT_REQUEST_ID AND HAS_ERRORS = 0   
     )
     
     
   ------------------------------------          
   -- GET MAX RECOUNT COUNT    
   ------------------------------------       
    SELECT @MAX_RECORD_COUNT = COUNT(ID)     
    FROM   #TEMP_POLICY    
    
     
    
  WHILE(@COUNTER<=@MAX_RECORD_COUNT)    
  BEGIN  
  
    SET @ERROR_NO=0    
  
      SELECT  @IMPORT_SERIAL_NO   = IMPORT_SERIAL_NO   
      FROM   #TEMP_POLICY (NOLOCK) WHERE ID   = @COUNTER   
      
   SELECT    
	 @AM_PM				     = AM_PM, --NOT
	 @LITIGATION_FILE        = LITIGATION_FILE,
	 @ADJUSTER			     = ADJUSTER,
	 @CATASTROPHE_EVENT_CODE = CATASTROPHE_EVENT_CODE,
	 @CLAIMANT_PARTY		 = CLAIMANT_PARTY,
	 @CLAIM_STATUS		     = CLAIM_STATUS,
	 @CLAIM_STATUS_UNDER	 = CLAIM_STATUS_UNDER,
	 @REINSURANCE_TYPE		 = REINSURANCE_TYPE,
	 @IS_VICTIM_CLAIM		 = IS_VICTIM_CLAIM  
   FROM  MIG_IL_CLAIM_NOTIFICATION_DETAILS WITH (NOLOCK)  
   WHERE  IMPORT_REQUEST_ID  = @IMPORT_REQUEST_ID   
   AND   IMPORT_SERIAL_NO    = @IMPORT_SERIAL_NO   

   
   
   ------------------------------------  VALIDATION OF COUNTRY  
  IF @LITIGATION_FILE NOT IN(10963,10940)    
      SET @ERROR_NO= --90      --WRONG COUNTRY ID  
  ELSE IF NOT EXISTS( SELECT * FROM CLM_ADJUSTER WHERE ADJUSTER_ID= @ADJUSTER AND ADJUSTER_TYPE=11736 AND DISPLAY_ON_CLAIM=10963 )
     SET @ERROR_NO= --90      --WRONG COUNTRY ID  
     ------------------------------------  VALIDATION OF STATE  
  IF NOT EXISTS (SELECT 1 FROM CLM_CLAIM_INFO (NOLOCK) WHERE @ADJUSTER = ADJUSTER_ID AND IS_ACTIVE='Y')  
     SET @ERROR_NO= --91      -- WRONG STATE ID  
    
  
 
END  
      
  
    SET @COUNTER+=1    
  END  
  
END TRY

END