
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MNT_ACCUMULATION_CRITERIA_MASTER]') AND type in (N'U'))
DROP TABLE [dbo].[MNT_ACCUMULATION_CRITERIA_MASTER]
CREATE TABLE [dbo].[MNT_ACCUMULATION_CRITERIA_MASTER](
      [CRITERIA_ID] INT NOT NULL,
      [CRITERIA_CODE] VARCHAR(25),
      [CRITERIA_DESC] VARCHAR(100),
      [LOB_ID] INT ,
      [IS_ACTIVE] CHAR(2) ,
      )
GO

ALTER TABLE [dbo].[MNT_ACCUMULATION_CRITERIA_MASTER] ADD CONSTRAINT [PK_MNT_ACCUMULATION_CRITERIA_MASTER_CRITERIA_ID] PRIMARY KEY
      CLUSTERED
      (
            CRITERIA_ID ASC
      )     WITH
      (
            PAD_INDEX = OFF
            ,STATISTICS_NORECOMPUTE = OFF
            ,IGNORE_DUP_KEY = OFF
            ,ALLOW_ROW_LOCKS = ON
            ,ALLOW_PAGE_LOCKS = ON
      ) 
GO


IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MNT_ACCUMULATION_REFERENCE]') AND type in (N'U'))
DROP TABLE [dbo].[MNT_ACCUMULATION_REFERENCE]
GO


CREATE TABLE [dbo].[MNT_ACCUMULATION_REFERENCE](
      [ACC_ID] INT NOT NULL,
      [ACC_REF_NO] NVARCHAR(10)  ,
      [LOB_ID] INT ,
      [CRITERIA_ID] INT , 
      [CRITERIA_VALUE] NVARCHAR(40) ,
      [TREATY_CAPACITY_LIMIT] DECIMAL(18, 2) , 
      [USED_LIMIT] DECIMAL(18,2) ,
      [EFFECTIVE_DATE] DATETIME ,
      [EXPIRATION_DATE] DATETIME ,
      [IS_ACTIVE] char(2) 
      )

GO
ALTER TABLE [dbo].[MNT_ACCUMULATION_REFERENCE] ADD CONSTRAINT [PK_MNT_ACCUMULATION_REFERENCE_ACC_ID] PRIMARY KEY
      CLUSTERED
      (
            ACC_ID ASC
      )     WITH
      (
            PAD_INDEX = OFF
            ,STATISTICS_NORECOMPUTE = OFF
            ,IGNORE_DUP_KEY = OFF
            ,ALLOW_ROW_LOCKS = ON
            ,ALLOW_PAGE_LOCKS = ON
      ) 
GO

ALTER TABLE [dbo].[MNT_ACCUMULATION_REFERENCE] ADD CONSTRAINT [FK_MNT_ACCUMULATION_REFERENCE_CRITERIA_ID] FOREIGN KEY
      (
         CRITERIA_ID
      )
      REFERENCES [dbo].[MNT_ACCUMULATION_CRITERIA_MASTER]
      (
		CRITERIA_ID
      )
      
GO

IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MNT_ACCUMULATION_REGISTER]') AND type in (N'U'))
DROP TABLE [dbo].[MNT_ACCUMULATION_REGISTER]
GO

CREATE TABLE [dbo].[MNT_ACCUMULATION_REGISTER](
      [ENTRY_DATE] DATETIME NOT NULL,
      [ACC_REF_NO] NVARCHAR(10) ,
      [CUSTOMER_ID] INT NOT NULL ,
      [POLICY_ID] INT  NOT NULL, 
      [POLICY_VERSION_ID] INT NOT NULL,
      [RISK_ID] INT NOT NULL , 
      [TOTAL_LIMIT] DECIMAL(18,2),
	  [IS_ACTIVE] CHAR(2) 
      
      )
GO

ALTER TABLE [dbo].[MNT_ACCUMULATION_REGISTER] ADD CONSTRAINT FK_MNT_ACCUMULATION_REFERENCE_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID_RISK_ID  PRIMARY KEY
      CLUSTERED
      (
            [CUSTOMER_ID],
			[POLICY_ID] , 
			[POLICY_VERSION_ID] ,
			[RISK_ID]  
      )     WITH
      (
            PAD_INDEX = OFF
            ,STATISTICS_NORECOMPUTE = OFF
            ,IGNORE_DUP_KEY = OFF
            ,ALLOW_ROW_LOCKS = ON
            ,ALLOW_PAGE_LOCKS = ON
      ) 
GO

ALTER TABLE [dbo].[MNT_ACCUMULATION_REFERENCE] ADD CONSTRAINT [FK_MNT_ACCUMULATION_REGISTER_ACC_ID] FOREIGN KEY
      (
         ACC_ID
      )
      REFERENCES [dbo].[MNT_ACCUMULATION_REFERENCE]
      (
		ACC_ID
      )
      
GO
EXEC Proc_AddExtendedProperty [MNT_ACCUMULATION_CRITERIA_MASTER]
EXEC Proc_AddExtendedProperty [MNT_ACCUMULATION_REFERENCE]
EXEC Proc_AddExtendedProperty [MNT_ACCUMULATION_REGISTER]