IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QQ_MOTOR_QUOTE_DETAILS]') AND type in (N'U'))
DROP TABLE [dbo].[QQ_MOTOR_QUOTE_DETAILS]

GO

/****** Object:  Table [dbo].[QQ_MOTOR_QUOTE_DETAILS]    Script Date: 08/09/2011 10:57:21 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[QQ_MOTOR_QUOTE_DETAILS](
	[CUSTOMER_ID] [int] NOT NULL,
	[POLICY_ID] [int] NOT NULL,
	[POLICY_VERSION_ID] [smallint] NOT NULL,
	[QUOTE_ID] [int] NOT NULL,
	[YEAR_OF_REG] [varchar](4) NULL,
	[MAKE] [nvarchar](75) NULL,
	[MODEL] [nvarchar](75) NULL,
	[MODEL_TYPE] [nvarchar](75) NULL,
	[ENG_CAPACITY] [int] NULL,
	[NO_OF_DRIVERS] [smallint] NULL,
	[ANY_CLAIM] [nchar](1) NULL,
	[NO_OF_CLAIM] [int] NULL,
	[TOTAL_CLAIM_AMT] [int] NULL,
	[COVERAGE_TYPE] [int] NULL,
	[NO_CLAIM_DISCOUNT] [nchar](1) NULL,
	[IS_ACTIVE] [nchar](1) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[IS_NEW] [nchar](4) NULL,
	[REGISTRATION_NO] [nvarchar](50) NULL,
	[COVER_NOTE_NO] [nvarchar](50) NULL,
	[DATE_LTA_REGISTRATION] [date] NULL,
	[ENGINE_NO] [nvarchar](30) NULL,
	[CHASSIS_NO] [nvarchar](30) NULL,
	[IS_UNDER_HIRE] [nchar](4) NULL,
	[FINANCE_COMP_NAME] [varchar](100) NULL,
	[IS_DEMERIT_POINT] [nchar](4) NULL,
	[DEMERIT_DESC] [nvarchar](500) NULL,
	[IS_REJECTED] [nchar](4) NULL,
	[REJECTED_DESC] [nvarchar](500) NULL,
	[IS_DISEASE] [nchar](4) NULL,
	[DISEASE_DESC] [nvarchar](500) NULL,
	[NAMED_DRIVER_AMT] [nvarchar](15) NULL,
	[UNNAMED_DRIVER_AMT] [nvarchar](15) NULL,
	[BASE_PREMIUM] [decimal](18, 2) NULL,
	[DEMERIT_DISC_AMT] [decimal](18, 2) NULL,
	[GST_AMOUNT] [decimal](18, 2) NULL,
	[FINAL_PREMIUM] [decimal](18, 2) NULL,
 CONSTRAINT [PK_POL_VEHICLES_POLICY_ID_POLICY_VERSION_ID_CUSTOMER_ID_QUOTE_ID] PRIMARY KEY NONCLUSTERED 
(
	[CUSTOMER_ID] ASC,
	[POLICY_ID] ASC,
	[POLICY_VERSION_ID] ASC,
	[QUOTE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[QQ_MOTOR_QUOTE_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_QQ_MOTOR_QUOTE_DETAILS_POLICY_ID_POLICY_VERSION_ID_CUSTOMER_ID] FOREIGN KEY([CUSTOMER_ID], [POLICY_ID], [POLICY_VERSION_ID])
REFERENCES [dbo].[POL_CUSTOMER_POLICY_LIST] ([CUSTOMER_ID], [POLICY_ID], [POLICY_VERSION_ID])
GO

ALTER TABLE [dbo].[QQ_MOTOR_QUOTE_DETAILS] CHECK CONSTRAINT [FK_QQ_MOTOR_QUOTE_DETAILS_POLICY_ID_POLICY_VERSION_ID_CUSTOMER_ID]
GO

