IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MNT_VEHICLE_MODEL_TYPE_LIST]') AND type in (N'U'))
DROP TABLE [dbo].[MNT_VEHICLE_MODEL_TYPE_LIST]





--drop table [MNT_VEHICLE_MODEL_TYPE_LIST]
GO

/****** Object:  Table [dbo].[MNT_VEHICLE_MODEL_TYPE_LIST]   Script Date: 06/22/2011 13:36:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MNT_VEHICLE_MODEL_TYPE_LIST](
	[ID] [int]IDENTITY(1,1) NOT NULL,	
	[MODEL_TYPE] [nvarchar](255) NULL,
	IS_ACTIVE nchar(2),
	LAST_UPDATED_DATETIME datetime
 CONSTRAINT [PK_MNT_VEHICLE_MODEL_TYPE_LIST] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

