IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MNT_UNDERWRITING_CLAIM_LIMITS') AND type in (N'U'))
DROP TABLE dbo.MNT_UNDERWRITING_CLAIM_LIMITS
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE MNT_UNDERWRITING_CLAIM_LIMITS
(
      ASSIGN_ID int NOT NULL,
      USER_ID int NOT NULL,
      COUNTRY_ID INT NOT NULL,      
      LOB_ID int NOT NULL,
      PML_LIMIT decimal(18, 2) NULL,
      PREMIUM_APPROVAL_LIMIT decimal(18,2) null,
      CLAIM_RESERVE_LIMIT decimal(18, 2) NULL,
      CLAIM_REOPEN INT NULL,
      CLAIM_SETTLMENT_LIMIT decimal(18, 2) NULL,
      CREATED_BY int NULL,
      CREATED_DATETIME datetime NULL,
      MODIFIED_BY int NULL,
      LAST_UPDATED_DATETIME datetime NULL 
)

ALTER TABLE dbo.MNT_UNDERWRITING_CLAIM_LIMITS ADD CONSTRAINT PK_MNT_UNDERWRITING_CLAIM_LIMITS_ASSIGN_ID PRIMARY KEY
      CLUSTERED
      (
            ASSIGN_ID ASC
      )     WITH
      (
            PAD_INDEX = OFF
            ,STATISTICS_NORECOMPUTE = OFF
            ,IGNORE_DUP_KEY = OFF
            ,ALLOW_ROW_LOCKS = ON
            ,ALLOW_PAGE_LOCKS = ON
      ) 
GO

ALTER TABLE MNT_UNDERWRITING_CLAIM_LIMITS ADD CONSTRAINT FK_MNT_UNDERWRITING_CLAIM_LIMITS_USERID FOREIGN KEY
      (
            USER_ID 
      )
      REFERENCES MNT_USER_LIST
      (
            USER_ID
      )
GO

ALTER TABLE dbo.MNT_UNDERWRITING_CLAIM_LIMITS ADD CONSTRAINT FK_MNT_UNDERWRITING_CLAIM_LIMITS_COUNTRY_ID FOREIGN KEY
      (
          COUNTRY_ID
      )
      REFERENCES MNT_COUNTRY_LIST
      (
          COUNTRY_ID
      ) 
GO
ALTER TABLE dbo.MNT_UNDERWRITING_CLAIM_LIMITS ADD CONSTRAINT FK_MNT_UNDERWRITING_CLAIM_LIMITS_CLAIM_REOPEN FOREIGN KEY
      (
          CLAIM_REOPEN
      )
      REFERENCES MNT_LOOKUP_VALUES
      (
          LOOKUP_UNIQUE_ID

      ) 
GO
ALTER TABLE  dbo.MNT_UNDERWRITING_CLAIM_LIMITS ALTER column CLAIM_REOPEN int null

EXEC Proc_AddExtendedProperty MNT_UNDERWRITING_CLAIM_LIMITS
GO
SET ANSI_PADDING OFF
GO


