IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'dbo.MNT_CURRENT_RATING_LIST') AND type in (N'U'))
DROP TABLE dbo.MNT_CURRENT_RATING_LIST
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE dbo.MNT_CURRENT_RATING_LIST
(
      RATING_ID INT NOT NULL,
      COMPANY_ID INT NOT NULL,
      COMPANY_TYPE nvarchar(6),
      AGENCY_ID INT NULL,
      RATING nvarchar (6) NULL,
      EFFECTIVE_YEAR INT NULL,
      CREATED_BY INT NULL,
      CREATED_DATETIME datetime NULL,
      MODIFIED_BY INT NULL,
      LAST_UPDATED_DATETIME datetime NULL   
) 
GO

ALTER TABLE dbo.MNT_CURRENT_RATING_LIST ADD CONSTRAINT PK_MNT_CURRENT_RATING_LIST_RATING_ID PRIMARY KEY
      CLUSTERED
      (
            RATING_ID ASC
      )     WITH
      (
            PAD_INDEX = OFF
            ,STATISTICS_NORECOMPUTE = OFF
            ,IGNORE_DUP_KEY = OFF
            ,ALLOW_ROW_LOCKS = ON
            ,ALLOW_PAGE_LOCKS = ON
      ) 
GO

ALTER TABLE dbo.MNT_CURRENT_RATING_LIST ADD CONSTRAINT FK_MNT_CURRENT_RATING_LIST FOREIGN KEY
      (
          COMPANY_ID
      )
      REFERENCES dbo.MNT_REIN_COMAPANY_LIST
      (
          REIN_COMAPANY_ID
      ) 
GO
 Exec Proc_AddExtendedProperty MNT_CURRENT_RATING_LIST
 Go
