/****** Object:  Table [dbo].[MNT_FUND_TYPES]    Script Date:  09/22/2011 12:55:15  ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MNT_FUND_TYPES]') AND type in (N'U'))
DROP TABLE [dbo].[MNT_FUND_TYPES]
GO
/****** Object:  Table [dbo].[MNT_FUND_TYPES]    Script Date: 09/22/2011 12:55:15 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MNT_FUND_TYPES](
	[FUND_TYPE_ID] [int] NOT NULL ,
	[FUND_TYPE_CODE] [nvarchar](20) Null,
	[FUND_TYPE_NAME] [nvarchar](100)NULL,
	[FUND_TYPE_SOURCE_D] [BIT] NULL,
	[FUND_TYPE_SOURCE_DO] [BIT] NULL,
	[FUND_TYPE_SOURCE_RIO] [BIT] NULL,
	[FUND_TYPE_SOURCE_RIA] [BIT] NULL,
	[IS_ACTIVE][CHAR](1)
	CONSTRAINT [PK_MNT_FUND_TYPES_FUND_TYPE_ID] PRIMARY KEY CLUSTERED
    ([FUND_TYPE_ID]ASC))
     EXEC Proc_AddExtendedProperty MNT_FUND_TYPES
GO

SET ANSI_PADDING OFF
GO
