IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MNT_VEHICLE_MODEL_LIST]') AND type in (N'U'))
DROP TABLE [dbo].[MNT_VEHICLE_MODEL_LIST]


GO

/****** Object:  Table [dbo].[MNT_VEHICLE_MODEL_LIST]    Script Date: 06/22/2011 13:36:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MNT_VEHICLE_MODEL_LIST](
	[ID] [int] NOT NULL,
	[MAKER_LOOKUP_ID] [int] NOT NULL,
	[MODEL] [nvarchar](255) NULL,
	[MODEL_TYPE] [nvarchar](255) NULL,	
	[MODEL_YEAR] [nvarchar](8) NULL,
	[EFFECTIVE_FROM_DATE] [datetime] NULL,
	[EFFECTIVE_TO_DATE] [datetime] NULL,
	IS_ACTIVE nchar(2),
	LAST_UPDATED_DATETIME datetime
 CONSTRAINT [PK_MNT_VEHICLE_MODEL_LIST_ID] PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MNT_VEHICLE_MODEL_LIST]  WITH NOCHECK ADD  CONSTRAINT [FK_MNT_VEHICLE_MODEL_LIST_MNT_LOOKUP_VALUES] FOREIGN KEY([MAKER_LOOKUP_ID])
REFERENCES [dbo].[MNT_LOOKUP_VALUES] ([LOOKUP_UNIQUE_ID])
GO

ALTER TABLE [dbo].[MNT_VEHICLE_MODEL_LIST] CHECK CONSTRAINT [FK_MNT_VEHICLE_MODEL_LIST_MNT_LOOKUP_VALUES]
GO

