IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[QQ_CUSTOMER_PARTICULAR]') AND type in (N'U'))
DROP TABLE [dbo].[QQ_CUSTOMER_PARTICULAR]

GO
/****** Object:  Table [dbo].[QQ_CUSTOMER_PARTICULAR]    Script Date: 08/09/2011 10:49:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[QQ_CUSTOMER_PARTICULAR](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_ID] [int] NOT NULL,
	[QUOTE_ID] [int] NOT NULL,
	[CUSTOMER_CODE] [nvarchar](10) NULL,
	[CUSTOMER_TYPE] [int] NULL,
	[CUSTOMER_FIRST_NAME] [nvarchar](100) NULL,
	[CUSTOMER_MIDDLE_NAME] [nvarchar](100) NULL,
	[CUSTOMER_LAST_NAME] [nvarchar](100) NULL,
	[DATE_OF_BIRTH] [datetime] NULL,
	[GENDER] [nchar](1) NULL,
	[NATIONALITY] [nvarchar](100) NULL,
	[IS_HOME_EMPLOYEE] [nchar](2) NULL,
	[CUSTOMER_OCCU] [int] NULL,
	[DRIVER_EXP_YEAR] [int] NULL,
	[ANY_CLAIM] [nchar](2) NULL,
	[EXIST_NCD_LESS_10] [nchar](2) NULL,
	[EXISTING_NCD] [nvarchar](25) NULL,
	[DEMERIT_DISCOUNT] [nchar](2) NULL,
	[CUSTOMER_AGENCY_ID] [smallint] NULL,
	[IS_ACTIVE] [nchar](1) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[CUSTOMER_ADDRESS1] [varchar](250) NULL,
	[CUSTOMER_ADDRESS2] [varchar](250) NULL,
	[CUSTOMER_CITY] [varchar](150) NULL,
	[CUSTOMER_STATE] [varchar](150) NULL,
	[CUSTOMER_ZIP] [varchar](150) NULL,
	[MARITAL_STATUS] [nchar](8) NULL,
	[CUSTOMER_CONTACT_NO] [nvarchar](30) NULL,
	[PASSPORT_NO] [nvarchar](30) NULL,
	[EXISTING_INSURER] [nvarchar](250) NULL,
	[EXISTING_POL_NUM] [nvarchar](80) NULL,
	[EXIST_POL_EXP_DATE] [date] NULL,
	[VEHICLE_NO] [nvarchar](40) NULL,
	[DATE_OF_QUOTATION] [varchar](20) NULL,
 CONSTRAINT [PK_QQ_CUSTOMER_PARTICULAR_ID_CUSTOMER_ID] PRIMARY KEY CLUSTERED 
(
	[ID] ASC,
	[CUSTOMER_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

