IF NOT EXISTS (SELECT TOP 1* FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'MNT_TEMPLATE_MASTER' AND [COLUMN_NAME] = 'HasPartyType')
BEGIN
  ALTER TABLE [dbo].[MNT_TEMPLATE_MASTER] ADD HasPartyType char(1)
END