IF NOT EXISTS (SELECT TOP 1
    *
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'Country')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD Country [varchar](5) NULL
END


IF NOT EXISTS (SELECT TOP 1
    *
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'City')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD City [nvarchar](50) NULL
END


IF NOT EXISTS (SELECT TOP 1
    *
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'CLM_Claims'
  AND [COLUMN_NAME] = 'State')
BEGIN
  ALTER TABLE [dbo].[CLM_Claims] ADD State [nvarchar](100) NULL
END