IF NOT EXISTS (SELECT TOP 1
    *
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE [TABLE_NAME] = 'MNT_Users'
  AND [COLUMN_NAME] = 'LOGApproverCheckbox')
BEGIN
  ALTER TABLE [dbo].[MNT_Users] ADD LOGApproverCheckbox Bit NULL
END