IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS where table_name = 'MNT_TEMPLATE_MASTER' and column_name = 'ParantId') 
BEGIN
  ALTER TABLE MNT_TEMPLATE_MASTER DROP COLUMN ParantId
END
IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS where table_name = 'MNT_TEMPLATE_MASTER' and column_name = 'ParentId') 
BEGIN
Alter table MNT_TEMPLATE_MASTER Add  ParentId int NULL
END