IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_MNT_LOOKUP_MULTILINGUAL_MNT_Lookups]') AND parent_object_id = OBJECT_ID(N'[dbo].[MNT_LOOKUP_MULTILINGUAL]'))
ALTER TABLE [dbo].[MNT_LOOKUP_MULTILINGUAL] DROP CONSTRAINT [FK_MNT_LOOKUP_MULTILINGUAL_MNT_Lookups]
GO

IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MNT_LOOKUP_MULTILINGUAL]') AND type in (N'U'))
DROP TABLE [dbo].[MNT_LOOKUP_MULTILINGUAL]
GO

CREATE TABLE [dbo].[MNT_LOOKUP_MULTILINGUAL](
	[LOOKUP_ID] [decimal](18, 0) NOT NULL,
	[LOOKUP_DESC] [nvarchar](500) NULL,
	[LANG_ID] [int] NOT NULL,
 CONSTRAINT [PK_MNT_LOOKUP_MULTILINGUAL] PRIMARY KEY CLUSTERED 
(
	[LOOKUP_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MNT_LOOKUP_MULTILINGUAL]  WITH CHECK ADD  CONSTRAINT [FK_MNT_LOOKUP_MULTILINGUAL_MNT_Lookups] FOREIGN KEY([LOOKUP_ID])
REFERENCES [dbo].[MNT_Lookups] ([LookupID])
GO

ALTER TABLE [dbo].[MNT_LOOKUP_MULTILINGUAL] CHECK CONSTRAINT [FK_MNT_LOOKUP_MULTILINGUAL_MNT_Lookups]
GO


