IF NOT EXISTS (SELECT TOP 1* FROM INFORMATION_SCHEMA.COLUMNS WHERE [TABLE_NAME] = 'MNT_TEMPLATE_MASTER' AND [COLUMN_NAME] = 'PartyToShown')
BEGIN
  ALTER TABLE [dbo].[MNT_TEMPLATE_MASTER] ADD PartyToShown int null
END
