
ALTER TABLE MNT_Lookups ALTER COLUMN [Lookupdesc] NVARCHAR(100)
ALTER TABLE MNT_Lookups ALTER COLUMN [Description] NVARCHAR(100)


/*** Remove Foreign Key Constraints from TODODIARYLIST ***/

IF EXISTS (SELECT * 
  FROM sys.foreign_keys 
   WHERE object_id = OBJECT_ID(N'dbo.FK_LISTTYPEID_TODODIARYLIST')
   AND parent_object_id = OBJECT_ID(N'dbo.TODODIARYLIST')
)
  ALTER TABLE TODODIARYLIST DROP CONSTRAINT [FK_LISTTYPEID_TODODIARYLIST]
  

