CREATE TABLE [dbo].[MNT_EMAIL](
	[IDEN_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[NAME] [varchar](100) NULL,
	[EMAIL] [varchar](100) NULL,
	[IsActive] [char](1) NULL,
	[CreatedDate] [datetime] NULL,
	[CreatedBy] [nvarchar](25) NULL,
	[ModifiedBy] [nvarchar](25) NULL,
	[ModifiedDate] [datetime] NULL,
 CONSTRAINT [PK_MNT_EMAIL_IDEN_ROW_ID] PRIMARY KEY NONCLUSTERED 
(
	[IDEN_ROW_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[MNT_EMAIL] ADD  DEFAULT ('Y') FOR [IsActive]
GO


