
/****** Object:  StoredProcedure [dbo].[Proc_MIG_IL_VEHICLE_DETAIL_Save]    Script Date: 08/28/2014 11:22:22 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Proc_MIG_IL_VEHICLE_DETAIL_Save]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Proc_MIG_IL_VEHICLE_DETAIL_Save]
GO


/****** Object:  StoredProcedure [dbo].[Proc_MIG_IL_VEHICLE_DETAIL_Save]    Script Date: 08/28/2014 11:22:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







 CREATE PROCEDURE [dbo].[Proc_MIG_IL_VEHICLE_DETAIL_Save]
@p_UPLOAD_FILE_ID int,
@p_VEHICLE_REGISTRATION_NO nvarchar(100),
@p_VEHICLE_MAKE nvarchar(50),
@p_VEHICLE_MODEL nvarchar(100),
@p_VEHICLE_CLASS nvarchar(50),
@p_MODEL_DESCRIPTION nvarchar(2000),
@p_BUS_CAPTAIN nvarchar(50),
@p_IMPORT_ACTION nvarchar(50),
@p_FileName nvarchar(200)  
AS
BEGIN
SET FMTONLY OFF;
	Insert into MIG_IL_VEHICLE_DETAIL (UPLOAD_FILE_ID,VEHICLE_REGISTRATION_NO,VEHICLE_MAKE,VEHICLE_MODEL,VEHICLE_CLASS,MODEL_DESCRIPTION,BUS_CAPTAIN,IMPORT_ACTION,FileName)
	values(@p_UPLOAD_FILE_ID,@p_VEHICLE_REGISTRATION_NO,@p_VEHICLE_MAKE,@p_VEHICLE_MODEL,@p_VEHICLE_CLASS,@p_MODEL_DESCRIPTION,@p_BUS_CAPTAIN,@p_IMPORT_ACTION,@p_FileName)
END

GO


