<?xml version="1.0" encoding="UTF-8"?>
<!--Designed and generated by Altova StyleVision Enterprise Edition 2011 rel. 2 sp1 - see http://www.altova.com/stylevision for more information.-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"  xmlns:msxsl="urn:schemas-microsoft-com:xslt"  xmlns:user="urn:user-namespace-here"    xmlns:clitype="clitype" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:iso4217="http://www.xbrl.org/2003/iso4217" xmlns:ix="http://www.xbrl.org/2008/inlineXBRL" xmlns:java="java" xmlns:link="http://www.xbrl.org/2003/linkbase" xmlns:xbrldi="http://xbrl.org/2006/xbrldi" xmlns:xbrli="http://www.xbrl.org/2003/instance" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xs="http://www.w3.org/2001/XMLSchema"    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:altova="http://www.altova.com" exclude-result-prefixes="clitype fn iso4217 ix java link xbrldi xbrli xlink xs xsi altova">
  <xsl:output version="4.0" method="html" indent="no" encoding="UTF-8" doctype-public="-//W3C//DTD HTML 4.01 Transitional//EN" doctype-system="http://www.w3.org/TR/html4/loose.dtd"/>
  <xsl:param name="SV_OutputFormat" select="'HTML'"/>
  <xsl:variable name="XML" select="/"/>
  <xsl:variable name="altova:nPxPerIn" select="96"/>
  <xsl:template name="br-replace">
    <xsl:param name="word"/>
    <!-- </xsl:text> on next line on purpose to get newline -->
    <xsl:variable name="cr" select="'~'">
    </xsl:variable>
    <xsl:choose>
      <xsl:when test="contains($word,$cr)">
        <xsl:value-of select="substring-before($word,$cr)"/>
        <br/>
        <xsl:call-template name="br-replace">
          <xsl:with-param name="word"

							select="substring-after($word,$cr)"/>

        </xsl:call-template>

      </xsl:when>
      <xsl:otherwise>
        <xsl:value-of select="$word"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>
  <msxsl:script language="c#" implements-prefix="user">
    <![CDATA[ 
		
		int intCSS=1;
		public int ApplyColor(int colorvalue)
		{
			intCSS=colorvalue;			
			return intCSS;
		}
		string Add_Location ="";
		public void ConcatLocation(double strLoc)
		{
		 Add_Location	= Add_Location + "/" +strLoc;
     Add_Location	=Add_Location.Substring(1,Add_Location.Length-1);	
			//return Add_Location;
		}
    
    	public string Getlocation()
		{
	
			return Add_Location;
		}
    
		int intTotalamp=0;
		public int Calculateamp(int tt)
		{
			intTotalamp = intTotalamp + tt;
			return intTotalamp;
		}
    
    string  tempdesc="";
		public string RetunDescription(string desc)
    {
      if(tempdesc!=desc)
      { 
         tempdesc= desc;
         return desc;
      }else
      {
          return "";
      }
    }
    string strPolicycurrency;
	
	int RiskID=0;
	public void SetRiskID(int flag)
		{
			RiskID=flag;
		
		}
	
	public int GetRiskID()
		{

			return RiskID;
		}
		
	int IsPrint=0;
	public void SetIsPrint(int flag)
		{
			IsPrint += flag;
		
		}
	
	public int GetIsPrint()
		{

			return IsPrint;
		}
		
	int IsPrintD=0;
	public void SetIsPrintD(int flag)
		{
			IsPrintD = flag;
		
		}
	
	public int GetIsPrintD()
		{

			return IsPrintD;
		}
    
]]>
  </msxsl:script>
  <xsl:template match="/">
    <html>
      <body>
        <xsl:for-each select="$XML">
          <br/>
          <span>
            <xsl:text>1. ENDOSSO DE COBRANÇA DE PRÊMIO</xsl:text>
          </span>
          <br/>
          <br/>
          <span>
            <xsl:text>Declara-se para os devidos fins e efeitos que, de conformidade com as condições da </xsl:text>
          </span>
          <br/>
          <span>
            <xsl:text>apólice, procede-se as alterações solicitadas pelo segurado, através de seu corretor.</xsl:text>
          </span>
          <br/>
          <br/>
          <span>
            <xsl:text>Face o exposto, e o de acordo com o(s) movimento(s) efetuado(s) na referida apólice, </xsl:text>
          </span>
          <br/>
          <span>
            <xsl:text>COBRA-SE do segurado, o prêmio correspondente o informado no item 4 abaixo, prêmio</xsl:text>
          </span>
          <br/>
          <span>
            <xsl:text>líquido deste endosso.</xsl:text>
          </span>
          <br/>
          <br/>
          <span>
            <xsl:text>2. PERÍODO DE VIGÊNCIA</xsl:text>
          </span>
          <br/>
          <br/>
          <span>
            <xsl:text>Vigência Apolice&#160; :&#160; </xsl:text>
          </span>
          <xsl:for-each select="POLICY_DOCUMENTS">
            <xsl:for-each select="APPLICATION">
              <xsl:for-each select="POLICY_EFFECTIVE_DATE">
                <xsl:apply-templates/>
              </xsl:for-each>
            </xsl:for-each>
          </xsl:for-each>
          <span>
            <xsl:text> - </xsl:text>
          </span>
          <xsl:for-each select="POLICY_DOCUMENTS">
            <xsl:for-each select="APPLICATION">
              <xsl:for-each select="POLICY_EXPIRATION_DATE">
                <xsl:apply-templates/>
              </xsl:for-each>
            </xsl:for-each>
          </xsl:for-each>
          <br/>
          <span>
            <xsl:text>Vigência do Endosso&#160; :&#160; </xsl:text>
          </span>
          <xsl:for-each select="POLICY_DOCUMENTS">
            <xsl:for-each select="BROKER">
              <xsl:for-each select="POL">
                <xsl:for-each select="ENDORSMENT_EFFECTIVE_DATE">
                  <xsl:apply-templates/>
                </xsl:for-each>
              </xsl:for-each>
            </xsl:for-each>
          </xsl:for-each>
          <span>
            <xsl:text> - </xsl:text>
          </span>
          <xsl:for-each select="POLICY_DOCUMENTS">
            <xsl:for-each select="BROKER">
              <xsl:for-each select="POL">
                <xsl:for-each select="ENDORSMENT_EXPIRATION_DATE">
                  <xsl:apply-templates/>
                </xsl:for-each>
              </xsl:for-each>
            </xsl:for-each>
          </xsl:for-each>
          <br/>
          <br/>
          <span>
            <xsl:text>3. VEÍCULOS MOVIMENTADOS NO PERÍODO</xsl:text>
          </span>
          <br/>
          <br/>
          <span>
            <xsl:text>Conforme constante da movimentação na especificação a seguir:</xsl:text>
          </span>
          <br/>
          <br/>
          <span>
            <xsl:text>Sem movimentação de itens</xsl:text>
          </span>
          <br/>
          <xsl:for-each select="POLICY_DOCUMENTS">
            <xsl:for-each select="RISKINFO">
              <xsl:for-each select="RISKS">
                <xsl:call-template name="br-replace">
                  <xsl:with-param name="word" select="REMARKS"/>
                </xsl:call-template>
              </xsl:for-each>
            </xsl:for-each>
          </xsl:for-each>
        </xsl:for-each>
        <br/>
        <span>
          <xsl:text>TABELA - &gt;</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>3.1 COBERTURA E LIMITES MÁXIMOS SEGURADOS DA SECAO 1 - RESPONSABILIDADE CIVIL </xsl:text>
        </span>
        <br/>
        <span>
          <xsl:text>FACULTATIVA</xsl:text>
        </span>
        <br/>
        <br/>
        <table border="0" width="100%">
          <xsl:variable name="altova:CurrContextGrid_073AA350" select="."/>
          <tbody>
            <xsl:for-each select="POLICY_DOCUMENTS">
              <xsl:for-each select="RISKINFO">
                <xsl:for-each select="RISKS">
                  <tr>
                    <td>
                      <span>
                        <xsl:text>Tabela&#160; :</xsl:text>
                      </span>
                      <xsl:for-each select="COV_GROUP_CODE">
                        <xsl:apply-templates/>
                      </xsl:for-each>
                      <br/>
                      <table border="0" width="100%">
                        <xsl:variable name="altova:CurrContextGrid_073ABD58" select="."/>
                        <tbody>
                          <xsl:for-each select="COVERAGE">
                            <tr>
                              <td>
                                <table style="border-collapse:collapse; table-layout:fixed; " border="0" width="100%">
                                  <xsl:variable name="altova:CurrContextGrid_073B28A8" select="."/>
                                  <tbody>
                                    <tr>
                                      <td>
                                        <span>
                                          <xsl:text>- </xsl:text>
                                        </span>
                                        <xsl:for-each select="IS_MAIN_Text">
                                          <xsl:apply-templates/>
                                        </xsl:for-each>
                                      </td>
                                      <td>
                                        <span>
                                          <xsl:text>:</xsl:text>
                                        </span>
                                        <xsl:for-each select="COV_DES">
                                          <xsl:apply-templates/>
                                        </xsl:for-each>
                                      </td>
                                      <td>
                                        <span>
                                          <xsl:text>= R$&#160; </xsl:text>
                                        </span>
                                        <xsl:for-each select="LIMIT_1">
                                          <xsl:apply-templates/>
                                        </xsl:for-each>
                                      </td>
                                    </tr>
                                  </tbody>
                                </table>
                              </td>
                            </tr>
                          </xsl:for-each>
                        </tbody>
                      </table>
                      <br/>
                    </td>
                  </tr>
                </xsl:for-each>
              </xsl:for-each>
            </xsl:for-each>
          </tbody>
        </table>
        <br/>
        <span>
          <xsl:text>4. PAGAMENTO DO PRÊMIO</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>RESUMO DO PRÊMIO LÍQUIDO:</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>PREMIO RCFO/APP---------------------------------------------- = R$</xsl:text>
        </span>
        <br/>
        <span>
          <xsl:text>TOTAL------------------------------------------------------------&#160; = R$</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>Importancia Segurada Total: </xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>5. FRANQUIA</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>Serão aplicadas Franquia para sinistros, nos limites e valores fixados na especificação </xsl:text>
        </span>
        <br/>
        <span>
          <xsl:text>da apólice e/ou faturas/endossos. </xsl:text>
        </span>
        <br/>
        <span>
          <xsl:text>Quando o sinistro decorrer da movimentação do veículo em marcha-re, a franquia será o </xsl:text>
        </span>
        <br/>
        <span>
          <xsl:text>dobro do valor previsto na especificação da fatura/endosso.</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>6. DECLARAÇÕES E CLAUSULAS</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>Conforme abaixo:</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>7. RATIFICAÇÃO</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>Permanecem inalterados os demais termos, clausulas e condições da apólice.</xsl:text>
        </span>
        <br/>
        <br/>
        <span>
          <xsl:text>Frota Movimentada</xsl:text>
        </span>
        <br/>
        <br/>
        <table style="border-collapse:collapse; table-layout:fixed; " border="0" width="140%">
          <xsl:variable name="altova:CurrContextGrid_073B6DD0" select="."/>
          <tbody>
            <tr>
              <td>
                <span>
                  <xsl:text>Item</xsl:text>
                </span>
              </td>
              <td style="width:2.24in; ">
                <span>
                  <xsl:text>Marca</xsl:text>
                </span>
              </td>
              <td>
                <span>
                  <xsl:text>Ano</xsl:text>
                </span>
              </td>
              <td>
                <span>
                  <xsl:text>Licenca</xsl:text>
                </span>
              </td>
              <td>
                <span>
                  <xsl:text>Chassis</xsl:text>
                </span>
              </td>
              <td>
                <span>
                  <xsl:text>Ordem</xsl:text>
                </span>
              </td>
              <td>
                <span>
                  <xsl:text>Cap</xsl:text>
                </span>
              </td>
              <td>
                <span>
                  <xsl:text>Tabela</xsl:text>
                </span>
              </td>
              <td>
                <span>
                  <xsl:text>Vigência</xsl:text>
                </span>
              </td>
            </tr>
            <tr>
              <td colspan="9">
                <table border="0" width="100%">
                  <xsl:variable name="altova:CurrContextGrid_073B8A38" select="."/>
                  <tbody>
                    <xsl:for-each select="POLICY_DOCUMENTS">
                      <xsl:for-each select="RISKINFO">
                        <xsl:for-each select="RISKS">
                          <tr>
                            <td>
                              <table style="border-collapse:collapse; table-layout:fixed; " border="0" width="100%">
                                <xsl:variable name="altova:CurrContextGrid_073B93F0" select="."/>
                                <tbody>
                                  <tr>
                                    <td style="width:1.67in; ">
                                      <xsl:for-each select="VEHICLE_NUMBER">
                                        <xsl:apply-templates/>
                                      </xsl:for-each>
                                      <br/>
                                    </td>
                                    <td style="width:2.22in; ">
                                      <xsl:for-each select="MAKE_MODEL">
                                        <xsl:apply-templates/>
                                      </xsl:for-each>
                                    </td>
                                    <td>
                                      <xsl:for-each select="MANUFACTURED_YEAR">
                                        <xsl:apply-templates/>
                                      </xsl:for-each>
                                    </td>
                                    <td>
                                      <xsl:for-each select="LICENSE_PLATE">
                                        <xsl:apply-templates/>
                                      </xsl:for-each>
                                    </td>
                                    <td>
                                      <xsl:for-each select="CHASSIS">
                                        <xsl:apply-templates/>
                                      </xsl:for-each>
                                    </td>
                                    <td>
                                      <xsl:for-each select="CLIENT_ORDER">
                                        <xsl:apply-templates/>
                                      </xsl:for-each>
                                    </td>
                                    <td>
                                      <xsl:for-each select="CAPACITY">
                                        <xsl:apply-templates/>
                                      </xsl:for-each>
                                    </td>
                                    <td>
                                      <xsl:for-each select="COV_GROUP_CODE">
                                        <xsl:apply-templates/>
                                      </xsl:for-each>
                                    </td>
                                    <td>
                                      <xsl:for-each select="$XML">
                                        <xsl:for-each select="POLICY_DOCUMENTS">
                                          <xsl:for-each select="BROKER">
                                            <xsl:for-each select="POL">
                                              <xsl:for-each select="ENDORSMENT_EFFECTIVE_DATE">
                                                <xsl:apply-templates/>
                                              </xsl:for-each>
                                            </xsl:for-each>
                                          </xsl:for-each>
                                        </xsl:for-each>
                                      </xsl:for-each>
                                      <span>
                                        <xsl:text> a </xsl:text>
                                      </span>
                                      <xsl:for-each select="$XML">
                                        <xsl:for-each select="POLICY_DOCUMENTS">
                                          <xsl:for-each select="BROKER">
                                            <xsl:for-each select="POL">
                                              <xsl:for-each select="ENDORSMENT_EXPIRATION_DATE">
                                                <xsl:apply-templates/>
                                              </xsl:for-each>
                                            </xsl:for-each>
                                          </xsl:for-each>
                                        </xsl:for-each>
                                      </xsl:for-each>
                                    </td>
                                  </tr>
                                </tbody>
                              </table>
                            </td>
                          </tr>
                        </xsl:for-each>
                      </xsl:for-each>
                    </xsl:for-each>
                  </tbody>
                </table>
              </td>
            </tr>
          </tbody>
        </table>
        <span>
          <xsl:text>-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------</xsl:text>
        </span>
        <br/>
        <span>
          <xsl:text>Total de Veículos - </xsl:text>
        </span>
        <br/>
        <br/>
        <br/>

      </body>

      <table  id="multitable"  style="border-collapse:collapse; font-family:Arial Narrow; table-layout:auto;display:inline" border="0" width="100%">
        <tbody>
          <xsl:for-each select="POLICY_DOCUMENTS">
            <xsl:for-each select="MULTIBROKER">
              <xsl:for-each select="POLR">
                <xsl:value-of select="user:SetIsPrint(IS_PRINT)"/>
              </xsl:for-each>
            </xsl:for-each>
          </xsl:for-each>
        </tbody>
        <xsl:choose>
          <xsl:when test="user:GetIsPrint() &gt;  '0'">
            <tr>
              <td colspan="3" >
                <span style="font-family:Arial; font-size:12pt ">
                  <xsl:text>NO PRESENTE SEGURO PARTICIPAM AS SEGUINTES CORRETORES:&#160; </xsl:text>
                </span>
              </td>
            </tr>
          </xsl:when >
          <xsl:otherwise>
            <xsl:text>&#160;&#160;&#160;</xsl:text>
          </xsl:otherwise>
        </xsl:choose>

        <xsl:variable name="altova:CurrContextGrid_0548CC00" select="."/>
        <tbody>
          <xsl:choose>
            <xsl:when test="user:GetIsPrint() &gt;  '0'">
              <tr>
                <td>
                  <span style="font-family:Arial; font-size:12pt ">
                    <xsl:text>Código </xsl:text>
                  </span>
                </td>
                <td>
                  <span style="font-family:Arial; font-size:12pt ">
                    <xsl:text>Filial </xsl:text>
                  </span>
                </td>
                <td>
                  <span style="font-family:Arial; font-size:12pt ">
                    <xsl:text>Nome </xsl:text>
                  </span>
                </td>
                <td>
                  <span style="font-family:Arial; font-size:12pt ">
                    <xsl:text>Participação</xsl:text>
                  </span>
                </td>
                <td id="Commisio">
                  <span style="font-family:Arial; font-size:12pt ">
                    <xsl:text>Comissão</xsl:text>
                  </span>
                </td>
              </tr>
            </xsl:when >
            <xsl:otherwise>
              <xsl:text>&#160;&#160;&#160;</xsl:text>
            </xsl:otherwise>
          </xsl:choose >
          <tr>
            <td valign ="top" style="width:20%" >
              <table style="font-family:Arial Narrow; font-size:12pt; " border="0" width="99%">
                <xsl:variable name="altova:CurrContextGrid_087FA198" select="."/>
                <tbody>
                  <xsl:for-each select="POLICY_DOCUMENTS">
                    <xsl:for-each select="MULTIBROKER">
                      <xsl:for-each select="POLR">
                        <xsl:choose>
                          <xsl:when test ="IS_PRINT = '1'">
                            <xsl:for-each select="BROKER_CODE">
                              <tr>
                                <td>
                                  <xsl:apply-templates/>
                                </td>
                              </tr>
                            </xsl:for-each>
                          </xsl:when>
                          <xsl:otherwise>
                            <xsl:text>&#160;&#160;&#160;</xsl:text>
                          </xsl:otherwise>
                        </xsl:choose>
                      </xsl:for-each>
                    </xsl:for-each>
                  </xsl:for-each>
                </tbody>
              </table>
            </td>
            <td  style="width:20%"    valign ="top">
              <table style="border-collapse:collapse; font-family:Arial Narrow; font-size:12pt; " border="0" width="100%">
                <xsl:variable name="altova:CurrContextGrid_0876B548" select="."/>
                <tbody>
                  <xsl:for-each select="POLICY_DOCUMENTS">
                    <xsl:for-each select="MULTIBROKER">
                      <xsl:for-each select="POLR">
                        <xsl:choose>
                          <xsl:when test ="IS_PRINT = '1'">
                            <xsl:for-each select="BANK_BRANCH">
                              <tr>
                                <td>
                                  <xsl:apply-templates/>
                                </td>
                              </tr>
                            </xsl:for-each>
                          </xsl:when>
                          <xsl:otherwise>
                            <xsl:text>&#160;&#160;&#160;</xsl:text>
                          </xsl:otherwise>
                        </xsl:choose >
                      </xsl:for-each>
                    </xsl:for-each>
                  </xsl:for-each>
                </tbody>
              </table>
            </td>
            <td style="width:40%"  valign ="top" nowrap="nowrap">
              <table border="0" width="100%">
                <xsl:variable name="altova:CurrContextGrid_08800900" select="."/>
                <tbody>
                  <xsl:for-each select="POLICY_DOCUMENTS">
                    <xsl:for-each select="MULTIBROKER">
                      <xsl:for-each select="POLR">
                        <xsl:choose>
                          <xsl:when test ="IS_PRINT = '1'">
                            <xsl:for-each select="BROKER_NAME">
                              <tr>
                                <td nowrap="nowrap">
                                  <xsl:apply-templates/>
                                </td>
                              </tr>
                            </xsl:for-each>
                          </xsl:when >
                          <xsl:otherwise>
                            <xsl:text>&#160;&#160;&#160;</xsl:text>
                          </xsl:otherwise>
                        </xsl:choose >
                      </xsl:for-each>
                    </xsl:for-each>
                  </xsl:for-each>
                </tbody>
              </table>
            </td>
            <td  style="width:12%"  valign ="top">
              <table border="0" width="100%">
                <xsl:variable name="altova:CurrContextGrid_08800900" select="."/>
                <tbody>
                  <xsl:for-each select="POLICY_DOCUMENTS">
                    <xsl:for-each select="MULTIBROKER">
                      <xsl:for-each select="POLR">
                        <xsl:choose>
                          <xsl:when test ="IS_PRINT = '1'">
                            <xsl:for-each select="BROKER_COMMISION">
                              <tr>
                                <td>
                                  <xsl:apply-templates/>
                                </td>
                              </tr>
                            </xsl:for-each>
                          </xsl:when >
                          <xsl:otherwise>
                            <xsl:text>&#160;&#160;&#160;</xsl:text>
                          </xsl:otherwise>
                        </xsl:choose >
                      </xsl:for-each>
                    </xsl:for-each>
                  </xsl:for-each>
                </tbody>
              </table>
            </td>
            <td id="Value"  style="width:25%" valign ="top">
              <table border="0" width="100%">
                <xsl:variable name="altova:CurrContextGrid_08800900" select="."/>
                <tbody>
                  <xsl:for-each select="POLICY_DOCUMENTS">
                    <xsl:for-each select="MULTIBROKER">
                      <xsl:for-each select="POLR">
                        <xsl:choose>
                          <xsl:when test ="IS_PRINT = '1'">
                            <xsl:for-each select="COMMISSION_PERCENT">
                              <tr>
                                <td>
                                  <xsl:apply-templates/>
                                </td>
                              </tr>
                            </xsl:for-each>
                          </xsl:when >
                          <xsl:otherwise>
                            <xsl:text>&#160;&#160;&#160;</xsl:text>
                          </xsl:otherwise>
                        </xsl:choose >
                      </xsl:for-each>
                    </xsl:for-each>
                  </xsl:for-each>
                </tbody>
              </table>
            </td>
          </tr>
        </tbody>
      </table>
      <br />

      <xsl:if test ="count($XML/POLICY_DOCUMENTS/COINSURANCE/COMPANY[IS_PRINT = '1']) &gt; '0'">
        <table  id="ceded_table" style="display:inline"   border="0" width="100%"  >
          <tbody>
            <xsl:for-each select="POLICY_DOCUMENTS">
              <xsl:for-each select="COINSURANCE">
                <xsl:for-each select="COMPANY">
                  <xsl:value-of select="user:SetIsPrint(IS_PRINT)"/>
                  <!--<xsl:value-of select ="user:GetIsPrint()"/>-->
                </xsl:for-each>
              </xsl:for-each>
            </xsl:for-each>
            <!--<xsl:choose>
						  <xsl:when test="user:GetIsPrint() &gt;  '0'">-->
            <tr>
              <td colspan="4"  style="font-family:Arial;font-size:12pt">
                <span  style="font-family:Arial ;font-size:12pt"  >
                  NO PRESENTE SEGURO PARTICIPAM AS SEGUINTES COMPANHIAS:
                </span>
              </td>
            </tr>
            <tr>
              <td style="width:20%;vertical-align:top" align="left">
                <span style="font-family:Arial ; font-size:12pt; ">
                  <xsl:text>Cia</xsl:text>
                </span>
              </td>
              <td  style="width:40%;vertical-align:top" align="left">
                <span style="font-family:Arial ; font-size:12pt; ">
                  <xsl:text>Nome</xsl:text>
                </span>

              </td>
              <td  style="width:20%;vertical-align:top" align="right" >
                <span style="font-family:Arial ; font-size:12pt; ">
                  <xsl:text>Participacao</xsl:text>
                </span>
              </td>
              <td id="CedededComissao"  style="width:20%;vertical-align:top;" align="right">
                <span style="font-family:Arial ; font-size:12pt; ">
                  <xsl:text>Comissão</xsl:text>
                </span>
              </td>
            </tr>
            <!--</xsl:when >
					  </xsl:choose >-->
          </tbody>
          <br></br>
        </table>
      </xsl:if>

      <xsl:if test ="count($XML/POLICY_DOCUMENTS/COINSURANCE/COMPANY[IS_PRINT = '1']) &gt; '0'">
        <tr>
          <td >
            <table style="font-family:Arial Narrow; font-size:12pt; " border="0" width="100%">
              <xsl:variable name="altova:CurrContextGrid_087FA198" select="."/>
              <tbody>
                <xsl:for-each select="POLICY_DOCUMENTS">
                  <xsl:for-each select="COINSURANCE">
                    <xsl:for-each select="COMPANY">
                      <!--<xsl:choose>
                        <xsl:when test ="IS_PRINT = '1'">-->
                      <tr>
                        <td valign ="top" style="width:20%" >
                          <xsl:value-of select ="SUSEP_NUM"/>
                        </td>
                        <td valign ="top" style="width:40%" nowrap ="nowrap">
                          <xsl:value-of select ="REIN_COMAPANY_NAME"/>
                        </td>
                        <td align="right"  valign ="top" style="width:20%;text-align:right" >
                          <xsl:value-of select ="COINSURANCE_PERCENT"/>
                        </td>
                        <td  align="right" id="feeCeded" style="width:20%;vertical-align:top" >
                          <xsl:value-of select ="COINSURANCE_FEE"/>
                        </td>
                      </tr>
                      <!--</xsl:when >
                      </xsl:choose >-->
                    </xsl:for-each>
                  </xsl:for-each>
                </xsl:for-each >
              </tbody>
            </table>
          </td>
        </tr>
      </xsl:if >
    </html>
  </xsl:template>
</xsl:stylesheet>
