//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cms.Account.Aspx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReinsuranceInstallmentDetails_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReinsuranceInstallmentDetails_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cms.Account.Aspx.ReinsuranceInstallmentDetails.aspx", typeof(ReinsuranceInstallmentDetails_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Report.
        /// </summary>
        internal static string btnReport {
            get {
                return ResourceManager.GetString("btnReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinsurance Installment Detail.
        /// </summary>
        internal static string capheader_field {
            get {
                return ResourceManager.GetString("capheader_field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Number.
        /// </summary>
        internal static string capPolNumber {
            get {
                return ResourceManager.GetString("capPolNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report is not available..
        /// </summary>
        internal static string errMsg {
            get {
                return ResourceManager.GetString("errMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no record for this report..
        /// </summary>
        internal static string errMsg2 {
            get {
                return ResourceManager.GetString("errMsg2", resourceCulture);
            }
        }
    }
}
