CREATE TRIGGER [dbo].[trgAfterUpdatePOL_EMAIL_SPOOL] ON [dbo].[POL_EMAIL_SPOOL] WITH EXECUTE AS CALLER AFTER  UPDATE AS 
BEGIN
   UPDATE dbo.POL_EMAIL_SPOOL
   SET ModifiedDate = GETDATE()
   FROM INSERTED i
   WHERE i.INDEN_ROW_ID = POL_EMAIL_SPOOL.INDEN_ROW_ID
END


