
IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_POL_MARINE_CARGO_GEN_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]') AND parent_object_id = OBJECT_ID(N'[dbo].[POL_MARINE_CARGO_GEN_INFO]'))
ALTER TABLE [dbo].[POL_MARINE_CARGO_GEN_INFO] DROP CONSTRAINT [FK_POL_MARINE_CARGO_GEN_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]
GO

/****** Object:  Table [dbo].[POL_MARINE_CARGO_GEN_INFO]    Script Date: 03/21/2012 12:15:31 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[POL_MARINE_CARGO_GEN_INFO]') AND type in (N'U'))
DROP TABLE [dbo].[POL_MARINE_CARGO_GEN_INFO]
GO

USE [EBX-ADV-DEV-SINGAPORE]
GO

/****** Object:  Table [dbo].[POL_MARINE_CARGO_GEN_INFO]    Script Date: 03/21/2012 12:15:31 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[POL_MARINE_CARGO_GEN_INFO](
	[CUSTOMER_ID] [int] NOT NULL,
	[POLICY_ID] [int] NOT NULL,
	[POLICY_VERSION_ID] [smallint] NOT NULL,
	[ANY_FARMING_BUSINESS_COND] [nchar](1) NULL,
	[DESC_BUSINESS] [nvarchar](150) NULL,
	[ANY_RESIDENCE_EMPLOYEE] [nchar](1) NULL,
	[DESC_RESIDENCE_EMPLOYEE] [nvarchar](150) NULL,
	[ANY_OTHER_RESI_OWNED] [nchar](1) NULL,
	[DESC_OTHER_RESIDENCE] [nvarchar](150) NULL,
	[ANY_OTH_INSU_COMP] [nchar](1) NULL,
	[DESC_OTHER_INSURANCE] [nvarchar](150) NULL,
	[HAS_INSU_TRANSFERED_AGENCY] [nchar](1) NULL,
	[DESC_INSU_TRANSFERED_AGENCY] [nvarchar](150) NULL,
	[ANY_COV_DECLINED_CANCELED] [nchar](1) NULL,
	[DESC_COV_DECLINED_CANCELED] [nvarchar](150) NULL,
	[ANIMALS_EXO_PETS_HISTORY] [int] NULL,
	[BREED] [nvarchar](100) NULL,
	[OTHER_DESCRIPTION] [nvarchar](100) NULL,
	[CONVICTION_DEGREE_IN_PAST] [nchar](1) NULL,
	[DESC_CONVICTION_DEGREE_IN_PAST] [nvarchar](150) NULL,
	[ANY_RENOVATION] [nchar](1) NULL,
	[DESC_RENOVATION] [nvarchar](150) NULL,
	[TRAMPOLINE] [nchar](1) NULL,
	[DESC_TRAMPOLINE] [nvarchar](150) NULL,
	[LEAD_PAINT_HAZARD] [nchar](1) NULL,
	[DESC_LEAD_PAINT_HAZARD] [nvarchar](150) NULL,
	[RENTERS] [nchar](1) NULL,
	[DESC_RENTERS] [nvarchar](150) NULL,
	[BUILD_UNDER_CON_GEN_CONT] [nchar](1) NULL,
	[REMARKS] [nvarchar](1000) NULL,
	[IS_ACTIVE] [nchar](1) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[MULTI_POLICY_DISC_APPLIED] [nchar](2) NULL,
	[NO_OF_PETS] [int] NULL,
	[IS_SWIMPOLL_HOTTUB] [char](1) NULL,
	[LAST_INSPECTED_DATE] [datetime] NULL,
	[IS_RENTED_IN_PART] [nchar](1) NULL,
	[IS_VACENT_OCCUPY] [nchar](1) NULL,
	[IS_DWELLING_OWNED_BY_OTHER] [nchar](1) NULL,
	[IS_PROP_NEXT_COMMERICAL] [nchar](1) NULL,
	[DESC_PROPERTY] [nvarchar](150) NULL,
	[ARE_STAIRWAYS_PRESENT] [nchar](1) NULL,
	[DESC_STAIRWAYS] [nvarchar](150) NULL,
	[IS_OWNERS_DWELLING_CHANGED] [nchar](1) NULL,
	[DESC_OWNER] [nvarchar](150) NULL,
	[DESC_VACENT_OCCUPY] [nvarchar](150) NULL,
	[DESC_RENTED_IN_PART] [nvarchar](150) NULL,
	[DESC_DWELLING_OWNED_BY_OTHER] [nvarchar](150) NULL,
	[ANY_HEATING_SOURCE] [nchar](1) NULL,
	[DESC_ANY_HEATING_SOURCE] [nvarchar](150) NULL,
	[NON_SMOKER_CREDIT] [nchar](1) NULL,
	[SWIMMING_POOL] [nchar](1) NULL,
	[SWIMMING_POOL_TYPE] [int] NULL,
	[location] [nvarchar](50) NULL,
	[ANY_FORMING] [nchar](1) NULL,
	[PREMISES] [int] NULL,
	[OF_ACRES] [decimal](18, 0) NULL,
	[ISANY_HORSE] [nchar](1) NULL,
	[OF_ACRES_P] [decimal](18, 0) NULL,
	[NO_HORSES] [int] NULL,
	[DOG_SURCHARGE] [nchar](2) NULL,
	[DESC_Location] [nvarchar](500) NULL,
	[DESC_FARMING_BUSINESS_COND] [nvarchar](300) NULL,
	[YEARS_INSU] [smallint] NULL,
	[YEARS_INSU_WOL] [smallint] NULL,
	[DESC_IS_SWIMPOLL_HOTTUB] [nvarchar](150) NULL,
	[DESC_MULTI_POLICY_DISC_APPLIED] [nvarchar](150) NULL,
	[DESC_BUILD_UNDER_CON_GEN_CONT] [nvarchar](150) NULL,
	[APPROVED_FENCE] [smallint] NULL,
	[DIVING_BOARD] [smallint] NULL,
	[SLIDE] [smallint] NULL,
	[PROVIDE_HOME_DAY_CARE] [nvarchar](2) NULL,
	[MODULAR_MANUFACTURED_HOME] [nvarchar](2) NULL,
	[BUILT_ON_CONTINUOUS_FOUNDATION] [nvarchar](2) NULL,
	[VALUED_CUSTOMER_DISCOUNT_OVERRIDE] [nvarchar](2) NULL,
	[VALUED_CUSTOMER_DISCOUNT_OVERRIDE_DESC] [nvarchar](200) NULL,
	[PROPERTY_ON_MORE_THAN] [nvarchar](2) NULL,
	[PROPERTY_ON_MORE_THAN_DESC] [nvarchar](1000) NULL,
	[DWELLING_MOBILE_HOME] [nvarchar](2) NULL,
	[DWELLING_MOBILE_HOME_DESC] [nvarchar](1000) NULL,
	[PROPERTY_USED_WHOLE_PART] [nvarchar](2) NULL,
	[PROPERTY_USED_WHOLE_PART_DESC] [nvarchar](1000) NULL,
	[ANY_PRIOR_LOSSES] [nvarchar](5) NULL,
	[ANY_PRIOR_LOSSES_DESC] [nvarchar](50) NULL,
	[BOAT_WITH_HOMEOWNER] [nchar](1) NULL,
	[NON_WEATHER_CLAIMS] [smallint] NULL,
	[WEATHER_CLAIMS] [smallint] NULL,
 CONSTRAINT [PK_POL_MARINE_CARGO_GEN_INFO_POLICY_ID_POLICY_VERSION_ID_CUSTOMER_ID] PRIMARY KEY NONCLUSTERED 
(
	[CUSTOMER_ID] ASC,
	[POLICY_ID] ASC,
	[POLICY_VERSION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[POL_MARINE_CARGO_GEN_INFO]  WITH NOCHECK ADD  CONSTRAINT [FK_POL_MARINE_CARGO_GEN_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID] FOREIGN KEY([CUSTOMER_ID], [POLICY_ID], [POLICY_VERSION_ID])
REFERENCES [dbo].[POL_CUSTOMER_POLICY_LIST] ([CUSTOMER_ID], [POLICY_ID], [POLICY_VERSION_ID])
GO

ALTER TABLE [dbo].[POL_MARINE_CARGO_GEN_INFO] NOCHECK CONSTRAINT [FK_POL_MARINE_CARGO_GEN_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]
GO


