
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[POL_ACCUMULATION_DETAILS]') AND type in (N'U'))
DROP TABLE [dbo].[POL_ACCUMULATION_DETAILS]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
 /*----------------------------------------------------------      
Proc Name       : [Proc_GetQQVehicleRatingInfo]      
Created by      : Kuldeep Saxena     
Date            : 11-Feb-2012      
Purpose			: To store aCCUMULATION DETAILS AT POLICY LEVEL
Revison History :      
Used In        : EAW
------------------------------------------------------------      
Date     Review By          Comments      
------   ------------       -------------------------

*/ 
CREATE TABLE [dbo].[POL_ACCUMULATION_DETAILS](
	ACCUMULATION_ID int NOT NULL,    
	ACCUMULATION_CODE VARCHAR(20),
	ACC_REF_NO NVARCHAR(20),
	TOTAL_NO_OF_POLICIES INT NULL,
	OWN_RETENTION_LIMIT DECIMAL(25,2) NULL,
	TREATY_CAPACITY_LIMIT DECIMAL(25,2) NULL,
	ACCUMULATION_LIMIT_AVAILABLE DECIMAL(25,2) NULL,
	TOTAL_SUM_INSURED DECIMAL(25,2) NULL,
	FACULTATIVE_RI DECIMAL(25,2) NULL,
	GROSS_RETAINED_SUM_INSURED DECIMAL(25,2) NULL,
	OWN_RETENTION DECIMAL(25,2) NULL,
	QUOTA_SHARE DECIMAL(25,2) NULL,
	FIRST_SURPLUS DECIMAL(25,2) NULL,
	OWN_ABSOLUTE_NET_RETENSTION DECIMAL(25,2) NULL
	
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[POL_ACCUMULATION_DETAILS] ADD CONSTRAINT [PK_POL_ACCUMULATION_DETAILS_ACCUMULATION_ID] PRIMARY KEY
	CLUSTERED
	(
		[ACCUMULATION_ID]	
	)	
GO

