CREATE TYPE [dbo].[TVP_MandateSummary] AS TABLE(
	[MandateId] [int] NOT NULL,
	[AccidentClaimId] [int] NOT NULL,
	[ReserveId] [int] NOT NULL,
	[ClaimID] [int] NOT NULL,
	[ClaimType] [int] NOT NULL,
	[MovementType] [nvarchar](2) NULL,
	[AssignedTo] [int] NULL,
	[InvestigationResult] [int] NULL,
	[Scenario] [nvarchar](max) NULL,
	[Evidence] [nvarchar](max) NULL,
	[RelatedFacts] [nvarchar](max) NULL,
	[COAssessment] [nvarchar](max) NULL,
	[SupervisorAssignto] [int] NULL,
	[ApproveRecommedations] [nvarchar](2) NULL,
	[SupervisorRemarks] [nvarchar](max) NULL,
	[PreMandate] [numeric](18, 2) NULL,
	[MovementMandate] [numeric](18, 2) NULL,
	[CurrentMandate] [numeric](18, 2) NULL,
	[InformSafetytoreviewfindings] [nvarchar](10) NULL,
	[MandateRecordNo] [nvarchar](100) NULL,
	[Createdby] [nvarchar](200) NULL,
	[Createddate] [datetime] NULL,
	[Modifiedby] [nvarchar](200) NULL,
	[Modifieddate] [datetime] NULL,
	[IsActive] [char](1) NULL,
	[PreMandateSP] [numeric](18, 2) NULL,
	[MovementMandateSP] [numeric](18, 2) NULL,
	[CurrentMandateSP] [numeric](18, 2) NULL,
	[PreviousOffers] [numeric](18, 2) NULL,
	[TPCounterOffer] [numeric](18, 2) NULL,
	[DateofNoticetoSafety] [datetime] NULL,
	[InformedInsurer] [datetime] NULL,
	[EZLinkCardNo] [varchar](1) NULL,
	[ODStatus] [varchar](1) NULL,
	[RecoverableFromInsurerBI] [varchar](1) NULL,
	[ProposedLiability][numeric](18, 2) NULL

)
GO