//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAS.Web.Objects.Resources.Masters {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BusCaptain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusCaptain() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCAS.Web.Objects.Resources.Masters.BusCaptain", typeof(BusCaptain).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Captain Code.
        /// </summary>
        public static string BusCaptainCode {
            get {
                return ResourceManager.GetString("BusCaptainCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Captain Listing.
        /// </summary>
        public static string BusCaptainListing {
            get {
                return ResourceManager.GetString("BusCaptainListing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Captain Listing Details.
        /// </summary>
        public static string BusCaptainListingDetails {
            get {
                return ResourceManager.GetString("BusCaptainListingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Captain Listing Master.
        /// </summary>
        public static string BusCaptainListingMaster {
            get {
                return ResourceManager.GetString("BusCaptainListingMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string BusCaptainName {
            get {
                return ResourceManager.GetString("BusCaptainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Captain Upload.
        /// </summary>
        public static string BusCaptainUpload {
            get {
                return ResourceManager.GetString("BusCaptainUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Joined.
        /// </summary>
        public static string DateJoined {
            get {
                return ResourceManager.GetString("DateJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Resigned.
        /// </summary>
        public static string DateResigned {
            get {
                return ResourceManager.GetString("DateResigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquiry on Bus Captain Listing Master.
        /// </summary>
        public static string EnquiryonBusCaptainListingMaster {
            get {
                return ResourceManager.GetString("EnquiryonBusCaptainListingMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Captain Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NRIC/Passport Number.
        /// </summary>
        public static string NRICPassportNo {
            get {
                return ResourceManager.GetString("NRICPassportNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File to Upload.
        /// </summary>
        public static string SelectFiletoUpload {
            get {
                return ResourceManager.GetString("SelectFiletoUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Admin.
        /// </summary>
        public static string SystemAdmin {
            get {
                return ResourceManager.GetString("SystemAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload File.
        /// </summary>
        public static string UploadFile {
            get {
                return ResourceManager.GetString("UploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload file is required..
        /// </summary>
        public static string Uploadfileisrequired {
            get {
                return ResourceManager.GetString("Uploadfileisrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Main Menu.
        /// </summary>
        public static string UploadMainMenu {
            get {
                return ResourceManager.GetString("UploadMainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Captain Listing Details.
        /// </summary>
        public static string UploadMainMenu_ {
            get {
                return ResourceManager.GetString("UploadMainMenu_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Listing Upload.
        /// </summary>
        public static string VehicleListingUpload {
            get {
                return ResourceManager.GetString("VehicleListingUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
