
/****** Object:  Table [dbo].[APP_DWELLING_SECTION_COVERAGES]    Script Date: 02/11/2012 16:31:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_DWELLING_SECTION_COVERAGES](
	[CUSTOMER_ID] [int] NOT NULL,
	[APP_ID] [int] NOT NULL,
	[APP_VERSION_ID] [smallint] NOT NULL,
	[DWELLING_ID] [smallint] NOT NULL,
	[COVERAGE_ID] [int] NOT NULL,
	[COVERAGE_CODE_ID] [int] NOT NULL,
	[LIMIT_OVERRIDE] [nvarchar](5) NULL,
	[LIMIT_1] [decimal](18, 0) NULL,
	[LIMIT_1_TYPE] [nvarchar](5) NULL,
	[LIMIT_2] [decimal](18, 0) NULL,
	[LIMIT_2_TYPE] [nvarchar](5) NULL,
	[DEDUCT_OVERRIDE] [nchar](1) NULL,
	[DEDUCTIBLE_1] [decimal](18, 0) NULL,
	[DEDUCTIBLE_1_TYPE] [nvarchar](5) NULL,
	[DEDUCTIBLE_2] [decimal](18, 0) NULL,
	[DEDUCTIBLE_2_TYPE] [nvarchar](5) NULL,
	[WRITTEN_PREMIUM] [decimal](18, 0) NULL,
	[FULL_TERM_PREMIUM] [decimal](18, 0) NULL,
	[IS_SYSTEM_COVERAGE] [nchar](1) NULL,
	[COVERAGE_TYPE] [nchar](10) NULL,
	[LIMIT1_AMOUNT_TEXT] [nvarchar](100) NULL,
	[LIMIT2_AMOUNT_TEXT] [nvarchar](100) NULL,
	[DEDUCTIBLE1_AMOUNT_TEXT] [nvarchar](100) NULL,
	[DEDUCTIBLE2_AMOUNT_TEXT] [nvarchar](100) NULL,
	[LIMIT_ID] [int] NULL,
	[DEDUC_ID] [int] NULL,
	[DEDUCTIBLE] [decimal](18, 0) NULL,
	[DEDUCTIBLE_TEXT] [nvarchar](100) NULL,
	[ADDDEDUCTIBLE_ID] [int] NULL,
 CONSTRAINT [PK_APP_DWELLING_SECTION_COVERAGES_CUSTOMER_ID_APP_ID_VERSION_ID_COVERAGE_ID] PRIMARY KEY NONCLUSTERED 
(
	[CUSTOMER_ID] ASC,
	[APP_ID] ASC,
	[APP_VERSION_ID] ASC,
	[DWELLING_ID] ASC,
	[COVERAGE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO

--ALTER TABLE [dbo].[APP_DWELLING_SECTION_COVERAGES]  WITH CHECK ADD  CONSTRAINT [FK_APP_DWELLING_SECTION_COVERAGES_CUSTOMER_ID_APP_ID_VERSION_ID] FOREIGN KEY([CUSTOMER_ID], [APP_ID], [APP_VERSION_ID], [DWELLING_ID])
--REFERENCES [dbo].[APP_DWELLINGS_INFO] ([CUSTOMER_ID], [APP_ID], [APP_VERSION_ID], [DWELLING_ID])
--GO

--ALTER TABLE [dbo].[APP_DWELLING_SECTION_COVERAGES] CHECK CONSTRAINT [FK_APP_DWELLING_SECTION_COVERAGES_CUSTOMER_ID_APP_ID_VERSION_ID]
--GO

--ALTER TABLE [dbo].[APP_DWELLING_SECTION_COVERAGES]  WITH CHECK ADD  CONSTRAINT [FK_APP_DWELLING_SECTION_COVERAGES_MNT_COVERAGE_COVERAGE_CODE_ID_COV_ID] FOREIGN KEY([COVERAGE_CODE_ID])
--REFERENCES [dbo].[MNT_COVERAGE] ([COV_ID])
--GO

--ALTER TABLE [dbo].[APP_DWELLING_SECTION_COVERAGES] CHECK CONSTRAINT [FK_APP_DWELLING_SECTION_COVERAGES_MNT_COVERAGE_COVERAGE_CODE_ID_COV_ID]
--GO

--ALTER TABLE [dbo].[APP_DWELLING_SECTION_COVERAGES] ADD  CONSTRAINT [DF_APP_DWELLING_SECTION_COVERAGES_WRITTEN_PREMIUM]  DEFAULT ((0)) FOR [WRITTEN_PREMIUM]
--GO

--ALTER TABLE [dbo].[APP_DWELLING_SECTION_COVERAGES] ADD  CONSTRAINT [DF_APP_DWELLING_SECTION_COVERAGES_FULL_TERM_PREMIUM]  DEFAULT ((0)) FOR [FULL_TERM_PREMIUM]
--GO


