 IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[INSERT_POL_BILLING_DETAILS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].INSERT_POL_BILLING_DETAILS
GO

SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON
GO  
       
-- =============================================    
-- Author:  Kuldeep Saxena   
-- Create date: 08-feb-2012   
-- Description: -    
-- =============================================    
    
CREATE PROCEDURE dbo.INSERT_POL_BILLING_DETAILS   
 @CUSTOMER_ID   INT,                     -- ID OF CUSTOMER WHOSE  POLICY PREMIUM BILL INSTALLMENT WILL BE POSTED                             
 @POLICY_ID  INT,                        -- POLICY IDENTIFICATION NUMBER                            
 @POLICY_VERSION_ID SMALLINT,  -- POLICY VERSION IDENTIFICATION NUMBER   
 @GROSS_PREMIUM DECIMAL(25,2)=NULL,
 @OTHER_CHARGES DECIMAL(25,2)=NULL,  
 @TOTAL_BEFORE_GST DECIMAL(25,2)=NULL,
 @GST DECIMAL(25,2)=NULL,        
 @TOTAL_AFTER_GST DECIMAL(25,2)=NULL,            
 @GROSS_COMMISSION DECIMAL(25,2)=NULL,
 @GST_ON_COMMISSION DECIMAL(25,2)=NULL,
 @TOTAL_COMM_AFTER_GST DECIMAL(25,2)=NULL,
 @NET_AMOUNT DECIMAL(25,2)=NULL,
 @CREATED_BY INT,
 @CREATED_DATETIME DATETIME
AS    
    
BEGIN    
DELETE FROM POL_BILLING_DETAILS where CUSTOMER_ID=@CUSTOMER_ID and POLICY_ID=@POLICY_ID and POLICY_VERSION_ID=@POLICY_VERSION_ID 
INSERT INTO POL_BILLING_DETAILS    
  (    
 CUSTOMER_ID,
 POLICY_ID,
 POLICY_VERSION_ID,
 GROSS_PREMIUM,
 OTHER_CHARGES,
 TOTAL_BEFORE_GST,
 GST,
 TOTAL_AFTER_GST,
 GROSS_COMMISSION,
 GST_ON_COMMISSION,
 TOTAL_COMM_AFTER_GST,
 NET_AMOUNT,
 CREATED_BY,    
 CREATED_DATETIME    
   )    
    
VALUES     
 (    
  @CUSTOMER_ID,
 @POLICY_ID,
 @POLICY_VERSION_ID,
 @GROSS_PREMIUM,
 @OTHER_CHARGES,
 @TOTAL_BEFORE_GST,
 @GST,
 @TOTAL_AFTER_GST,
 @GROSS_COMMISSION,
 @GST_ON_COMMISSION,
 @TOTAL_COMM_AFTER_GST,
 @NET_AMOUNT,
 @CREATED_BY,
 @CREATED_DATETIME

 )    
  
END    
Go
----