  
/*----------------------------------------------------------                                            
Proc Name        : dbo.Poc_GetRiskEffectiveDate  
Created by       : Lalit chauhan        
Date             : 22/10/2010                                          
Purpose          :         
Used In          : Ebix Advantage                                        
------------------------------------------------------------                                            
Date     Review By          Comments              
  
  
Poc_GetRiskEffectiveDate 2156,506,3  
------   ------------       -------------------------      
sp_find 'Poc_GetRiskEffectiveDate',p  
DROP PROC Poc_GetRiskEffectiveDate 28070,134,4  
EXEC Poc_GetRiskEffectiveDate 28070,235,3,'10/01/2011'    
*/  
ALTER PROC [dbo].[Poc_GetRiskEffectiveDate] --28718,83,2  
(  
@CUSTOMER_ID INT,  
@POLICY_ID INT,  
@POLICY_VERSION_ID INT  
)  
AS  
BEGIN   
 DECLARE @POLICY_LOB INT,@CURRENT_TERM INT  
  SELECT @POLICY_LOB = POLICY_LOB,@CURRENT_TERM  = CURRENT_TERM FROM POL_CUSTOMER_POLICY_LIST WITH(NOLOCK)  
  WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID   
  AND POLICY_VERSION_ID = @POLICY_VERSION_ID  
  CREATE TABLE #tempRISK_DETAILS (ID INT identity (1,1),WRITTEN_PREMIUM DECIMAL(25,2),CUSTOMER_ID INT,POLICY_ID INT,  
  POLICY_VERSION_ID INT,RISK_ID INT  
  )  
    
      
  
    
  IF(@POLICY_LOB IN (9,26))  
  BEGIN   
   INSERT INTO #tempRISK_DETAILS  
   SELECT a.*  
   --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
   FROM (SELECT SUM(WRITTEN_PREMIUM) WRITTEN_PREMIUM  
   ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
   ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.PERIL_ID PERIL_ID FROM POL_PERILS P WITH(NOLOCK)  
   JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
   P.CUSTOMER_ID = c.CUSTOMER_ID and   
   P.POLICY_ID = c.POLICY_ID and  
   P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
   P.PERIL_ID = c.RISK_ID  
   WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
   AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
   FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
   WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
   AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
    AND p.IS_ACTIVE = 'Y'  
   GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.PERIL_ID)a  
  END  
  IF(@POLICY_LOB IN (13))  
  BEGIN   
   INSERT INTO #tempRISK_DETAILS  
   SELECT a.*  
   --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
   FROM (SELECT SUM(WRITTEN_PREMIUM) WRITTEN_PREMIUM  
   ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
   ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.MARITIME_ID PERIL_ID   
   FROM POL_MARITIME P WITH(NOLOCK)  
   JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
   P.CUSTOMER_ID = c.CUSTOMER_ID and   
   P.POLICY_ID = c.POLICY_ID and  
   P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
   P.MARITIME_ID = c.RISK_ID  
   WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
   AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
   FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
   WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
   AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
    AND p.IS_ACTIVE = 'Y'  
   GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.MARITIME_ID)a  
  END  
  IF(@POLICY_LOB IN (17,18,28,29,31,30,36,38))  
  BEGIN   
   INSERT INTO #tempRISK_DETAILS  
   SELECT a.*  
   --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
   FROM (SELECT SUM(WRITTEN_PREMIUM) WRITTEN_PREMIUM  
   ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
   ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.VEHICLE_ID PERIL_ID   
   FROM POL_CIVIL_TRANSPORT_VEHICLES P WITH(NOLOCK)  
   JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
   P.CUSTOMER_ID = c.CUSTOMER_ID and   
   P.POLICY_ID = c.POLICY_ID and  
   P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
   P.VEHICLE_ID = c.RISK_ID  
   WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
   AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
   FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
   WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
   AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
    AND p.IS_ACTIVE = 'Y'  
   GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.VEHICLE_ID)a  
  END  
  
  IF(@POLICY_LOB IN (38))  
  BEGIN   
   INSERT INTO #tempRISK_DETAILS  
   SELECT a.*  
   --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
   FROM (SELECT SUM(pol.RECEIVED_PRMIUM) WRITTEN_PREMIUM  
   ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
   ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.VEHICLE_ID PERIL_ID   
   FROM POL_VEHICLES P WITH(NOLOCK)  
   LEFT OUTER JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
   P.CUSTOMER_ID = c.CUSTOMER_ID and   
   P.POLICY_ID = c.POLICY_ID and  
   P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
   P.VEHICLE_ID = c.RISK_ID  
   LEFT OUTER JOIN POL_CUSTOMER_POLICY_LIST POL ON
   P.CUSTOMER_ID = POL.CUSTOMER_ID and   
   P.POLICY_ID = POL.POLICY_ID and  
   P.POLICY_VERSION_ID = POL.POLICY_VERSION_ID
   WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
   AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
   FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
   WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
   AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
    AND p.IS_ACTIVE = 'Y'  
   GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.VEHICLE_ID)a  
  END  
  
  
  IF(@POLICY_LOB IN (20,23))  
  BEGIN   
   INSERT INTO #tempRISK_DETAILS  
   SELECT a.*  
   --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
   FROM (SELECT SUM(WRITTEN_PREMIUM) WRITTEN_PREMIUM  
   ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
   ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.COMMODITY_ID PERIL_ID   
   FROM POL_COMMODITY_INFO P WITH(NOLOCK)  
   JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
   P.CUSTOMER_ID = c.CUSTOMER_ID and   
   P.POLICY_ID = c.POLICY_ID and  
   P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
   P.COMMODITY_ID = c.RISK_ID  
   WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
   AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
   FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
   WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
   AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
    AND p.IS_ACTIVE = 'Y'  
   GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.COMMODITY_ID)a  
  END  
  IF(@POLICY_LOB IN (15,21,33,34))  
  BEGIN   
   INSERT INTO #tempRISK_DETAILS  
   SELECT a.*  
   --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
   FROM (SELECT SUM(WRITTEN_PREMIUM) WRITTEN_PREMIUM  
   ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
   ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.PERSONAL_INFO_ID PERIL_ID   
   FROM POL_PERSONAL_ACCIDENT_INFO P WITH(NOLOCK)  
   JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
   P.CUSTOMER_ID = c.CUSTOMER_ID and   
   P.POLICY_ID = c.POLICY_ID and  
   P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
   P.PERSONAL_INFO_ID = c.RISK_ID  
   WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
   AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
   FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
   WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
   AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
    AND p.IS_ACTIVE = 'Y'  
   GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.PERSONAL_INFO_ID)a  
  END  
  IF(@POLICY_LOB IN (22))  
  BEGIN   
   INSERT INTO #tempRISK_DETAILS  
   SELECT a.*  
   --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
   FROM (SELECT SUM(WRITTEN_PREMIUM) WRITTEN_PREMIUM  
   ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
   ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.PERSONAL_ACCIDENT_ID PERIL_ID   
   FROM POL_PASSENGERS_PERSONAL_ACCIDENT_INFO P WITH(NOLOCK)  
   JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
   P.CUSTOMER_ID = c.CUSTOMER_ID and   
   P.POLICY_ID = c.POLICY_ID and  
   P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
   P.PERSONAL_ACCIDENT_ID = c.RISK_ID  
   WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
   AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
   FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
   WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
   AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
    AND p.IS_ACTIVE = 'Y'  
   GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.PERSONAL_ACCIDENT_ID)a  
  END  
  IF(@POLICY_LOB IN (10,11,12,14,16,19,25,27,32))  
  BEGIN   
    INSERT INTO #tempRISK_DETAILS  
    SELECT a.*  
    --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
    FROM (SELECT SUM(WRITTEN_PREMIUM) WRITTEN_PREMIUM  
    ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
    ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.PRODUCT_RISK_ID PERIL_ID   
    FROM POL_PRODUCT_LOCATION_INFO P WITH(NOLOCK)  
    JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
    P.CUSTOMER_ID = c.CUSTOMER_ID and   
    P.POLICY_ID = c.POLICY_ID and  
    P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
    P.PRODUCT_RISK_ID = c.RISK_ID  
    WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
    AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
    FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
    WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
    AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
     AND p.IS_ACTIVE = 'Y'  
    GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.PRODUCT_RISK_ID)a  
   END  
  IF(@POLICY_LOB IN (35,37))  
  BEGIN   
    INSERT INTO #tempRISK_DETAILS  
    SELECT a.*  
    --PP.EFFECTIVE_DATETIME,ISNULL(PP.[EXPIRY_DATE],PL.POLICY_EXPIRATION_DATE) [EXPIRY_DATE]  
    FROM (SELECT SUM(WRITTEN_PREMIUM) WRITTEN_PREMIUM  
    ,p.CUSTOMER_ID CUSTOMER_ID,p.POLICY_ID POLICY_ID  
    ,p.POLICY_VERSION_ID POLICY_VERSION_ID, p.PENHOR_RURAL_ID PERIL_ID   
    FROM POL_PENHOR_RURAL_INFO P WITH(NOLOCK)  
    JOIN POL_PRODUCT_COVERAGES C WITH(NOLOCK) ON  
    P.CUSTOMER_ID = c.CUSTOMER_ID and   
    P.POLICY_ID = c.POLICY_ID and  
    P.POLICY_VERSION_ID = c.POLICY_VERSION_ID AND  
    P.PENHOR_RURAL_ID = c.RISK_ID  
    WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID  
    AND P.POLICY_VERSION_ID in (SELECT POLICY_VERSION_ID  
    FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
    WHERE PL.CUSTOMER_ID = P.CUSTOMER_ID AND PL.POLICY_ID = P.POLICY_ID  
    AND PL.CURRENT_TERM = @CURRENT_TERM and POLICY_VERSION_ID < @POLICY_VERSION_ID)  
     AND p.IS_ACTIVE = 'Y'  
    GROUP BY p.CUSTOMER_ID,p.POLICY_ID,p.POLICY_VERSION_ID,p.PENHOR_RURAL_ID)a  
  END   
  
 DECLARE  @ID  INT = 1,@PREV_VERSION INT ,@CURRENT_VERSION INT  
 --SELECT * FROM #tempRISK_DETAILS  
   
 WHILE 1=1  
 BEGIN   
  IF NOT EXISTS(SELECT * FROM #tempRISK_DETAILS WHERE ID = @ID)  
   BREAK  
  SELECT  @PREV_VERSION = P.POLICY_VERSION_ID ,@CURRENT_VERSION = NEW_POLICY_VERSION_ID   
  FROM POL_POLICY_PROCESS P  WITH(NOLOCK) JOIN  
  #tempRISK_DETAILS A WITH(NOLOCK)   
   ON A.CUSTOMER_ID = P.CUSTOMER_ID aND   
  A.POLICY_ID = P.POLICY_ID AND   
  A.POLICY_VERSION_ID = P.NEW_POLICY_VERSION_ID  
  WHERE A.ID = @ID  
  --SELECT @PREV_VERSION ,@CURRENT_VERSION  
    
  ---get policy risk difference   
  if(@PREV_VERSION <> @CURRENT_VERSION )  
   BEGIN   
     UPDATE C SET C.WRITTEN_PREMIUM =  changePremium  FROM  #tempRISK_DETAILS C,  
     (select POLICY_VERSION_ID,RISK_ID,SUM(CurrentPremium) as CurrentPremium ,SUM(PremviousPreium) as PreviousPreium,  
   SUM(CurrentPremium) - SUM(PremviousPreium) as changePremium  
   from  
   (  
   select a.POLICY_VERSION_ID,  
   a.RISK_ID,sum(isnull(a.WRITTEN_PREMIUM,0)) as CurrentPremium , null as PremviousPreium--,  
    from POL_PRODUCT_COVERAGES A WITH(NOLOCK)  
   where a.CUSTOMER_ID=@CUSTOMER_ID and a.POLICY_ID=@POLICY_ID   
   and a.POLICY_VERSION_ID=@CURRENT_VERSION  
     
   group by  
   a.POLICY_VERSION_ID,  
   a.RISK_ID  
  
   union  
  
   select a.POLICY_VERSION_ID + 1 ,  
   a.RISK_ID, null as CurrentPremium,  sum(isnull(a.WRITTEN_PREMIUM,0)) as PremviousPreium  
    from POL_PRODUCT_COVERAGES A WITH(NOLOCK)  
      join POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)   
      ON   
      PL.CUSTOMER_ID = A.CUSTOMER_ID AND   
      PL.POLICY_ID = A.POLICY_ID AND   
      PL.POLICY_VERSION_ID = A.POLICY_VERSION_ID  
   where a.CUSTOMER_ID=@CUSTOMER_ID and a.POLICY_ID=@POLICY_ID   
   and a.POLICY_VERSION_ID=@PREV_VERSION  
      AND PL.CURRENT_TERM = @CURRENT_TERM  
   group by  
   a.POLICY_VERSION_ID,  
   a.RISK_ID  
   ) tmp  
   group by  POLICY_VERSION_ID,RISK_ID)D  
   WHERE C.POLICY_VERSION_ID = D.POLICY_VERSION_ID  
   AND C.RISK_ID = D.RISK_ID  
   AND D.PreviousPreium IS NOT NULL  
    
    
       
  END  
    
    
    
    
    
   
  SELECT @ID = @ID + 1  
    
 END  
   
 --SELECT * FROM #tempRISK_DETAILS  
 DELETE FROM  #tempRISK_DETAILS WHERE ISNULL(WRITTEN_PREMIUM,0) = 0    
 --SELECT * FROM #tempRISK_DETAILS  
   
 SELECT @CUSTOMER_ID CUSTOMER_ID,@POLICY_ID POLICY_ID,b.POLICY_VERSION_ID ,b.RISK_ID,  
 b.WRITTEN_PREMIUM,PP.EFFECTIVE_DATETIME EFFECTIVE_DATETIME,isnull(PP.EXPIRY_DATE,PL.POLICY_EXPIRATION_DATE)   
 POL_EXPIRY_DATE FROM  #tempRISK_DETAILS  b WITH(NOLOCK)  
 JOIN POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  ON   
 PL.CUSTOMER_ID = @CUSTOMER_ID AND   
 PL.POLICY_ID  = @POLICY_ID AND   
 PL.POLICY_VERSION_ID = b.POLICY_VERSION_ID  
 JOIN POL_POLICY_PROCESS PP ON  PP.CUSTOMER_ID  = PL.CUSTOMER_ID   
 AND PP.POLICY_ID  = PL.POLICY_ID  AND   
 PP.NEW_POLICY_VERSION_ID =PL.POLICY_VERSION_ID  
   
  
   
-- SELECT * FROM #tempRISK_DETAILS  
   
 drop table #tempRISK_DETAILS  
   
END  
--GO  
--EXEC Poc_GetRiskEffectiveDate 28070,235,3  
  
  