IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_POL_MARINE_CARGO_VOYAGE_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]') AND parent_object_id = OBJECT_ID(N'[dbo].[POL_MARINE_CARGO_VOYAGE_INFO]'))
ALTER TABLE [dbo].[POL_MARINE_CARGO_VOYAGE_INFO] DROP CONSTRAINT [FK_POL_MARINE_CARGO_VOYAGE_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_POL_MARINE_CARGO_VOYAGE_INFO_CO_APPLICANT_ID]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[POL_MARINE_CARGO_VOYAGE_INFO] DROP CONSTRAINT [DF_POL_MARINE_CARGO_VOYAGE_INFO_CO_APPLICANT_ID]
END

GO

/****** Object:  Table [dbo].[POL_MARINE_CARGO_VOYAGE_INFO]    Script Date: 03/19/2012 13:18:34 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[POL_MARINE_CARGO_VOYAGE_INFO]') AND type in (N'U'))
DROP TABLE [dbo].[POL_MARINE_CARGO_VOYAGE_INFO]
GO

USE [EBX-ADV-DEV-SINGAPORE]
GO

/****** Object:  Table [dbo].[POL_MARINE_CARGO_VOYAGE_INFO]    Script Date: 03/19/2012 13:18:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[POL_MARINE_CARGO_VOYAGE_INFO](
	[CUSTOMER_ID] [int] NOT NULL,
	[POLICY_ID] [int] NOT NULL,
	[POLICY_VERSION_ID] [smallint] NOT NULL,
	[VOYAGE_ID] [int] NOT NULL,
	[VOYAGE_NUMBER] [numeric](10, 0) NULL,
	[IS_ACTIVE] [nvarchar](2) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[CO_APPLICANT_ID] [int] NULL,
	[ORIGINAL_VERSION_ID] [int] NULL

 CONSTRAINT [PK_POL_MARINE_CARGO_VOYAGE_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID_VOYAGE_ID] PRIMARY KEY NONCLUSTERED 
(
	[CUSTOMER_ID] ASC,
	[POLICY_ID] ASC,
	[POLICY_VERSION_ID] ASC,
	[VOYAGE_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[POL_MARINE_CARGO_VOYAGE_INFO]  WITH NOCHECK ADD  CONSTRAINT [FK_POL_MARINE_CARGO_VOYAGE_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID] FOREIGN KEY([CUSTOMER_ID], [POLICY_ID], [POLICY_VERSION_ID])
REFERENCES [dbo].[POL_CUSTOMER_POLICY_LIST] ([CUSTOMER_ID], [POLICY_ID], [POLICY_VERSION_ID])
GO

ALTER TABLE [dbo].[POL_MARINE_CARGO_VOYAGE_INFO] NOCHECK CONSTRAINT [FK_POL_MARINE_CARGO_VOYAGE_INFO_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]
GO

ALTER TABLE [dbo].[POL_MARINE_CARGO_VOYAGE_INFO] ADD  CONSTRAINT [DF_POL_MARINE_CARGO_VOYAGE_INFO_CO_APPLICANT_ID]  DEFAULT ((0)) FOR [CO_APPLICANT_ID]
GO


