ALTER Procedure PROC_GET_POL_BILLING_DETAILS
(@CUSTOMER_ID   INT,                     -- ID OF CUSTOMER WHOSE  POLICY PREMIUM BILL INSTALLMENT WILL BE POSTED                               
 @POLICY_ID  INT,                        -- POLICY IDENTIFICATION NUMBER                              
 @POLICY_VERSION_ID SMALLINT
 ) as
 begin
 IF EXISTS (SELECT CUSTOMER_ID FROM POL_BILLING_DETAILS where CUSTOMER_ID=@CUSTOMER_ID and POLICY_ID=@POLICY_ID and POLICY_VERSION_ID=@POLICY_VERSION_ID)
 BEGIN
SELECT * FROM POL_BILLING_DETAILS PBD left JOIN QQ_MOTOR_QUOTE_DETAILS QMD ON PBD.CUSTOMER_ID=QMD.CUSTOMER_ID AND PBD.POLICY_ID=QMD.POLICY_ID AND PBD.POLICY_VERSION_ID=QMD.POLICY_VERSION_ID 
 where --PBD.CUSTOMER_ID=28925 and PBD.POLICY_ID=466 and PBD.POLICY_VERSION_ID=1
 PBD.CUSTOMER_ID=@CUSTOMER_ID and PBD.POLICY_ID=@POLICY_ID and PBD.POLICY_VERSION_ID=@POLICY_VERSION_ID
 END

END