

CREATE PROCEDURE PROC_VALIDATE_UNDERWRITER_LIMITS

@CUSTOMER_ID INT,
@POLICY_ID INT,
@POLICY_VERSION_ID INT,
@BASE_CURRENCY INT,
@UNDERWRITER INT,
@RETVAL INT OUTPUT

AS

BEGIN

	DECLARE @LOB INT,
	@BILL_CURRENCY INT,
	--@ROWS INT,
	@CURRENCY_RATE INT,
	@PREMIUM INT,
	@PML INT,
	@MODIFIED_PML INT

	SELECT @LOB=POLICY_LOB, @BILL_CURRENCY=BILLING_CURRENCY, @PREMIUM = RECEIVED_PRMIUM FROM POL_CUSTOMER_POLICY_LIST WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID 
			
	IF(@BASE_CURRENCY='3')-- WHEN BASE CURRENCY IS SINGAPORE DOLLAR
	BEGIN		

		--SELECT @ROWS = COUNT(*) FROM MNT_UNDERWRITING_CLAIM_LIMITS WHERE GETDATE() >= EFFECTIVEDATE AND GETDATE() <= ENDDATE AND LOB_ID = @LOB
		--SELECT @PML = PREMIUM_APPROVAL_LIMIT FROM MNT_UNDERWRITING_CLAIM_LIMITS WHERE LOB_ID=@LOB AND GETDATE() >= EFFECTIVEDATE AND GETDATE() < ENDDATE
		
		SELECT @PML = PREMIUM_APPROVAL_LIMIT FROM MNT_UNDERWRITING_CLAIM_LIMITS WHERE LOB_ID=@LOB AND GETDATE()>= EffectiveDate AND GETDATE() <= EndDate AND USER_ID=@UNDERWRITER
		
		
		IF(@BILL_CURRENCY=3)
		BEGIN
			--SELECT CONVERT(VARCHAR,EffectiveDate,103) AS EFFECTIVE_DATE, CONVERT(VARCHAR, EndDate,103) AS END_DATE, LOB_ID,CONVERT(VARCHAR,GETDATE(),103) AS DATE_TODAY,@PML = PREMIUM_APPROVAL_LIMIT FROM MNT_UNDERWRITING_CLAIM_LIMITS WHERE GETDATE() >= EFFECTIVEDATE AND GETDATE() < ENDDATE AND LOB_ID = @LOB							
			IF(@PREMIUM <= @PML)								
				--RETURN 1 --
				SET @RETVAL = 1						
			ELSE
				--RETURN 2 --
				SET @RETVAL = 2
		END
		ELSE --WHEN BILLING CURRENCY IS NOT EQUAL TO SINGAPORE DOLLAR
		BEGIN
			SELECT TOP 1 @CURRENCY_RATE = RATE FROM MNT_CURRENCY_RATE_MASTER WHERE GETDATE() >= RATE_EFFETIVE_FROM AND GETDATE() <= RATE_EFFETIVE_TO AND CURRENCY_ID=@BILL_CURRENCY			
			SET @MODIFIED_PML = @CURRENCY_RATE * @PML
			
			IF(@PREMIUM <= @MODIFIED_PML)			
				--RETURN 1 
				SET @RETVAL = 1			
			ELSE
				--RETURN 2 
				SET @RETVAL = 2
		END			
	END
END

--DROP PROC PROC_VALIDATE_UNDERWRITER_LIMITS