  
 /*----------------------------------------------------------                    
 Proc Name       : dbo.Proc_GetPolicyPremiumXML          
 Created by      : Lalit Chauhan    
 Date            : May 26, 2010      
 Purpose         : SAVE POLICY TOTAL VALUE FOR ACT_POLICY_INSTALL_PLAN_DATA    
 Revison History :                    
 Used In     : Ebix Advantage                    
------------------------------------------------------------                    
Date     Review By          Comments                    
------   ------------       -------------------------    
Drop Proc Proc_UpdateInstall_Plan_Data    
    
*/    
Create Proc [dbo].[Proc_UpdateInstall_Plan_Data]     
(    
 @CUSTOMER_ID   INT,                     -- ID OF CUSTOMER WHOSE  POLICY PREMIUM BILL INSTALLMENT WILL BE POSTED             
 @POLICY_ID  INT,                        -- POLICY IDENTIFICATION NUMBER            
 @POLICY_VERSION_ID SMALLINT,            -- POLICY VERSION IDENTIFICATION NUMBER    
 @TOTAL_PREMIUM DECIMAL(25,2),           -- POLICY PREMIUM AMOUNT        
 @TOTAL_INTEREST_AMOUNT DECIMAL(25,2),   -- POLICY INTEREST AMOUNT        
 @TOTAL_FEES DECIMAL(25,2),              -- POLICY FEES        
 @TOTAL_TAXES DECIMAL(25,2),             -- POLICY TAXES        
 @TOTAL_AMOUNT DECIMAL(25,2),            -- POLICY TAXES     
 @PLAN_ID INT,              -- PLAN_ID    
 @MODIFIED_BY INT,    
 @LAST_UPDATED_DATETIME DATETIME,  
 @TOTAL_CHANGE_INFORCE_PRM DECIMAL(25,2),               
 @TOTAL_TRAN_PREMIUM decimal(25,2),  
 @TOTAL_TRAN_INTEREST_AMOUNT DECIMAL(25,2),  
 @TOTAL_TRAN_FEES DECIMAL(25,2),  
 @TOTAL_TRAN_TAXES DECIMAL(25,2),  
 @TOTAL_TRAN_AMOUNT DECIMAL(25,2),  
 @TOTAL_STATE_FEES DECIMAL(25,2),  
 @TOTAL_TRAN_STATE_FEES DECIMAL(25,2),  
 --Added by Kuldeep for tfs 3408 on 8-feb-2012
 @TOTAL_AFTER_GST DECIMAL(25,2)=NULL,            
 @TOTAL_BEFORE_GST DECIMAL(25,2)=NULL,
 @GROSS_COMMISSION DECIMAL(25,2)=NULL,
 @GST_ON_COMMISSION DECIMAL(25,2)=NULL,
 @TOTAL_COMM_AFTER_GST DECIMAL(25,2)=NULL
 --@TRAN_TYPE  
)AS    
BEGIN    
DECLARE     
  @PLAN_DESCRIPTION NVARCHAR(150),            
  @PLAN_TYPE  NCHAR(50),          
  @NO_OF_PAYMENTS  SMALLINT,          
  @MONTHS_BETWEEN  SMALLINT,          
  @PERCENT_BREAKDOWN1  DECIMAL(7,4),          
  @PERCENT_BREAKDOWN2  DECIMAL(7,4),          
  @PERCENT_BREAKDOWN3  DECIMAL(7,4),           
  @PERCENT_BREAKDOWN4  DECIMAL(7,4),          
  @PERCENT_BREAKDOWN5  DECIMAL(7,4),           
  @PERCENT_BREAKDOWN6  DECIMAL(7,4),          
  @PERCENT_BREAKDOWN7  DECIMAL(7,4),          
  @PERCENT_BREAKDOWN8  DECIMAL(7,4),          
  @PERCENT_BREAKDOWN9  DECIMAL(7,4),          
  @PERCENT_BREAKDOWN10 DECIMAL(7,4),          
  @PERCENT_BREAKDOWN11 DECIMAL(7,4),          
  @PERCENT_BREAKDOWN12 DECIMAL(7,4),          
  @MODE_OF_PAYMENT INT ,          
  @MODE_OF_DOWN_PAYMENT INT,    
  @IS_ACTIVE_PLAN nchar(1),    
  @INSTALLMENTS_IN_DOWN_PAYMENT INT    
    
   SELECT        
   @PLAN_DESCRIPTION=PLAND.PLAN_DESCRIPTION,                                      --select selected PLAN description from ACT_INSTALL_PLAN_DETAIL         
   @PLAN_TYPE=PLAND.PLAN_TYPE,             --select PLAN Type        
   @NO_OF_PAYMENTS=PLAND.NO_OF_PAYMENTS,                                          --select No of Payment         
   @MONTHS_BETWEEN =PLAND.MONTHS_BETWEEN,          
   @PERCENT_BREAKDOWN1 =PLAND.PERCENT_BREAKDOWN1,          
   @PERCENT_BREAKDOWN2=PLAND.PERCENT_BREAKDOWN2,          
   @PERCENT_BREAKDOWN3=PLAND.PERCENT_BREAKDOWN3,          
   @PERCENT_BREAKDOWN4=PLAND.PERCENT_BREAKDOWN4,          
   @PERCENT_BREAKDOWN5=PLAND.PERCENT_BREAKDOWN5,          
   @PERCENT_BREAKDOWN6=PLAND.PERCENT_BREAKDOWN6,          
   @PERCENT_BREAKDOWN7=PLAND.PERCENT_BREAKDOWN7,          
   @PERCENT_BREAKDOWN8=PLAND.PERCENT_BREAKDOWN8,          
   @PERCENT_BREAKDOWN9=PLAND.PERCENT_BREAKDOWN9,          
   @PERCENT_BREAKDOWN10=PLAND.PERCENT_BREAKDOWN10,          
   @PERCENT_BREAKDOWN11=PLAND.PERCENT_BREAKDOWN11,          
   @PERCENT_BREAKDOWN12=PLAND.PERCENT_BREAKDOWN12,           
   @MODE_OF_PAYMENT=PLAND.PLAN_PAYMENT_MODE,          
   @IS_ACTIVE_PLAN=PLAND.IS_ACTIVE,          
   @INSTALLMENTS_IN_DOWN_PAYMENT=PLAND.NO_INS_DOWNPAY            
   FROM ACT_INSTALL_PLAN_DETAIL PLAND WITH(NOLOCK)       
    WHERE IDEN_PLAN_ID=@PLAN_ID      
    IF(@@ERROR<>0)    
    RETURN -1    
        
 UPDATE ACT_POLICY_INSTALL_PLAN_DATA SET          
        
    PLAN_DESCRIPTION=@PLAN_DESCRIPTION,    
    PLAN_TYPE=@PLAN_TYPE,          
    NO_OF_PAYMENTS=@NO_OF_PAYMENTS,    
    MONTHS_BETWEEN=@MONTHS_BETWEEN,    
    PERCENT_BREAKDOWN1=@PERCENT_BREAKDOWN1,          
    PERCENT_BREAKDOWN2=@PERCENT_BREAKDOWN2,    
    PERCENT_BREAKDOWN3=@PERCENT_BREAKDOWN3,    
    PERCENT_BREAKDOWN4=@PERCENT_BREAKDOWN4,          
    PERCENT_BREAKDOWN5=@PERCENT_BREAKDOWN5,    
    PERCENT_BREAKDOWN6=@PERCENT_BREAKDOWN6,    
    PERCENT_BREAKDOWN7=PERCENT_BREAKDOWN7,          
    PERCENT_BREAKDOWN8=PERCENT_BREAKDOWN8,    
    PERCENT_BREAKDOWN9=@PERCENT_BREAKDOWN9,    
    PERCENT_BREAKDOWN10=@PERCENT_BREAKDOWN10,          
    PERCENT_BREAKDOWN11=@PERCENT_BREAKDOWN11,    
    PERCENT_BREAKDOWN12=@PERCENT_BREAKDOWN12,           
    INSTALLMENTS_IN_DOWN_PAYMENT=@INSTALLMENTS_IN_DOWN_PAYMENT,    
    MODE_OF_PAYMENT=@MODE_OF_PAYMENT,              
    IS_ACTIVE_PLAN=@IS_ACTIVE_PLAN,    
    TOTAL_PREMIUM=@TOTAL_PREMIUM,    
    TOTAL_INTEREST_AMOUNT=@TOTAL_INTEREST_AMOUNT,          
    TOTAL_FEES=@TOTAL_FEES,    
    TOTAL_TAXES=@TOTAL_TAXES,    
    TOTAL_AMOUNT=@TOTAL_AMOUNT,    
    MODIFIED_BY=@MODIFIED_BY,    
    LAST_UPDATED_DATETIME = @LAST_UPDATED_DATETIME,  
    TOTAL_CHANGE_INFORCE_PRM = @TOTAL_CHANGE_INFORCE_PRM,  
    TOTAL_TRAN_PREMIUM = @TOTAL_TRAN_PREMIUM,  
    TOTAL_TRAN_INTEREST_AMOUNT = @TOTAL_TRAN_INTEREST_AMOUNT,  
    TOTAL_TRAN_FEES = @TOTAL_TRAN_FEES,  
    TOTAL_TRAN_TAXES = @TOTAL_TRAN_TAXES,  
    TOTAL_TRAN_AMOUNT = @TOTAL_TRAN_AMOUNT,  
    TOTAL_STATE_FEES = @TOTAL_STATE_FEES,  
    TOTAL_TRAN_STATE_FEES = @TOTAL_TRAN_STATE_FEES  
        
 WHERE CUSTOMER_ID = @CUSTOMER_ID AND  POLICY_ID = @POLICY_ID AND  POLICY_VERSION_ID = @POLICY_VERSION_ID        
    IF(@@ERROR<>0)    
    RETURN -1    
   
 EXEC Proc_Update_POL_BILLING_DETAILS @CUSTOMER_ID,@POLICY_ID,@POLICY_VERSION_ID,@TOTAL_PREMIUM,@TOTAL_INTEREST_AMOUNT,@TOTAL_BEFORE_GST,@TOTAL_TAXES,@TOTAL_AFTER_GST,@GROSS_COMMISSION,@GST_ON_COMMISSION,@TOTAL_COMM_AFTER_GST,@TOTAL_AMOUNT,@MODIFIED_BY,@LAST_UPDATED_DATETIME
     
END  