--drop Proc PROC_GET_INSTALLMENT_DETAILS

CREATE PROCEDURE PROC_GET_INSTALLMENT_DETAILS
(      
@CUSTOMER_ID INT,      
@POLICY_ID INT,      
@POLICY_VERSION_ID SMALLINT
)      
AS       
BEGIN      
--Declare @Payment_Mode varchar(20)
--SELECT @Payment_Mode=LOOKUP_VALUE_DESC FROM MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID=(Select PAYMENT_MODE from ACT_POLICY_INSTALLMENT_DETAILS WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID AND POLICY_VERSION_ID=@POLICY_VERSION_ID)
SELECT 
INSTALLMENT_NO as 'Install #',
CONVERT(VARCHAR,INSTALLMENT_EFFECTIVE_DATE,103) 'Installment Effective Date',
CONVERT(VARCHAR,INSTALLMENT_EXPIRE_DATE,103) as 'Installment Due Date',
CONVERT(VARCHAR,RECEIVED_DATE,103) as 'Installment Processing Date',
LK.LOOKUP_VALUE_DESC as 'Payment Mode',
RELEASED_STATUS as ' Processed',
TOTAL as 'Amount',
(TOTAL -RECEIVED_AMOUNT) AS 'Balance Amount' 
FROM ACT_POLICY_INSTALLMENT_DETAILS inner join MNT_LOOKUP_VALUES lk on lk.LOOKUP_UNIQUE_ID=PAYMENT_MODE WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID AND POLICY_VERSION_ID=@POLICY_VERSION_ID
END