 IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROC_INSERT_POL_ACCUMULATION_DETAILS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[PROC_INSERT_POL_ACCUMULATION_DETAILS]
GO

SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON
GO  
       
-- =============================================    
-- Author:  Kuldeep Saxena   
-- Create date: 11-feb-2012   
-- Description: -    
-- =============================================    
    
CREATE PROCEDURE dbo.PROC_INSERT_POL_ACCUMULATION_DETAILS   
(
	 @ACCUMULATION_ID int output,
	@ACCUMULATION_CODE VARCHAR(20),
	@ACC_REF_NO NVARCHAR(20),
	@TOTAL_NO_OF_POLICIES INT=0,
	@OWN_RETENTION_LIMIT DECIMAL(25,2)=0.0,
	@TREATY_CAPACITY_LIMIT DECIMAL(25,2)=0.0,
	@ACCUMULATION_LIMIT_AVAILABLE DECIMAL(25,2)=0.0,
	@TOTAL_SUM_INSURED DECIMAL(25,2)=0.0,
	@FACULTATIVE_RI DECIMAL(25,2)=0.0,
	@GROSS_RETAINED_SUM_INSURED DECIMAL(25,2)=0.0,
	@OWN_RETENTION DECIMAL(25,2)=0.0,
	@QUOTA_SHARE DECIMAL(25,2)=0.0,
	@FIRST_SURPLUS DECIMAL(25,2)=0.0,
	@OWN_ABSOLUTE_NET_RETENSTION DECIMAL(25,2)=0.0,
	@CREATED_BY INT,
	@CREATED_DATETIME DATETIME,
	
	@CUSTOMER_ID INT,
	@POLICY_ID INT,
	@POLICY_VERSION_ID SMALLINT
)	
AS    
    
BEGIN    
DELETE FROM POL_ACCUMULATION_DETAILS where ACCUMULATION_CODE=@ACCUMULATION_CODE
SELECT @ACCUMULATION_ID=(SELECT ISNULL(MAX(ACCUMULATION_ID),0)+1 FROM POL_ACCUMULATION_DETAILS)

INSERT INTO POL_ACCUMULATION_DETAILS    
  (    
	ACCUMULATION_ID ,    
	ACCUMULATION_CODE ,
	ACC_REF_NO ,
	TOTAL_NO_OF_POLICIES ,
	OWN_RETENTION_LIMIT,
	TREATY_CAPACITY_LIMIT ,
	ACCUMULATION_LIMIT_AVAILABLE ,
	TOTAL_SUM_INSURED ,
	FACULTATIVE_RI ,
	GROSS_RETAINED_SUM_INSURED ,
	OWN_RETENTION ,
	QUOTA_SHARE ,
	FIRST_SURPLUS ,
	OWN_ABSOLUTE_NET_RETENSTION ,
	CREATED_BY ,
	CREATED_DATETIME,

	CUSTOMER_ID,
	POLICY_ID,
	POLICY_VERSION_ID
	
   )    
    
VALUES     
 (    
	@ACCUMULATION_ID ,    
	@ACCUMULATION_CODE ,
	@ACC_REF_NO ,
	@TOTAL_NO_OF_POLICIES ,
	@OWN_RETENTION_LIMIT,
	@TREATY_CAPACITY_LIMIT ,
	@ACCUMULATION_LIMIT_AVAILABLE ,
	@TOTAL_SUM_INSURED ,
	@FACULTATIVE_RI ,
	@GROSS_RETAINED_SUM_INSURED ,
	@OWN_RETENTION ,
	@QUOTA_SHARE ,
	@FIRST_SURPLUS ,
	@OWN_ABSOLUTE_NET_RETENSTION ,
	@CREATED_BY ,
	@CREATED_DATETIME,

	@CUSTOMER_ID,
	@POLICY_ID,
	@POLICY_VERSION_ID
 )    
  
END    
Go
----