
IF  EXISTS (SELECT * FROM SYS.OBJECTS WHERE OBJECT_ID = OBJECT_ID(N'[DBO].[PROC_GETPOLICYNEWBUSINESSFORMOTOR]') AND TYPE IN (N'P', N'PC'))
DROP PROCEDURE [DBO].[PROC_GETPOLICYNEWBUSINESSFORMOTOR]
GO

SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON
GO

/*----------------------------------------------------------              
PROC NAME       : PROC_GETPOLICYNEWBUSINESSFORMOTOR              
CREATED BY      : AVIJIT GOSWAMI        
DATE            : 06/02/2012              
PURPOSE   : GENERATE INPUT XML FOR SINGAPORE PROJECT         
REVISON HISTORY :              
          
------------------------------------------------------------              
DATE     REVIEW BY          COMMENTS              
------   ------------       -------------------------*/            
     
CREATE PROCEDURE [DBO].[PROC_GETPOLICYNEWBUSINESSFORMOTOR]                        
(                                                                          
 @CUSTOMER_ID   INT,                                                                          
 @POLICY_ID      INT,                                                                          
 @POLICY_VERSION_ID   INT,                                                                          
 @CALLEDFROM  VARCHAR(20)=NULL,                       
 @LANG_ID SMALLINT =3   ,            
 @OUTPUTPROCESSID INT OUTPUT                                                                
)                                                                        
AS                              
BEGIN              
DECLARE @PROCESSID INT                
SELECT @PROCESSID = PROCESS_ID , @OUTPUTPROCESSID = PROCESS_ID FROM POL_POLICY_PROCESS WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND NEW_POLICY_VERSION_ID = @POLICY_VERSION_ID AND PROCESS_STATUS <> 'ROLLBACK'                
IF(@PROCESSID IN (24,25)) --FOR POLICY NEWBUSINESS               
BEGIN                
 SELECT                 
  ISNULL(POL.POLICY_NUMBER,'') POLICY_NO,  
  ISNULL(MLM.LOB_DESC,'') RISK_CLASS,      
  ISNULL(MCL.COUNTRY_NAME,'') PLACE_OF_ISSUE,      
  ISNULL(CONVERT(VARCHAR,POL.CREATED_DATETIME,103),'') DATE_OF_ISSUE,
  ISNULL(CAL.ACCOUNT_NUMBER,'') ACCOUNT_NUMBER,                  
  ISNULL(POLICYINFO.CUSTOMER_CODE,'') INSURED_CODE,
  ISNULL(QMQD.COVER_NOTE_NO,'')COVER_NOTE_NO,      
  ISNULL(POLICYINFO.CUSTOMER_FIRST_NAME,'') + '' + ISNULL(POLICYINFO.CUSTOMER_MIDDLE_NAME,'') + '' + ISNULL(POLICYINFO.CUSTOMER_LAST_NAME,'') AS INSURED,                  
  ISNULL(POLICYINFO.CUSTOMER_ADDRESS1,'') ADDRESS1,  
  ISNULL(MCL.COUNTRY_NAME,'') COUNTRY,         
  ISNULL(CUSTOMER_ZIP,'') ZIP,      
  ISNULL(CONVERT(VARCHAR,RECEIVED_PRMIUM),'')RECEIVED_PRMIUM,                
  ISNULL(MAM.ACTIVITY_DESC,'') OCCUPATION_BUSINESS,      
  ISNULL(CONVERT(VARCHAR,POL.POLICY_EFFECTIVE_DATE,103),'') POLICY_EFFECTIVE_DATE,      
  ISNULL(CONVERT(VARCHAR,POL.POLICY_EXPIRATION_DATE,103),'') POLICY_EXPIRATION_DATE,                  
  ISNULL(PV.VEHICLE_ID,'') RISK_LOCATION_NO,      
  ISNULL(PV.REGN_PLATE_NUMBER,'') REGISTRATION_NUMBER,      
  ISNULL(MNT_VEHICLE_MODEL_TYPE_LIST.MODEL_TYPE,'') TYPE_OF_BODY,      
  ISNULL(MLV.LOOKUP_VALUE_DESC,'') MAKE_OF_VEHICLE,                  
  ISNULL(PV.VEHICLE_CC,'') CC_TONNAGE,  
  ISNULL(POL.POLICY_DISP_VERSION,'')ENDORSEMENT_NUMBER,                  
  ISNULL(PV.VEHICLE_YEAR,'') YEAR_OF_MANUFACTURE,      
  ISNULL(PV.VIN,'') ENGINE_NO,      
  ISNULL(PV.CHASIS_NUMBER,'') CHASSIS_NO,      
  ISNULL(MC.COV_DES,'') TYPE_OF_COVER,  
  ISNULL(PBD.GROSS_PREMIUM,0.00)PREMIUM,  
  ISNULL(PBD.GST,0.00)GST_ON_PREMIUM,  
  ISNULL(PBD.TOTAL_AFTER_GST,0.00)PREMIUM_WITH_GST,  
  ISNULL(MCM.CURR_DESC,'')CURRENCY  
                       
  FROM CLT_CUSTOMER_LIST POLICYINFO LEFT OUTER JOIN                  
  POL_CUSTOMER_POLICY_LIST POL ON  
  POLICYINFO.CUSTOMER_ID = POL.CUSTOMER_ID  
  LEFT OUTER JOIN CLT_APPLICANT_LIST CAL ON  
  POLICYINFO.CUSTOMER_ID = CAL.CUSTOMER_ID 
  AND CAL.IS_PRIMARY_APPLICANT = '1'         
  LEFT OUTER JOIN POL_VEHICLES PV ON  
  PV.CUSTOMER_ID = POL.CUSTOMER_ID AND  
  PV.POLICY_ID = POL.POLICY_ID AND  
  PV.POLICY_VERSION_ID = POL.POLICY_VERSION_ID        
  LEFT OUTER JOIN MNT_LOOKUP_VALUES MLV      
  ON PV.MAKE = MLV.LOOKUP_UNIQUE_ID      
  AND MLV.LOOKUP_ID = '1308'   
  INNER JOIN MNT_VEHICLE_MODEL_LIST ON    
  MNT_VEHICLE_MODEL_LIST.ID  = PV.MODEL    
 INNER JOIN MNT_VEHICLE_MODEL_TYPE_LIST ON    
 MNT_VEHICLE_MODEL_TYPE_LIST.ID = PV.MOTORCYCLE_TYPE        
  LEFT OUTER JOIN MNT_LOB_MASTER MLM ON      
  MLM.LOB_ID = POL.POLICY_LOB    
  LEFT OUTER JOIN MNT_COVERAGE MC  
  ON MC.COV_ID = PV.VEHICLE_COVERAGE  
  LEFT OUTER JOIN MNT_ACTIVITY_MASTER MAM ON  
  MAM.ACTIVITY_ID=POLICYINFO.PREFIX  
  LEFT OUTER JOIN POL_BILLING_DETAILS PBD ON  
  PBD.CUSTOMER_ID=POL.CUSTOMER_ID  
  AND  PBD.POLICY_ID=POL.POLICY_ID  
  AND PBD.POLICY_VERSION_ID=POL.POLICY_VERSION_ID  
    
  LEFT OUTER JOIN MNT_CURRENCY_MASTER MCM  
  ON POL.POLICY_CURRENCY=MCM.CURRENCY_ID  
  LEFT OUTER JOIN MNT_COUNTRY_LIST MCL ON  
  MCL.COUNTRY_ID=POLICYINFO.CUSTOMER_COUNTRY
  
  LEFT OUTER JOIN QQ_MOTOR_QUOTE_DETAILS QMQD ON
  QMQD.CUSTOMER_ID = POL.CUSTOMER_ID AND
  QMQD.POLICY_ID = POL.POLICY_ID AND
  QMQD.POLICY_VERSION_ID = POL.POLICY_VERSION_ID   
                  
  WHERE POL.CUSTOMER_ID = @CUSTOMER_ID AND POL.POLICY_ID = @POLICY_ID AND POL.POLICY_VERSION_ID = @POLICY_VERSION_ID   

 FOR XML AUTO,ELEMENTS                 
               
 SELECT ISNULL(CLAUSE.CLAUSE_CODE,'') AS CLAUSE_CODE
 ,ISNULL(CLAUSE.CLAUSE_DESCRIPTION,'') AS CLAUSE_DESCRIPTIONFROM 
 FROM POL_CLAUSES CLAUSE              
 LEFT OUTER JOIN MNT_CLAUSES CLAUSE1 ON              
 CLAUSE.POL_CLAUSE_ID = CLAUSE1.CLAUSE_ID              
 WHERE              
 CLAUSE.CUSTOMER_ID = @CUSTOMER_ID AND CLAUSE.POLICY_ID = @POLICY_ID AND CLAUSE.POLICY_VERSION_ID = @POLICY_VERSION_ID              
                       
FOR XML AUTO,ELEMENTS
END                
IF(@PROCESSID IN(3,14,15)) --FOR ENDORSEMENT               
BEGIN                
                
 SELECT                 
  ISNULL(POL.POLICY_NUMBER,'') POLICY_NO,                
  ISNULL(MLM.LOB_DESC,'') RISK_CLASS,               
  ISNULL(MCL.COUNTRY_NAME,'') PLACE_OF_ISSUE,              
  ISNULL(CONVERT(VARCHAR,POL.CREATED_DATETIME,103),'') DATE_OF_ISSUE,                 
  ISNULL(CAL.ACCOUNT_NUMBER,'') ACCOUNT_NUMBER,                  
  ISNULL(POLICYINFO.CUSTOMER_CODE,'') INSURED_CODE,      
  ISNULL(POLICYINFO.CUSTOMER_FIRST_NAME,'') + '' + ISNULL(POLICYINFO.CUSTOMER_MIDDLE_NAME,'') + '' + ISNULL(POLICYINFO.CUSTOMER_LAST_NAME,'') AS INSURED,                
  ISNULL(POLICYINFO.CUSTOMER_ADDRESS1,'') ADDRESS1,        
  ISNULL(MCL.COUNTRY_NAME,'') COUNTRY,    
  ISNULL(CUSTOMER_ZIP,'') ZIP,                 
  ISNULL(CONVERT(VARCHAR,RECEIVED_PRMIUM),'')RECEIVED_PRMIUM,                
  ISNULL(CONVERT(VARCHAR,POL.POLICY_EFFECTIVE_DATE,103),'') POLICY_EFFECTIVE_DATE,                
  ISNULL(CONVERT(VARCHAR,POL.POLICY_EXPIRATION_DATE,103),'') POLICY_EXPIRATION_DATE,                  
  ISNULL(PPP.POLICY_VERSION_ID,'')ENDORSEMENT_NUMBER,                
  ISNULL(MLV.LOOKUP_VALUE_DESC,'')ENDORSEMENT_TYPE,                
  ISNULL(PPP.COMMENTS,'')COMMENTS                  
  FROM                   
  CLT_CUSTOMER_LIST POLICYINFO LEFT OUTER JOIN                  
  POL_CUSTOMER_POLICY_LIST POL ON                  
  POLICYINFO.CUSTOMER_ID = POL.CUSTOMER_ID                  
  LEFT OUTER JOIN CLT_APPLICANT_LIST CAL ON                  
  POLICYINFO.CUSTOMER_ID = CAL.CUSTOMER_ID  
  AND CAL.IS_PRIMARY_APPLICANT = '1'                          
  LEFT OUTER JOIN POL_VEHICLES PV ON                   
  PV.CUSTOMER_ID = POL.CUSTOMER_ID AND                  
  PV.POLICY_ID = POL.POLICY_ID AND                  
  PV.POLICY_VERSION_ID = POL.POLICY_VERSION_ID                  
  LEFT OUTER JOIN POL_POLICY_PROCESS PPP ON                
  PPP.CUSTOMER_ID = POL.CUSTOMER_ID AND                  
  PPP.POLICY_ID = POL.POLICY_ID AND                  
  PPP.NEW_POLICY_VERSION_ID = POL.POLICY_VERSION_ID AND PPP.PROCESS_STATUS <> 'ROLLBACK'                
  LEFT OUTER JOIN MNT_LOOKUP_VALUES MLV                
  ON PPP.ENDORSEMENT_TYPE = MLV.LOOKUP_UNIQUE_ID AND MLV.LOOKUP_ID = '1235'      
  LEFT OUTER JOIN MNT_LOB_MASTER MLM ON      
  MLM.LOB_ID = POL.POLICY_LOB  
  LEFT OUTER JOIN MNT_COUNTRY_LIST MCL ON  
  MCL.COUNTRY_ID=POLICYINFO.CUSTOMER_COUNTRY   
                       
  WHERE POL.CUSTOMER_ID = @CUSTOMER_ID AND POL.POLICY_ID = @POLICY_ID AND POL.POLICY_VERSION_ID = @POLICY_VERSION_ID  
    
 FOR XML AUTO,ELEMENTS
 
 SELECT ISNULL(CLAUSE.CLAUSE_CODE,'') AS CLAUSE_CODE
 ,ISNULL(CLAUSE.CLAUSE_DESCRIPTION,'') AS CLAUSE_DESCRIPTIONFROM 
 FROM POL_CLAUSES CLAUSE              
 LEFT OUTER JOIN MNT_CLAUSES CLAUSE1 ON              
 CLAUSE.POL_CLAUSE_ID = CLAUSE1.CLAUSE_ID              
 WHERE              
 CLAUSE.CUSTOMER_ID = @CUSTOMER_ID AND CLAUSE.POLICY_ID = @POLICY_ID AND CLAUSE.POLICY_VERSION_ID = @POLICY_VERSION_ID              
                       
FOR XML AUTO,ELEMENTS
 
END        
IF(@PROCESSID IN(2,12,13)) --FOR CANCELLATION               
BEGIN                      
 SELECT                 
  ISNULL(POL.POLICY_NUMBER,'') POLICY_NO,  
  ISNULL(MLM.LOB_DESC,'') RISK_CLASS,       
  ISNULL(MCL.COUNTRY_NAME,'') PLACE_OF_ISSUE,               
  ISNULL(CONVERT(VARCHAR,POL.CREATED_DATETIME,103),'') DATE_OF_ISSUE,              
  ISNULL(CAL.ACCOUNT_NUMBER,'') ACCOUNT_NUMBER,                  
  ISNULL(POLICYINFO.CUSTOMER_CODE,'') INSURED_CODE,      
  ISNULL(POLICYINFO.CUSTOMER_FIRST_NAME,'') + '' + ISNULL(POLICYINFO.CUSTOMER_MIDDLE_NAME,'') + '' + ISNULL(POLICYINFO.CUSTOMER_LAST_NAME,'') AS INSURED,        
  ISNULL(POLICYINFO.CUSTOMER_ADDRESS1,'') ADDRESS1,        
  ISNULL(MCL.COUNTRY_NAME,'') COUNTRY,       
  ISNULL(CUSTOMER_ZIP,'') ZIP,                  
  ISNULL(CONVERT(VARCHAR,RECEIVED_PRMIUM),'')RECEIVED_PRMIUM,                
  ISNULL(CONVERT(VARCHAR,POL.POLICY_EFFECTIVE_DATE,103),'') POLICY_EFFECTIVE_DATE,                
  ISNULL(CONVERT(VARCHAR,POL.POLICY_EXPIRATION_DATE,103),'') POLICY_EXPIRATION_DATE,                  
  ISNULL(PPP.POLICY_VERSION_ID,'')ENDORSEMENT_NUMBER,                
  ISNULL(MLV.LOOKUP_VALUE_DESC,'')CANCELLATION_TYPE,                
  ISNULL(PPP.OTHER_REASON,'') COMMENTS               
  FROM                   
  CLT_CUSTOMER_LIST POLICYINFO LEFT OUTER JOIN                  
  POL_CUSTOMER_POLICY_LIST POL ON                  
  POLICYINFO.CUSTOMER_ID = POL.CUSTOMER_ID                  
  LEFT OUTER JOIN CLT_APPLICANT_LIST CAL ON                  
  POLICYINFO.CUSTOMER_ID = CAL.CUSTOMER_ID  
  AND CAL.IS_PRIMARY_APPLICANT = '1'                          
  LEFT OUTER JOIN POL_VEHICLES PV ON                   
  PV.CUSTOMER_ID = POL.CUSTOMER_ID AND                  
  PV.POLICY_ID = POL.POLICY_ID AND                  
  PV.POLICY_VERSION_ID = POL.POLICY_VERSION_ID                  
  LEFT OUTER JOIN POL_POLICY_PROCESS PPP ON                
  PPP.CUSTOMER_ID = POL.CUSTOMER_ID AND                  
  PPP.POLICY_ID = POL.POLICY_ID AND                  
  PPP.NEW_POLICY_VERSION_ID = POL.POLICY_VERSION_ID AND PPP.PROCESS_STATUS <> 'ROLLBACK'                
  LEFT OUTER JOIN MNT_LOOKUP_VALUES MLV                
  ON PPP.CANCELLATION_TYPE = MLV.LOOKUP_UNIQUE_ID AND MLV.LOOKUP_ID = '1302'       
  LEFT OUTER JOIN MNT_LOB_MASTER MLM ON      
  MLM.LOB_ID = POL.POLICY_LOB  
   LEFT OUTER JOIN MNT_COUNTRY_LIST MCL ON  
  MCL.COUNTRY_ID=POLICYINFO.CUSTOMER_COUNTRY   
  WHERE POL.CUSTOMER_ID = @CUSTOMER_ID AND POL.POLICY_ID = @POLICY_ID AND POL.POLICY_VERSION_ID = @POLICY_VERSION_ID  
                   
 FOR XML AUTO,ELEMENTS
 
 SELECT ISNULL(CLAUSE.CLAUSE_CODE,'') AS CLAUSE_CODE
 ,ISNULL(CLAUSE.CLAUSE_DESCRIPTION,'') AS CLAUSE_DESCRIPTIONFROM 
 FROM POL_CLAUSES CLAUSE              
 LEFT OUTER JOIN MNT_CLAUSES CLAUSE1 ON              
 CLAUSE.POL_CLAUSE_ID = CLAUSE1.CLAUSE_ID              
 WHERE              
 CLAUSE.CUSTOMER_ID = @CUSTOMER_ID AND CLAUSE.POLICY_ID = @POLICY_ID AND CLAUSE.POLICY_VERSION_ID = @POLICY_VERSION_ID              
                       
FOR XML AUTO,ELEMENTS
END 
 
IF(@PROCESSID IN (5,6,18,19,20,21)) --FOR POLICY RENEWAL              
BEGIN                
 SELECT                 
    ISNULL(POL.POLICY_NUMBER,'') POLICY_NO,  
  ISNULL(MLM.LOB_DESC,'') RISK_CLASS,      
  ISNULL(MCL.COUNTRY_NAME,'') PLACE_OF_ISSUE,      
  ISNULL(CONVERT(VARCHAR,POL.CREATED_DATETIME,103),'') DATE_OF_ISSUE,                  
  ISNULL(CAL.ACCOUNT_NUMBER,'') ACCOUNT_NUMBER,                  
  ISNULL(POLICYINFO.CUSTOMER_CODE,'') INSURED_CODE,
  ISNULL(QMQD.COVER_NOTE_NO,'')COVER_NOTE_NO,      
  ISNULL(POLICYINFO.CUSTOMER_FIRST_NAME,'') + '' + ISNULL(POLICYINFO.CUSTOMER_MIDDLE_NAME,'') + '' + ISNULL(POLICYINFO.CUSTOMER_LAST_NAME,'') AS INSURED,                  
  ISNULL(POLICYINFO.CUSTOMER_ADDRESS1,'') ADDRESS1,  
  ISNULL(MCL.COUNTRY_NAME,'') COUNTRY,         
  ISNULL(CUSTOMER_ZIP,'') ZIP,      
  ISNULL(CONVERT(VARCHAR,RECEIVED_PRMIUM),'')RECEIVED_PRMIUM,                
  ISNULL(MAM.ACTIVITY_DESC,'') OCCUPATION_BUSINESS,      
  ISNULL(CONVERT(VARCHAR,POL.POLICY_EFFECTIVE_DATE,103),'') POLICY_EFFECTIVE_DATE,      
  ISNULL(CONVERT(VARCHAR,POL.POLICY_EXPIRATION_DATE,103),'') POLICY_EXPIRATION_DATE,                  
  ISNULL(PV.VEHICLE_ID,'') RISK_LOCATION_NO,      
  ISNULL(PV.REGN_PLATE_NUMBER,'') REGISTRATION_NUMBER,      
  ISNULL(MNT_VEHICLE_MODEL_TYPE_LIST.MODEL_TYPE,'') TYPE_OF_BODY,      
  ISNULL(MLV.LOOKUP_VALUE_DESC,'') MAKE_OF_VEHICLE,                  
  ISNULL(PV.VEHICLE_CC,'') CC_TONNAGE,  
  ISNULL(POL.POLICY_DISP_VERSION,'')ENDORSEMENT_NUMBER,                  
  ISNULL(PV.VEHICLE_YEAR,'') YEAR_OF_MANUFACTURE,      
  ISNULL(PV.VIN,'') ENGINE_NO,      
  ISNULL(PV.CHASIS_NUMBER,'') CHASSIS_NO,      
  ISNULL(MC.COV_DES,'') TYPE_OF_COVER,  
  ISNULL(PBD.GROSS_PREMIUM,0.00)PREMIUM,  
  ISNULL(PBD.GST,0.00)GST_ON_PREMIUM,  
  ISNULL(PBD.TOTAL_AFTER_GST,0.00)PREMIUM_WITH_GST,  
  ISNULL(MCM.CURR_DESC,'')CURRENCY  
                       
  FROM CLT_CUSTOMER_LIST POLICYINFO LEFT OUTER JOIN                  
  POL_CUSTOMER_POLICY_LIST POL ON  
  POLICYINFO.CUSTOMER_ID = POL.CUSTOMER_ID  
  LEFT OUTER JOIN CLT_APPLICANT_LIST CAL ON  
  POLICYINFO.CUSTOMER_ID = CAL.CUSTOMER_ID
  AND CAL.IS_PRIMARY_APPLICANT = '1'                    
  LEFT OUTER JOIN POL_VEHICLES PV ON  
  PV.CUSTOMER_ID = POL.CUSTOMER_ID AND  
  PV.POLICY_ID = POL.POLICY_ID AND  
  PV.POLICY_VERSION_ID = POL.POLICY_VERSION_ID        
  LEFT OUTER JOIN MNT_LOOKUP_VALUES MLV      
  ON PV.MAKE = MLV.LOOKUP_UNIQUE_ID      
  AND MLV.LOOKUP_ID = '1308'   
  INNER JOIN MNT_VEHICLE_MODEL_LIST ON    
  MNT_VEHICLE_MODEL_LIST.ID  = PV.MODEL    
 INNER JOIN MNT_VEHICLE_MODEL_TYPE_LIST ON    
 MNT_VEHICLE_MODEL_TYPE_LIST.ID = PV.MOTORCYCLE_TYPE        
  LEFT OUTER JOIN MNT_LOB_MASTER MLM ON      
  MLM.LOB_ID = POL.POLICY_LOB    
  LEFT OUTER JOIN MNT_COVERAGE MC  
  ON MC.COV_ID = PV.VEHICLE_COVERAGE  
  LEFT OUTER JOIN MNT_ACTIVITY_MASTER MAM ON  
  MAM.ACTIVITY_ID=POLICYINFO.PREFIX  
  LEFT OUTER JOIN POL_BILLING_DETAILS PBD ON  
  PBD.CUSTOMER_ID=POL.CUSTOMER_ID  
  AND  PBD.POLICY_ID=POL.POLICY_ID  
  AND PBD.POLICY_VERSION_ID=POL.POLICY_VERSION_ID  
    
  LEFT OUTER JOIN MNT_CURRENCY_MASTER MCM  
  ON POL.POLICY_CURRENCY=MCM.CURRENCY_ID  
  LEFT OUTER JOIN MNT_COUNTRY_LIST MCL ON  
  MCL.COUNTRY_ID=POLICYINFO.CUSTOMER_COUNTRY 
  
  LEFT OUTER JOIN QQ_MOTOR_QUOTE_DETAILS QMQD ON
  QMQD.CUSTOMER_ID = POL.CUSTOMER_ID AND
  QMQD.POLICY_ID = POL.POLICY_ID
  --QMQD.POLICY_VERSION_ID = POL.POLICY_VERSION_ID    
                  
 WHERE POL.CUSTOMER_ID = @CUSTOMER_ID AND POL.POLICY_ID = @POLICY_ID AND POL.POLICY_VERSION_ID = @POLICY_VERSION_ID  
 FOR XML AUTO,ELEMENTS                 
               
 SELECT ISNULL(CLAUSE.CLAUSE_CODE,'') AS CLAUSE_CODE
 ,ISNULL(CLAUSE.CLAUSE_DESCRIPTION,'') AS CLAUSE_DESCRIPTIONFROM 
 FROM POL_CLAUSES CLAUSE              
 LEFT OUTER JOIN MNT_CLAUSES CLAUSE1 ON              
 CLAUSE.POL_CLAUSE_ID = CLAUSE1.CLAUSE_ID              
 WHERE              
 CLAUSE.CUSTOMER_ID = @CUSTOMER_ID AND CLAUSE.POLICY_ID = @POLICY_ID AND CLAUSE.POLICY_VERSION_ID = @POLICY_VERSION_ID
               
FOR XML AUTO,ELEMENTS
END             
  RETURN @OUTPUTPROCESSID                 
END 