  
ALTER PROCEDURE  [dbo].[Proc_Application_Refusal]  
(  
 @CUSTOMER_ID INT,  
 @POLICY_ID INT,  
 @POLICY_VERSION_ID SMALLINT  
)  
AS  
BEGIN  
  
SELECT   
 MDL.DIV_CITY,   
 CASE LEN(DAY(PPP.COMPLETED_DATETIME))  
  WHEN 1 THEN '0' + CAST(DAY(PPP.COMPLETED_DATETIME) AS VARCHAR(2))  
  WHEN 2 THEN CAST(DAY(PPP.COMPLETED_DATETIME) AS VARCHAR(2))  
 END  
  + ' DE ' +   
 dbo.fun_GetMonth_BR(convert(varchar(4),MONTH(PPP.COMPLETED_DATETIME),100))  
  +   
 ' DE ' + CAST(YEAR(PPP.COMPLETED_DATETIME) AS VARCHAR(4)) As Sao_Paulo ,  
   
 MAL.AGENCY_DISPLAY_NAME AS BROKER_NAME,  
 MAL.AGENCY_ADD1+', '+MAL.AGENCY_ADD2 AS BROKER_ADDRESS,  
 MAL.AGENCY_ZIP+' - '+MAL.AGENCY_CITY+'/'+ CSL.STATE_CODE  AS ZIP,  
 MLMM.LOB_DESC+' no. '+PCPL.APP_NUMBER AS Ref,  
 CCL.CUSTOMER_FIRST_NAME + ISNULL(' '+CCL.CUSTOMER_MIDDLE_NAME,'')+ ISNULL(' '+CCL.CUSTOMER_LAST_NAME,'') AS CUSTOMER_NAME,    
 MLMM.LOB_DESC+' no. '+PCPL.APP_NUMBER AS PROPOSTA_DE_SEGURO,  --Added by Aditya for tfs bug # 1165  
 PCPL.BROKER_REQUEST_NO AS PEDIDO_DO_CORRETOR,    
 UPPER(MDL.DIV_NAME) + ' - ' + DIV_ADD1+' - '+MDL.DIV_ADD2+' - CEP '+MDL.DIV_ZIP+' - '+MDL.DIV_CITY+' - Fone '+MDL.DIV_PHONE+' Fax '+MDL.DIV_FAX AS Branch_Name  
       
FROM   
 MNT_DIV_LIST MDL WITH(NOLOCK)  
INNER JOIN   
 POL_CUSTOMER_POLICY_LIST PCPL WITH(NOLOCK) ON MDL.DIV_ID = PCPL.DIV_ID    
INNER JOIN  
 MNT_LOB_MASTER_MULTILINGUAL MLMM WITH(NOLOCK) ON MLMM.LOB_ID = PCPL.POLICY_LOB   
   
INNER JOIN  
 MNT_AGENCY_LIST MAL WITH(NOLOCK) ON MAL.AGENCY_ID = PCPL.AGENCY_ID   
   
INNER JOIN  
 POL_POLICY_PROCESS PPP WITH(NOLOCK) ON PPP.CUSTOMER_ID = PCPL.CUSTOMER_ID AND PPP.POLICY_ID = PCPL.POLICY_ID AND PPP.NEW_POLICY_VERSION_ID =PCPL.POLICY_VERSION_ID   
LEFT OUTER JOIN  
 MNT_COUNTRY_STATE_LIST CSL WITH(NOLOCK) ON (CSL.STATE_ID = MAL.AGENCY_STATE AND CSL.COUNTRY_ID = 7)  
INNER JOIN    
    CLT_CUSTOMER_LIST CCL WITH(NOLOCK) ON CCL.CUSTOMER_ID=PCPL.CUSTOMER_ID  --Added by Aditya for tfs bug # 1165  
   
WHERE  
  PCPL.CUSTOMER_ID = @CUSTOMER_ID AND  
  PCPL.POLICY_ID = @POLICY_ID AND  
  PCPL.POLICY_VERSION_ID = @POLICY_VERSION_ID  
   
END  


select * from POL_PROCESS_MASTER


select * from POL_VEHICLES where CUSTOMER_ID = 28718 and POLICY_ID = 55 and POLICY_VERSION_ID = 5
select * from POL_CUSTOMER_POLICY_LIST where CUSTOMER_ID = 28721 and POLICY_ID = 5
  