--DROP PROC Proc_Get_Prem_Comm


Create Procedure Proc_Get_Prem_Comm
(@CUSTOMER_ID   INT,                     -- ID OF CUSTOMER WHOSE  POLICY PREMIUM BILL INSTALLMENT WILL BE POSTED                               
 @POLICY_ID  INT,                        -- POLICY IDENTIFICATION NUMBER                              
 @POLICY_VERSION_ID SMALLINT
 ) as
 begin
 IF EXISTS (SELECT TOTAL_PREMIUM FROM ACT_POLICY_INSTALL_PLAN_DATA where CUSTOMER_ID=@CUSTOMER_ID and POLICY_ID=@POLICY_ID and POLICY_VERSION_ID=@POLICY_VERSION_ID)
 BEGIN
select TOTAL_PREMIUM AS RECEIVED_PRMIUM,POLICY_LEVEL_COMISSION from POL_CUSTOMER_POLICY_LIST PCL LEFT JOIN ACT_POLICY_INSTALL_PLAN_DATA APD ON
APD.CUSTOMER_ID=PCL.CUSTOMER_ID AND APD.POLICY_ID=PCL.POLICY_ID AND APD.POLICY_VERSION_ID=PCL.POLICY_VERSION_ID
 where APD.CUSTOMER_ID=@CUSTOMER_ID and APD.POLICY_ID=@POLICY_ID and APD.POLICY_VERSION_ID=@POLICY_VERSION_ID
 END
 ELSE
 BEGIN
 select RECEIVED_PRMIUM,POLICY_LEVEL_COMISSION from POL_CUSTOMER_POLICY_LIST 
 where CUSTOMER_ID=@CUSTOMER_ID and POLICY_ID=@POLICY_ID and POLICY_VERSION_ID=@POLICY_VERSION_ID
 END
END