IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Proc_GetLookUpTableDataForVessel]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Proc_GetLookUpTableDataForVessel]
GO
CREATE   PROCEDURE dbo.Proc_GetLookUpTableDataForVessel  
@CalledFrom varchar(50)
AS  
BEGIN  
if(@CalledFrom = 'TypeOfVessel')
BEGIN
	SELECT MNTL.LOOKUP_VALUE_CODE LOOKUP_UNIQUE_ID,MNTL.LOOKUP_VALUE_DESC LOOKUP_VALUE_DESC FROM MNT_LOOKUP_TABLES MT  
	left outer join MNT_LOOKUP_VALUES MNTL on MNTL.LOOKUP_ID = MT.LOOKUP_ID where MT.LOOKUP_ID = '1453' --ORDER BY MT.LOOKUP_NAME  
END
else if(@CalledFrom = 'ClassUnClass')
begin 
	SELECT MNTL.LOOKUP_VALUE_CODE LOOKUP_UNIQUE_ID,MNTL.LOOKUP_VALUE_DESC LOOKUP_VALUE_DESC FROM MNT_LOOKUP_TABLES MT  
	left outer join MNT_LOOKUP_VALUES MNTL on MNTL.LOOKUP_ID = MT.LOOKUP_ID where MT.LOOKUP_ID = '1454' --ORDER BY MT.LOOKUP_NAME 
end
else if(@CalledFrom = 'YesNo')
begin 
	SELECT MNTL.LOOKUP_VALUE_CODE  LOOKUP_UNIQUE_ID,MNTL.LOOKUP_VALUE_DESC LOOKUP_VALUE_DESC FROM MNT_LOOKUP_TABLES MT  
	left outer join MNT_LOOKUP_VALUES MNTL on MNTL.LOOKUP_ID = MT.LOOKUP_ID where MT.LOOKUP_ID = '1126' --ORDER BY MT.LOOKUP_NAME 
end
END  
  
  