IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Proc_UpdateDefaultBroker]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Proc_UpdateDefaultBroker]
GO

SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON
GO  
    
-- =============================================                  
-- Author:  Charles Gomes                  
-- Created date: 8-April-2010                  
-- Description: Updates Default Broker in Renumeration Tab                  
-- DROP PROC Proc_UpdateDefaultBroker                
-- =============================================                  
                  
--begin tran            
--DROP PROC Proc_UpdateDefaultBroker            
--go                  
                  
CREATE PROCEDURE [dbo].[Proc_UpdateDefaultBroker]                   
 @AGENCY_ID INT,                   
 @CUSTOMER_ID INT,                  
 @POLICY_ID INT,                  
 @POLICY_VERSION_ID SMALLINT,                  
 @OLD_AGENCY_ID INT                  
AS                  
BEGIN                   
        
  DECLARE @REMUNERATION_ID INT,         
  @MAX_REMUNERATION_ID INT,         
  @COMMISSION_PERCENT DECIMAL(8,2),        
  @COUNTRY_ID INT,        
  @LOB_ID SMALLINT,        
  @SUB_LOB_ID SMALLINT,        
  @EFFECTIVE_FROM_DATE DATETIME,        
  @EFFECTIVE_TO_DATE DATETIME,        
  @CURRENT_TERM SMALLINT ,       
  @CO_APPLICANT_ID INT        
        
  SELECT @CO_APPLICANT_ID=APPLICANT_ID FROM POL_APPLICANT_LIST WHERE CUSTOMER_ID =@CUSTOMER_ID AND POLICY_ID=@POLICY_ID AND POLICY_VERSION_ID=@POLICY_VERSION_ID AND IS_PRIMARY_APPLICANT=1        
         
  IF EXISTS(SELECT REMUNERATION_ID FROM POL_REMUNERATION WITH(NOLOCK) WHERE                    
   CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID         
   AND BROKER_ID = @OLD_AGENCY_ID AND ISNULL(IS_ACTIVE,'N')='Y' and CO_APPLICANT_ID=@CO_APPLICANT_ID and COMMISSION_TYPE=43)                  
  BEGIN                      
    --Primary Key of Old Broker                      
    SELECT @REMUNERATION_ID = REMUNERATION_ID FROM POL_REMUNERATION WITH(NOLOCK) WHERE                  
    CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID AND BROKER_ID = @OLD_AGENCY_ID            
    and CO_APPLICANT_ID=@CO_APPLICANT_ID and COMMISSION_TYPE=43         
    SELECT @REMUNERATION_ID              
                    
    --Update the Old Broker entry with new Broker                    
    IF NOT EXISTS(SELECT REMUNERATION_ID FROM POL_REMUNERATION WITH(NOLOCK) WHERE         
    CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID AND BROKER_ID = @AGENCY_ID and CO_APPLICANT_ID=@CO_APPLICANT_ID and COMMISSION_TYPE=43)                  
    BEGIN         
   UPDATE POL_REMUNERATION SET BROKER_ID = @AGENCY_ID, LEADER=10963, LAST_UPDATED_DATETIME = GETDATE(),COMMISSION_PERCENT=100--Added by kuldeep for temp purpose on 11_jan_2012            
   WHERE REMUNERATION_ID = @REMUNERATION_ID         
   AND CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID AND BROKER_ID = @OLD_AGENCY_ID and CO_APPLICANT_ID=@CO_APPLICANT_ID and COMMISSION_TYPE=43                     
    END          
    ELSE --Update only the Leader Column           
    BEGIN        
  UPDATE POL_REMUNERATION SET LEADER=10963, LAST_UPDATED_DATETIME = GETDATE(),COMMISSION_PERCENT=100   --Added by kuldeep for temp purpose on 11_jan_2012                     
  WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID AND BROKER_ID = @AGENCY_ID and CO_APPLICANT_ID=@CO_APPLICANT_ID  and COMMISSION_TYPE=43      
    END              
                
  END                  
  ELSE --New Entry                  
  BEGIN         
                   
   SELECT @MAX_REMUNERATION_ID = ISNULL(MAX(REMUNERATION_ID),0)+1 FROM POL_REMUNERATION WITH(NOLOCK)         
   WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID    
           
   SELECT @COUNTRY_ID = CAST(CLT.CUSTOMER_COUNTRY AS INT), @LOB_ID = CAST(CPL.POLICY_LOB AS SMALLINT), @CURRENT_TERM = CPL.CURRENT_TERM,        
   @SUB_LOB_ID = CAST(CPL.POLICY_SUBLOB AS INT),@EFFECTIVE_FROM_DATE = CPL.APP_EFFECTIVE_DATE, @EFFECTIVE_TO_DATE = CPL.APP_EXPIRATION_DATE        
   FROM POL_CUSTOMER_POLICY_LIST CPL WITH(NOLOCK)        
   LEFT OUTER JOIN CLT_CUSTOMER_LIST CLT WITH(NOLOCK)         
   ON CLT.CUSTOMER_ID = CPL.CUSTOMER_ID         
   WHERE CPL.CUSTOMER_ID = @CUSTOMER_ID AND CPL.POLICY_ID = @POLICY_ID AND CPL.POLICY_VERSION_ID = @POLICY_VERSION_ID        
                
   --Get Agency Commission Percentage from Maintenance        
   IF @CURRENT_TERM = 1 --First Term        
   BEGIN        
    SELECT @COMMISSION_PERCENT = ISNULL(COMMISSION_PERCENT,0) FROM ACT_REG_COMM_SETUP WITH(NOLOCK)          
    WHERE UPPER(COMMISSION_TYPE) = 'A' AND UPPER(TERM)='F' AND COUNTRY_ID = @COUNTRY_ID AND LOB_ID = @LOB_ID AND SUB_LOB_ID = @SUB_LOB_ID        
    AND AGENCY_ID = @AGENCY_ID AND CONVERT(VARCHAR,EFFECTIVE_FROM_DATE,101) >= CONVERT(VARCHAR,@EFFECTIVE_FROM_DATE,101)         
    AND CONVERT(VARCHAR,EFFECTIVE_TO_DATE,101) <= CONVERT(VARCHAR,@EFFECTIVE_TO_DATE,101)            
   END        
   ELSE --Other Terms        
   BEGIN        
    SELECT @COMMISSION_PERCENT = ISNULL(COMMISSION_PERCENT,0) FROM ACT_REG_COMM_SETUP WITH(NOLOCK)          
    WHERE UPPER(COMMISSION_TYPE) = 'A' AND UPPER(TERM)='O' AND COUNTRY_ID = @COUNTRY_ID AND LOB_ID = @LOB_ID AND SUB_LOB_ID = @SUB_LOB_ID        
    AND AGENCY_ID = @AGENCY_ID AND CONVERT(VARCHAR,EFFECTIVE_FROM_DATE,101) >= CONVERT(VARCHAR,@EFFECTIVE_FROM_DATE,101)         
    AND CONVERT(VARCHAR,EFFECTIVE_TO_DATE,101) <= CONVERT(VARCHAR,@EFFECTIVE_TO_DATE,101)        
   END        
           
   SELECT @COMMISSION_PERCENT        
                       
   IF NOT EXISTS(SELECT REMUNERATION_ID FROM POL_REMUNERATION WITH(NOLOCK) WHERE                    
   CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID AND BROKER_ID = @AGENCY_ID and CO_APPLICANT_ID=@CO_APPLICANT_ID and COMMISSION_TYPE=43)                
   BEGIN         
         
    --COMMISSION_TYPE = 14629 -> Commission    ,IN ACT_TRANSACTION_CODES COMMISSION =>43        
    INSERT INTO POL_REMUNERATION(REMUNERATION_ID,CUSTOMER_ID,POLICY_ID,POLICY_VERSION_ID,BROKER_ID,COMMISSION_PERCENT,COMMISSION_TYPE,IS_ACTIVE,                  
    CREATED_BY,CREATED_DATETIME,MODIFIED_BY,LAST_UPDATED_DATETIME,BRANCH,LEADER,RISK_ID,CO_APPLICANT_ID)  -- INSERT RISK ID FOR SHOWINF RENUMERATION RISK WISE ADDED BY SONAL 11-08-2010                
    VALUES                  
    (@MAX_REMUNERATION_ID,@CUSTOMER_ID,@POLICY_ID,@POLICY_VERSION_ID,@AGENCY_ID,100,43,'Y',NULL,GETDATE(),NULL,NULL,0,10963,0,@CO_APPLICANT_ID)                  
   END                
  END  -- End of Else        
          
  --Remove all Other Leader entries, if exists        
    IF EXISTS(SELECT REMUNERATION_ID FROM POL_REMUNERATION WITH(NOLOCK) WHERE         
    CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID         
    AND BROKER_ID != @AGENCY_ID AND ISNULL(LEADER,10964)=10963 and CO_APPLICANT_ID=@CO_APPLICANT_ID and COMMISSION_TYPE=43)                  
    BEGIN                   
  UPDATE POL_REMUNERATION SET LEADER=10964, LAST_UPDATED_DATETIME = GETDATE(),COMMISSION_PERCENT=100--Added by kuldeep for temp purpose on 11_jan_2012            
   WHERE           
  CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID AND BROKER_ID != @AGENCY_ID and CO_APPLICANT_ID=@CO_APPLICANT_ID and COMMISSION_TYPE=43             
    END           
                        
END             
            
--go            
--exec Proc_UpdateDefaultBroker 93,2043,362,1,93                
--select * from POL_REMUNERATION where CUSTOMER_ID=2043 and POLICY_ID=362            
--rollback tran    