  
/*                 
----------------------------------------------------------                                      
Proc Name       : dbo.Proc_GetPolicy_NBS_Amount                            
Created by      : LALIT CHAUHAN                          
Date            : 05/20/2010                                      
Purpose         : If policy is endorsment in progress      
Revison History :                                      
Used In         : Ebix Advantage                                      
------------------------------------------------------------                                      
Date     Review By          Comments                                      
------   ------------       -------------------------                      
drop proc   
proc_GetPolicy_NBSAmount 2156,490,2,'UENDRS'    
      
*/                    
CREATE PROC [dbo].[proc_GetPolicy_NBSAmount]     
(      
@CUSTOMER_ID INT,      
@POLICY_ID INT,      
@POLICY_VERSION_ID SMALLINT,      
@POLICY_STATUS NVARCHAR(20) = NULL     
)      
AS       
BEGIN      
DECLARE @PREV_VERSION_ID SMALLINT,@POLICY_EFFECTIVE_DATE DATETIME  ,@EXPIRY_DATE DATETIME    
DECLARE @NBS_VERSION INT,@NBS_PREMIUM DECIMAL(25,2),@NBS_INTER DECIMAL(25,2),@NBS_TAX DECIMAL(25,2),  
@NBS_FEES DECIMAL(25,2),@NBS_TOTAL DECIMAL(25,2),@CURRENT_TERM INT  
 --IF(@POLICY_STATUS='UENDRS' or @POLICY_STATUS='MENDORSE' or @POLICY_STATUS='14' or @POLICY_STATUS='3')       
  --BEGIN      
      
    SELECT @CURRENT_TERM = CURRENT_TERM FROM  POL_CUSTOMER_POLICY_LIST WITH(NOLOCK)   
    WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID  = @POLICY_ID   
    AND POLICY_VERSION_ID = @POLICY_VERSION_ID  
       
      
     IF EXISTS(SELECT POLICY_VERSION_ID  FROM POL_POLICY_PROCESS WITH(NOLOCK)       
        WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID AND NEW_POLICY_VERSION_ID=@POLICY_VERSION_ID AND POL_POLICY_PROCESS.PROCESS_STATUS <> 'ROLLBACK')      
        BEGIN      
          
        SELECT @NBS_VERSION = POL_POLICY_PROCESS.POLICY_VERSION_ID  
          FROM POL_POLICY_PROCESS WITH(NOLOCK)    
          JOIN POL_CUSTOMER_POLICY_LIST  WITH(NOLOCK) ON    
          POL_POLICY_PROCESS.CUSTOMER_ID = POL_CUSTOMER_POLICY_LIST.CUSTOMER_ID AND    
          POL_POLICY_PROCESS.POLICY_ID=POL_CUSTOMER_POLICY_LIST.POLICY_ID  AND   
          POL_POLICY_PROCESS.NEW_POLICY_VERSION_ID = POL_CUSTOMER_POLICY_LIST.POLICY_VERSION_ID     
        WHERE POL_POLICY_PROCESS.CUSTOMER_ID = @CUSTOMER_ID  
     AND POL_POLICY_PROCESS.POLICY_ID= @POLICY_ID  
     AND POL_POLICY_PROCESS.PROCESS_STATUS <> 'ROLLBACK'   
     AND POL_POLICY_PROCESS.PROCESS_ID = 25  --get Nbs Policy Version ID  
       
  SELECT @NBS_PREMIUM = TOTAL_PREMIUM,@NBS_INTER= TOTAL_INTEREST_AMOUNT,  
  @NBS_FEES = TOTAL_FEES , @NBS_TAX = TOTAL_TAXES, @NBS_TOTAL = TOTAL_AMOUNT  
   FROM ACT_POLICY_INSTALL_PLAN_DATA WITH(NOLOCK) WHERE CUSTOMER_ID = @CUSTOMER_ID   
   AND POLICY_ID = @POLICY_ID   
  AND POLICY_VERSION_ID  =@NBS_VERSION  
       
          
        SELECT @PREV_VERSION_ID =  MAX(POLICY_VERSION_ID)   
        FROM ACT_POLICY_INSTALL_PLAN_DATA WITH(NOLOCK)  
  WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND   
  POLICY_VERSION_ID IN   
  (SELECT POLICY_VERSION_ID FROM POL_CUSTOMER_POLICY_LIST p  WITH(NOLOCK)  
  WHERE p.CUSTOMER_ID = @CUSTOMER_ID AND p.POLICY_ID = @POLICY_ID   
  AND p.CURRENT_TERM = @CURRENT_TERM and p.POLICY_VERSION_ID<@POLICY_VERSION_ID)  
          
     
        SELECT @POLICY_EFFECTIVE_DATE =  ISNULL(ISNULL(PP.EFFECTIVE_DATETIME,pl.POL_VER_EFFECTIVE_DATE),POLICY_EFFECTIVE_DATE) ,  
  @EXPIRY_DATE = ISNULL(ISNULL(PP.EXPIRY_DATE,pl.POL_VER_EXPIRATION_DATE),POLICY_EXPIRATION_DATE)   
  FROM POL_CUSTOMER_POLICY_LIST PL WITH(NOLOCK)  
  LEFT OUTER JOIN POL_POLICY_PROCESS PP WITH(NOLOCK) ON  
  PP.CUSTOMER_ID = PL.CUSTOMER_ID AND   
  PP.POLICY_ID = PL.POLICY_ID AND   
  PP.NEW_POLICY_VERSION_ID = PL.POLICY_VERSION_ID  
   WHERE pl.CUSTOMER_ID = @CUSTOMER_ID and pl.POLICY_ID = @POLICY_ID  
  and pl.POLICY_VERSION_ID = @POLICY_VERSION_ID  
          
          
      --SELECT --@PREV_VERSION_ID = POL_POLICY_PROCESS.NEW_POLICY_VERSION_ID,   
        --@POLICY_EFFECTIVE_DATE = ISNULL(ISNULL(EFFECTIVE_DATETIME,POL_CUSTOMER_POLICY_LIST.POLICY_EFFECTIVE_DATE),APP_EFFECTIVE_DATE),      
        --@EXPIRY_DATE= ISNULL(ISNULL(EXPIRY_DATE,POL_CUSTOMER_POLICY_LIST.POLICY_EXPIRATION_DATE),APP_EXPIRATION_DATE)        
        --  FROM POL_POLICY_PROCESS WITH(NOLOCK)    
        --  RIGHT OUTER JOIN POL_CUSTOMER_POLICY_LIST  WITH(NOLOCK) ON    
        --  POL_POLICY_PROCESS.CUSTOMER_ID = POL_CUSTOMER_POLICY_LIST.CUSTOMER_ID AND    
        --  POL_POLICY_PROCESS.POLICY_ID=POL_CUSTOMER_POLICY_LIST.POLICY_ID   
        --  AND POL_CUSTOMER_POLICY_LIST.CURRENT_TERM = @CURRENT_TERM  
        --WHERE POL_POLICY_PROCESS.CUSTOMER_ID = @CUSTOMER_ID   
        -- AND POL_POLICY_PROCESS.POLICY_ID=@POLICY_ID           
        -- AND POL_POLICY_PROCESS.PROCESS_STATUS <> 'ROLLBACK'     
        -- AND POL_POLICY_PROCESS.NEW_POLICY_VERSION_ID=(SELECT MAX(B.POLICY_VERSION_ID)   
        -- FROM ACT_POLICY_INSTALLMENT_DETAILS B WITH(NOLOCK) WHERE B.CUSTOMER_ID =POL_CUSTOMER_POLICY_LIST.CUSTOMER_ID  AND  
        -- B.POLICY_ID = POL_CUSTOMER_POLICY_LIST.POLICY_ID  and B.POLICY_VERSION_ID< @POLICY_VERSION_ID  
        --   )  
                
                   
        SELECT     
        @POLICY_EFFECTIVE_DATE AS POLICY_EFFECTIVE_DATE,    
        @EXPIRY_DATE AS [EXPIRY_DATE],    
        TOTAL_AMOUNT,    
        TOTAL_FEES,    
        TOTAL_INTEREST_AMOUNT,    
        TOTAL_TAXES,    
        TOTAL_PREMIUM,    
        TOTAL_INFO_PRM,    
        TOTAL_CHANGE_INFORCE_PRM,    
        TOTAL_STATE_FEES,    
        TOTAL_TRAN_STATE_FEES,    
           MODE_OF_PAYMENT,    
           MODE_OF_DOWN_PAYMENT,  
           ISNULL(@NBS_PREMIUM,0) NBS_PREMIUM,  
           ISNULL(@NBS_INTER,0) NBS_INTEREST,  
           ISNULL(@NBS_FEES,0)  NBS_FEES,  
           ISNULL(@NBS_TAX,0) NBS_TAX,  
           ISNULL(@NBS_TOTAL,0) NBS_TOTAL , 
         --added by kuldeep for TFS 3408
			PBD.TOTAL_BEFORE_GST,
			PBD.TOTAL_AFTER_GST,
			PBD.GROSS_COMMISSION,
			PBD.GST_ON_COMMISSION,
			PBD.TOTAL_COMM_AFTER_GST
         
         FROM ACT_POLICY_INSTALL_PLAN_DATA API WITH(NOLOCK)
         INNER JOIN POL_BILLING_DETAILS PBD 
         ON API.CUSTOMER_ID=PBD.CUSTOMER_ID  AND API.POLICY_ID=PBD.POLICY_ID And API.POLICY_VERSION_ID=PBD.POLICY_VERSION_ID    
         WHERE API.CUSTOMER_ID=@CUSTOMER_ID            
         AND API.POLICY_ID=@POLICY_ID And API.POLICY_VERSION_ID=@POLICY_VERSION_ID    
            --TILL HERE
            
         SELECT ISNULL(@NBS_PREMIUM,0) NBS_PREMIUM,  
           ISNULL(@NBS_INTER,0) NBS_INTEREST,  
           ISNULL(@NBS_FEES,0)  NBS_FEES,  
           ISNULL(@NBS_TAX,0) NBS_TAX,  
           ISNULL(@NBS_TOTAL,0) NBS_TOTAL   
                 
    --   END      
  END      
      
END   