
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROC_ACTIVATEDEACTIVATEVOYAGEINFO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[PROC_ACTIVATEDEACTIVATEVOYAGEINFO]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE  PROC [dbo].[PROC_ACTIVATEDEACTIVATEVOYAGEINFO]  
(          
 @CUSTOMER_ID INT,      
 @POLICY_ID INT,      
 @POLICY_VERSION_ID INT,      
 @VOYAGE_ID  INT,          
 @IS_ACTIVE   NCHAR(1)          
)          
AS          
BEGIN  
UPDATE POL_MARINE_CARGO_VOYAGE_INFO      
 SET           
    IS_ACTIVE  = @IS_ACTIVE  ,
    ORIGINAL_VERSION_ID = CASE  WHEN @IS_ACTIVE='Y' THEN 0 ELSE  @POLICY_VERSION_ID END           
 WHERE          
    CUSTOMER_ID=@CUSTOMER_ID AND    
    POLICY_ID=@POLICY_ID AND    
    POLICY_VERSION_ID=@POLICY_VERSION_ID  AND
    VOYAGE_ID=@VOYAGE_ID        
      
   
END      
      

GO


