IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Proc_InsertPOL_REINSURANCE_BREAKDOWN_DETAILS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Proc_InsertPOL_REINSURANCE_BREAKDOWN_DETAILS]
GO

SET ANSI_NULLS ON 
GO

SET QUOTED_IDENTIFIER ON
GO
                    
            
--begin tran            
--DROP PROC Proc_InsertPOL_REINSURANCE_BREAKDOWN_DETAILS            
--go            
 /**************************************************                  
CREATED BY    : Pravesh K Chandel                 
CREATED DATETIME : 15 Nov 2010                  
PURPOSE    : INsert record into Reinsurance Break down table on Commit of Process            
Review      :            
Review By  Date               
Purpose                  
DROP PROC Proc_InsertPOL_REINSURANCE_BREAKDOWN_DETAILS            
***************************************************/                  
            
CREATE PROCEDURE [dbo].[Proc_InsertPOL_REINSURANCE_BREAKDOWN_DETAILS]  --2185,30,1,924, 0            
(                    
 @CUSTOMER_ID  INT,                    
 @POLICY_ID   INT,                    
 @POLICY_VERSION_ID INT,                    
 @CREATED_BY   INT =null,                    
 @PROCESS_ID int                
)                    
AS                    
BEGIN                    
              
-- done for Product 0171, Notes in Itrack 910 Monica Notes on 4/8/2011              
DECLARE @TIV NUMERIC(25,2)              
DECLARE @PREMIUM NUMERIC(25,2)              
DECLARE @LOBID INT      
SELECT @LOBID = POLICY_LOB FROM POL_CUSTOMER_POLICY_LIST WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID      
/*              
SELECT               
@TIV = SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670                
     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
     ELSE CAST(LIMIT AS DECIMAL(18,2))END              
    ELSE 0              
    END              
   ) ,              
              
@PREMIUM= SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(written_prem AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(written_prem AS DECIMAL(18,2))END)              
FROM CLT_PREMIUM_SPLIT SPLT WITH(NOLOCK)              
JOIN CLT_PREMIUM_SPLIT_DETAILS SPLD WITH(NOLOCK) ON SPLT.UNIQUE_ID = SPLD.SPLIT_UNIQUE_ID              
JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= SPLD.COMP_EXT --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670              
JOIN POL_CUSTOMER_POLICY_LIST POL WITH(NOLOCK) ON  SPLT.CUSTOMER_ID=POL.CUSTOMER_ID AND SPLT.POLICY_ID=POL.POLICY_ID              
AND SPLT.POLICY_VERSION_ID= POL.POLICY_VERSION_ID               
LEFT JOIN POL_CO_INSURANCE CO with(nolock) on  SPLT.CUSTOMER_ID=CO.CUSTOMER_ID and SPLT.POLICY_ID=CO.POLICY_ID               
AND SPLT.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES              
              
JOIN POL_PRODUCT_LOCATION_INFO LOC WITH(NOLOCK) ON              
LOC.CUSTOMER_ID=POL.CUSTOMER_ID               
AND LOC.POLICY_ID=POL.POLICY_ID               
AND LOC.POLICY_VERSION_ID=POL.POLICY_VERSION_ID              
AND LOC.PORTABLE_EQUIPMENT=10964              
AND LOC.PRODUCT_RISK_ID = SPLT.RISK_ID              
WHERE SPLT.CUSTOMER_ID=@CUSTOMER_ID               
AND SPLT.POLICY_ID=@POLICY_ID AND SPLT.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND POL.POLICY_LOB=14 -- FOR 0171 Product              
*/              
              
--EXEC Proc_CMP_EXCEEDEDPREMIUM @CUSTOMER_ID,@POLICY_ID,@POLICY_VERSION_ID              
;         
      
      
              
WITH CONTRACTS1              
AS              
(              
select               
pol.CUSTOMER_ID,pol.POLICY_ID,POL.POLICY_VERSION_ID,pol.POL_VER_EFFECTIVE_DATE,pol.POL_VER_EXPIRATION_DATE,              
pol.POLICY_NUMBER,POL.POLICY_LOB as LOB_ID,              
CONT.CONTRACT_ID,              
CONT.CONTRACT_NUMBER,CONT.CONTRACT_TYPE,CONT.CONTRACT_DESC,              
CONT.COMMISSION,              
CONT.CONTACT_YEAR,CONT.EFFECTIVE_DATE,CONT.EXPIRATION_DATE,CONT.TERMINATION_DATE,         
CONT.SEQUENCE_NUMBER,CONT.CONTRACT_NAME_ID,              
CONT.COVERAGE_CODE,              
MJR.REINSURANCE_COMPANY as REIN_COMPANY_ID,              
MJR.WHOLE_PERCENT,              
LYR.LAYER,              
LYR.LAYER_AMOUNT,              
LYR.REIN_CEDED_PERCENTAGE,              
LYR.REIN_CEDED,              
LYR.RETENTION_AMOUNT,           
LYR.RETENTION_PERCENTAGE--,              
--LYR1.LAYER as PRE_LAYER,LYR1.LAYER_AMOUNT AS PRE_LAYER_AMOUNT              
              
from MNT_REINSURANCE_CONTRACT CONT with(nolock)              
inner join MNT_REIN_CONTRACT_LOB LOB with(nolock) on CONT.CONTRACT_ID=LOB.CONTRACT_ID               
--INNER JOIN MNT_LOOKUP_VALUES LK with(nolock) ON CONT.CALCULATION_BASE=LK.LOOKUP_UNIQUE_ID              
INNER JOIN MNT_REIN_LOSSLAYER LYR with(nolock) ON LYR.CONTRACT_ID=CONT.CONTRACT_ID              
LEFT JOIN MNT_REIN_LOSSLAYER LYR1 with(nolock) ON LYR1.CONTRACT_ID=CONT.CONTRACT_ID AND LYR1.LAYER<LYR.LAYER              
LEFT join MNT_REINSURANCE_MAJORMINOR_PARTICIPATION MJR with(nolock) on MJR.CONTRACT_ID=CONT.CONTRACT_ID              
AND MJR.LAYER=LYR.LAYER              
join POL_CUSTOMER_POLICY_LIST pol with(nolock) on pol.POLICY_LOB = LOB.CONTRACT_LOB               
and pol.CUSTOMER_ID=@CUSTOMER_ID and pol.policy_id=@POLICY_ID and pol.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND ISNULL(POL.POLICY_EFFECTIVE_DATE,pol.APP_EFFECTIVE_DATE) <= ISNULL(CONT.TERMINATION_DATE,'3000-01-01')              
AND IsNULL(POL.POLICY_EFFECTIVE_DATE,POL.APP_EFFECTIVE_DATE) >= ISNULL(CONT.effective_date,'3000-01-01')  --added by Lalit July 28 2011.itrack # 1434              
AND ISNULL(DISREGARD_RI_CONTRACT,10964) =  10964 ----Disregard RI contract No.RI contract applicable on this policy.tfs# 180.itrack#  1492     
WHERE  CONT.IS_ACTIVE = 'Y'      
),              
FACULTATIVE              
AS              
(              
select RI.CUSTOMER_ID,RI.POLICY_ID,RI.POLICY_VERSION_ID,PCPL.POL_VER_EFFECTIVE_DATE,PCPL.POL_VER_EXPIRATION_DATE,              
PCPL.POLICY_NUMBER,PCPL.POLICY_LOB as LOB_ID,              
0 AS CONTRACT_ID,'Facultative' as CONTRACT_NUMBER,CONTRACT_FACULTATIVE as CONTRACT_TYPE,              
'Facultative' aS CONTRACT_DESC,RI.REINSURANCE_COMMISSION AS COMMISSION,YEAR(GETDATE()) AS CONTACT_YEAR,              
POLICY_EFFECTIVE_DATE AS EFFECTIVE_DATE,'3000-01-01' AS EXPIRATION_DATE,'3000-01-01' AS TERMINATION_DATE,              
10 AS SEQUENCE_NUMBER,NULL AS CONTRACT_NAME_ID,NULL AS COVERAGE_CODE,RI.COMPANY_ID AS REIN_COMPANY_ID,              
NULL AS WHOLE_PERCENT,1 AS LAYER,'1000000000000000' AS LAYER_AMOUNT, RI.REINSURANCE_CEDED AS REIN_CEDED_PERCENTAGE,              
'0' as REIN_CEDED,'0' AS RETENTION_AMOUNT,NULL AS RETENTION_PERCENTAGE,NULL AS PRE_LAYER,NULL AS PRE_LAYER_AMOUNT               
 ,RISK_ID as RISK_ID, ISNULL(REIN_PREMIUM,0) AS FACULTATIVE_REIN_PREMIUM, COMM_AMOUNT AS COMM_AMOUNT,            
  LAYER_AMOUNT AS FAC_LAYER_AMOUNT  --Added by aditya for tfs # 177            
 from POL_REINSURANCE_INFO RI with(nolock)                
JOIN POL_CUSTOMER_POLICY_LIST PCPL WITH(NOLOCK) ON PCPL.CUSTOMER_ID=RI.CUSTOMER_ID              
AND PCPL.POLICY_ID=RI.POLICY_ID AND PCPL.POLICY_VERSION_ID=RI.POLICY_VERSION_ID              
where RI.CUSTOMER_ID=@CUSTOMER_ID and RI.POLICY_ID=@POLICY_ID AND RI.POLICY_VERSION_ID=@POLICY_VERSION_ID and RI.IS_ACTIVE = 'Y'              
            
),              
--select * from CONTRACTS1              
              
CONTRACTS              
as(              
select A.*,B.LAYER as PRE_LAYER,B.LAYER_AMOUNT as PRE_LAYER_AMOUNT               
from CONTRACTS1 A              
left join CONTRACTS1 B on               
a.CUSTOMER_ID = b.CUSTOMER_ID and a.POLICY_ID = a.POLICY_ID and b.POLICY_VERSION_ID = b.POLICY_VERSION_ID              
and b.LAYER<a.LAYER              
),     
  
--select * from CONTRACTS           
--SELECT * FROM  MNT_LOOKUP_VALUES WHERE LOOKUP_ID= 1360              
/*              
PORTABLE_LOCATION as              
(              
SELECT LOCATION,--COVG.COV_ID,              
              
REPLACE(RTRIM((SELECT convert(varchar,PRODUCT_RISK_ID) + '' + ' ' FROM POL_PRODUCT_LOCATION_INFO A               
WHERE (A.CUSTOMER_ID=@CUSTOMER_ID and A.POLICY_ID=@POLICY_ID and A.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND A.LOCATION=LOC.LOCATION and A.PORTABLE_EQUIPMENT=10964) FOR XML PATH (''))),' ',',') AS RiskIDs,              
     
 SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670                
     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01          
     ELSE CAST(LIMIT AS DECIMAL(18,2))END              
    ELSE 0              
    END              
   ) as TIV,              
 SUM(CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 910 Monica's Note # 16               
  CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
  ELSE CAST(LIMIT AS DECIMAL(18,2))END              
 ELSE 0         
 END               
 ) as TOTAL_TIV,              
               
SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(written_prem AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(written_prem AS DECIMAL(18,2))END)              
  as PREMIUM,              
10964 as PORTABLE_EQUIPMENT              
              
FROM CLT_PREMIUM_SPLIT SPLT WITH(NOLOCK)              
JOIN CLT_PREMIUM_SPLIT_DETAILS SPLD WITH(NOLOCK) ON SPLT.UNIQUE_ID = SPLD.SPLIT_UNIQUE_ID              
JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= SPLD.COMP_EXT --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670              
JOIN POL_CUSTOMER_POLICY_LIST POL WITH(NOLOCK) ON  SPLT.CUSTOMER_ID=POL.CUSTOMER_ID AND SPLT.POLICY_ID=POL.POLICY_ID              
AND SPLT.POLICY_VERSION_ID= POL.POLICY_VERSION_ID               
LEFT JOIN POL_CO_INSURANCE CO with(nolock) on  SPLT.CUSTOMER_ID=CO.CUSTOMER_ID and SPLT.POLICY_ID=CO.POLICY_ID               
AND SPLT.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES              
              
JOIN POL_PRODUCT_LOCATION_INFO LOC WITH(NOLOCK) ON              
LOC.CUSTOMER_ID=POL.CUSTOMER_ID               
AND LOC.POLICY_ID=POL.POLICY_ID               
AND LOC.POLICY_VERSION_ID=POL.POLICY_VERSION_ID              
AND LOC.PRODUCT_RISK_ID = SPLT.RISK_ID              
AND LOC.PORTABLE_EQUIPMENT=10964              
              
WHERE SPLT.CUSTOMER_ID=@CUSTOMER_ID               
AND SPLT.POLICY_ID=@POLICY_ID AND SPLT.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND POL.POLICY_LOB='14' -- FOR 0171 Product              
group by LOCATION--,COVG.COV_ID              
              
UNION              
              
SELECT LOCATION,              
CONVERT(VARCHAR,RISK_ID) AS RiskIDs,              
               
 SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670                
     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
     ELSE CAST(LIMIT AS DECIMAL(18,2))END              
    ELSE 0              
    END              
   ) as TIV,              
              
 SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 910 Monica's Note # 16               
   CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(LIMIT AS DECIMAL(18,2))END              
   ELSE 0               
   END                
 ) as TOTAL_TIV,              
              
SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(written_prem AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(written_prem AS DECIMAL(18,2))END)              
   as PREMIUM,              
10963 as PORTABLE_EQUIPMENT                
FROM CLT_PREMIUM_SPLIT SPLT WITH(NOLOCK)              
JOIN CLT_PREMIUM_SPLIT_DETAILS SPLD WITH(NOLOCK) ON SPLT.UNIQUE_ID = SPLD.SPLIT_UNIQUE_ID              
JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= SPLD.COMP_EXT --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670              
JOIN POL_CUSTOMER_POLICY_LIST POL WITH(NOLOCK) ON  SPLT.CUSTOMER_ID=POL.CUSTOMER_ID AND SPLT.POLICY_ID=POL.POLICY_ID              
AND SPLT.POLICY_VERSION_ID= POL.POLICY_VERSION_ID               
LEFT JOIN POL_CO_INSURANCE CO with(nolock) on  SPLT.CUSTOMER_ID=CO.CUSTOMER_ID and SPLT.POLICY_ID=CO.POLICY_ID               
AND SPLT.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES              
              
JOIN POL_PRODUCT_LOCATION_INFO LOC WITH(NOLOCK) ON              
LOC.CUSTOMER_ID=POL.CUSTOMER_ID               
AND LOC.POLICY_ID=POL.POLICY_ID               
AND LOC.POLICY_VERSION_ID=POL.POLICY_VERSION_ID              
AND LOC.PRODUCT_RISK_ID = SPLT.RISK_ID              
AND LOC.PORTABLE_EQUIPMENT<>10964              
              
WHERE SPLT.CUSTOMER_ID=@CUSTOMER_ID               
AND SPLT.POLICY_ID=@POLICY_ID AND SPLT.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND POL.POLICY_LOB='14' -- FOR 0171 Product              
group by LOCATION,RISK_ID --,COVG.COV_ID              
)              
*/              
PORTABLE_LOCATION as              
(              
SELECT LOCATION,--COVG.COV_ID,              
              
REPLACE(RTRIM((SELECT convert(varchar,PRODUCT_RISK_ID) + '' + ' ' FROM POL_PRODUCT_LOCATION_INFO A               
WHERE (A.CUSTOMER_ID=@CUSTOMER_ID and A.POLICY_ID=@POLICY_ID and A.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND A.LOCATION=LOC.LOCATION and A.PORTABLE_EQUIPMENT=10964) FOR XML PATH (''))),' ',',') AS RiskIDs,              
              
 SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670                
     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT_1 AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
     ELSE CAST(LIMIT_1 AS DECIMAL(25,2))END              
    ELSE 0              
    END              
   ) as TIV,              
 SUM(CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 910 Monica's Note # 16               
  CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT_1 AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
  ELSE CAST(LIMIT_1 AS DECIMAL(25,2))END              
 ELSE 0              
 END               
 ) as TOTAL_TIV,              
               
SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(WRITTEN_PREMIUM AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(WRITTEN_PREMIUM AS DECIMAL(25,2))END)              
   as PREMIUM,              
10964 as PORTABLE_EQUIPMENT              
              
FROM POL_PRODUCT_COVERAGES (NOLOCK) PPC               
JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= PPC.COVERAGE_CODE_ID --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670              
JOIN POL_CUSTOMER_POLICY_LIST POL WITH(NOLOCK) ON  PPC.CUSTOMER_ID=POL.CUSTOMER_ID AND PPC.POLICY_ID=POL.POLICY_ID              
AND PPC.POLICY_VERSION_ID= POL.POLICY_VERSION_ID               
LEFT JOIN POL_CO_INSURANCE CO with(nolock) on  PPC.CUSTOMER_ID=CO.CUSTOMER_ID and PPC.POLICY_ID=CO.POLICY_ID               
AND PPC.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES              
              
JOIN POL_PRODUCT_LOCATION_INFO LOC WITH(NOLOCK) ON              
LOC.CUSTOMER_ID=POL.CUSTOMER_ID               
AND LOC.POLICY_ID=POL.POLICY_ID               
AND LOC.POLICY_VERSION_ID=POL.POLICY_VERSION_ID              
AND LOC.PRODUCT_RISK_ID = PPC.RISK_ID              
AND LOC.PORTABLE_EQUIPMENT=10964              
              
WHERE PPC.CUSTOMER_ID=@CUSTOMER_ID               
AND PPC.POLICY_ID=@POLICY_ID AND PPC.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND POL.POLICY_LOB='14' -- FOR 0171 Product              
group by LOCATION--,COVG.COV_ID              
              
UNION              
              
SELECT LOCATION,              
CONVERT(VARCHAR,RISK_ID) AS RiskIDs,              
               
 SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670                
     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT_1 AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
     ELSE CAST(LIMIT_1 AS DECIMAL(25,2))END              
    ELSE 0              
    END              
   ) as TIV,              
              
 SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 910 Monica's Note # 16               
   CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT_1 AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(LIMIT_1 AS DECIMAL(25,2))END              
   ELSE 0               
   END                
 ) as TOTAL_TIV,              
              
SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(WRITTEN_PREMIUM AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(WRITTEN_PREMIUM AS DECIMAL(25,2))END)              
   as PREMIUM,              
10963 as PORTABLE_EQUIPMENT                
FROM  POL_PRODUCT_COVERAGES (NOLOCK) PPC               
JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= PPC.COVERAGE_CODE_ID --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670              
JOIN POL_CUSTOMER_POLICY_LIST POL WITH(NOLOCK) ON  PPC.CUSTOMER_ID=POL.CUSTOMER_ID AND PPC.POLICY_ID=POL.POLICY_ID              
AND PPC.POLICY_VERSION_ID= POL.POLICY_VERSION_ID               
LEFT JOIN POL_CO_INSURANCE CO with(nolock) on  PPC.CUSTOMER_ID=CO.CUSTOMER_ID and PPC.POLICY_ID=CO.POLICY_ID               
AND PPC.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES              
              
JOIN POL_PRODUCT_LOCATION_INFO LOC WITH(NOLOCK) ON              
LOC.CUSTOMER_ID=POL.CUSTOMER_ID               
AND LOC.POLICY_ID=POL.POLICY_ID               
AND LOC.POLICY_VERSION_ID=POL.POLICY_VERSION_ID              
AND LOC.PRODUCT_RISK_ID = PPC.RISK_ID              
AND LOC.PORTABLE_EQUIPMENT<>10964              
AND LOC.IS_ACTIVE='Y'              
              
WHERE PPC.CUSTOMER_ID=@CUSTOMER_ID               
AND PPC.POLICY_ID=@POLICY_ID AND PPC.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND POL.POLICY_LOB='14' -- FOR 0171 Product              
group by LOCATION,RISK_ID --,COVG.COV_ID              
)              
--select * from PORTABLE_LOCATION              
,              
RISKS as              
(              
/*              
SELECT --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,              
convert(nvarchar,RISK_ID) as RISK_ID,              
SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670                
     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
     ELSE CAST(LIMIT AS DECIMAL(18,2))END              
    ELSE 0              
    END              
   ) AS TIV,              
SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 910 Monica's Note # 16               
   CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
     ELSE CAST(LIMIT AS DECIMAL(18,2))END              
  ELSE 0              
     END                  
 ) AS TOTAL_TIV,                    
--SUM(written_prem) as PREMIUM              
SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(written_prem AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(written_prem AS DECIMAL(18,2))END) AS PREMIUM              
FROM CLT_PREMIUM_SPLIT SPLT WITH(NOLOCK)              
JOIN CLT_PREMIUM_SPLIT_DETAILS SPLD WITH(NOLOCK) ON SPLT.UNIQUE_ID = SPLD.SPLIT_UNIQUE_ID              
JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= SPLD.COMP_EXT --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670              
JOIN POL_CUSTOMER_POLICY_LIST POL WITH(NOLOCK) ON  SPLT.CUSTOMER_ID=POL.CUSTOMER_ID AND SPLT.POLICY_ID=POL.POLICY_ID              
AND SPLT.POLICY_VERSION_ID= POL.POLICY_VERSION_ID               
LEFT JOIN POL_CO_INSURANCE CO with(nolock) on  SPLT.CUSTOMER_ID=CO.CUSTOMER_ID and SPLT.POLICY_ID=CO.POLICY_ID               
AND SPLT.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES              
              
WHERE SPLT.CUSTOMER_ID=@CUSTOMER_ID               
and SPLT.POLICY_ID=@POLICY_ID AND SPLT.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND POL.POLICY_LOB<>'14' -- FOR other then 0171 Product              
GROUP BY --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,RISK_ID              
RISK_ID              
*/         
         
SELECT --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,            
convert(nvarchar,PV.VEHICLE_ID) as RISK_ID,            
--SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670              
--     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01              
--     ELSE CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2))END            
--    ELSE 0            
--    END            
--   )           
CAST(PBD.NET_AMOUNT AS DECIMAL(25,2)) AS TIV,            
--SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 910 Monica's Note # 16             
--   CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01              
--     ELSE CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2))END            
--  ELSE 0            
--     END                
-- )           
 CAST(PBD.NET_AMOUNT AS DECIMAL(25,2)) AS TOTAL_TIV,                  
--SUM(written_prem) as PREMIUM            
--SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01              
--   ELSE CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2))END)           
  CAST(PBD.NET_AMOUNT AS DECIMAL(25,2))  AS PREMIUM         
  FROM POL_BILLING_DETAILS PBD        
LEFT OUTER JOIN  POL_CUSTOMER_POLICY_LIST POL (NOLOCK) ON PBD.CUSTOMER_ID = POL.CUSTOMER_ID AND PBD.POLICY_ID = POL.POLICY_ID AND PBD.POLICY_VERSION_ID = POL.POLICY_VERSION_ID     
LEFT OUTER JOIN POL_PRODUCT_COVERAGES  PPC WITH(NOLOCK) ON  PPC.CUSTOMER_ID=POL.CUSTOMER_ID AND PPC.POLICY_ID=POL.POLICY_ID             
LEFT OUTER JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= PPC.COVERAGE_CODE_ID --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670            
LEFT OUTER JOIN POL_VEHICLES PV WITH(NOLOCK) ON  PV.CUSTOMER_ID=POL.CUSTOMER_ID AND PV.POLICY_ID=POL.POLICY_ID           
AND PV.POLICY_VERSION_ID= POL.POLICY_VERSION_ID             
LEFT outer JOIN POL_CO_INSURANCE CO with(nolock) on  PPC.CUSTOMER_ID=CO.CUSTOMER_ID and PPC.POLICY_ID=CO.POLICY_ID             
AND PPC.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES            
            
WHERE POL.CUSTOMER_ID= @CUSTOMER_ID             
and POL.POLICY_ID= @POLICY_ID AND POL.POLICY_VERSION_ID=@POLICY_VERSION_ID            
AND POL.POLICY_LOB<>'14' AND POLICY_LOB <> '1' -- FOR other then 0171 Product            
--GROUP BY --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,RISK_ID            
--RISK_ID            
UNION              
select RiskIDs as RISK_ID,TIV,TOTAL_TIV,PREMIUM  from PORTABLE_LOCATION       
UNION      
 SELECT --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,            
convert(nvarchar,PV.DWELLING_ID) as RISK_ID,            
--SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670              
--     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01              
--   ELSE CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2))END            
--    ELSE 0            
--    END            
--   )           
CAST(POL.NET_AMOUNT AS DECIMAL(25,2)) AS TIV,            
--SUM( CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 910 Monica's Note # 16             
--   CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01              
--     ELSE CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2))END            
--  ELSE 0            
--     END                
-- )           
 CAST(POL.NET_AMOUNT AS DECIMAL(25,2)) AS TOTAL_TIV,                  
--SUM(written_prem) as PREMIUM            
--SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01              
-- ELSE CAST(POL.RECEIVED_PRMIUM AS DECIMAL(25,2))END)           
  CAST(POL.NET_AMOUNT  AS DECIMAL(25,2))  AS PREMIUM            
FROM  POL_BILLING_DETAILS (NOLOCK) POL           
LEFT OUTER JOIN POL_CUSTOMER_POLICY_LIST POLICY WITH(NOLOCK) ON POLICY.CUSTOMER_ID=POL.CUSTOMER_ID AND POLICY.POLICY_ID=POL.POLICY_ID  AND POLICY.POLICY_VERSION_ID = POL.POLICY_VERSION_ID            
LEFT OUTER JOIN POL_PRODUCT_COVERAGES  PPC WITH(NOLOCK) ON  PPC.CUSTOMER_ID=POL.CUSTOMER_ID AND PPC.POLICY_ID=POL.POLICY_ID             
LEFT OUTER JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= PPC.COVERAGE_CODE_ID --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670            
          
LEFT OUTER JOIN POL_DWELLINGS_INFO PV WITH(NOLOCK) ON  PV.CUSTOMER_ID=POL.CUSTOMER_ID AND PV.POLICY_ID=POL.POLICY_ID           
AND PV.POLICY_VERSION_ID= POL.POLICY_VERSION_ID             
LEFT outer JOIN POL_CO_INSURANCE CO with(nolock) on  PPC.CUSTOMER_ID=CO.CUSTOMER_ID and PPC.POLICY_ID=CO.POLICY_ID             
AND PPC.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES            
            
WHERE POL.CUSTOMER_ID= @CUSTOMER_ID             
and POL.POLICY_ID= @POLICY_ID AND POL.POLICY_VERSION_ID=@POLICY_VERSION_ID            
AND POLICY.POLICY_LOB = '1' -- FOR other then 0171 Product            
--GROUP BY --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,RISK_ID            
--RISK_ID             
           
/*              
SELECT --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,              
RISK_ID,              
SUM(CASE WHEN LOC.PORTABLE_EQUIPMENT=10964 and PLOC.LOCATION = LOC.LOCATION THEN isnull(PLOC.TIV,0)              
ELSE               
   CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 670                
     CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
     ELSE CAST(LIMIT AS DECIMAL(18,2))END              
   ELSE 0              
   END              
END ) AS TIV,              
SUM( CASE WHEN LOC.PORTABLE_EQUIPMENT=10964 and PLOC.LOCATION = LOC.LOCATION THEN isnull(PLOC.TIV,0)              
ELSE              
   CASE WHEN  COVG.REINSURANCE_LOB=10963 THEN -- ADDED AS PER iTRACK 910 Monica's Note # 16               
    CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0))=0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
     ELSE CAST(LIMIT AS DECIMAL(18,2))END              
 ELSE 0              
 END                   
END                   
) AS TOTAL_TIV,                
--SUM(written_prem) as PREMIUM              
SUM(CASE WHEN LOC.PORTABLE_EQUIPMENT=10964 and PLOC.LOCATION = LOC.LOCATION THEN isnull(PLOC.PREMIUM,0)              
ELSE              
 CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(written_prem AS DECIMAL(18,2)) * case when (ISNULL(CO.COINSURANCE_PERCENT,0)) = 0 then 100 else (ISNULL(CO.COINSURANCE_PERCENT,0)) end * 0.01                
   ELSE CAST(written_prem AS DECIMAL(18,2))END              
END) AS PREMIUM              
FROM CLT_PREMIUM_SPLIT SPLT WITH(NOLOCK)              
JOIN CLT_PREMIUM_SPLIT_DETAILS SPLD WITH(NOLOCK) ON SPLT.UNIQUE_ID = SPLD.SPLIT_UNIQUE_ID              
JOIN MNT_COVERAGE COVG WITH(NOLOCK) ON  COVG.COV_ID= SPLD.COMP_EXT --AND COVG.REINSURANCE_LOB=10963 -- channged asper Itrack 670              
JOIN POL_CUSTOMER_POLICY_LIST POL WITH(NOLOCK) ON  SPLT.CUSTOMER_ID=POL.CUSTOMER_ID AND SPLT.POLICY_ID=POL.POLICY_ID              
AND SPLT.POLICY_VERSION_ID= POL.POLICY_VERSION_ID               
LEFT JOIN POL_CO_INSURANCE CO with(nolock) on  SPLT.CUSTOMER_ID=CO.CUSTOMER_ID and SPLT.POLICY_ID=CO.POLICY_ID               
AND SPLT.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES              
              
JOIN POL_PRODUCT_LOCATION_INFO LOC WITH(NOLOCK) ON              
LOC.CUSTOMER_ID=@CUSTOMER_ID               
AND LOC.POLICY_ID=@POLICY_ID               
AND LOC.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND LOC.PRODUCT_RISK_ID = SPLT.RISK_ID              
--AND LOC.PORTABLE_EQUIPMENT=10964              
LEFT JOIN PORTABLE_LOCATION PLOC ON PLOC.LOCATION = LOC.LOCATION and PLOC.COV_ID =COVG.COV_ID              
              
WHERE SPLT.CUSTOMER_ID=@CUSTOMER_ID               
AND SPLT.POLICY_ID=@POLICY_ID AND SPLT.POLICY_VERSION_ID=@POLICY_VERSION_ID              
AND POL.POLICY_LOB='14' -- FOR 0171 Product              
GROUP BY --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,RISK_ID              
RISK_ID              
*/              
)              
--select * from RISKS               
,              
/*              
RISKS AS              
(              
SELECT --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,              
RISK_ID,--SUM(LIMIT_1) AS TIV,              
SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(LIMIT_1 AS DECIMAL(18,2)) * (100-ISNULL(CO.COINSURANCE_PERCENT,0)) * 0.01 ELSE CAST(LIMIT_1 AS DECIMAL(18,2))END) AS TIV,              
--SUM(written_premium) as PREMIUM              
SUM(CASE WHEN POL.CO_INSURANCE=14548 THEN CAST(WRITTEN_PREMIUM AS DECIMAL(18,2)) * (100-ISNULL(CO.COINSURANCE_PERCENT,0))* 0.01  ELSE CAST(WRITTEN_PREMIUM AS DECIMAL(18,2))END) AS PREMIUM              
              
FROM POL_PRODUCT_COVERAGES pr              
join POL_CUSTOMER_POLICY_LIST pol with(nolock) on  PR.CUSTOMER_ID=POL.CUSTOMER_ID and PR.POLICY_ID=POL.POLICY_ID               
AND PR.POLICY_VERSION_ID= POL.POLICY_VERSION_ID               
LEFT JOIN POL_CO_INSURANCE CO with(nolock) on  PR.CUSTOMER_ID=CO.CUSTOMER_ID and PR.POLICY_ID=CO.POLICY_ID               
AND PR.POLICY_VERSION_ID=CO.POLICY_VERSION_ID AND CO.LEADER_FOLLOWER = 14548 -- LEADER YES              
              
WHERE pr.CUSTOMER_ID=@CUSTOMER_ID and PR.POLICY_ID=@POLICY_ID              
GROUP BY --pr.CUSTOMER_ID,pr.POLICY_ID,pr.POLICY_VERSION_ID,RISK_ID              
RISK_ID              
),              
*/              
-- Contract type 1-Quota Share, 2-Surplus              
RI_PREMIUM1 AS              
(              
select CON.CUSTOMER_ID,CON.POLICY_ID,CON.POLICY_VERSION_ID,              
RISKS.RISK_ID,TIV,PREMIUM AS PREMIUM,CONTRACT_DESC,CONTRACT_ID,CONTRACT_NUMBER,REIN_COMPANY_ID,CONTRACT_TYPE,COMMISSION,LAYER,LAYER_AMOUNT AS ACT_LAYER_AMOUNT,
REIN_CEDED,REIN_CEDED_PERCENTAGE,RETENTION_AMOUNT,RETENTION_PERCENTAGE,          
   
CON.POL_VER_EFFECTIVE_DATE,CON.POL_VER_EXPIRATION_DATE,CON.POLICY_NUMBER,CON.LOB_ID,CON.CONTACT_YEAR,CON.SEQUENCE_NUMBER,              
--CAST(TIV AS DECIMAL(18,2)) as TIV1,CON.PRE_LAYER_AMOUNT,              
--(CAST(TIV AS DECIMAL(18,2)) -  CAST(REPLACE(ISNULL(CON.PRE_LAYER_AMOUNT,0),',','') AS DECIMAL(18,2)) ) as TIV2,              
CASE               
 WHEN CONTRACT_TYPE=39 THEN -- IF CONTRACT TYPE IS QUOTA SHARE APPLY %AGE ITRACK 910 discussed with Monica(system supposed to have only one layer per contract with increasing layer number              
  CASE               
  WHEN CAST(TIV AS DECIMAL(25,2)) >  CAST(REPLACE(LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
  THEN (CAST(REPLACE(LAYER_AMOUNT,',','') AS decimal(25,2)) - CAST(REPLACE(ISNULL(PRE_LAYER_AMOUNT,0),',','') AS DECIMAL(25,2))) * CAST(REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01               
  WHEN CAST(TIV AS DECIMAL(25,2)) <=  CAST(REPLACE(LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
  THEN (CAST(TIV AS DECIMAL(25,2)) -  CAST(REPLACE(ISNULL(CON.PRE_LAYER_AMOUNT,0),',','') AS DECIMAL(25,2)) )              
    * CAST(REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01                
 ELSE              
 0 END              
               
 WHEN CONTRACT_TYPE=40 THEN -- IF CONTRACT TYPE IS SURPLUS APPLY RETENTION AMOUNT              
 CASE               
   WHEN CAST(TIV AS DECIMAL(25,2)) >  CAST(REPLACE(LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
   THEN (CAST(REPLACE(LAYER_AMOUNT,',','') AS decimal(25,2)) - CAST(REPLACE(ISNULL(PRE_LAYER_AMOUNT,RETENTION_AMOUNT),',','') AS DECIMAL(25,2))) --* CAST(REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01               
   WHEN CAST(TIV AS DECIMAL(25,2)) <=  CAST(REPLACE(LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
   THEN (CAST(TIV AS DECIMAL(25,2)) -  CAST(REPLACE(ISNULL(CON.PRE_LAYER_AMOUNT,RETENTION_AMOUNT),',','') AS DECIMAL(25,2)) )              
    -- * CAST(REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01  -- commented on 17 march 2011 refer Itrack 910, calculation change to Retention amount discussed with Rajan              
 ELSE              
 0 END              
ELSE              
0              
END               
AS LAYER_AMOUNT   ,            
'0' AS FACULTATIVE_REIN_PREMIUM,            
'0' AS COMM_AMOUNT                 
FROM RISKS,CONTRACTS CON              
              
UNION              
              
select FAC.CUSTOMER_ID,FAC.POLICY_ID,FAC.POLICY_VERSION_ID,              
RISKS.RISK_ID,case when FAC.CONTRACT_TYPE=14628 then TOTAL_TIV else TIV end as TIV,              
PREMIUM AS PREMIUM,FAC.CONTRACT_DESC,FAC.CONTRACT_ID,FAC.CONTRACT_NUMBER,FAC.REIN_COMPANY_ID,              
FAC.CONTRACT_TYPE,FAC.COMMISSION,FAC.LAYER,FAC.LAYER_AMOUNT AS ACT_LAYER_AMOUNT,              
--FAC.REIN_CEDED,FAC.REIN_CEDED_PERCENTAGE,FAC.RETENTION_AMOUNT,FAC.RETENTION_PERCENTAGE,              
--TIV*FAC.REIN_CEDED_PERCENTAGE * 0.01 as REIN_CEDED,FAC.REIN_CEDED_PERCENTAGE,TIV*(100-FAC.REIN_CEDED_PERCENTAGE)*0.01 as RETENTION_AMOUNT,(100-FAC.REIN_CEDED_PERCENTAGE) as RETENTION_PERCENTAGE,              
case when FAC.CONTRACT_TYPE=14628 then TOTAL_TIV else TIV end*FAC.REIN_CEDED_PERCENTAGE * 0.01 as REIN_CEDED,FAC.REIN_CEDED_PERCENTAGE,              
case when FAC.CONTRACT_TYPE=14628 then TOTAL_TIV else TIV end*(100-FAC.REIN_CEDED_PERCENTAGE)*0.01 as RETENTION_AMOUNT,(100-FAC.REIN_CEDED_PERCENTAGE) as RETENTION_PERCENTAGE,              
FAC.POL_VER_EFFECTIVE_DATE,FAC.POL_VER_EXPIRATION_DATE,FAC.POLICY_NUMBER,FAC.LOB_ID,FAC.CONTACT_YEAR,FAC.SEQUENCE_NUMBER,              
--CAST(TIV AS DECIMAL(18,2)) as TIV1,CON.PRE_LAYER_AMOUNT,              
CASE               
 WHEN FAC.CONTRACT_TYPE=1 THEN -- IF CONTRACT TYPE IS QUOTA SHARE APPLY %AGE ITRACK 910 discussed with Monica(system supposed to have only one layer per contract with increasing layer number              
 CASE               
  WHEN CAST(TIV AS DECIMAL(25,2)) >  CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
  THEN (CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS decimal(25,2)) - CAST(REPLACE(ISNULL(FAC.PRE_LAYER_AMOUNT,0),',','') AS DECIMAL(25,2))) * CAST(FAC.REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01               
  WHEN CAST(TIV AS DECIMAL(25,2)) <=  CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
  THEN (CAST(TIV AS DECIMAL(25,2)) -  CAST(REPLACE(ISNULL(FAC.PRE_LAYER_AMOUNT,0),',','') AS DECIMAL(25,2)) )              
   * CAST(FAC.REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01   --commented on 17 march 2011 refer Itrack 910              
 ELSE              
 0 END              
 WHEN FAC.CONTRACT_TYPE=2 THEN -- IF CONTRACT TYPE IS SURPLUS APPLY RETENTION AMOUNT              
 CASE               
   WHEN CAST(TIV AS DECIMAL(25,2)) >  CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
   THEN (CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS decimal(25,2)) - CAST(REPLACE(ISNULL(FAC.PRE_LAYER_AMOUNT,FAC.RETENTION_AMOUNT),',','') AS DECIMAL(25,2))) --* CAST(REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01               
   WHEN CAST(TIV AS DECIMAL(25,2)) <=  CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
   THEN (CAST(TIV AS DECIMAL(25,2)) -  CAST(REPLACE(ISNULL(FAC.PRE_LAYER_AMOUNT,FAC.RETENTION_AMOUNT),',','') AS DECIMAL(25,2)) )              
    -- * CAST(REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01  -- commented on 17 march 2011 refer Itrack 910, calculation change to Retention amount discussed with Rajan              
 ELSE              
 0 END              
WHEN FAC.CONTRACT_TYPE=14628 THEN -- IF CONTRACT TYPE facultative set at Policy level under Reinsurance tab            
CASE WHEN FAC.FAC_LAYER_AMOUNT IS NOT NULL THEN FAC.FAC_LAYER_AMOUNT ELSE  --Added by aditya for tfs # 177            
 CASE               
   WHEN CAST(TOTAL_TIV AS DECIMAL(25,2)) >  CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
   THEN (CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS decimal(25,2)) - CAST(REPLACE(ISNULL(FAC.PRE_LAYER_AMOUNT,FAC.RETENTION_AMOUNT),',','') AS DECIMAL(25,2))) --* CAST(REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01               
   WHEN CAST(TOTAL_TIV AS DECIMAL(25,2)) <=  CAST(REPLACE(FAC.LAYER_AMOUNT,',','') AS DECIMAL(25,2))               
   THEN (CAST(TOTAL_TIV AS DECIMAL(25,2)) -  CAST(REPLACE(ISNULL(FAC.PRE_LAYER_AMOUNT,FAC.RETENTION_AMOUNT),',','') AS DECIMAL(25,2)) )              
     * CAST(FAC.REIN_CEDED_PERCENTAGE AS DECIMAL(10,2)) * 0.01  -- commented on 17 march 2011 refer Itrack 910, calculation change to Retention amount discussed with Rajan              
 ELSE              
 0 END             
 END              
ELSE              
0              
END                
AS LAYER_AMOUNT   ,            
FACULTATIVE_REIN_PREMIUM   ,            
COMM_AMOUNT AS COMM_AMOUNT            
              
--FROM RISKS, CONTRACTS CON, FACULTATIVE FAC               
FROM RISKS, FACULTATIVE FAC              
 where FAC.RISK_ID = RISKS.RISK_ID            
/*WHERE               
(              
CAST(TIV AS DECIMAL(18,2)) >  CAST(REPLACE(CON.LAYER_AMOUNT,',','') AS DECIMAL(18,2))              
AND CON.LAYER =              
 (              
 SELECT MAX(LAYER) FROM CONTRACTS              
 WHERE CUSTOMER_ID=CON.CUSTOMER_ID AND POLICY_ID=CON.POLICY_ID              
 AND POLICY_VERSION_ID=CON.POLICY_VERSION_ID AND CONTRACT_ID = CON.CONTRACT_ID              
 )              
)*/              
)               
--SELECT * FROM RI_PREMIUM1              
,              
RI_PREMIUM              
AS              
(              
SELECT               
CUSTOMER_ID,POLICY_ID,POLICY_VERSION_ID,              
RISK_ID,TIV,PREMIUM,CONTRACT_DESC,CONTRACT_ID,CONTRACT_NUMBER,REIN_COMPANY_ID,              
POL_VER_EFFECTIVE_DATE,POL_VER_EXPIRATION_DATE,POLICY_NUMBER,LOB_ID,CONTACT_YEAR,SEQUENCE_NUMBER,              
CONTRACT_TYPE,COMMISSION,LAYER,              
cast(LAYER_AMOUNT as numeric(25,2)) AS ACT_LAYER_AMOUNT,    
cast(REIN_CEDED as numeric(25,2)) as REIN_CEDED,REIN_CEDED_PERCENTAGE,              
cast(RETENTION_AMOUNT as numeric(25,2)) as RETENTION_AMOUNT,              
              
cast(case when TIV<= RETENTION_AMOUNT THEN  RETENTION_PERCENTAGE              
      when CONTRACT_TYPE = 1 or LAYER= 1 THEN cast(RETENTION_AMOUNT/TIV AS decimal(12,4))*100               
  else null end as decimal(25,3) ) as RETENTION_PERCENTAGE, -- since in second or above layer 100% would be cedded              
              
cast(REIN_CEDED as numeric(25,2)) as LAYER_AMOUNT,              
              
case when CONTRACT_TYPE=14628 then REIN_CEDED_PERCENTAGE else              
cast(100*LAYER_AMOUNT/TIV as decimal(12,3))              
end              
AS LAYER_PER,              
case when CONTRACT_TYPE=14628 then CASE WHEN FACULTATIVE_REIN_PREMIUM <> 0 THEN FACULTATIVE_REIN_PREMIUM ELSE  cast(REIN_CEDED_PERCENTAGE * PREMIUM * 0.01 as decimal(25,3)) END else              
cast((cast(100*LAYER_AMOUNT/TIV as decimal(12,4)))*PREMIUM * 0.01 as decimal(25,3))              
end              
AS RI_LAYER_PREM,              
case when CONTRACT_TYPE=14628 then CASE WHEN COMM_AMOUNT IS NOT NULL THEN COMM_AMOUNT ELSE  cast(REIN_CEDED_PERCENTAGE * PREMIUM * 0.01 * COMMISSION * 0.01 as decimal(25,3)) END else              
cast(((cast(100*LAYER_AMOUNT/TIV as decimal(12,4)))*PREMIUM * 0.01)* COMMISSION * 0.01 as decimal(25,3))               
end              
AS RI_LAYER_PREM_COMM              
              
 FROM  RI_PREMIUM1              
 where --TIV<>0 AND               
 PREMIUM<>0              
 and case when CONTRACT_TYPE=14628 then 1 else TIV end <>               
     case when CONTRACT_TYPE=14628 then 2 else 0 end              
)              
              
--select * from RI_PREMIUM              
--WHERE LAYER_AMOUNT > 0              
--ORDER BY RISK_ID,LAYER              
--  
select * into RI_PREMIUM_temp from RI_PREMIUM     
--select * from RI_PREMIUM1
            
              
if not exists(select * from POL_REINSURANCE_BREAKDOWN_DETAILS where CUSTOMER_ID=@CUSTOMER_ID and POLICY_ID=@POLICY_ID and POLICY_VERSION_ID=@POLICY_VERSION_ID)              
begin              
              
insert into POL_REINSURANCE_BREAKDOWN_DETAILS (              
CUSTOMER_ID,POLICY_ID,POLICY_VERSION_ID,              
LOB_ID,              
--STATE_ID,              
POLICY_NUMBER,              
--INSURED_NAME,ADDRESS,CITY,ZIP_CODE,              
--LOB_DESC,STATE_DESC,              
APP_EFFECTIVE_DATE,APP_EXPIRATION_DATE,              
--REINS_SPECIAL_ACPT,              
--PROCESS_TRAN_DATE,TRAN_EFF_DATE,TRAN_DESC,              
MONTH_NUMBER,YEAR_NUMBER,              
SEQUENCE_NUMBER,              
--COV_CATEGORY_ID,COMPLETED,              
--STATEMENT_DATE,              
CONTRACT_NUMBER,              
--PREMIUM_BASE,        
CONTRACT_YEAR,              
TOTAL_INS_VALUE,              
TIV_GROUP,              
LAYER,LAYER_AMOUNT,              
REIN_LIMIT_FAB,              
--COV_CATEGORY,              
TRAN_PREMIUM,              
--EARNED,WRITTEN,              
--CONSTRACTION,PROTECTION,CENTRAL_ALARM,NEW_HOME,HOME_AGE,DEDUCT_LAYER_1,DEDUCT_LAYER_2              
RATE,REIN_PREMIUM,COMM_PERCENTAGE,COMM_AMOUNT,              
--NET_DUE              
MAJOR_PARTICIPANT,              
RETENTION_PER,REIN_CEDED,              
RISK_ID,              
PROCESS_ID              
)              
              
SELECT               
CUSTOMER_ID,POLICY_ID,POLICY_VERSION_ID,              
LOB_ID,              
POLICY_NUMBER,              
POL_VER_EFFECTIVE_DATE,POL_VER_EXPIRATION_DATE,              
month(GETDATE()),              
YEAR(getdate()),              
SEQUENCE_NUMBER,              
CONTRACT_NUMBER,              
CONTACT_YEAR,              
TIV,              
0, -- FOR TIV GROUP              
LAYER,ACT_LAYER_AMOUNT,              
0, -- REIN_FAB              
PREMIUM,              
--CONTRACT_DESC,CONTRACT_ID,CONTRACT_TYPE,              
COMMISSION,              
--RETENTION_AMOUNT,              
--LAYER_AMOUNT,              
RI_LAYER_PREM,              
LAYER_PER,            
--REIN_CEDED_PERCENTAGE,              
RI_LAYER_PREM_COMM,              
REIN_COMPANY_ID,              
RETENTION_PERCENTAGE,              
REIN_CEDED,              
RISK_ID,              
@PROCESS_ID              
 FROM RI_PREMIUM_temp              
WHERE  LAYER_AMOUNT > 0              
ORDER BY RISK_ID,LAYER              
end              
              
drop table RI_PREMIUM_temp     
--select * from POL_REINSURANCE_BREAKDOWN_DETAILS where CUSTOMER_ID = @CUSTOMER_ID and POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID   
end  
--go  
--EXEC [Proc_InsertPOL_REINSURANCE_BREAKDOWN_DETAILS]  28814,497,1,924, 0  
------SELECT * FROM POL_REINSURANCE_BREAKDOWN_DETAILS WHERE CUSTOMER_ID = 2185 AND POLICY_ID = 22 AND POLICY_VERSION_ID = 1  
--ROLLBACK TRAN            
  
  
--select * from POL_REINSURANCE_BREAKDOWN_DETAILS where CUSTOMER_ID = 2185 and POLICY_ID = 28  
             
            