IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROC_DELETEVOYAGEINFO]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[PROC_DELETEMARITIME]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

  
CREATE PROC [dbo].[PROC_DELETEVOYAGEINFO]    
(     
 @VOYAGE_ID  INT ,  
 @CUSTOMER_ID INT,      
 @POLICY_ID INT,      
 @POLICY_VERSION_ID INT  
      
)                
AS                
BEGIN                
    
  DELETE FROM POL_MARINE_CARGO_VOYAGE_INFO WHERE CUSTOMER_ID=@CUSTOMER_ID AND  POLICY_ID=@POLICY_ID AND    POLICY_VERSION_ID=@POLICY_VERSION_ID  AND VOYAGE_ID=@VOYAGE_ID    

END         
    

GO


