//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAS.Web.Objects.Resources.ClaimProcessing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ClaimLogRequest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ClaimLogRequest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCAS.Web.Objects.Resources.ClaimProcessing.ClaimLogRequest", typeof(ClaimLogRequest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant Name.
        /// </summary>
        public static string ClaimantNameId {
            get {
                return ResourceManager.GetString("ClaimantNameId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Log Processing.
        /// </summary>
        public static string ClaimLogProcessing {
            get {
                return ResourceManager.GetString("ClaimLogProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim No.
        /// </summary>
        public static string ClaimNo {
            get {
                return ResourceManager.GetString("ClaimNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim Registrations.
        /// </summary>
        public static string ClaimRegistrations {
            get {
                return ResourceManager.GetString("ClaimRegistrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO&apos;s Remarks.
        /// </summary>
        public static string CORemarks {
            get {
                return ResourceManager.GetString("CORemarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        public static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital.
        /// </summary>
        public static string Hospital {
            get {
                return ResourceManager.GetString("Hospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Name.
        /// </summary>
        public static string Hospital_Id {
            get {
                return ResourceManager.GetString("Hospital_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG Amount.
        /// </summary>
        public static string LOGAmount {
            get {
                return ResourceManager.GetString("LOGAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG Date.
        /// </summary>
        public static string LOGDate {
            get {
                return ResourceManager.GetString("LOGDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG No.
        /// </summary>
        public static string LOGNo {
            get {
                return ResourceManager.GetString("LOGNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG Ref No.
        /// </summary>
        public static string LOGRefNo {
            get {
                return ResourceManager.GetString("LOGRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG Request.
        /// </summary>
        public static string LOGRequest {
            get {
                return ResourceManager.GetString("LOGRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG Request Details.
        /// </summary>
        public static string LOGRequestDetails {
            get {
                return ResourceManager.GetString("LOGRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandate No.
        /// </summary>
        public static string MandateNo {
            get {
                return ResourceManager.GetString("MandateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By.
        /// </summary>
        public static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified Date.
        /// </summary>
        public static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New LOG Processing.
        /// </summary>
        public static string NewLOGProcessing {
            get {
                return ResourceManager.GetString("NewLOGProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New LOG Request.
        /// </summary>
        public static string NewLOGRequest {
            get {
                return ResourceManager.GetString("NewLOGRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claimant Name is required..
        /// </summary>
        public static string RFVClaimantName {
            get {
                return ResourceManager.GetString("RFVClaimantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hospital Name is required..
        /// </summary>
        public static string RFVHospitalName {
            get {
                return ResourceManager.GetString("RFVHospitalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG Date is required..
        /// </summary>
        public static string RFVLOGDate {
            get {
                return ResourceManager.GetString("RFVLOGDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search screen.
        /// </summary>
        public static string searchscreen {
            get {
                return ResourceManager.GetString("searchscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Claim No.
        /// </summary>
        public static string SubClaimNo {
            get {
                return ResourceManager.GetString("SubClaimNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Claim No.
        /// </summary>
        public static string SubClaimNo_ {
            get {
                return ResourceManager.GetString("SubClaimNo_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Void.
        /// </summary>
        public static string Void {
            get {
                return ResourceManager.GetString("Void", resourceCulture);
            }
        }
    }
}
