/***********************
itrack -1663
created by ankit kr goel
*****************/
DROP VIEW [VW_REPORT_FORM_PPNG]
GO
CREATE VIEW [dbo].[VW_REPORT_FORM_PPNG] AS                      
SELECT                       
PPR.PROCESS_ID,                      
APIPD.TOTAL_TRAN_PREMIUM,                      
0 AS COMPANY_ID,                 
PCPL.CUSTOMER_ID,                
PCPL.POLICY_ID,                
PCPL.POLICY_VERSION_ID,                     
'' AS COM_TYPE,                      
PCPL.CO_INSURANCE,                      
--MLM.SUSEP_LOB_CODE,                      
PCPL.SUSEP_LOB_CODE,  --Modified by Pradeep- SUSEP Lob code from Policy Level              
PPR.EFFECTIVE_DATETIME AS PPR_EFFECTIVE_DATETIME,                      
--PPR_1.EFFECTIVE_DATETIME AS PPR_1_EFFECTIVE_DATETIME,                
CASE WHEN (PPR_1.PROCESS_ID = 37) AND (PPR_1.LAST_REVERT_BACK IS NOT NULL)                  
 THEN (                
   SELECT  EFFECTIVE_DATETIME FROM POL_POLICY_PROCESS PPP3 WITH (NOLOCK)                 
   WHERE PPP3.CUSTOMER_ID = PCPL_1.CUSTOMER_ID                 
   AND PPP3.POLICY_ID=PCPL_1.POLICY_ID                 
   AND PPP3.NEW_POLICY_VERSION_ID=                 
   CAST(dbo.Piece(PPR_1.LAST_REVERT_BACK,'^',3) AS SMALLINT)                
   AND PROCESS_STATUS='COMPLETE'            
 ) --EFFECTIVE_DATETIME                
 ELSE  ISNULL(PPR_1.EFFECTIVE_DATETIME,ISNULL(PCPL_1.POL_VER_EFFECTIVE_DATE,PPR.EFFECTIVE_DATETIME))    --ISNULL(PPR_1.EFFECTIVE_DATETIME,PPR.EFFECTIVE_DATETIME)               
 END AS PPR_1_EFFECTIVE_DATETIME,               
--PPR.COMPLETED_DATETIME AS PPR_COMPLETED_DATETIME,                      
--PPR_1.COMPLETED_DATETIME AS PPR_1_COMPLETED_DATETIME,               
CASE WHEN (PPR_1.PROCESS_ID = 37) AND (PPR_1.LAST_REVERT_BACK IS NOT NULL)                  
 THEN(                
   SELECT  COMPLETED_DATETIME FROM POL_POLICY_PROCESS PPP3 WITH (NOLOCK)                 
   WHERE PPP3.CUSTOMER_ID = PCPL_1.CUSTOMER_ID                 
   AND PPP3.POLICY_ID=PCPL_1.POLICY_ID                 
   AND PPP3.NEW_POLICY_VERSION_ID=                 
   CAST(dbo.Piece(PPR_1.LAST_REVERT_BACK,'^',3) AS SMALLINT)            
   AND PROCESS_STATUS='COMPLETE'                
 ) --EFFECTIVE_DATETIME                
 ELSE ISNULL(PPR_1.COMPLETED_DATETIME,ISNULL(PCPL_1.POL_VER_EFFECTIVE_DATE, PPR.COMPLETED_DATETIME))     --ISNULL(PPR_1.COMPLETED_DATETIME,PPR.COMPLETED_DATETIME)                
 END AS PPR_1_COMPLETED_DATETIME,              
                      
PCPL.POLICY_EXPIRATION_DATE,                      
--PCPL_1.POL_VER_EXPIRATION_DATE,               
CASE WHEN (PPR_1.PROCESS_ID = 37) AND (PPR_1.LAST_REVERT_BACK IS NOT NULL)                 
 THEN                 
 (                
   SELECT   POL_VER_EXPIRATION_DATE FROM POL_CUSTOMER_POLICY_LIST PPP3 WITH (NOLOCK)                 
   WHERE PPP3.CUSTOMER_ID = PCPL_1.CUSTOMER_ID                 
   AND PPP3.POLICY_ID=PCPL_1.POLICY_ID                 
   AND PPP3.POLICY_VERSION_ID=                 
   CAST(dbo.Piece(PPR_1.LAST_REVERT_BACK,'^',3) AS SMALLINT)             
                 
 ) --EFFECTIVE_DATETIME                
 ELSE  ISNULL(PCPL_1.POL_VER_EXPIRATION_DATE,ISNULL(PCPL_1.POL_VER_EXPIRATION_DATE,PCPL.POL_VER_EXPIRATION_DATE)) --ISNULL(PCPL_1.POL_VER_EXPIRATION_DATE,PCPL.POL_VER_EXPIRATION_DATE)                
  END AS POL_VER_EXPIRATION_DATE,                       
PPR.COMPLETED_DATETIME,                      
APIPD.TRAN_TYPE,                      
--APIPD.TOTAL_PREMIUM AS APIPD_TOTAL_PREMIUM,               
 CASE WHEN  PCPL.CO_INSURANCE =14548           
    AND   PCI.LEADER_FOLLOWER = 14548   --IN (14548,14549) IN LEADER POLIYC LEARDER RECORD          
    THEN  APIPD.TOTAL_TRAN_PREMIUM * PCI.COINSURANCE_PERCENT  *.01 --APIPD.TOTAL_PREMIUM           
   WHEN  PCPL.CO_INSURANCE =14548           
    AND   PCI.LEADER_FOLLOWER = 14549   --IN (14548,14549) IN LEADER POLIYC LEARDER RECORD          
    THEN  APIPD.TOTAL_TRAN_PREMIUM * PCI.COINSURANCE_PERCENT  *.01    --APIPD.TOTAL_PREMIUM * PCI.COINSURANCE_PERCENT  *.01                  
   --WHEN  PCI.LEADER_FOLLOWER IN (14548,14549) THEN APIPD.TOTAL_PREMIUM * PCI.COINSURANCE_PERCENT *.01                  
  ELSE APIPD.TOTAL_TRAN_PREMIUM  --APIPD.TOTAL_PREMIUM                   
  END AS APIPD_TOTAL_PREMIUM,                     
--APIPD_1.TOTAL_PREMIUM AS APIPD_1_TOTAL_PREMIUM ,               
CASE WHEN  PCPL_1.CO_INSURANCE =14548 AND  PCI.LEADER_FOLLOWER = 14548 --WHEN PCI.LEADER_FOLLOWER IN (14548,14549)              
  THEN  APIPD_1.TOTAL_TRAN_PREMIUM * PCI.COINSURANCE_PERCENT  *.01  --APIPD_1.TOTAL_PREMIUM * PCI.COINSURANCE_PERCENT  *.01                  
  WHEN  PCPL.CO_INSURANCE =14548           
    AND   PCI.LEADER_FOLLOWER = 14549           
     THEN APIPD_1.TOTAL_TRAN_PREMIUM * PCI.COINSURANCE_PERCENT  *.01           
  ELSE APIPD_1.TOTAL_TRAN_PREMIUM  --APIPD_1.TOTAL_PREMIUM                   
  END AS APIPD_1_TOTAL_PREMIUM ,                     
PCPL.POLICY_EFFECTIVE_DATE,                      
PPR.[EXPIRY_DATE],            
MRCL_1.SUSEP_NUM as MRCL_1_SUSEP_NUM,                      
PCPL.POLICY_NUMBER ,                    
MLM.IS_ACTIVE,                    
PCI.LEADER_FOLLOWER,             
            
CASE WHEN  PCPL.CO_INSURANCE =14549 AND           
   PCI.LEADER_FOLLOWER = 14549 THEN (SELECT PRI2.SUSEP_NUM FROM MNT_REIN_COMAPANY_LIST PRI2 WITH(NOLOCK)            
           INNER JOIN  POL_CO_INSURANCE PCI2 WITH(NOLOCK)             
            ON PCI2.COMPANY_ID = PRI2.REIN_COMAPANY_ID            
           WHERE PCI2.CUSTOMER_ID = PCPL.CUSTOMER_ID            
           AND PCI2.POLICY_ID = PCPL.POLICY_ID            
           AND PCI2.POLICY_VERSION_ID = PCPL.POLICY_VERSION_ID            
           AND PCI2.LEADER_FOLLOWER =14548)            
  ELSE MRCL.SUSEP_NUM END as SUSEP_NUM             
  
  
,CASE WHEN  PCPL.CO_INSURANCE =14548           
    AND   PCI.LEADER_FOLLOWER = 14548   --IN (14548,14549) IN LEADER POLIYC LEARDER RECORD          
    THEN  AAOI.TOTAL_DUE * PCI.COINSURANCE_PERCENT  *.01 --APIPD.TOTAL_PREMIUM           
   WHEN  PCPL.CO_INSURANCE =14548           
    AND   PCI.LEADER_FOLLOWER = 14549   --IN (14548,14549) IN LEADER POLIYC LEARDER RECORD          
    THEN  AAOI.TOTAL_DUE * PCI.COINSURANCE_PERCENT  *.01    --APIPD.TOTAL_PREMIUM * PCI.COINSURANCE_PERCENT  *.01                  
   --WHEN  PCI.LEADER_FOLLOWER IN (14548,14549) THEN APIPD.TOTAL_PREMIUM * PCI.COINSURANCE_PERCENT *.01                  
  ELSE AAOI.TOTAL_DUE --APIPD.TOTAL_PREMIUM                   
  END AS BROKER_COMMISSION   
  
--,AAOI.TOTAL_DUE
,PPE.ENDORSEMENT_NO
                        
FROM (                      
  SELECT CUSTOMER_ID,NEW_POLICY_ID,NEW_POLICY_VERSION_ID,PROCESS_ID,EFFECTIVE_DATETIME,[EXPIRY_DATE],COMPLETED_DATETIME                      
  FROM POL_POLICY_PROCESS (NOLOCK) WHERE PROCESS_ID in (25,12,14,18,37) ) PPR                      
JOIN  POL_CUSTOMER_POLICY_LIST (NOLOCK) PCPL                        
  ON PPR.CUSTOMER_ID=PCPL.CUSTOMER_ID AND PPR.NEW_POLICY_ID=PCPL.POLICY_ID AND PPR.NEW_POLICY_VERSION_ID= PCPL.POLICY_VERSION_ID                        
LEFT OUTER JOIN MNT_LOB_MASTER (NOLOCK) MLM  ON MLM.LOB_ID=PCPL.POLICY_LOB                        
LEFT OUTER JOIN           
(          
 select PCI_1.CUSTOMER_ID,PCI_1.POLICY_ID,PCI_1.POLICY_VERSION_ID,PCI_1.COMPANY_ID,PCI_1.LEADER_FOLLOWER,PCI_1.COINSURANCE_PERCENT from POL_CO_INSURANCE (NOLOCK) PCI_1          
 join POL_CUSTOMER_POLICY_LIST PCPL_2          
 on  PCPL_2.CUSTOMER_ID=PCI_1.CUSTOMER_ID AND PCPL_2.POLICY_ID=PCI_1.POLICY_ID AND PCPL_2.POLICY_VERSION_ID=PCI_1.POLICY_VERSION_ID          
 where          
 PCPL_2.CO_INSURANCE  =case when PCI_1.LEADER_FOLLOWER  =14549 then 14549 end          
          
  or PCPL_2.CO_INSURANCE  =case when PCPL_2.CO_INSURANCE  =14548 then 14548 end            
              
    
                
             
           
          
) PCI ON (PCPL.CUSTOMER_ID=PCI.CUSTOMER_ID AND PCPL.POLICY_ID=PCI.POLICY_ID AND PCPL.POLICY_VERSION_ID=PCI.POLICY_VERSION_ID)                        
LEFT OUTER JOIN MNT_REIN_COMAPANY_LIST (NOLOCK) MRCL ON MRCL.REIN_COMAPANY_ID=PCI.COMPANY_ID                        
LEFT OUTER JOIN POL_REINSURANCE_INFO (NOLOCK) PRI                        
  ON (PCPL.CUSTOMER_ID=PRI.CUSTOMER_ID AND PCPL.POLICY_ID=PRI.POLICY_ID AND PCPL.POLICY_VERSION_ID=PRI.POLICY_VERSION_ID)                        
LEFT OUTER JOIN ACT_POLICY_INSTALL_PLAN_DATA (NOLOCK) APIPD                        
  ON (PCPL.CUSTOMER_ID=APIPD.CUSTOMER_ID AND PCPL.POLICY_ID=APIPD.POLICY_ID AND PCPL.POLICY_VERSION_ID=APIPD.POLICY_VERSION_ID )                        
LEFT OUTER JOIN ACT_POLICY_INSTALL_PLAN_DATA (NOLOCK) APIPD_1                        
  ON (APIPD.CUSTOMER_ID=APIPD_1.CUSTOMER_ID AND APIPD.POLICY_ID=APIPD_1.POLICY_ID AND APIPD.POLICY_VERSION_ID=(APIPD_1.POLICY_VERSION_ID+1) )                        
  --NEW ADDED--
LEFT OUTER JOIN  ACT_AGENCY_OPEN_ITEMS AAOI WITH(NOLOCK)
		 ON (AAOI.CUSTOMER_ID=PCPL.CUSTOMER_ID AND AAOI.POLICY_ID=PCPL.POLICY_ID AND AAOI.POLICY_VERSION_ID=PCPL.POLICY_VERSION_ID )                        
--LEFT OUTER JOIN  ACT_AGENCY_OPEN_ITEMS AAOI_1 WITH(NOLOCK)
-- ON (AAOI.CUSTOMER_ID=AAOI_1.CUSTOMER_ID AND AAOI.POLICY_ID=AAOI_1.POLICY_ID AND AAOI.POLICY_VERSION_ID=(AAOI_1.POLICY_VERSION_ID+1) )                        
LEFT OUTER JOIN MNT_REIN_COMAPANY_LIST (NOLOCK) MRCL_1                        
  ON  PRI.COMPANY_ID=MRCL_1.REIN_COMAPANY_ID                        
LEFT OUTER JOIN POL_CUSTOMER_POLICY_LIST (NOLOCK) PCPL_1                        
  ON (PCPL.CUSTOMER_ID=PCPL_1.CUSTOMER_ID AND PCPL.POLICY_ID=PCPL_1.POLICY_ID AND PCPL.POLICY_VERSION_ID=(PCPL_1.POLICY_VERSION_ID+1) )                        
LEFT OUTER JOIN POL_POLICY_PROCESS (NOLOCK) PPR_1                        
  ON  (PCPL.CUSTOMER_ID=PPR_1.CUSTOMER_ID AND PCPL.POLICY_ID=PPR_1.NEW_POLICY_ID AND PCPL.POLICY_VERSION_ID=(PPR_1.NEW_POLICY_VERSION_ID+1)                   
		and PPR_1.PROCESS_ID in (25,12,14,18,37)                
	  )
LEFT OUTER JOIN POL_POLICY_ENDORSEMENTS PPE WITH(NOLOCK) 
	 ON PPE.CUSTOMER_ID=PCPL.CUSTOMER_ID AND PPE.POLICY_ID=PCPL.POLICY_ID AND PPE.POLICY_VERSION_ID= PCPL.POLICY_VERSION_ID                                  
   -------------------------------------------------------------------------
   ----------------------------------------------------------------------------
   ---UNION            
  --WHERE   PCPL.POLICY_NUMBER ='050452011200196000120'                   
   --------------------------------------------------------------------------
   --------------------------------------------------------------------------
   
 UNION                   
  SELECT                             
 PPR.PROCESS_ID,                            
 sum(APIPD.REIN_PREMIUM)  AS TOTAL_TRAN_PREMIUM,      
 --APIPD.REIN_PREMIUM,                            
 PRI.COMPANY_ID,                       
 PCPL.CUSTOMER_ID,                      
 PCPL.POLICY_ID,                      
 PCPL.POLICY_VERSION_ID,                           
 MRCL_1.COM_TYPE,                            
 PCPL.CO_INSURANCE,                            
 --MLM.SUSEP_LOB_CODE,                          
 PCPL.SUSEP_LOB_CODE,  --Modified by Pradeep- SUSEP Lob code from Policy Level                            
 PPR.EFFECTIVE_DATETIME AS PPR_EFFECTIVE_DATETIME,                            
 --PPR_1.EFFECTIVE_DATETIME AS PPR_1_EFFECTIVE_DATETIME,                
 CASE WHEN (PPR_1.PROCESS_ID = 37) AND (PPR_1.LAST_REVERT_BACK IS NOT NULL)                  
 THEN (                
   SELECT  EFFECTIVE_DATETIME FROM POL_POLICY_PROCESS PPP3 WITH (NOLOCK)                 
   WHERE PPP3.CUSTOMER_ID = PCPL_1.CUSTOMER_ID                 
   AND PPP3.POLICY_ID=PCPL_1.POLICY_ID                 
   AND PPP3.NEW_POLICY_VERSION_ID=                 
   CAST(dbo.Piece(PPR_1.LAST_REVERT_BACK,'^',3) AS SMALLINT)             
   AND PROCESS_STATUS='COMPLETE'                 
 ) --EFFECTIVE_DATETIME                
 ELSE  ISNULL(PPR_1.EFFECTIVE_DATETIME,PPR.EFFECTIVE_DATETIME)               
 END AS PPR_1_EFFECTIVE_DATETIME,                 
                       
 --PPR.COMPLETED_DATETIME AS PPR_COMPLETED_DATETIME,                            
 --PPR_1.COMPLETED_DATETIME AS PPR_1_COMPLETED_DATETIME,                 
 CASE WHEN (PPR_1.PROCESS_ID = 37) AND (PPR_1.LAST_REVERT_BACK IS NOT NULL)                  
 THEN(                
   SELECT  COMPLETED_DATETIME FROM POL_POLICY_PROCESS PPP3 WITH (NOLOCK)                 
   WHERE PPP3.CUSTOMER_ID = PCPL_1.CUSTOMER_ID                 
   AND PPP3.POLICY_ID=PCPL_1.POLICY_ID                 
   AND PPP3.NEW_POLICY_VERSION_ID=                 
   CAST(dbo.Piece(PPR_1.LAST_REVERT_BACK,'^',3) AS SMALLINT)             
   AND PROCESS_STATUS='COMPLETE'                 
 ) --EFFECTIVE_DATETIME                
 ELSE ISNULL(PPR_1.COMPLETED_DATETIME,PPR.COMPLETED_DATETIME)              
 END AS PPR_1_COMPLETED_DATETIME,                
                            
 PCPL.POLICY_EXPIRATION_DATE,                
 CASE WHEN (PPR_1.PROCESS_ID = 37) AND (PPR_1.LAST_REVERT_BACK IS NOT NULL)                 
 THEN                 
 (                
   SELECT   POL_VER_EXPIRATION_DATE FROM POL_CUSTOMER_POLICY_LIST PPP3 WITH (NOLOCK)                 
   WHERE PPP3.CUSTOMER_ID = PCPL_1.CUSTOMER_ID                 
   AND PPP3.POLICY_ID=PCPL_1.POLICY_ID                 
   AND PPP3.POLICY_VERSION_ID=                 
   CAST(dbo.Piece(PPR_1.LAST_REVERT_BACK,'^',3) AS SMALLINT)             
                  
 ) --EFFECTIVE_DATETIME                
 ELSE  ISNULL(PCPL_1.POL_VER_EXPIRATION_DATE,PCPL.POL_VER_EXPIRATION_DATE)                  
  END AS POL_VER_EXPIRATION_DATE,                           
 --PCPL_1.POL_VER_EXPIRATION_DATE,                            
 PPR.COMPLETED_DATETIME,                            
 NULL AS TRAN_TYPE,       
 --APIPD.REIN_PREMIUM APIPD_TOTAL_PREMIUM,       
      
                           
 SUM(APIPD.REIN_PREMIUM) AS APIPD_TOTAL_PREMIUM,                            
 --SUM(APIPD_1.REIN_PREMIUM) AS APIPD_1_TOTAL_PREMIUM ,      
  --CASE WHEN PPR.PROCESS_ID = 25 THEN SUM(APIPD.REIN_PREMIUM)       
  --ELSE SUM(APIPD_1.REIN_PREMIUM)END APIPD_1_TOTAL_PREMIUM,     
CASE WHEN PPR.PROCESS_ID IN (25,18) THEN SUM(APIPD.REIN_PREMIUM)       
  ELSE (SELECT sum(POL_RI.REIN_PREMIUM) FROM POL_REINSURANCE_BREAKDOWN_DETAILS POL_RI     
   WHERE     
   POL_RI.CUSTOMER_ID=PCPL.CUSTOMER_ID     
   AND POL_RI.POLICY_ID=PCPL.POLICY_ID     
   AND POL_RI.POLICY_VERSION_ID+1=PCPL.POLICY_VERSION_ID    
   GROUP BY POL_RI.CUSTOMER_ID,POL_RI.POLICY_ID,POL_RI.POLICY_VERSION_ID    
   )    
  END APIPD_1_TOTAL_PREMIUM,                            
 PCPL.POLICY_EFFECTIVE_DATE,                            
 PPR.[EXPIRY_DATE],                            
 MRCL_1.SUSEP_NUM as MRCL_1_SUSEP_NUM,                            
 PCPL.POLICY_NUMBER ,                          
 MLM.IS_ACTIVE,                          
  0 as LEADER_FOLLOWER,              
 MRCL.SUSEP_NUM,
 0 AS BROKER_COMMISSION,
 PPE.ENDORSEMENT_NO 
 
 
                                 
 FROM (                            
   SELECT CUSTOMER_ID,NEW_POLICY_ID,NEW_POLICY_VERSION_ID,PROCESS_ID,EFFECTIVE_DATETIME,[EXPIRY_DATE],COMPLETED_DATETIME,LAST_REVERT_BACK                         
   FROM POL_POLICY_PROCESS (NOLOCK) WHERE PROCESS_ID in (25,12,14,18,37)                
   --AND PROCESS_STATUS <>'ROLLBACK'                 
   ) PPR                            
 JOIN  POL_CUSTOMER_POLICY_LIST (NOLOCK) PCPL                              
   ON PPR.CUSTOMER_ID=PCPL.CUSTOMER_ID AND PPR.NEW_POLICY_ID=PCPL.POLICY_ID AND PPR.NEW_POLICY_VERSION_ID= PCPL.POLICY_VERSION_ID                     
 LEFT OUTER JOIN MNT_LOB_MASTER (NOLOCK) MLM  ON MLM.LOB_ID=PCPL.POLICY_LOB                              
 --LEFT OUTER JOIN POL_CO_INSURANCE (NOLOCK) PCI ON (PCPL.CUSTOMER_ID=PCI.CUSTOMER_ID AND PCPL.POLICY_ID=PCI.POLICY_ID AND PCPL.POLICY_VERSION_ID=PCI.POLICY_VERSION_ID)                              
                         
 LEFT OUTER JOIN POL_REINSURANCE_INFO (NOLOCK) PRI                              
   ON (PCPL.CUSTOMER_ID=PRI.CUSTOMER_ID AND PCPL.POLICY_ID=PRI.POLICY_ID AND PCPL.POLICY_VERSION_ID=PRI.POLICY_VERSION_ID)                              
 inner JOIN MNT_REIN_COMAPANY_LIST (NOLOCK) MRCL ON MRCL.REIN_COMAPANY_ID=Pri.COMPANY_ID             
 LEFT OUTER JOIN POL_REINSURANCE_BREAKDOWN_DETAILS (NOLOCK) APIPD                              
   ON (PCPL.CUSTOMER_ID=APIPD.CUSTOMER_ID AND PCPL.POLICY_ID=APIPD.POLICY_ID AND PCPL.POLICY_VERSION_ID=APIPD.POLICY_VERSION_ID )                                
 --LEFT OUTER JOIN ACT_POLICY_INSTALL_PLAN_DATA (NOLOCK) APIPD                              
 --  ON (PCPL.CUSTOMER_ID=APIPD.CUSTOMER_ID AND PCPL.POLICY_ID=APIPD.POLICY_ID AND PCPL.POLICY_VERSION_ID=APIPD.POLICY_VERSION_ID )                              
                   
 LEFT OUTER JOIN POL_REINSURANCE_BREAKDOWN_DETAILS (NOLOCK) APIPD_1                              
   ON (APIPD.CUSTOMER_ID=APIPD_1.CUSTOMER_ID AND APIPD.POLICY_ID=APIPD_1.POLICY_ID AND APIPD.POLICY_VERSION_ID=(APIPD_1.POLICY_VERSION_ID+1) )                              
 --LEFT OUTER JOIN ACT_POLICY_INSTALL_PLAN_DATA (NOLOCK) APIPD_1                              
 --  ON (APIPD.CUSTOMER_ID=APIPD_1.CUSTOMER_ID AND APIPD.POLICY_ID=APIPD_1.POLICY_ID AND APIPD.POLICY_VERSION_ID=(APIPD_1.POLICY_VERSION_ID+1) )                              
                   
 LEFT OUTER JOIN MNT_REIN_COMAPANY_LIST (NOLOCK) MRCL_1                              
   ON  PRI.COMPANY_ID=MRCL_1.REIN_COMAPANY_ID                              
 LEFT OUTER JOIN POL_CUSTOMER_POLICY_LIST (NOLOCK) PCPL_1                              
   ON (PCPL.CUSTOMER_ID=PCPL_1.CUSTOMER_ID AND PCPL.POLICY_ID=PCPL_1.POLICY_ID AND PCPL.POLICY_VERSION_ID=(PCPL_1.POLICY_VERSION_ID+1) )                              
 LEFT OUTER JOIN POL_POLICY_PROCESS (NOLOCK) PPR_1                              
   ON  (PCPL.CUSTOMER_ID=PPR_1.CUSTOMER_ID AND PCPL.POLICY_ID=PPR_1.NEW_POLICY_ID AND PCPL.POLICY_VERSION_ID=(PPR_1.NEW_POLICY_VERSION_ID+1)                         
   and PPR_1.PROCESS_ID in (25,12,14,18,37)                       
   )       
  LEFT OUTER JOIN POL_POLICY_ENDORSEMENTS PPE WITH(NOLOCK) 
	 ON PPE.CUSTOMER_ID=PCPL.CUSTOMER_ID AND PPE.POLICY_ID=PCPL.POLICY_ID AND PPE.POLICY_VERSION_ID= PCPL.POLICY_VERSION_ID                       
   --WHERE   PCPL.POLICY_NUMBER ='050452011050982000092'           
              
   GROUP BY PPR.PROCESS_ID,PRI.COMPANY_ID,                       
 PCPL.CUSTOMER_ID,                      
 PCPL.POLICY_ID,                      
 PCPL.POLICY_VERSION_ID,                           
 MRCL_1.COM_TYPE,                            
 PCPL.CO_INSURANCE, PCPL.SUSEP_LOB_CODE, PPR.EFFECTIVE_DATETIME,          
 PCPL_1.CUSTOMER_ID,          
 PCPL_1.POLICY_ID,                      
 PCPL_1.POLICY_VERSION_ID,          
 PPR_1.LAST_REVERT_BACK,          
 PPR_1.PROCESS_ID,          
 PPR_1.EFFECTIVE_DATETIME ,          
 PPR_1.COMPLETED_DATETIME,          
 PPR.COMPLETED_DATETIME,          
 PCPL.POLICY_EXPIRATION_DATE,          
 PCPL_1.POL_VER_EXPIRATION_DATE,          
 PCPL.POL_VER_EXPIRATION_DATE,          
 PCPL.POLICY_EFFECTIVE_DATE,          
  PPR.[EXPIRY_DATE],          
   MRCL_1.SUSEP_NUM,          
    PCPL.POLICY_NUMBER,          
     MLM.IS_ACTIVE,          
      MRCL.SUSEP_NUM,
       PPE.ENDORSEMENT_NO           