/*
DROP PROC dbo.PROC_GET_POLICY_REIN_INSLT_DETAILS  
EXEC PROC_GET_POLICY_REIN_INSLT_DETAILS 28516,76,1 
*/
CREATE PROCEDURE dbo.PROC_GET_POLICY_REIN_INSLT_DETAILS    
 @CUSTOMER_ID       INT,              
 @POLICY_ID        INT,              
 @POLICY_VERSION_ID  SMALLINT     
    
AS    
BEGIN                        
SET NOCOUNT ON;     
DECLARE @NOOFPOLINSTALLMENT INT  , @RES INT   

SELECT @NOOFPOLINSTALLMENT = NO_OF_PAYMENTS FROM ACT_POLICY_INSTALL_PLAN_DATA APIPD WITH(NOLOCK) WHERE APIPD.CUSTOMER_ID = @CUSTOMER_ID AND APIPD.POLICY_ID = @POLICY_ID AND APIPD.POLICY_VERSION_ID = @POLICY_VERSION_ID 

CREATE TABLE #TEMP  
(  
	 IDENTITY_COL INT IDENTITY(1,1),  
	 CONTRACT_NUMBER VARCHAR(200),   
	 MAX_NO_INSTALLMENT INT,  
	 COMPANY_ID INT,
	 POLICY_INSTALLMENT INT 
) 

INSERT INTO #TEMP   
(  
	 CONTRACT_NUMBER,  
	 MAX_NO_INSTALLMENT,  
	 COMPANY_ID,
	 POLICY_INSTALLMENT  
)    
SELECT * FROM    
(   
	SELECT CONT.CONTRACT_NUMBER,CONT.MAX_NO_INSTALLMENT,NULL AS COMPANY_ID,@NOOFPOLINSTALLMENT AS POLICY_INSTALLMENT   
	FROM MNT_REINSURANCE_CONTRACT CONT WITH(NOLOCK)  
	INNER JOIN MNT_REIN_CONTRACT_LOB LOB WITH(NOLOCK) on CONT.CONTRACT_ID=LOB.CONTRACT_ID   
	INNER JOIN MNT_REIN_LOSSLAYER LYR WITH(NOLOCK) ON LYR.CONTRACT_ID=CONT.CONTRACT_ID  
	LEFT JOIN MNT_REIN_LOSSLAYER LYR1 WITH(NOLOCK) ON LYR1.CONTRACT_ID=CONT.CONTRACT_ID AND LYR1.LAYER<LYR.LAYER  
	LEFT join MNT_REINSURANCE_MAJORMINOR_PARTICIPATION MJR WITH(NOLOCK) on MJR.CONTRACT_ID=CONT.CONTRACT_ID  AND MJR.LAYER=LYR.LAYER  
	JOIN POL_CUSTOMER_POLICY_LIST pol WITH(NOLOCK) ON pol.POLICY_LOB = LOB.CONTRACT_LOB AND pol.CUSTOMER_ID=@CUSTOMER_ID and pol.policy_id=@POLICY_ID and pol.POLICY_VERSION_ID=@POLICY_VERSION_ID  
	AND ISNULL(POL.POLICY_EFFECTIVE_DATE,pol.APP_EFFECTIVE_DATE) <= ISNULL(CONT.TERMINATION_DATE,'3000-01-01')  
	AND IsNULL(POL.POLICY_EFFECTIVE_DATE,POL.APP_EFFECTIVE_DATE) >= ISNULL(CONT.effective_date,'3000-01-01')
	
	UNION ALL

	SELECT 'Facultative' AS CONTRACT_NUMBER,RI.MAX_NO_INSTALLMENT,RI.COMPANY_ID AS COMPANY_ID,@NOOFPOLINSTALLMENT AS POLICY_INSTALLMENT
	FROM POL_REINSURANCE_INFO RI with(nolock)    
	JOIN POL_CUSTOMER_POLICY_LIST PCPL WITH(NOLOCK) ON PCPL.CUSTOMER_ID=RI.CUSTOMER_ID  
	AND PCPL.POLICY_ID=RI.POLICY_ID AND PCPL.POLICY_VERSION_ID=RI.POLICY_VERSION_ID  
	WHERE RI.CUSTOMER_ID=@CUSTOMER_ID and RI.POLICY_ID=@POLICY_ID AND RI.POLICY_VERSION_ID=@POLICY_VERSION_ID   
) A



IF ((SELECT COUNT(*) FROM #TEMP T WHERE T.MAX_NO_INSTALLMENT < T.POLICY_INSTALLMENT) > 0)
	SELECT 1 AS 'RESULT'
ELSE 
	SELECT 0 AS 'RESULT'
	
END