 IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Proc_Fetch_Motor_QQ_Details]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Proc_Fetch_Motor_QQ_Details]
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO


 
 /*----------------------------------------------------------    
Proc Name       : [Proc_Fetch_Motor_QQ_Details]    
Created by      : Agniswar Das    
Date            : 7/17/2011    
Purpose			: Demo    
Revison History :    
Used In        : Singapore    
------------------------------------------------------------    
Date     Review By          Comments    
------   ------------       -------------------------*/   





CREATE PROC dbo.Proc_Fetch_Motor_QQ_Details    
(    
 @CUSTOMER_ID int,    
 @POLICY_ID int,    
 @POLICY_VERSION_ID int     
)    
    
As    
    
    
SELECT PL.CUSTOMER_ID,PL.POLICY_ID,PL.POLICY_VERSION_ID,  
PL.APP_NUMBER,PL.POLICY_EFFECTIVE_DATE,  
PL.POLICY_EXPIRATION_DATE,  
  
CP.QUOTE_ID,CP.CUSTOMER_TYPE,LV.LOOKUP_VALUE_DESC as CUSTOMER_TYPE_DESC,CP.DATE_OF_QUOTATION,  
CP.CUSTOMER_FIRST_NAME,CP.CUSTOMER_MIDDLE_NAME,CP.CUSTOMER_LAST_NAME,  
CP.CUSTOMER_ADDRESS1,CP.CUSTOMER_ADDRESS2,CP.CUSTOMER_CITY,CP.CUSTOMER_STATE,  
CP.CUSTOMER_ZIP,CP.MARITAL_STATUS,CP.CUSTOMER_CONTACT_NO,CP.PASSPORT_NO,CP.EXISTING_INSURER,  
CP.EXISTING_POL_NUM,CP.EXIST_POL_EXP_DATE,CP.VEHICLE_NO,  
CP.DATE_OF_BIRTH,CP.GENDER,CP.NATIONALITY,CN.COUNTRY_NAME,CP.IS_HOME_EMPLOYEE,  
CP.DRIVER_EXP_YEAR,CP.EXISTING_NCD,CP.DEMERIT_DISCOUNT,  
CP.CUSTOMER_AGENCY_ID, AL.AGENCY_DISPLAY_NAME + ' (' + AL.AGENCY_CODE + ')' AS AGENCY_NAME,  
  
QD.YEAR_OF_REG,QD.MAKE,LO.LOOKUP_VALUE_DESC as MAKE_DESC,QD.MODEL,ML.MODEL as MODEL_DESC,  
QD.MODEL_TYPE,TL.MODEL_TYPE as MODEL_TYPE_DESC,QD.ENG_CAPACITY,QD.NO_OF_DRIVERS,QD.ANY_CLAIM,  
QD.NO_OF_CLAIM,QD.TOTAL_CLAIM_AMT,QD.COVERAGE_TYPE,MC.COV_DES,QD.NO_CLAIM_DISCOUNT,QD.IS_NEW,  
QD.REGISTRATION_NO,QD.COVER_NOTE_NO,QD.DATE_LTA_REGISTRATION,QD.ENGINE_NO,QD.CHASSIS_NO,  
QD.IS_UNDER_HIRE,QD.FINANCE_COMP_NAME,QD.IS_DEMERIT_POINT,QD.DEMERIT_DESC,QD.IS_REJECTED,  
QD.REJECTED_DESC,QD.IS_DISEASE,QD.DISEASE_DESC,QD.NAMED_DRIVER_AMT,QD.UNNAMED_DRIVER_AMT,QD.FINAL_PREMIUM   
  
FROM POL_CUSTOMER_POLICY_LIST PL    
INNER JOIN CLT_QUICKQUOTE_LIST QL    
ON PL.CUSTOMER_ID = QL.CUSTOMER_ID    
AND PL.POLICY_ID = QL.APP_ID    
AND PL.POLICY_VERSION_ID = QL.APP_VERSION_ID    
INNER JOIN QQ_CUSTOMER_PARTICULAR CP    
ON CP.CUSTOMER_ID = QL.CUSTOMER_ID    
AND CP.QUOTE_ID = QL.QQ_ID    
INNER JOIN QQ_MOTOR_QUOTE_DETAILS QD    
ON QD.CUSTOMER_ID = PL.CUSTOMER_ID    
AND QD.POLICY_ID = PL.POLICY_ID    
AND QD.POLICY_VERSION_ID = PL.POLICY_VERSION_ID    
INNER JOIN MNT_COUNTRY_LIST CN    
ON CN.COUNTRY_ID = CP.NATIONALITY   
INNER JOIN MNT_COVERAGE MC  
ON MC.COV_ID = QD.COVERAGE_TYPE   
INNER JOIN MNT_LOOKUP_VALUES LV    
ON LV.LOOKUP_UNIQUE_ID = CP.CUSTOMER_TYPE    
INNER JOIN MNT_LOOKUP_VALUES LO  
ON LO.LOOKUP_UNIQUE_ID = QD.MAKE  
INNER JOIN MNT_VEHICLE_MODEL_LIST ML  
ON ML.ID = QD.MODEL  
INNER JOIN MNT_VEHICLE_MODEL_TYPE_LIST TL  
ON TL.ID = QD.MODEL_TYPE  
INNER JOIN MNT_AGENCY_LIST AL  
ON AL.AGENCY_ID = CP.CUSTOMER_AGENCY_ID  
WHERE PL.CUSTOMER_ID = @CUSTOMER_ID    
AND PL.POLICY_ID = @POLICY_ID    
AND PL.POLICY_VERSION_ID = @POLICY_VERSION_ID    
  