--begin tran    
---- EXEC [Proc_CMP_EXCEEDEDPREMIUM] 28025, 81, 3,17  
--DROP PROC Proc_CMP_EXCEEDEDPREMIUM    
--go    
 /**************************************************          
CREATED BY    : SHIKHA CHOURASIYA        
CREATED DATETIME : 16 Nov 2011          
PURPOSE    : COMPARE TIV > MAXLAYER FOR EXCEEDED PREMIUM    
Review      :    
Review By  Date       
Purpose          
DROP PROC Proc_CMP_EXCEEDEDPREMIUM    
***************************************************/          
CREATE PROCEDURE [dbo].[Proc_CMP_EXCEEDEDPREMIUM]    
(          
 @CUSTOMER_ID  INT,          
 @POLICY_ID   INT,          
 @POLICY_VERSION_ID INT      
 )          
AS          
BEGIN     
SET NOCOUNT ON;  
DECLARE @MAX_LAYER_AMOUNT DECIMAL(18,2)  
DECLARE @CMPEXCEEDEDPRMIUM VARCHAR(1)  
DECLARE @LOB_ID INT  
  
SET @LOB_ID = (SELECT POLICY_LOB FROM POL_CUSTOMER_POLICY_LIST PCPL WHERE PCPL.CUSTOMER_ID = @CUSTOMER_ID AND PCPL.POLICY_ID = @POLICY_ID  AND PCPL.POLICY_VERSION_ID =  @POLICY_VERSION_ID  )  
  
 SELECT @MAX_LAYER_AMOUNT =  MAX(CAST(ISNULL(A.LAYER_AMOUNT,0) AS INT))   
 FROM MNT_REIN_LOSSLAYER A WITH(NOLOCK)  
    JOIN MNT_REIN_CONTRACT_LOB B WITH(NOLOCK) ON A.CONTRACT_ID = B.CONTRACT_ID     
 JOIN POL_CUSTOMER_POLICY_LIST C WITH(NOLOCK) ON B.CONTRACT_LOB = C.POLICY_LOB     
 JOIN MNT_REINSURANCE_CONTRACT D WITH(NOLOCK) ON D.CONTRACT_ID = B.CONTRACT_ID    
 WHERE C.CUSTOMER_ID = @CUSTOMER_ID AND C.POLICY_ID = @POLICY_ID  AND C.POLICY_VERSION_ID =  @POLICY_VERSION_ID    
   
   
 IF EXISTS(SELECT SUM(LIMIT_1)   
    FROM POL_PRODUCT_COVERAGES C  
    WHERE C.CUSTOMER_ID = @CUSTOMER_ID AND C.POLICY_ID = @POLICY_ID AND C.POLICY_VERSION_ID = @POLICY_VERSION_ID   
    GROUP BY RISK_ID  
    HAVING SUM(LIMIT_1) > @MAX_LAYER_AMOUNT)  
 SET @CMPEXCEEDEDPRMIUM = 1  
 ELSE  
 SET @CMPEXCEEDEDPRMIUM = 0   
   
  
   
 IF (@CMPEXCEEDEDPRMIUM = 1) 
 BEGIN 
  IF @LOB_ID IN (9,26)    
   UPDATE POL_PERILS SET EXCEEDED_PREMIUM = '10963' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (11,12,14,16,19,25,27,32)     
   UPDATE POL_PRODUCT_LOCATION_INFO SET EXCEEDED_PREMIUM = '10963' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (15,21,33,34)   
   UPDATE POL_PERSONAL_ACCIDENT_INFO SET EXCEEDED_PREMIUM = '10963' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (35,37)     
   UPDATE POL_PENHOR_RURAL_INFO SET EXCEEDED_PREMIUM = '10963' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (17,18,27,28,29,30)    
   UPDATE POL_CIVIL_TRANSPORT_VEHICLES SET EXCEEDED_PREMIUM = '10963' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (13)    
   UPDATE POL_MARITIME SET EXCEEDED_PREMIUM = '10963' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID      
  IF @LOB_ID IN (22)    
   UPDATE POL_PASSENGERS_PERSONAL_ACCIDENT_INFO SET EXCEEDED_PREMIUM = '10963' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (20,23)    
   UPDATE POL_COMMODITY_INFO SET EXCEEDED_PREMIUM = '10963' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID        
 END
 ELSE 
 BEGIN  
  IF @LOB_ID IN (9,26)    
   UPDATE POL_PERILS SET EXCEEDED_PREMIUM = '10964' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (11,12,14,16,19,25,27,32)     
   UPDATE POL_PRODUCT_LOCATION_INFO SET EXCEEDED_PREMIUM = '10964' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (15,21,33,34)   
   UPDATE POL_PERSONAL_ACCIDENT_INFO SET EXCEEDED_PREMIUM = '10964' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (35,37)     
   UPDATE POL_PENHOR_RURAL_INFO SET EXCEEDED_PREMIUM = '10964' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (17,18,27,28,29,30)    
   UPDATE POL_CIVIL_TRANSPORT_VEHICLES SET EXCEEDED_PREMIUM = '10964' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (13)    
   UPDATE POL_MARITIME SET EXCEEDED_PREMIUM = '10964' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID      
  IF @LOB_ID IN (22)    
   UPDATE POL_PASSENGERS_PERSONAL_ACCIDENT_INFO SET EXCEEDED_PREMIUM = '10964' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID    
  IF @LOB_ID IN (20,23)    
   UPDATE POL_COMMODITY_INFO SET EXCEEDED_PREMIUM = '10964' WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID  AND POLICY_VERSION_ID =  @POLICY_VERSION_ID  
 END
END  
  
  