 /**************************************************        
CREATED BY    : SHIKHA CHOURASIYA  
CREATED DATETIME : 21 Nov 2011        
PURPOSE    : FETCH RECORD OF REINSURANCE INSTALLMENT  
Review      :  
Review By  Date     
Purpose        
DROP PROC PROC_REINSURANCE_INSTALLMENT_DETAILS  889982011080173000011
***************************************************/        
CREATE PROCEDURE [dbo].[PROC_REINSURANCE_INSTALLMENT_DETAILS]  
(        
@POLICY_NUMBER NVARCHAR(21)   
)    
AS        
BEGIN  
SET NOCOUNT ON;

DECLARE @CUSTOMER_ID INT        
DECLARE @POLICY_ID INT        


SELECT  @CUSTOMER_ID = CUSTOMER_ID,
		@POLICY_ID  = POLICY_ID
FROM POL_CUSTOMER_POLICY_LIST WITH(NOLOCK) 
WHERE POLICY_NUMBER = @POLICY_NUMBER 

SELECT * FROM ACT_POLICY_REIN_INSTALLMENT_DETAILS WITH(NOLOCK) WHERE CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID

END

