  
--Proc Name       : dbo.Proc_UPDATE_POL_BILLING_INFO      
--Created by      : SNEHA      
--Date            : 16/11/2011             
--Purpose   :To Update in POL_BILLING_INFO    
--Revison History :                
--Used In   : Ebix Advantage                
--------------------------------------------------------------                
--Date     Review By          Comments                
--------   ------------       -------------------------*/                
--DROP PROC dbo.Proc_UPDATE_POL_BILLING_INFO 
CREATE PROC [dbo].Proc_UPDATE_POL_BILLING_INFO  
(
@BILLING_ID					[INT] ,
@CUSTOMER_ID				[NVARCHAR](10) ,
@POLICY_ID					[NVARCHAR](10) ,
@POLICY_VERSION_ID			[NVARCHAR](10) ,
@LOB_ID						[NVARCHAR](10) ,
@BILLING_TYPE				[NVARCHAR](10) ,
@BILLING_PLAN				[NVARCHAR](10) ,
@DOWN_PAYMENT_MODE			[NVARCHAR](10) ,
@PROXY_SIGN_OBTAIN			[NVARCHAR](10) ,
@UNDERWRITER				[NVARCHAR](50) ,
@ROLLOVER					[NVARCHAR](10) ,
@RECIVED_PREMIUM			[NVARCHAR](20) ,
@COMP_APP_BONUS_APPLIES		[nchar](2) ,
@CURRENT_RESIDENCE			[NVARCHAR](50) 

)

AS
BEGIN

	UPDATE POL_BILLING_INFO
		SET 
			
			BILLING_TYPE			=@BILLING_TYPE,
			BILLING_PLAN			=@BILLING_PLAN,
			DOWN_PAYMENT_MODE		=@DOWN_PAYMENT_MODE,
			PROXY_SIGN_OBTAIN		=@PROXY_SIGN_OBTAIN,
			UNDERWRITER				=@UNDERWRITER,
			ROLLOVER				=@ROLLOVER,
			RECIVED_PREMIUM			=@RECIVED_PREMIUM,
			COMP_APP_BONUS_APPLIES	=@COMP_APP_BONUS_APPLIES,
			CURRENT_RESIDENCE		=@CURRENT_RESIDENCE

		WHERE BILLING_ID=@BILLING_ID AND CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID AND POLICY_VERSION_ID=@POLICY_VERSION_ID AND LOB_ID=@LOB_ID
END