/****** Object:  StoredProcedure [dbo].[Proc_GetBase_Header_AI_PN]    Script Date: 09/16/2011 16:03:18 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Proc_GetBase_Header_AI_PN]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Proc_GetBase_Header_AI_PN]
GO

/****** Object:  StoredProcedure [dbo].[Proc_GetBase_Header_AI_PN]    Script Date: 09/16/2011 16:03:18 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




---------------------------------------------------------------
--Proc Name          : dbo.Proc_GetBase_Header_AI_PN    
--Created by         :          
--Date               :  5 August 2011       
--------------------------------------------------------
--Date     Review By          Comments        
------   ------------       -------------------------*/       
-- drop proc dbo.[Proc_GetBase_Header_AI_PN]      
CREATE  PROCEDURE [dbo].[Proc_GetBase_Header_AI_PN]      
(        
 	@CUSTOMER_ID INT,
	@POLICY_ID INT,
	@NOTICE_DUE_DATE DATE,
	@CARRIER_CODE NVARCHAR(20),
    @LANG_ID INT 
  )        
AS       
BEGIN      

DECLARE @MAX_TERM INT
--DECLARE @MAX_VERSION_ID INT
DECLARE @MAXTERM_CURRENT_VERSION_ID INT
DECLARE @CURRENT_VERSION_ID INT
DECLARE @MORTGAGEE INT
DECLARE @RENEWED VARCHAR(20)
DECLARE @CURRENT_STATUS	Varchar(20) 
DECLARE @ADD_INT_ID	Char(2)
DECLARE @DWELLING_ID Int
DECLARE @CURRENT_TERM Int
DECLARE @POLICY_EFFECTIVE_DATE Datetime                        
DECLARE @POLICY_EXPIRATION_DATE Datetime
--DECLARE @SUB_LOB_ID Smallint
DECLARE @BILL_TYPE char(2)
--DECLARE @BILL_TYPE_ID INT
--DECLARE @POLICY_LOB   NVARCHAR(5)
--DECLARE @INSTALL_PLAN_ID Int
DECLARE @MINDAYS_PREMIUM  Int
--DECLARE @DAYS_DUE_PREM_NOTICE_PRINTD Int
DECLARE @NON_SUFFICIENT_FUND_FEES Decimal(18,2)
--DECLARE @REINSTATEMENT_FEES Decimal(18,2)
DECLARE @LATE_FEES Decimal(18,2)                                        
--DECLARE @INSTALLMENT_FEES Decimal(18,2)
--DECLARE @BILL_DATE DateTime
DECLARE @OCRA varchar(25)
DECLARE @PLAN_DESCRIPTION NVARCHAR(35)
--DECLARE @LOB_ID	Int
--DECLARE @IS_HOME_EMP Bit
DECLARE @SHOW_INSTALLMENTS Char(1)
--DECLARE @PLAN_PAYMENT_MODE	Int
DECLARE @AMOUNT_PAID Decimal(18,2)
DECLARE @TOTAL_DUE Decimal(18,2)
DECLARE @MINIMUM_DUE Decimal(18,2)
DECLARE @TOTAL_FEE DECIMAL(18,2)
DECLARE @FIRST_INS_FEE  DECIMAL(18,2)
DECLARE @TOTAL_PREMIUM_DUE	Decimal(18,2)
DECLARE @POLICY_NO NVARCHAR(50)
DECLARE @APP_TERM NVARCHAR(20)
DECLARE @CUSTOMER_NAME NVARCHAR(200)
DECLARE @CUSTOMER_SUFFIX NVARCHAR(20)
DECLARE @CUSTOMER_ADDRESS1 NVARCHAR(500)
DECLARE @CUSTOMER_ADDRESS2 NVARCHAR(500)
DECLARE @CUSTOMER_CITY NVARCHAR(200)
DECLARE @STATE_CODE NVARCHAR(20)
DECLARE @CUSTOMER_ZIP NVARCHAR(50)
DECLARE @AGENCY_ID NVARCHAR(50) 
DECLARE @AGENCY_DISPLAY_NAME NVARCHAR(500)               
DECLARE @AGENCY_CODE NVARCHAR(50)               
DECLARE @AGENCY_ADD1 NVARCHAR(500)  
DECLARE @AGENCY_ADD2 NVARCHAR(500)
DECLARE @AGENCY_CITY NVARCHAR(500)  
DECLARE @APP_INCEPTION_DATE DATE                                 
DECLARE @APP_EXPIRATION_DATE DATE 
DECLARE @AGENCY_ZIP NVARCHAR(100)
DECLARE @AGENCY_PHONE NVARCHAR(100)
DECLARE @NOTICE_TYPE NVARCHAR(100)
DECLARE @LOB_DESCRIPTION NVARCHAR(500)
DECLARE @POLICY_TYPE NVARCHAR(100)
DECLARE @POLICY_NUMBER NVARCHAR(100)
DECLARE @LOB_CODE NVARCHAR(50)
DECLARE @NSF_FEE DECIMAL(18,2)
DECLARE @LATE_FEE DECIMAL(18,2)
DECLARE @BILL_PLAN NVARCHAR(100)
DECLARE @EFFECTIVE_DATE NVARCHAR(100)
DECLARE @DUE_DATE NVARCHAR(100)
DECLARE @SHOW_INS_SCHEDULE NVARCHAR(50)
DECLARE @BILL_MORTAGAGEE NVARCHAR(50)
DECLARE @STATUS NVARCHAR(50)

	

SET @MORTGAGEE = 11276

	SELECT	@MAX_TERM = MAX(CURRENT_TERM)--,
			--@MAX_VERSION_ID = MAX(POLICY_VERSION_ID ) 
	FROM POL_CUSTOMER_POLICY_LIST (NOLOCK)      
	WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID  
	
	SELECT	@MAXTERM_CURRENT_VERSION_ID =ISNULL(MAX(POLICY_VERSION_ID),0)           
	FROM POL_CUSTOMER_POLICY_LIST (NOLOCK)                             
	WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID AND CURRENT_TERM = @MAX_TERM

	SELECT @CURRENT_VERSION_ID =ISNULL(MAX(NEW_POLICY_VERSION_ID),0) FROM POL_POLICY_PROCESS                                               
	WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID AND PROCESS_ID IN(18,25,32)
	
	SELECT	@ADD_INT_ID = CASE WHEN BILL_TYPE_ID = @MORTGAGEE THEN ISNULL(ADD_INT_ID,0) ELSE 0 END			
	FROM POL_CUSTOMER_POLICY_LIST 
	WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID  AND POLICY_VERSION_ID = @CURRENT_VERSION_ID
	
	SELECT  @CURRENT_TERM = CURRENT_TERM , -- Have to verified           
			@POLICY_EFFECTIVE_DATE  = APP_EFFECTIVE_DATE,                        
			@POLICY_EXPIRATION_DATE = APP_EXPIRATION_DATE,                    
			--@SUB_LOB_ID = ISNULL(POLICY_SUBLOB ,0), -- Have to verified                       
			@BILL_TYPE  = BILL_TYPE--,                        
			--@BILL_TYPE_ID=BILL_TYPE_ID,                         
			--@POLICY_LOB=POLICY_LOB                         
	FROM POL_CUSTOMER_POLICY_LIST (NOLOCK)                        
	WHERE   CUSTOMER_ID = @CUSTOMER_ID AND POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @MAXTERM_CURRENT_VERSION_ID    
	
	            
	IF EXISTS(SELECT BILL_TYPE FROM POL_CUSTOMER_POLICY_LIST (NOLOCK) WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID AND BILL_TYPE='DB')              
		BEGIN
			SET @RENEWED  = 'YES'              
		END
	ELSE              
		BEGIN
			SET @RENEWED  = 'NO' 
		END
	
	SELECT  --@INSTALL_PLAN_ID = CPL.INSTALL_PLAN_ID ,                                        
			@MINDAYS_PREMIUM = INS_MASTER.MINDAYS_PREMIUM,                                        
			--@DAYS_DUE_PREM_NOTICE_PRINTD = INS_MASTER.DAYS_DUE_PREM_NOTICE_PRINTD,                                        
			@NON_SUFFICIENT_FUND_FEES = INS_MASTER.NON_SUFFICIENT_FUND_FEES,                                         
			--@REINSTATEMENT_FEES  = INS_MASTER.REINSTATEMENT_FEES ,                                        
			@LATE_FEES   = INS_MASTER.LATE_FEES,                                        
			--@INSTALLMENT_FEES       = INSTALLMENT_FEES,                  
			@CURRENT_TERM           = CPL.CURRENT_TERM  ,                          
			--@BILL_DATE   =    DATEADD(DD,INS_MASTER.DAYS_DUE_PREM_NOTICE_PRINTD, GETDATE() ),                        
			@OCRA = CPL.POLICY_NUMBER         ,
			@PLAN_DESCRIPTION       = INS_MASTER.PLAN_DESCRIPTION , 
			--@LOB_ID					= CPL.POLICY_LOB , 
			--@IS_HOME_EMP			=  ISNULL(CPL.IS_HOME_EMP, 0) , 
			@SHOW_INSTALLMENTS	  = CASE ISNULL(INS_MASTER.SYSTEM_GENERATED_FULL_PAY,0) WHEN 1 THEN 'N' ELSE 'Y' END              
	FROM POL_CUSTOMER_POLICY_LIST CPL                                        
	INNER JOIN ACT_INSTALL_PLAN_DETAIL INS_MASTER                                        
	ON INS_MASTER.IDEN_PLAN_ID = CPL.INSTALL_PLAN_ID                                        
	WHERE CPL.CUSTOMER_ID =@CUSTOMER_ID                                  
	AND   CPL.POLICY_ID = @POLICY_ID                                         
	AND   CPL.POLICY_VERSION_ID = @CURRENT_VERSION_ID                                         
        
     
	IF(@NOTICE_DUE_DATE IS NULL)      
		BEGIN   
			SET  @NOTICE_DUE_DATE = GETDATE()      
			--SELECT  @DUE_DATE = GETDATE()        
			IF( CAST(CONVERT(VARCHAR,DATEADD(DD,@MINDAYS_PREMIUM, GetDate() ),101) AS DATETIME)  > CAST(CONVERT(VARCHAR,@NOTICE_DUE_DATE,101) AS VARCHAR)) 
				BEGIN           
					SET @NOTICE_DUE_DATE = DATEADD(DD,@MINDAYS_PREMIUM, GetDate())
				END          
		END	  
      
	IF(DATENAME(DW,@NOTICE_DUE_DATE) = 'Sunday')          
		BEGIN           
			SET @NOTICE_DUE_DATE = DATEADD(DD,1, @NOTICE_DUE_DATE )          
		END          
	IF(DATENAME(DW,@NOTICE_DUE_DATE) = 'Saturday')          
		BEGIN           
			SET @NOTICE_DUE_DATE = DATEADD(DD,2, @NOTICE_DUE_DATE )          
		END          
      
	SET @AMOUNT_PAID = 0  
         
	DECLARE @AMOUNT_DUE TABLE 
	(
			MINIMUM_DUE DECIMAL(18,2),                                        
			TOTAL_DUE DECIMAL(18,2),                                        
			AGENCY_ID INT,        
			AGENCYCODE VARCHAR(20),
			PREM Decimal(18,2) , 
			FEE Decimal(18,2),            
			FIRST_INS_FEE Decimal(18,2) ,
			TOTAL_PREMIUM_DUE Decimal(18,2) 
	)        
	      
	INSERT INTO @AMOUNT_DUE exec Proc_GetTotalAndMinimumDue @CUSTOMER_ID,@POLICY_ID,@CURRENT_VERSION_ID , @NOTICE_DUE_DATE      

	SELECT @TOTAL_DUE=TOTAL_DUE, @MINIMUM_DUE=MINIMUM_DUE,  @TOTAL_FEE=FEE, @FIRST_INS_FEE=FIRST_INS_FEE , @TOTAL_PREMIUM_DUE  = TOTAL_PREMIUM_DUE
	FROM @AMOUNT_DUE            
       
	IF (@TOTAL_DUE < 9999999 OR @TOTAL_DUE > -9999999) AND (@MINIMUM_DUE > -9999999 OR @MINIMUM_DUE < 9999999)
		BEGIN    
			SET @OCRA = @OCRA + ' X ' + RIGHT('000000' + CONVERT(VARCHAR,CONVERT(INT,@TOTAL_DUE * 100)),6) + RIGHT('000000' + CONVERT(VARCHAR,CONVERT(INT,@MINIMUM_DUE * 100)),6)
        END
                                        
	SELECT 		
		@POLICY_NO = PCPL.POLICY_NUMBER,
		@APP_TERM =	dbo.fun_GetLanguageBasedDateFormat(PCPL.APP_EFFECTIVE_DATE,@LANG_ID) + '-' + dbo.fun_GetLanguageBasedDateFormat(PCPL.APP_EXPIRATION_DATE,@LANG_ID),
		@CUSTOMER_NAME = RTRIM(ISNULL(CCL.CUSTOMER_FIRST_NAME,'')) + ' ' +                                         
		CASE WHEN CCL.CUSTOMER_MIDDLE_NAME IS NULL THEN '' ELSE RTRIM(CCL.CUSTOMER_MIDDLE_NAME) + ' ' END +                       
		ISNULL(CCL.CUSTOMER_LAST_NAME,''),
		@CUSTOMER_SUFFIX = ISNULL(CCL.CUSTOMER_SUFFIX,''),
		@CUSTOMER_ADDRESS1 = RTRIM(CCL.CUSTOMER_ADDRESS1), 
		@CUSTOMER_ADDRESS2 = RTRIM(CCL.CUSTOMER_ADDRESS2),                                               
		@CUSTOMER_CITY = CCL.CUSTOMER_CITY,
		@STATE_CODE = MCSL.STATE_CODE,
		@CUSTOMER_ZIP = CCL.CUSTOMER_ZIP,
		@AGENCY_ID = MAL.AGENCY_ID,
		@AGENCY_DISPLAY_NAME = MAL.AGENCY_DISPLAY_NAME,
		@AGENCY_CODE = MAL.AGENCY_CODE,                                              
		@AGENCY_ADD1 = MAL.AGENCY_ADD1, 
		@AGENCY_ADD2 = MAL.AGENCY_ADD2, 
		@AGENCY_CITY = MAL.AGENCY_CITY,                                  
		@APP_INCEPTION_DATE = PCPL.APP_EFFECTIVE_DATE,
		@APP_EXPIRATION_DATE = PCPL.APP_EXPIRATION_DATE,
		@AGENCY_ZIP = MAL.AGENCY_ZIP,
		@AGENCY_PHONE = MAL.AGENCY_PHONE,
		@NOTICE_TYPE = 'Premium Notice',                                 
		@LOB_DESCRIPTION = MLM.LOB_DESC,
		@POLICY_TYPE = CASE MLV2.LOOKUP_VALUE_DESC WHEN '' THEN MLV.LOOKUP_VALUE_CODE ELSE MLV2.LOOKUP_VALUE_DESC END,
		@POLICY_NUMBER = PCPL.POLICY_NUMBER,
		@LOB_CODE = MLM.LOB_CODE,
		@BILL_PLAN = PCPL.BILL_TYPE_ID,
		@DUE_DATE =	dbo.fun_GetLanguageBasedDateFormat(PCPL.APP_EFFECTIVE_DATE,@LANG_ID) ,
		@EFFECTIVE_DATE = dbo.fun_GetLanguageBasedDateFormat(@NOTICE_DUE_DATE,@LANG_ID)
	FROM POL_CUSTOMER_POLICY_LIST PCPL                                         
	INNER JOIN CLT_CUSTOMER_LIST CCL                                         
	ON CCL.CUSTOMER_ID=PCPL.CUSTOMER_ID 
	INNER JOIN POL_POLICY_STATUS_MASTER PSM (NOLOCK)                          
	ON PSM.POLICY_STATUS_CODE = PCPL.POLICY_STATUS                                             
	LEFT OUTER JOIN MNT_COUNTRY_STATE_LIST MCSL                                   
	ON CCL.CUSTOMER_STATE = MCSL.STATE_ID 
	LEFT OUTER JOIN MNT_LOB_MASTER MLM                                         
	ON PCPL.POLICY_LOB = MLM.LOB_ID                                              
	LEFT OUTER JOIN MNT_AGENCY_LIST MAL                                         
	ON PCPL.AGENCY_ID = MAL.AGENCY_ID 
	LEFT OUTER JOIN ACT_INSTALL_PLAN_DETAIL  ACT  (NOLOCK)                         
	ON PCPL.INSTALL_PLAN_ID = ACT.IDEN_PLAN_ID   
	LEFT OUTER JOIN MNT_LOOKUP_VALUES MLV with(nolock)      
	ON MLV.LOOKUP_UNIQUE_ID = PCPL.POLICY_TYPE
	LEFT OUTER JOIN MNT_LOOKUP_VALUES_MULTILINGUAL MLV2 ON
	MLV.LOOKUP_UNIQUE_ID=MLV2.LOOKUP_UNIQUE_ID and MLV2.LANG_ID=@LANG_ID	
	WHERE PCPL.CUSTOMER_ID=@CUSTOMER_ID AND PCPL.POLICY_ID=@POLICY_ID AND PCPL.POLICY_VERSION_ID=@CURRENT_VERSION_ID
			
	SELECT  @STATUS = dbo.fun_GetPolicyDisplayStatus(POL.CUSTOMER_ID,POL.POLICY_ID,POL.POLICY_VERSION_ID, @LANG_ID)
	FROM POL_CUSTOMER_POLICY_LIST POL (NOLOCK) 
	WHERE POL.CUSTOMER_ID=@CUSTOMER_ID AND POL.POLICY_ID=@POLICY_ID AND POL.POLICY_VERSION_ID=@MAXTERM_CURRENT_VERSION_ID  
	
End

SELECT
	@POLICY_NO AS POLICY_NO,
	@APP_TERM AS APP_TERM,
	@CUSTOMER_NAME AS CUSTOMER_NAME,
	@CUSTOMER_SUFFIX AS CUSTOMER_SUFFIX,
	@OCRA AS OCRA, @PLAN_DESCRIPTION  AS PLAN_DESCRIPTION,
	@CUSTOMER_ADDRESS1 AS CUSTOMER_ADDRESS1, 
	@CUSTOMER_ADDRESS2 AS CUSTOMER_ADDRESS2,
	@CUSTOMER_CITY AS CUSTOMER_CITY,
	@STATE_CODE AS STATE_CODE,
	@CUSTOMER_ZIP AS CUSTOMER_ZIP,
	@AGENCY_ID AS AGENCY_ID, 
	@AGENCY_DISPLAY_NAME AS AGENCY_DISPLAY_NAME,
	@AGENCY_CODE AS AGENCY_CODE, 
	@AGENCY_ADD1 AS AGENCY_ADD1,
	@AGENCY_ADD2 AS AGENCY_ADD2,
	@AGENCY_CITY AS AGENCY_CITY, 
	dbo.fun_GetLanguageBasedDateFormat(@APP_INCEPTION_DATE,@LANG_ID) AS APP_INCEPTION_DATE,
	dbo.fun_GetLanguageBasedDateFormat(@APP_EXPIRATION_DATE,@LANG_ID) AS APP_EXPIRATION_DATE,	
	@AGENCY_ZIP AS AGENCY_ZIP,
	@AGENCY_PHONE AS AGENCY_PHONE,
	@NOTICE_TYPE AS NOTICE_TYPE,
	@LOB_DESCRIPTION AS LOB_DESCRIPTION,
	@POLICY_TYPE AS POLICY_TYPE,
	@POLICY_NUMBER AS POLICY_NUMBER,
	@LOB_CODE AS LOB_CODE,
	'$' + convert(varchar(30),convert(money,@TOTAL_DUE),1) AS TOTAL_DUE,
	'$' + convert(varchar(30),convert(money,@MINIMUM_DUE),1) AS MINIMUM_DUE,   
	'$' + convert(varchar(30),convert(money,@AMOUNT_PAID),1) AS AMOUNT_PAID,
	'$' + CONVERT(VARCHAR(30),CONVERT(MONEY,ISNULL(@NON_SUFFICIENT_FUND_FEES,0)),1) AS NSF_FEE,
	'$' + CONVERT(VARCHAR(30),CONVERT(MONEY,ISNULL(@LATE_FEES,0)),1) AS LATE_FEE,
	@BILL_PLAN AS BILL_PLAN,
	@DUE_DATE AS DUE_DATE, 
	@EFFECTIVE_DATE AS NOTICE_DUE_DATE,     
	@SHOW_INSTALLMENTS AS SHOW_INS_SCHEDULE  ,
	@ADD_INT_ID AS BILL_MORTAGAGEE  ,
	@TOTAL_PREMIUM_DUE AS TOTAL_PREMIUM_DUE,
	@BILL_TYPE AS BILL_TYPE ,
	@RENEWED AS RENEWED,
	@STATUS AS STATUS



GO

