   
 /*----------------------------------------------------------                      
Proc Name       : dbo.[Proc_Insert_POL_SUP_FORM_WAREHOUSE]              
Created by      : SNEHA          
Date            : 23/11/2011                      
Purpose         :INSERT RECORDS IN POL_SUP_FORM_WAREHOUSE TABLE.                      
Revison History :                      
Used In        : Ebix Advantage                      
------------------------------------------------------------                      
Date     Review By          Comments                      
------   ------------       -------------------------      
DROP PROC dbo.[Proc_Insert_POL_SUP_FORM_WAREHOUSE]        
      
*/  

CREATE PROC dbo.[Proc_Insert_POL_SUP_FORM_WAREHOUSE]  
(
@CUSTOMER_ID				INT,
@POLICY_ID					INT,
@POLICY_VERSION_ID			SMALLINT,
@LOCATION_ID				SMALLINT,
@PREMISES_ID				INT,
@WAREHOUSE_ID				INT OUT,
@BUILDINGS					INT,
@OWN_MGMR					NVARCHAR(10),
@RES_MGMR					NVARCHAR(10),
@DAYTIME_ATTNDT				NVARCHAR(10),
@ANY_BUSS_ACTY				NVARCHAR(10),
@VLT_STYLE					NVARCHAR(10),
@TRUCK_RENTAL				NVARCHAR(10),
@MGMR_KYS_CUST_UNIT			NVARCHAR(10),
@NOTICE_SENT				NVARCHAR(10),
@SALES_TENANT_LST_TWELVE_MNTHS	INT,
@ANY_COLD_STORAGE			NVARCHAR(10),
@MGMR_TYPE					NVARCHAR(10),
@STORAGEUNITS				INT,
@IS_FENCED					NVARCHAR(10),
@IS_PRKNG_AVL				NVARCHAR(10),
@IS_BOAT_PRKNG_AVL			NVARCHAR(10),
@ANY_FIREARMS				NVARCHAR(10),
@TENANT_LCKS_CHK			NVARCHAR(10),
@ANY_BUSN_GUIDELINES		NVARCHAR(10),
@NO_DYS_TENANT_PROP_SOLD	INT,
@DISP_PUBL					NVARCHAR(10),
@ANY_CLIMATE_CNTL			NVARCHAR(10),
@GUARD_DOG					NVARCHAR(10)
)
AS
BEGIN
SELECT @WAREHOUSE_ID =ISNULL(MAX(WAREHOUSE_ID),0)+1 FROM POL_SUP_FORM_WAREHOUSE


INSERT INTO POL_SUP_FORM_WAREHOUSE
(
CUSTOMER_ID,
POLICY_ID,
POLICY_VERSION_ID,
LOCATION_ID,
PREMISES_ID,
WAREHOUSE_ID,
BUILDINGS,
OWN_MGMR,
RES_MGMR,
DAYTIME_ATTNDT,
ANY_BUSS_ACTY,
VLT_STYLE,
TRUCK_RENTAL,
MGMR_KYS_CUST_UNIT,
NOTICE_SENT,
SALES_TENANT_LST_TWELVE_MNTHS,
ANY_COLD_STORAGE,
MGMR_TYPE,
STORAGEUNITS,
IS_FENCED,
IS_PRKNG_AVL,
IS_BOAT_PRKNG_AVL,
ANY_FIREARMS,
TENANT_LCKS_CHK,
ANY_BUSN_GUIDELINES,
NO_DYS_TENANT_PROP_SOLD,
DISP_PUBL,
ANY_CLIMATE_CNTL,
GUARD_DOG
)
VALUES
(
@CUSTOMER_ID				,
@POLICY_ID					,
@POLICY_VERSION_ID			,
@LOCATION_ID				,
@PREMISES_ID				,
@WAREHOUSE_ID				,
@BUILDINGS					,
@OWN_MGMR					,
@RES_MGMR					,
@DAYTIME_ATTNDT				,
@ANY_BUSS_ACTY				,
@VLT_STYLE					,
@TRUCK_RENTAL				,
@MGMR_KYS_CUST_UNIT			,
@NOTICE_SENT				,
@SALES_TENANT_LST_TWELVE_MNTHS	,
@ANY_COLD_STORAGE			,
@MGMR_TYPE					,
@STORAGEUNITS				,
@IS_FENCED					,
@IS_PRKNG_AVL				,
@IS_BOAT_PRKNG_AVL			,
@ANY_FIREARMS				,
@TENANT_LCKS_CHK			,
@ANY_BUSN_GUIDELINES		,
@NO_DYS_TENANT_PROP_SOLD	,
@DISP_PUBL					,
@ANY_CLIMATE_CNTL		,
@GUARD_DOG
)
END
