IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Proc_GetLobByCountryID]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].Proc_GetLobByCountryID
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROC Proc_GetLobByCountryID   
@COUNTRY_ID INT  
AS  
SELECT LOB_ID,LOB_CODE,LOB_DESC FROM MNT_LOB_MASTER with (NOLOCK)  where LOB_ID IN (   
 SELECT LOB_ID from MNT_LOB_STATE with (NOLOCK) where STATE_ID IN   
  (  
   SELECT STATE_ID from MNT_COUNTRY_STATE_LIST with (NOLOCK) where COUNTRY_ID=@COUNTRY_ID) and IS_ACTIVE='Y')