 IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[Proc_Update_Motor_QQ_Details]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[Proc_Update_Motor_QQ_Details]
GO

SET ANSI_NULLS OFF
GO

SET QUOTED_IDENTIFIER OFF
GO


 
 /*----------------------------------------------------------    
Proc Name       : [Proc_Update_Motor_QQ_Details]    
Created by      : Agniswar Das    
Date            : 7/17/2011    
Purpose			: Demo    
Revison History :    
Used In        : Singapore    
------------------------------------------------------------    
Date     Review By          Comments    
------   ------------       -------------------------*/   





CREATE PROC dbo.Proc_Update_Motor_QQ_Details (  
 @CUSTOMER_ID int,    
 @POLICY_ID int,    
 @POLICY_VERSION_ID int ,  
 @CUSTOMER_ADDRESS1 varchar(250) = null,  
 @CUSTOMER_ADDRESS2 varchar(250) = null,  
 @CUSTOMER_CITY varchar(150) = null,  
 @CUSTOMER_STATE varchar(150) = null,  
 @CUSTOMER_ZIP varchar(150) = null,  
 @MARITAL_STATUS nchar(8) = null,  
 @CUSTOMER_CONTACT_NO nvarchar(60) = null,  
 @PASSPORT_NO nvarchar(60) = null,  
 @EXISTING_INSURER nvarchar(500) = null,  
 @EXISTING_POL_NUM nvarchar(160) = null,  
 @EXIST_POL_EXP_DATE varchar(250) = null,  
 @VEHICLE_NO nvarchar(80) = null,  
 @IS_NEW nchar(4) = null,  
 @REGISTRATION_NO nvarchar(100) = null,  
 @COVER_NOTE_NO nvarchar(100) = null,  
 @DATE_LTA_REGISTRATION varchar(25) = null,  
 @ENGINE_NO nvarchar(60) = null,  
 @CHASSIS_NO nvarchar(60) = null,  
 @IS_UNDER_HIRE nchar(4) = null,  
 @FINANCE_COMP_NAME varchar(100) = null,  
 @IS_DEMERIT_POINT nchar(4) = null,  
 @DEMERIT_DESC varchar(800) = null,  
 @IS_REJECTED nchar(4) = null,  
 @REJECTED_DESC varchar(800) = null,  
 @IS_DISEASE nchar(4) = null,  
 @DISEASE_DESC varchar(800) = null  
)  
  
AS  
  
BEGIN  
  
UPDATE CP  
SET  
CP.CUSTOMER_ADDRESS1 = @CUSTOMER_ADDRESS1,  
CP.CUSTOMER_ADDRESS2 = @CUSTOMER_ADDRESS2,  
CP.CUSTOMER_CITY = @CUSTOMER_CITY,  
CP.CUSTOMER_STATE = @CUSTOMER_STATE,  
CP.CUSTOMER_ZIP = @CUSTOMER_ZIP,  
CP.MARITAL_STATUS = @MARITAL_STATUS,  
CP.CUSTOMER_CONTACT_NO = @CUSTOMER_CONTACT_NO,  
CP.PASSPORT_NO = @PASSPORT_NO,  
CP.EXISTING_INSURER = @EXISTING_INSURER,  
CP.EXISTING_POL_NUM = @EXISTING_POL_NUM,  
CP.EXIST_POL_EXP_DATE = @EXIST_POL_EXP_DATE,  
CP.VEHICLE_NO = @VEHICLE_NO  
  
FROM POL_CUSTOMER_POLICY_LIST PL    
INNER JOIN CLT_QUICKQUOTE_LIST QL    
ON PL.CUSTOMER_ID = QL.CUSTOMER_ID    
AND PL.POLICY_ID = QL.APP_ID    
AND PL.POLICY_VERSION_ID = QL.APP_VERSION_ID    
INNER JOIN QQ_CUSTOMER_PARTICULAR CP    
ON CP.CUSTOMER_ID = QL.CUSTOMER_ID    
AND CP.QUOTE_ID = QL.QQ_ID    
INNER JOIN QQ_MOTOR_QUOTE_DETAILS QD    
ON QD.CUSTOMER_ID = PL.CUSTOMER_ID    
AND QD.POLICY_ID = PL.POLICY_ID    
AND QD.POLICY_VERSION_ID = PL.POLICY_VERSION_ID    
INNER JOIN MNT_COUNTRY_LIST CN    
ON CN.COUNTRY_ID = CP.NATIONALITY   
INNER JOIN MNT_COVERAGE MC  
ON MC.COV_ID = QD.COVERAGE_TYPE   
INNER JOIN MNT_LOOKUP_VALUES LV    
ON LV.LOOKUP_UNIQUE_ID = CP.CUSTOMER_TYPE    
INNER JOIN MNT_LOOKUP_VALUES LO  
ON LO.LOOKUP_UNIQUE_ID = QD.MAKE  
INNER JOIN MNT_VEHICLE_MODEL_LIST ML  
ON ML.ID = QD.MODEL  
INNER JOIN MNT_VEHICLE_MODEL_TYPE_LIST TL  
ON TL.ID = QD.MODEL_TYPE  
INNER JOIN MNT_AGENCY_LIST AL  
ON AL.AGENCY_ID = CP.CUSTOMER_AGENCY_ID  
WHERE PL.CUSTOMER_ID = @CUSTOMER_ID    
AND PL.POLICY_ID = @POLICY_ID    
AND PL.POLICY_VERSION_ID = @POLICY_VERSION_ID    
  
  
  
UPDATE QD  
SET  
QD.IS_NEW = @IS_NEW,  
QD.REGISTRATION_NO = @REGISTRATION_NO,  
QD.COVER_NOTE_NO = @COVER_NOTE_NO,  
QD.DATE_LTA_REGISTRATION = @DATE_LTA_REGISTRATION,  
QD.ENGINE_NO = @ENGINE_NO,  
QD.CHASSIS_NO = @CHASSIS_NO,  
QD.IS_UNDER_HIRE = @IS_UNDER_HIRE,  
QD.FINANCE_COMP_NAME = @FINANCE_COMP_NAME,  
QD.IS_DEMERIT_POINT = @IS_DEMERIT_POINT,  
QD.DEMERIT_DESC = @DEMERIT_DESC,  
QD.IS_REJECTED = @IS_REJECTED,  
QD.REJECTED_DESC = @REJECTED_DESC,  
QD.IS_DISEASE = @IS_DISEASE,  
QD.DISEASE_DESC = @DISEASE_DESC  
  
FROM POL_CUSTOMER_POLICY_LIST PL    
INNER JOIN CLT_QUICKQUOTE_LIST QL    
ON PL.CUSTOMER_ID = QL.CUSTOMER_ID    
AND PL.POLICY_ID = QL.APP_ID    
AND PL.POLICY_VERSION_ID = QL.APP_VERSION_ID    
INNER JOIN QQ_CUSTOMER_PARTICULAR CP    
ON CP.CUSTOMER_ID = QL.CUSTOMER_ID    
AND CP.QUOTE_ID = QL.QQ_ID    
INNER JOIN QQ_MOTOR_QUOTE_DETAILS QD    
ON QD.CUSTOMER_ID = PL.CUSTOMER_ID    
AND QD.POLICY_ID = PL.POLICY_ID    
AND QD.POLICY_VERSION_ID = PL.POLICY_VERSION_ID    
INNER JOIN MNT_COUNTRY_LIST CN    
ON CN.COUNTRY_ID = CP.NATIONALITY   
INNER JOIN MNT_COVERAGE MC  
ON MC.COV_ID = QD.COVERAGE_TYPE   
INNER JOIN MNT_LOOKUP_VALUES LV    
ON LV.LOOKUP_UNIQUE_ID = CP.CUSTOMER_TYPE    
INNER JOIN MNT_LOOKUP_VALUES LO  
ON LO.LOOKUP_UNIQUE_ID = QD.MAKE  
INNER JOIN MNT_VEHICLE_MODEL_LIST ML  
ON ML.ID = QD.MODEL  
INNER JOIN MNT_VEHICLE_MODEL_TYPE_LIST TL  
ON TL.ID = QD.MODEL_TYPE  
INNER JOIN MNT_AGENCY_LIST AL  
ON AL.AGENCY_ID = CP.CUSTOMER_AGENCY_ID  
WHERE PL.CUSTOMER_ID = @CUSTOMER_ID    
AND PL.POLICY_ID = @POLICY_ID    
AND PL.POLICY_VERSION_ID = @POLICY_VERSION_ID   
  
END