/*  
DROP  PROCEDURE dbo.PROC_POLICY_REIN_INSTALLMENT_DETAILS    
EXEC PROC_POLICY_REIN_INSTALLMENT_DETAILS 4510,7,1  
*/  
CREATE PROCEDURE dbo.PROC_POLICY_REIN_INSTALLMENT_DETAILS    
 @CUSTOMER_ID       INT,              
 @POLICY_ID        INT,              
 @POLICY_VERSION_ID  SMALLINT     
    
AS    
BEGIN                        
 SET NOCOUNT ON;     
DECLARE @NOOFPOLINSTALLMENT INT    
DECLARE @COUNT INT   
  
SELECT @NOOFPOLINSTALLMENT = NO_OF_PAYMENTS FROM ACT_POLICY_INSTALL_PLAN_DATA APIPD WITH(NOLOCK) WHERE APIPD.CUSTOMER_ID = @CUSTOMER_ID AND APIPD.POLICY_ID = @POLICY_ID AND APIPD.POLICY_VERSION_ID = @POLICY_VERSION_ID  ;  
    
CREATE TABLE #TEMP  
(  
 IDENTITY_COL INT IDENTITY(1,1),  
 CONTRACT_NUMBER VARCHAR(200),   
 MAX_NO_INSTALLMENT INT,  
 COMPANY_ID INT,  
 REIN_PREMIUM DECIMAL(18,2),  
 POLICY_INSTALLMENT INT  
)    
    
INSERT INTO #TEMP   
(  
 CONTRACT_NUMBER,  
 MAX_NO_INSTALLMENT,  
 COMPANY_ID,  
 REIN_PREMIUM,  
 POLICY_INSTALLMENT  
)    
SELECT * FROM    
(   
SELECT RI.CONTRACT_NUMBER,REIN.MAX_NO_INSTALLMENT,NULL AS COMPANY_ID,REIN_PREMIUM,@NOOFPOLINSTALLMENT AS POLICY_INSTALLMENT FROM POL_REINSURANCE_BREAKDOWN_DETAILS RI (NOLOCK)  
JOIN MNT_REINSURANCE_CONTRACT REIN (NOLOCK) ON   
UPPER(RI.CONTRACT_NUMBER )= UPPER(REIN.CONTRACT_NUMBER)  
WHERE CUSTOMER_ID = @CUSTOMER_ID AND   
POLICY_ID = @POLICY_ID AND POLICY_VERSION_ID = @POLICY_VERSION_ID AND UPPER(RI.CONTRACT_NUMBER) <> 'Facultative'  
  
UNION ALL  
  
SELECT RI.CONTRACT_NUMBER,REIN.MAX_NO_INSTALLMENT,REIN.COMPANY_ID AS COMPANY_ID,REIN_PREMIUM,@NOOFPOLINSTALLMENT AS POLICY_INSTALLMENT  FROM POL_REINSURANCE_BREAKDOWN_DETAILS RI (NOLOCK)  
JOIN POL_REINSURANCE_INFO REIN (NOLOCK) ON   
RI.CUSTOMER_ID = REIN.CUSTOMER_ID AND   
RI.POLICY_ID = REIN.POLICY_ID AND   
RI.POLICY_VERSION_ID = REIN.POLICY_VERSION_ID  
WHERE RI.CUSTOMER_ID = @CUSTOMER_ID AND   
RI.POLICY_ID = @POLICY_ID AND RI.POLICY_VERSION_ID = @POLICY_VERSION_ID AND UPPER(RI.CONTRACT_NUMBER) = 'Facultative'  
) A  
  
  
UPDATE #TEMP  
SET MAX_NO_INSTALLMENT = POLICY_INSTALLMENT  
WHERE  POLICY_INSTALLMENT <= MAX_NO_INSTALLMENT  
  
  
  
DECLARE @COUNT_START INT  
SELECT  @COUNT_START = MIN(IDENTITY_COL) FROM #TEMP  
  
WHILE ((SELECT MAX(IDENTITY_COL) FROM #TEMP) >= @COUNT_START)  
BEGIN   
  DECLARE @MAX_NO_INSTL INT  
  DECLARE  @INDEX INT = 1  
  SELECT @MAX_NO_INSTL = MAX_NO_INSTALLMENT FROM #TEMP WHERE IDENTITY_COL = @COUNT_START  
    
   
    WHILE(@MAX_NO_INSTL >= @INDEX)  
     BEGIN   
                        
         INSERT INTO ACT_POLICY_REIN_INSTALLMENT_DETAILS(CUSTOMER_ID,POLICY_ID,POLICY_VERSION_ID,REIN_COMPANY_ID,CONTRACT_NUMBER,INSTALLMENT_NO,INSTALLMENT_AMOUNT,  
         INTEREST_AMOUNT,FEE,TAXES,TOTAL,INSTALLMENT_EFFECTIVE_DATE,RELEASED_STATUS,PAYMENT_MODE,CREATED_BY,CREATED_DATETIME,MODIFIED_BY,LAST_UPDATED_DATETIME,PAID_AMOUNT,  
         RECEIVED_AMOUNT,RECEIVED_DATE,INSTALLMENT_EXPIRE_DATE,ACC_CO_DISCOUNT,IS_COMMISSION_PROCESS,IS_PAID_TO_PAGNET,PAGNET_DATE)  
           
         SELECT @CUSTOMER_ID,@POLICY_ID,@POLICY_VERSION_ID,CASE WHEN T.CONTRACT_NUMBER = UPPER('Facultative') THEN PRI1.COMPANY_ID ELSE NULL END AS REIN_COMP_ID,  
         PRBD1.CONTRACT_NUMBER,@INDEX,(PRBD1.REIN_PREMIUM/@NOOFPOLINSTALLMENT) AS INSTALLMENT_AMT,  
         0,0,0,0,GETDATE(),'Y',NULL,NULL,GETDATE(),NULL,NULL,0,0,NULL,NULL,NULL,NULL,NULL,NULL    
         FROM #TEMP T WITH(NOLOCK)   
         LEFT OUTER JOIN POL_REINSURANCE_BREAKDOWN_DETAILS PRBD1 WITH(NOLOCK)ON T.CONTRACT_NUMBER = PRBD1.CONTRACT_NUMBER  
         LEFT OUTER JOIN POL_REINSURANCE_INFO PRI1 WITH(NOLOCK) ON PRBD1.CUSTOMER_ID = PRI1.CUSTOMER_ID AND PRBD1.POLICY_ID = PRI1.POLICY_ID AND PRBD1.POLICY_VERSION_ID = PRI1.POLICY_VERSION_ID   
         LEFT OUTER JOIN MNT_REINSURANCE_CONTRACT MRC1 WITH(NOLOCK) ON PRBD1.CONTRACT_NUMBER = MRC1.CONTRACT_NUMBER  
         WHERE PRBD1.CUSTOMER_ID = @CUSTOMER_ID AND PRBD1.POLICY_ID = @POLICY_ID AND PRBD1.POLICY_VERSION_ID = @POLICY_VERSION_ID   
         and T.IDENTITY_COL  = @COUNT_START  
          
       SET @INDEX  +=1  
     END     
SET @COUNT_START +=1  
END  
  
END  