    
 /*----------------------------------------------------------                      
Proc Name       : dbo.[Proc_GET_POL_SUP_FORM_CONTRACTOR]              
Created by      : SNEHA          
Date            : 23/11/2011                      
Purpose         :INSERT RECORDS IN POL_SUP_FORM_CONTRACTOR TABLE.                      
Revison History :                      
Used In        : Ebix Advantage                      
------------------------------------------------------------                      
Date     Review By          Comments                      
------   ------------       -------------------------      
DROP PROC dbo.[Proc_GET_POL_SUP_FORM_CONTRACTOR] 28,1,1,1,1,1
*/

CREATE PROC dbo.[Proc_GET_POL_SUP_FORM_CONTRACTOR]
(
@CUSTOMER_ID				[INT],
@POLICY_ID					[INT],
@POLICY_VERSION_ID			[SMALLINT],
@LOCATION_ID				[SMALLINT],
@PREMISES_ID				[INT],
@CONTRACTOR_ID				[INT] 
)
AS
BEGIN
SELECT 
		TYP_CONTRACTOR,YR_EXP,CONT_LICENSE,LICENSE_HOLDER,LMT_CONTRACTOR_OCC,LMT_CONTRACTOR_AGG,TOT_CST_PST_YR,IS_EXPL_ENVRNT,IS_FIRE_ALARM,IS_HOSPITALS,IS_EXP_ENVRNT,IS_SWIMMING_POOL,IS_BRG_ALARM,IS_PWR_PLANTS,IS_BCK_EQUIPMNT,IS_LIVE_WIRES,IS_ARPT_CONSTRCT,IS_HIGH_VOLTAGE,IS_TRAFFIC_WRK,IS_LND_FILL,IS_DAM_CONSTRNT,IS_REFINERY,IS_HZD_MATERIAL,IS_PETRO_PLNT,IS_NUCL_PLNT,IS_PWR_LINES,DRW_PLANS,OPR_BLASTING,OPR_TRENCHING,OPR_EXCAVACATION,IS_SECTY_POLICY,ANY_DEMOLITION,ANY_CRANES,PERCENT_ROOFING,ANY_LESS_LMTS,ANY_SHOP_WRK,PERCENT_RENOVATION,ANY_GUTTING,PERCENT_SNOWPLOWING,ANY_WRK_LOAD,PERCENT_PNTG_OUTSIDE,PERCENT_PNTG_INSIDE,ANY_PNTG_TNKS,PERCENT_PNTG_SPRY,ANY_EPOXIES,ANY_ACID,ANY_LEASE_EQUIPMNT,ANY_BOATS_OWND,DRCT_SIGHT_WRK_IN_PRGRSS,PRDCT_SOLD_IN_APPL_NAME,UTILITY_CMPNY_CALLED,TYP_IN_DGGN_PRCSS,PERMIT_OBTAINED,PERCENT_SPRINKLE_WRK,ANY_EXCAVAION,ANY_PEST_SPRAY,PERCENT_TREE_TRIMNG,ANY_WRK_OFFSEASON,ANY_MIX_TRANSIT,ANY_CONTSRUCTION_WRK,ANY_WRK_ABVE_THREE_STORIES,ANY_SCAFHOLDING_ABVE_TWELVE_FEET,ANY_PNTG_TOWERS,ANY_SPRAY_GUNS,ANY_REMOVAL_DONE,ANY_WAXING_FLOORS,PER_RESIDENT,PER_COMMERICAL,PER_CONST,PER_REMODEL,MAJOR_ELECT,CARRY_LIMITS,'IS_ACTIVE' AS IS_ACTIVE
FROM 
			POL_SUP_FORM_CONTRACTOR
	WHERE 
			CUSTOMER_ID				=@CUSTOMER_ID       AND
			POLICY_ID				=@POLICY_ID         AND
			POLICY_VERSION_ID		=@POLICY_VERSION_ID	AND
			LOCATION_ID				=@LOCATION_ID       AND
			PREMISES_ID				=@PREMISES_ID       AND
			CONTRACTOR_ID			=@CONTRACTOR_ID
END