IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROC_IOF_REPORT]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[PROC_IOF_REPORT]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO




-- =============================================                    
-- Author:  <SHIKHA CHOURASIYA>                    
-- Create date: <2011-11-04>                    
-- ===============================================                    
---I-TRACK #1783                    
--  *********************  MODIFICATION HISTORY   *********************                    
-- MODIFIED BY :                      
-- MODIFIED DATE :                    
-- DESCRIPTION :                       
--   ************************************************************                    
--  *********************  EXECUTION PATH   *********************            
 -- EXEC [PROC_IOF_REPORT] 119                  
 -- DROP PROC [PROC_IOF_REPORT]                 
-- =============================================                    
CREATE PROCEDURE [dbo].[PROC_IOF_REPORT]      
@DEPOSIT_ID INT = NULL    
    
AS                        
BEGIN                        
SET NOCOUNT ON;    
WITH IOF_REPORT    
AS    
(    
select     
ACDLI.DEPOSIT_ID,    
ACD.DEPOSIT_NUMBER ,    
--PCPL.DIV_ID,    
DIV.DIV_CODE,    
PCPL.SUSEP_LOB_CODE,    
--ACDLI.TOTAL_PREMIUM_COLLECTION,    
ACDLI.RISK_PREMIUM  + ISNULL(ACDLI.FEE,0) + ISNULL(ACDLI.TAX,0) + ISNULL(ACDLI.INTEREST,0) AS TOTAL_PREMIUM,    
--ACDLI.LATE_FEE,    
PCPL.POLICY_NUMBER,    
    
ISNULL((select CONVERT(VARCHAR(10),ISNULL(LOOK_UP.Type,'')) + '.' +    
+ '000000' + CONVERT(VARCHAR(10),ISNULL(a.ENDORSEMENT_NO,0))     
 +       
   CASE       
    WHEN ppe.END_VERIFY_DIGIT IS NOT NULL THEN '.' + CONVERT(VARCHAR(10), ppe.END_VERIFY_DIGIT)      
    ELSE  '.' + CONVERT(VARCHAR(10),0)       
   END     
from POL_POLICY_ENDORSEMENTS  a     
left join POL_POLICY_PROCESS ppp WITH(NOLOCK) ON (PPP.CUSTOMER_ID = a.CUSTOMER_ID       
            AND PPP.POLICY_ID = a.POLICY_ID      
            AND PPP.NEW_POLICY_VERSION_ID = a.POLICY_VERSION_ID      
            AND PPP.PROCESS_STATUS <> 'ROLLBACK')    
left join MNT_LOOKUP_VALUES look_up WITH(NOLOCK) ON (ppp.ENDORSEMENT_TYPE = LOOK_UP.LOOKUP_UNIQUE_ID)    
where a.CUSTOMER_ID = PPE.CUSTOMER_ID and a.POLICY_ID = PPE.POLICY_ID and a.POLICY_VERSION_ID = PPE.POLICY_VERSION_ID),'0.0000000.0') AS ENDORSEMENT_NO,    
    
    
--ISNULL(PPE.ENDORSEMENT_NO,0) AS ENDORSEMENT_NO,    
ACDLI.INSTALLMENT_NO,    
ACDLI.RISK_PREMIUM+ ACDLI.FEE+ACDLI.INTEREST AS VALOR_PREMIO,    
ACDLI.TAX AS VALOR_ISOF,    
'AI ' + PIB.OUR_NUMBER AS OUR_NUMBER,    
CAL.FIRST_NAME + ISNULL(' ' + CAL.MIDDLE_NAME,'') + ISNULL(' ' + CAL.LAST_NAME,'') AS APPLICANT_NAME    
,ACDLI.IS_EXCEPTION,    
 ACDLI.IS_APPROVE,    
 ABI.BANK_NAME,    
 ABI.BANK_CITY,    
 ABI.BANK_STATE,    
 ABI.NUMBER     
     
 --ACDLI.*    
    
FROM ACT_CURRENT_DEPOSIT_LINE_ITEMS ACDLI WITH(NOLOCK)    
JOIN POL_CUSTOMER_POLICY_LIST PCPL WITH(NOLOCK) ON PCPL.CUSTOMER_ID=ACDLI.CUSTOMER_ID AND PCPL.POLICY_ID=ACDLI.POLICY_ID AND PCPL.POLICY_VERSION_ID = ACDLI.POLICY_VERSION_ID    
INNER JOIN ACT_CURRENT_DEPOSITS ACD WITH(NOLOCK) ON (ACD.DEPOSIT_ID = ACDLI.DEPOSIT_ID AND ACD.DEPOSIT_TYPE = 14831  AND ACD.IS_COMMITED = 'Y')--FOR NORMAL DEPOSIT TYPE    
LEFT JOIN ACT_BANK_INFORMATION ABI WITH(NOLOCK) ON (ABI.BANK_ID = ACD.ACCOUNT_ID)    
LEFT JOIN POL_POLICY_ENDORSEMENTS PPE WITH(NOLOCK) ON PPE.CUSTOMER_ID=ACDLI.CUSTOMER_ID AND PPE.POLICY_ID=ACDLI.POLICY_ID AND PPE.POLICY_VERSION_ID = ACDLI.POLICY_VERSION_ID    
LEFT JOIN MNT_DIV_LIST DIV (NOLOCK) ON DIV.DIV_ID=PCPL.DIV_ID    
JOIN POL_INSTALLMENT_BOLETO PIB WITH(NOLOCK) ON PIB.CUSTOMER_ID=ACDLI.CUSTOMER_ID AND PIB.POLICY_ID=ACDLI.POLICY_ID AND PIB.POLICY_VERSION_ID = ACDLI.POLICY_VERSION_ID AND PIB.BOLETO_ID=ACDLI.BOLETO_NO AND PIB.IS_ACTIVE='Y'    
JOIN ACT_POLICY_INSTALLMENT_DETAILS APID (NOLOCK) ON APID.ROW_ID = PIB.INSTALLEMT_ID AND APID.INSTALLMENT_NO=PIB.INSTALLMENT_NO    
LEFT JOIN POL_APPLICANT_LIST PAL (NOLOCK) ON PAL.CUSTOMER_ID=ACDLI.CUSTOMER_ID AND PAL.POLICY_ID = ACDLI.POLICY_ID AND PAL.POLICY_VERSION_ID= ACDLI.POLICY_VERSION_ID AND PAL.APPLICANT_ID = APID.CO_APPLICANT_ID    
LEFT JOIN CLT_APPLICANT_LIST CAL (NOLOCK) ON CAL.CUSTOMER_ID=PAL.CUSTOMER_ID AND CAL.APPLICANT_ID=PAL.APPLICANT_ID    
    
WHERE     
ACDLI.DEPOSIT_ID = ISNULL(@DEPOSIT_ID,ACDLI.DEPOSIT_ID)    
AND APID.RELEASED_STATUS = 'Y'    
AND ACDLI.IS_ACTIVE = 'Y'     
AND     
   ((     
    
   ISNULL(ACDLI.IS_EXCEPTION, 'N') = 'N' AND     
    
   ISNULL(ACDLI.IS_APPROVE, '') <> 'R'     
    
   )OR     
    
   (     
    
   ISNULL(ACDLI.IS_EXCEPTION, 'N') = 'Y' AND     
    
   ISNULL(ACDLI.IS_APPROVE, '') = 'A'     
    
   ))     
--ORDER BY ACDLI.DEPOSIT_ID    
),    
TOTAL_AMOUNT_TABLE AS    
(    
select DEPOSIT_ID, COUNT(*) AS NUMBER_OF_INSTALLMENT,    
SUM(TOTAL_PREMIUM) AS PREMIUM_TOTAL,    
SUM(VALOR_PREMIO) AS VALOR_PREMIO_TOTAL,    
SUM(VALOR_ISOF) AS VALOR_ISOF_TOTAL    
 from IOF_REPORT    
 GROUP BY DEPOSIT_ID     
 )    
    
select     
IOF.DEPOSIT_ID ,    
IOF.DEPOSIT_NUMBER ,    
UPPER(IOF.BANK_NAME) AS BANK_NAME,    
UPPER(IOF.BANK_CITY) AS BANK_CITY,    
IOF.BANK_STATE,    
'RELACAO PARA RECOLHIMENTO DE I.S.O.F. DOS TITULOS CREDITADOS ATRAVES DE CARNES :' AS FIXED_TEXT,    
CASE WHEN LEN(DIV_CODE) = 1 THEN LEFT('0' + DIV_CODE,2)   
ELSE DIV_CODE END AS OE,    
RIGHT('0000' + SUSEP_LOB_CODE,4) AS RAMO,    
dbo.fun_FormatCurrency(TOTAL_PREMIUM,2) AS 'VALOR TITULO',    
POLICY_NUMBER AS 'APOLICE',    
ENDORSEMENT_NO AS DOCUMENTO,    
RIGHT('00' + CONVERT(NVARCHAR(2),INSTALLMENT_NO),2) AS PT,    
dbo.fun_FormatCurrency(VALOR_PREMIO,2) AS 'VALOR PREMIO',    
dbo.fun_FormatCurrency(VALOR_ISOF,2) AS 'VALOR ISOF',    
OUR_NUMBER AS 'NUMERO BANCO',    
APPLICANT_NAME AS SEGURADO,    
RIGHT('0000' + CONVERT(NVARCHAR(4),NUMBER_OF_INSTALLMENT),4) AS 'QUANT. DOC.',    
dbo.fun_FormatCurrency(TIOF.PREMIUM_TOTAL,2) AS PREMIUM_TOTAL,    
dbo.fun_FormatCurrency(TIOF.VALOR_PREMIO_TOTAL,2) AS VALOR_PREMIO_TOTAL,    
dbo.fun_FormatCurrency(TIOF.VALOR_ISOF_TOTAL,2) AS VALOR_ISOF_TOTAL,    
IOF.NUMBER,    
'COMPANHIA DE SEGUROS ALIANCA DA BAHIA' AS FIXED_TEXT1    
    
from IOF_REPORT IOF    
 JOIN TOTAL_AMOUNT_TABLE  TIOF ON IOF.DEPOSIT_ID = TIOF.DEPOSIT_ID    
 ORDER BY IOF.DEPOSIT_ID    
END 