/*----------------------------------------------------------                                                                  
Proc Name             : Dbo.[PROC_IBNR_REPORT]                                                         
Created by            : PUNEET KUMAR                                        
Date                  : 23 SEPT 2011                                                        
Purpose               :     
Revison History       :                                                                  
Used In               : CLAIM MODULE     
Itrack      : 1664 TFS Bug         
------------------------------------------------------------                                                                  
Date     Review By          Comments                                     
                            
drop Proc [PROC_REL_SIN_RET_EPG] '2011-08-12 18:42:38.793'                                           
------   ------------       -------------------------*/                                                                  
                                
CREATE PROCEDURE [dbo].[PROC_REL_SIN_RET_EPG]          
@FROM_DATETIME DATETIME =NULL,                            
@TO_DATETIME DATETIME =NULL                                    
AS                                      
BEGIN                                
    
SELECT        
	  POL.CUSTOMER_ID,            
	  POL.POLICY_ID,            
	  POL.POLICY_VERSION_ID,         
	  (TOTAL_TRAN_AMOUNT + (ACOI.TOTAL_DUE) - (SELECT SUM(PRBD.REIN_PREMIUM) FROM POL_REINSURANCE_BREAKDOWN_DETAILS PRBD WHERE APIPD.CUSTOMER_ID = PRBD.CUSTOMER_ID AND APIPD.POLICY_ID = PRBD.POLICY_ID AND APIPD.POLICY_VERSION_ID = PRBD.POLICY_VERSION_ID)) as EarnedPremium         
INTO #TempEarnedPremium            
FROM POL_CUSTOMER_POLICY_LIST POL            
INNER JOIN ACT_POLICY_INSTALL_PLAN_DATA APIPD ON POL.CUSTOMER_ID=APIPD.CUSTOMER_ID AND  POL.POLICY_ID=APIPD.POLICY_ID AND POL.POLICY_VERSION_ID=APIPD.POLICY_VERSION_ID          
LEFT OUTER JOIN ACT_COI_OPEN_ITEMS ACOI ON ACOI.TRANS_DESC = 'Coi Premium' and APIPD.CUSTOMER_ID = ACOI.CUSTOMER_ID AND APIPD.POLICY_ID = ACOI.POLICY_ID AND APIPD.POLICY_VERSION_ID = ACOI.POLICY_VERSION_ID         
                                    
 
CREATE TABLE #TEMPPOL
 (
 FIRST_NOTICE_OF_LOSS VARCHAR(50),
 SUSEP_LOB_CODE VARCHAR(50),
 OUTSTANDING_RESERVE VARCHAR(50),
 EARNED_PREMIUM_AMT VARCHAR(50),
 BROKER_COMMISION_AMT VARCHAR(50),
 ENR_PROLABORE_AMT VARCHAR(50)
 )	  
                 
INSERT INTO #TEMPPOL 
(
	FIRST_NOTICE_OF_LOSS,
	SUSEP_LOB_CODE,
	OUTSTANDING_RESERVE,
	EARNED_PREMIUM_AMT,
	BROKER_COMMISION_AMT,
	ENR_PROLABORE_AMT
)
SELECT 
	T.FIRST_NOTICE_OF_LOSS,
	T.SUSEP_LOB_CODE,
	T.OUTSTANDING_RESERVE,
	T.EARNED_PREMIUM_AMT,
	T.BROKER_COMMISION_AMT,
	T.ENR_PROLABORE_AMT
FROM
(  
	SELECT
	CONVERT(VARCHAR,MONTH(PPR.COMPLETED_DATETIME)) + '/' + CONVERT(VARCHAR,YEAR(PPR.COMPLETED_DATETIME))  AS FIRST_NOTICE_OF_LOSS, 
	MLM.SUSEP_LOB_CODE AS SUSEP_LOB_CODE,
	0.00 AS OUTSTANDING_RESERVE,
	0.00 AS EARNED_PREMIUM_AMT,
	SUM(TEMP.COMM) AS BROKER_COMMISION_AMT,
	SUM(ISNULL(TEMP.[ENFEE/PRLBR],0)) AS ENR_PROLABORE_AMT 
	FROM POL_CUSTOMER_POLICY_LIST POL    
	INNER JOIN POL_POLICY_PROCESS PPR WITH(NOLOCK) ON POL.CUSTOMER_ID = PPR.CUSTOMER_ID  AND POL.POLICY_ID = PPR.POLICY_ID  AND POL.POLICY_VERSION_ID = PPR.NEW_POLICY_VERSION_ID     
	INNER JOIN MNT_LOB_MASTER MLM WITH(NOLOCK) ON POL.POLICY_LOB = MLM.LOB_ID    
	INNER JOIN ACT_POLICY_INSTALL_PLAN_DATA APIPD WITH(NOLOCK)  ON POL.CUSTOMER_ID = APIPD.CUSTOMER_ID AND POL.POLICY_ID = APIPD.POLICY_ID AND POL.POLICY_VERSION_ID = APIPD.POLICY_VERSION_ID    
	LEFT OUTER JOIN POL_POLICY_ENDORSEMENTS PPE WITH(NOLOCK)  ON PPR.CUSTOMER_ID = PPE.CUSTOMER_ID AND PPR.POLICY_ID = PPE.POLICY_ID AND PPR.NEW_POLICY_VERSION_ID = PPE.POLICY_VERSION_ID   
	LEFT OUTER JOIN POL_CO_INSURANCE PCI WITH(NOLOCK) ON POL.CUSTOMER_ID = PCI.CUSTOMER_ID AND POL.POLICY_ID = PCI.POLICY_ID AND POL.POLICY_VERSION_ID = PCI.POLICY_VERSION_ID  AND PCI.LEADER_FOLLOWER = 14549 AND POL.CO_INSURANCE = 14548  
	INNER JOIN (SELECT [1] AS [ENFEE/PRLBR] ,[2] AS [COMM],CUSTOMER_ID,POLICY_ID ,POLICY_VERSION_ID    
	FROM  
	(SELECT CASE WHEN COMMISSION_TYPE IN('ENFEE','PRLBR') THEN 1  
	  ELSE 2 END AS COMMISSION_TYPE,AGENCY_COMM_AMT ,CUSTOMER_ID,POLICY_ID ,POLICY_VERSION_ID    
		FROM ACT_AGENCY_OPEN_ITEMS) AS SourceTable  
	PIVOT  
	(  
	sum(AGENCY_COMM_AMT)  
	FOR COMMISSION_TYPE IN ([1],[2])  
	) AS PivotTable) AS TEMP ON TEMP.CUSTOMER_ID = POL.CUSTOMER_ID AND TEMP.POLICY_ID = POL.POLICY_ID AND TEMP.POLICY_VERSION_ID = POL.POLICY_VERSION_ID    
	WHERE    
	 PPR.PROCESS_STATUS='Complete'    
	 AND PPR.PROCESS_ID in (14,25) -- fOR ENDORSEMENT & NBS    
	 AND PPR.COMPLETED_DATETIME BETWEEN  @FROM_DATETIME  AND @TO_DATETIME 
	 GROUP BY CONVERT(VARCHAR,MONTH(PPR.COMPLETED_DATETIME)) + '/' + CONVERT(VARCHAR,YEAR(PPR.COMPLETED_DATETIME)),MLM.SUSEP_LOB_CODE

) T


CREATE TABLE #TEMPCLM
 (
 SUSEP_LOB_CODE NVARCHAR(10),
 OUTSTANDING_CLAIM_RESERVE VARCHAR(50),
 EARNED_PREMIUM VARCHAR(50)
 )
INSERT INTO #TEMPCLM
(
	SUSEP_LOB_CODE,
	OUTSTANDING_CLAIM_RESERVE,
	EARNED_PREMIUM
)
SELECT
	T1.SUSEP_LOB_CODE,
	T1.OUTSTANDING_CLAIM_RESERVE,
	T1.EARNED_PREMIUM
FROM
(
	SELECT  
	 --CONVERT(VARCHAR,MONTH(CLM.FIRST_NOTICE_OF_LOSS)) + '/' + CONVERT(VARCHAR,YEAR(CLM.FIRST_NOTICE_OF_LOSS))  AS FIRST_NOTICE_OF_LOSS,--'Mês de referência',            
	  LOB.SUSEP_LOB_CODE AS SUSEP_LOB_CODE,--'Cod Ramo',               
	  dbo.fun_FormatCurrency(ABS(SUM(ACT.CLAIM_RESERVE_AMOUNT - (ACT.CLAIM_RI_RESERVE + ACT.CO_TOTAL_RESERVE_AMT))),2) AS OUTSTANDING_CLAIM_RESERVE,--'Vlr Sin Retido',               
	  dbo.fun_FormatCurrency(SUM(ISNULL(EAR.EarnedPremium,0)),2) AS EARNED_PREMIUM--'Vlr Prêmio Ganho',            
	  FROM CLM_CLAIM_INFO CLM WITH(NOLOCK)           
	  LEFT OUTER JOIN MNT_LOB_MASTER LOB WITH(NOLOCK) ON  LOB.LOB_ID=CAST(ISNULL(CLM.LOB_ID,0) AS INT)           
	  INNER JOIN CLM_ACTIVITY ACT WITH(NOLOCK) ON ACT.CLAIM_ID=CLM.CLAIM_ID  AND ACT.ACTIVITY_ID = (SELECT MAX(ACTIVITY_ID) FROM CLM_ACTIVITY CA WHERE ACT.CLAIM_ID = CA.CLAIM_ID  AND CA.ACTIVITY_STATUS = '11801')      
	  LEFT OUTER JOIN CLM_PARTIES PARTY WITH(NOLOCK) ON PARTY.CLAIM_ID=CLM.CLAIM_ID AND PARTY_TYPE_ID=618 AND SOURCE_PARTY_ID=1               
	  LEFT OUTER JOIN #TempEarnedPremium EAR  WITH(NOLOCK) ON EAR.CUSTOMER_ID=CLM.CUSTOMER_ID AND EAR.POLICY_ID=CLM.POLICY_ID AND EAR.POLICY_VERSION_ID=CLM.POLICY_VERSION_ID                         
	  WHERE  CLM.CLAIM_STATUS=11739          
	  AND CLM.FIRST_NOTICE_OF_LOSS BETWEEN @FROM_DATETIME  AND @TO_DATETIME              
	  AND ACT.IS_ACTIVE='Y'                
	  AND ISNULL(ACT.IS_VOIDED_REVERSED_ACTIVITY,'')=''           
	  GROUP BY LOB.SUSEP_LOB_CODE
) T1

UPDATE #TEMPPOL SET OUTSTANDING_RESERVE = OUTSTANDING_CLAIM_RESERVE,EARNED_PREMIUM_AMT = EARNED_PREMIUM FROM #TEMPCLM WHERE #TEMPPOL.SUSEP_LOB_CODE = #TEMPCLM.SUSEP_LOB_CODE 

SELECT 
FIRST_NOTICE_OF_LOSS AS  'Mês de referência',
T.SUSEP_LOB_CODE AS 'Cod Ramo',
OUTSTANDING_RESERVE AS 'Vlr Sin Retido',
EARNED_PREMIUM_AMT AS 'Vlr Prêmio Ganho',
dbo.fun_FormatCurrency(ABS(BROKER_COMMISION_AMT),2) AS 'Vlr Comissão',
dbo.fun_FormatCurrency(ABS(ENR_PROLABORE_AMT),2) AS 'Vlr Com de Agenciamento e Pro-labore'
FROM #TEMPPOL T 
LEFT OUTER JOIN #TEMPCLM TP ON T.SUSEP_LOB_CODE = TP.SUSEP_LOB_CODE 
ORDER BY T.SUSEP_LOB_CODE

DROP TABLE #TempEarnedPremium
DROP TABLE #TEMPCLM
DROP TABLE #TEMPPOL  
END         
    
    
   
   