CREATE PROC PROC_GET_POL_SUP_FORM_OLD_BLD 
@CUSTOMER_ID Int,
@POLICY_ID Int,
@POLICY_VERSION_ID int,
@LOCATION_ID int,
@PREMISES_ID int,
@OLDBLD_ID int
AS
SELECT CUSTOMER_ID,POLICY_ID,POLICY_VERSION_ID,LOCATION_ID,PREMISES_ID,OLDBLD_ID,WHN_WIRING_UPDT,WIRING_IN_CNDCT,FUSES_RPLCD,ALM_WIRING,WHN_PLBMG_MODRS,
TYP_WTR_PIPS,WHN_HEATNG_MODRS,TYP_SYS,TYP_FUEL,WHN_ROOF_REPRD,WHN_ROOF_REPLCD,ROOF_MTRL,SPF,ANY_ABSTS,ANY_FRB_ABSTS,ABSTS_ABT_DNE,'IS_ACTIVE' As IS_ACTIVE FROM POL_SUP_FORM_OLD_BLD
WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID And POLICY_VERSION_ID=@POLICY_VERSION_ID AND LOCATION_ID=@LOCATION_ID And PREMISES_ID=@PREMISES_ID AND
OLDBLD_ID=@OLDBLD_ID 