
GO

/****** Object:  StoredProcedure [dbo].[PROC_MIG_IL_INSERT_POLICY_COINSURER_DETAILS]    Script Date: 09/21/2011 12:41:19 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROC_MIG_IL_INSERT_POLICY_COINSURER_DETAILS]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[PROC_MIG_IL_INSERT_POLICY_COINSURER_DETAILS]
GO


GO

/****** Object:  StoredProcedure [dbo].[PROC_MIG_IL_INSERT_POLICY_COINSURER_DETAILS]    Script Date: 09/21/2011 12:41:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================  
-- Author:  <ADITYA GOEL>  
-- Create date: <2011-09-09>  
-- Description: <insert data in POL_CO_INSURANCE Table>  
-- =============================================  
CREATE PROCEDURE [dbo].[PROC_MIG_IL_INSERT_POLICY_COINSURER_DETAILS]   
  
--------------------------------- INPUT PARAMETER  
@IMPORT_REQUEST_ID  INT  
-------------------------------------------------  
    
AS  
BEGIN  
   
-------------------------------- DECLARATION PART  
----------------------------------------------------------------------------------------  
DECLARE @IMPORT_SERIAL_NO INT
DECLARE @COINSURANCE_ID INT
DECLARE @COMPANY_ID INT
DECLARE @CUSTOMER_ID INT
DECLARE @POLICY_ID INT
DECLARE @POLICY_VERSION_ID INT
DECLARE @APPLICANT_ID INT
DECLARE @CREATED_BY INT
DECLARE @MODIFIED_BY INT 


BEGIN 

-------------------------------- INSERT INTO POL_CO_INSURANCE 
INSERT INTO POL_CO_INSURANCE
([COINSURANCE_ID],
[COMPANY_ID],
[CUSTOMER_ID],
[POLICY_ID],
[POLICY_VERSION_ID],
[CO_INSURER_NAME],
[LEADER_FOLLOWER],
[COINSURANCE_PERCENT],
[COINSURANCE_FEE],
[BROKER_COMMISSION],
[TRANSACTION_ID],
[LEADER_POLICY_NUMBER],
[IS_ACTIVE],
[CREATED_BY],
[CREATED_DATETIME],
[MODIFIED_BY],
[LAST_UPDATED_DATETIME],
[BRANCH_COINSURANCE_ID],
[ENDORSEMENT_POLICY_NUMBER]
)
SELECT @COINSURANCE_ID,
@COMPANY_ID,
@CUSTOMER_ID,
@POLICY_ID,
@POLICY_VERSION_ID,
COINSURER_NAME,
LEADER_FOLLOWER,
COI_SHARE, --COINSURANCE_PERCENT
COINSURANCE_FEE,
NULL,  --BROKER_COMMISSION
TRANSACTION_ID,
LEADER_POLICY_NUMBER,
'Y', --IS_ACTIVE
@CREATED_BY,
GETDATE(), --CREATED_DATETIME
@MODIFIED_BY,
NULL, --LAST_UPDATED_DATETIME
NULL, --BRANCH_COINSURANCE_ID
ENDORSEMENT_NUMBER --ENDORSEMENT_POLICY_NUMBER


FROM MIG_IL_POLICY_COINSURER_DETAILS
WHERE      IMPORT_REQUEST_ID=@IMPORT_REQUEST_ID  
 AND       IMPORT_SERIAL_NO = @IMPORT_SERIAL_NO   
 AND       IS_PROCESSED  = 'N'   
 AND       IS_ACTIVE='Y'  

END
END


 

GO


