IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[PROC_POL_IL_UPDATE_POLICY_BOLETO_DATA]') AND type in (N'P', N'PC'))
DROP PROCEDURE [dbo].[PROC_POL_IL_UPDATE_POLICY_BOLETO_DATA]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

-- =============================================            
-- Created by:  <Pradeep Kr. Kushwaha>            
-- Create date: <15-11-2011>            
-- Description: <Update data in MIG IL boleto POLICY TABLE >            
-- DROP PROC [PROC_POL_IL_UPDATE_POLICY_BOLETO_DATA] 28033,338,4,NULL  ,null,'INSTALLMENT'   
-- =============================================                      
CREATE PROC [DBO].[PROC_POL_IL_UPDATE_POLICY_BOLETO_DATA]           
	@CUSTOMER_ID INT=NULL,    
	@POLICY_ID INT=NULL,     
	@POLICY_VERSION_ID INT=NULL,             
	@INSTALLEMT_ID INT=NULL,
	@CALLED_FROM NVARCHAR(50)=NULL
AS          
BEGIN    
	IF(@CALLED_FROM='POLICY')
	BEGIN
		UPDATE POL_CUSTOMER_POLICY_LIST SET IL_DOCUMENT_GENERATED=1 
		 WHERE  CUSTOMER_ID			=	@CUSTOMER_ID		AND 
				POLICY_ID			=	@POLICY_ID			AND 
				POLICY_VERSION_ID	=	@POLICY_VERSION_ID	 
	END
	ELSE
	BEGIN
		 UPDATE POL_IL_POLICY_BOLETO_DETAILS SET IS_BOLETO_GENERATED=1 ,BOLETO_GENERATED_DATE=GETDATE()
		 WHERE  CUSTOMER_ID			=	@CUSTOMER_ID		AND 
				POLICY_ID			=	@POLICY_ID			AND 
				POLICY_VERSION_ID	=	@POLICY_VERSION_ID	AND 
				INSTALLMENT_ID		=	@INSTALLEMT_ID	
			
	END
	 
	 
END

GO