  
CREATE PROC [dbo].[Proc_GetMaxPremisesLocationNum]   
 @CUSTOMER_ID  INT ,  
 @POLICY_ID INT,
 @POLICY_VERSION_ID INT,
 @LOCATION_NUMBER NUMERIC OUT  
AS                                
                                
BEGIN    

 SELECT  @LOCATION_NUMBER=ISNULL(MAX(LOCATION_ID),0)+1 FROM POL_BOP_PREMISESLOCATIONS  WITH (NOLOCK)  
 WHERE   
  CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID   
  AND POLICY_VERSION_ID=@POLICY_VERSION_ID 
 RETURN 1    
 
END  
  