CREATE PROC PROC_FETCH_POL_SUP_FORM_OLD_BLD  
@CUSTOMER_ID Int,  
@POLICY_ID Int,  
@POLICY_VERSION_ID int,  
@LOCATION_ID int,  
@PREMISES_ID int  
AS  
BEGIN  
IF NOT EXISTS(SELECT OLDBLD_ID FROM POL_SUP_FORM_OLD_BLD   
 WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID And   
 POLICY_VERSION_ID=@POLICY_VERSION_ID AND LOCATION_ID=@LOCATION_ID And PREMISES_ID=@PREMISES_ID)  
BEGIN  
SELECT -1 AS OLDBLD_ID    
END  
ELSE  
BEGIN  
SELECT ISNULL(OLDBLD_ID,0) AS OLDBLD_ID FROM POL_SUP_FORM_OLD_BLD   
 WHERE CUSTOMER_ID=@CUSTOMER_ID AND POLICY_ID=@POLICY_ID And POLICY_VERSION_ID=@POLICY_VERSION_ID   
 AND LOCATION_ID=@LOCATION_ID And PREMISES_ID=@PREMISES_ID  
END  
END