//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsWeb.Maintenance {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddMarineCargoSetAgents_aspx {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddMarineCargoSetAgents_aspx() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmsWeb.Maintenance.AddMarineCargoSetAgents.aspx", typeof(AddMarineCargoSetAgents_aspx).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string cmbCountry {
            get {
                return ResourceManager.GetString("cmbCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Address1.
        /// </summary>
        internal static string txtAddress1 {
            get {
                return ResourceManager.GetString("txtAddress1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Address2.
        /// </summary>
        internal static string txtAddress2 {
            get {
                return ResourceManager.GetString("txtAddress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settling Agent Code.
        /// </summary>
        internal static string txtAgentCode {
            get {
                return ResourceManager.GetString("txtAgentCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settling Agent Id.
        /// </summary>
        internal static string txtAgentId {
            get {
                return ResourceManager.GetString("txtAgentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent Name.
        /// </summary>
        internal static string txtAgentName {
            get {
                return ResourceManager.GetString("txtAgentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string txtCity {
            get {
                return ResourceManager.GetString("txtCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey Cod.
        /// </summary>
        internal static string txtSurveyCode {
            get {
                return ResourceManager.GetString("txtSurveyCode", resourceCulture);
            }
        }
    }
}
