CREATE PROCEDURE [dbo].[Proc_Get_MIG_IL_VEHICLE_DETAIL]
	@UPLOAD_FILE_ID [int] = null
WITH EXECUTE AS CALLER
AS
SET FMTONLY OFF;
SELECT [UPLOAD_FILE_ID]
      ,[UPLOAD_SERIAL_NO]
      ,[VEHICLE_REGISTRATION_NO]
      ,[VEHICLE_MAKE]
      ,[VEHICLE_MODEL]
      ,[VEHICLE_CLASS]
      ,[MODEL_DESCRIPTION]
      ,[BUS_CAPTAIN]
      ,[IMPORT_ACTION]
      ,[FileName]
  FROM [MIG_IL_VEHICLE_DETAIL]
where UPLOAD_FILE_ID=@UPLOAD_FILE_ID


