CREATE PROCEDURE [dbo].[PROC_MIG_IL_VEHICLE_Error_Satus]
	@UPLOAD_FILE_ID [int],
	@HASERROR [varchar](50)
WITH EXECUTE AS CALLER
AS
BEGIN                    
UPDATE MNT_VEHICLELISTINGUPLOAD SET [STATUS]='COMP',IS_PROCESSED='Y',HasError=@HASERROR WHERE UploadFileId=@UPLOAD_FILE_ID
END


