CREATE PROCEDURE [dbo].[Proc_Clm_Claimrecovery]
	@AccidentClaimId [int],
	@PolicyId [int],
	@ClaimentId [int],
	@UserName [nvarchar](50),
	@Address [nvarchar](max),
	@RecoveryReason [nvarchar](500),
	@CurrCode [nchar](10),
	@ClaimID [int],
	@ExchangeRate [numeric](18, 0),
	@LocalCurrAmt [numeric](18, 0),
	@Status [int],
	@PaymentDetails [nvarchar](200),
	@CreatedBy [nvarchar](25),
	@ModifiedBy [nvarchar](25)
WITH EXECUTE AS CALLER
AS
INSERT INTO clm_claimrecovery 
				([AccidentClaimId],
				 [PolicyId],
				 [ClaimentId],
                 [RecoverFrom],   
                 [Address1],   
                 [recoveryreason],   
                 --[currcode],  
                 [ClaimID],   
                 --[exchangerate],   
                 --[localcurramt],   
                 --[status],   
                 --[paymentdetails],   
                 --[isactive],   
                 [createddate],   
                 [createdby],   
                 [modifiedby],   
                 [modifieddate])   
    VALUES      (@AccidentClaimId,
				 @PolicyId,
				 @ClaimentId,
				 @UserName,   
                 @Address,   
                 @RecoveryReason,   
                 --@CurrCode,  
                 @ClaimID,   
                 --@ExchangeRate,   
                 --@LocalCurrAmt,   
                 --@Status,   
                 --@PaymentDetails,   
                 --'Y',   
                 Getdate(),   
                 @CreatedBy,   
                 @ModifiedBy,   
                 Getdate())


