//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCAS.Web.Objects.Resources.ClaimUploadProcessing {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TacFileUploadEditor {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TacFileUploadEditor() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MCAS.Web.Objects.Resources.ClaimUploadProcessing.TacFileUploadEditor", typeof(TacFileUploadEditor).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus.
        /// </summary>
        public static string Bus {
            get {
                return ResourceManager.GetString("Bus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Claim File To Upload.
        /// </summary>
        public static string DownloadClaimFileToUpload {
            get {
                return ResourceManager.GetString("DownloadClaimFileToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Log.
        /// </summary>
        public static string FailedLog {
            get {
                return ResourceManager.GetString("FailedLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Records.
        /// </summary>
        public static string FailedRecords {
            get {
                return ResourceManager.GetString("FailedRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG File.
        /// </summary>
        public static string LOGFile {
            get {
                return ResourceManager.GetString("LOGFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Name.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization Type.
        /// </summary>
        public static string OrganizationType {
            get {
                return ResourceManager.GetString("OrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rep.
        /// </summary>
        public static string Rep {
            get {
                return ResourceManager.GetString("Rep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReUpload.
        /// </summary>
        public static string ReUpload {
            get {
                return ResourceManager.GetString("ReUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled Start Date &amp; Time is required..
        /// </summary>
        public static string RFVDateTime {
            get {
                return ResourceManager.GetString("RFVDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAC_ACC_REP File is required..
        /// </summary>
        public static string RFVTAC_ACC_REP {
            get {
                return ResourceManager.GetString("RFVTAC_ACC_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAC_IP_BUS File is required..
        /// </summary>
        public static string RFVTAC_IP_BUS {
            get {
                return ResourceManager.GetString("RFVTAC_IP_BUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAC_IP File is required..
        /// </summary>
        public static string RFVTAC_IPFile {
            get {
                return ResourceManager.GetString("RFVTAC_IPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Start Date &amp; Time.
        /// </summary>
        public static string ScheduleStartDateTime {
            get {
                return ResourceManager.GetString("ScheduleStartDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File To Upload(TAC_ACC_REP).
        /// </summary>
        public static string SelectFileToUpload_TAC_ACC_REP {
            get {
                return ResourceManager.GetString("SelectFileToUpload_TAC_ACC_REP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File To Upload(TAC_IP).
        /// </summary>
        public static string SelectFileToUpload_TAC_IP {
            get {
                return ResourceManager.GetString("SelectFileToUpload_TAC_IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File To Upload(TAC_IP_BUS).
        /// </summary>
        public static string SelectFileToUpload_TAC_IP_BUS {
            get {
                return ResourceManager.GetString("SelectFileToUpload_TAC_IP_BUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry!! You dont have permission for this screen.
        /// </summary>
        public static string SorryYoudonthavepermissionforthisscreen {
            get {
                return ResourceManager.GetString("SorryYoudonthavepermissionforthisscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Records.
        /// </summary>
        public static string SuccessRecords {
            get {
                return ResourceManager.GetString("SuccessRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAC File Upload.
        /// </summary>
        public static string TACFileUpload {
            get {
                return ResourceManager.GetString("TACFileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAC Upload.
        /// </summary>
        public static string TACUpload {
            get {
                return ResourceManager.GetString("TACUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Records.
        /// </summary>
        public static string TotalRecords {
            get {
                return ResourceManager.GetString("TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Date &amp; Time.
        /// </summary>
        public static string UploadedDateTime {
            get {
                return ResourceManager.GetString("UploadedDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload From Date.
        /// </summary>
        public static string UploadFromDate {
            get {
                return ResourceManager.GetString("UploadFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Reference Number.
        /// </summary>
        public static string UploadReferenceNumber {
            get {
                return ResourceManager.GetString("UploadReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Ref No.
        /// </summary>
        public static string UploadRefNo {
            get {
                return ResourceManager.GetString("UploadRefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Status.
        /// </summary>
        public static string UploadStatus {
            get {
                return ResourceManager.GetString("UploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload To Date.
        /// </summary>
        public static string UploadToDate {
            get {
                return ResourceManager.GetString("UploadToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View TAC File Upload Status.
        /// </summary>
        public static string ViewTACFileUploadStatus {
            get {
                return ResourceManager.GetString("ViewTACFileUploadStatus", resourceCulture);
            }
        }
    }
}
