IF  EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'[dbo].[FK_ACT_POLICY_REIN_INSTALLMENT_DETAILS_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]') AND parent_object_id = OBJECT_ID(N'[dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS]'))
ALTER TABLE [dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS] DROP CONSTRAINT [FK_ACT_POLICY_REIN_INSTALLMENT_DETAILS_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]
GO


/****** Object:  Table [dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS]    Script Date: 02/04/2012 17:07:04 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS]') AND type in (N'U'))
DROP TABLE [dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS]
GO


/****** Object:  Table [dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS]    Script Date: 02/04/2012 17:07:05 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS](
	[IDEN_ROW_ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_ID] [int] NOT NULL,
	[POLICY_ID] [int] NOT NULL,
	[POLICY_VERSION_ID] [smallint] NOT NULL,
	[REIN_COMPANY_ID] [int] NULL,
	[CONTRACT_NUMBER] [nvarchar](100) NULL,
	[INSTALLMENT_NO] [int] NOT NULL,
	[INSTALLMENT_AMOUNT] [decimal](25, 2) NULL,
	[INTEREST_AMOUNT] [decimal](25, 2) NULL,
	[FEE] [decimal](25, 2) NULL,
	[TAXES] [decimal](25, 2) NULL,
	[TOTAL] [decimal](25, 2) NULL,
	[INSTALLMENT_EFFECTIVE_DATE] [datetime] NULL,
	[RELEASED_STATUS] [char](1) NULL,
	[PAYMENT_MODE] [int] NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[PAID_AMOUNT] [decimal](18, 2) NOT NULL,
	[RECEIVED_AMOUNT] [decimal](25, 8) NULL,
	[RECEIVED_DATE] [datetime] NULL,
	[INSTALLMENT_EXPIRE_DATE] [datetime] NULL,
	[ACC_CO_DISCOUNT] [decimal](9, 2) NULL,
	[IS_COMMISSION_PROCESS] [varchar](2) NULL,
	[IS_PAID_TO_PAGNET] [varchar](2) NULL,
	[PAGNET_DATE] [datetime] NULL,
	[REIN_INSTALLMENT_NO] [varchar](100) NULL,
 CONSTRAINT [PK_ACT_POLICY_REIN_INSTALLMENT_DETAILS_IDEN_ROW_ID_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID_REIN_INSTALLMENT_NO] PRIMARY KEY NONCLUSTERED 
(
	[IDEN_ROW_ID] ASC,
	[CUSTOMER_ID] ASC,
	[POLICY_ID] ASC,
	[POLICY_VERSION_ID] ASC,
	[INSTALLMENT_NO] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_ACT_POLICY_REIN_INSTALLMENT_DETAILS_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID] FOREIGN KEY([CUSTOMER_ID], [POLICY_ID], [POLICY_VERSION_ID])
REFERENCES [dbo].[POL_CUSTOMER_POLICY_LIST] ([CUSTOMER_ID], [POLICY_ID], [POLICY_VERSION_ID])
GO

ALTER TABLE [dbo].[ACT_POLICY_REIN_INSTALLMENT_DETAILS] CHECK CONSTRAINT [FK_ACT_POLICY_REIN_INSTALLMENT_DETAILS_CUSTOMER_ID_POLICY_ID_POLICY_VERSION_ID]
GO


