
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--drop table APP_DWELLINGS_INFO
CREATE TABLE [dbo].[APP_DWELLINGS_INFO](
	[CUSTOMER_ID] [int] NOT NULL,
	[APP_ID] [int] NOT NULL,
	[APP_VERSION_ID] [smallint] NOT NULL,
	[DWELLING_ID] [smallint] NOT NULL,
	[DWELLING_NUMBER] [int] NULL,
	[LOCATION_ID] [smallint] NULL,
	[SUB_LOC_ID] [smallint] NULL,
	[YEAR_BUILT] [smallint] NULL,
	[PURCHASE_YEAR] [smallint] NULL,
	[PURCHASE_PRICE] [decimal](18, 2) NULL,
	[MARKET_VALUE] [decimal](18, 2) NULL,
	[REPLACEMENT_COST] [decimal](18, 2) NULL,
	[BUILDING_TYPE] [int] NULL,
	[OCCUPANCY] [int] NULL,
	[NEED_OF_UNITS] [smallint] NULL,
	[USAGE] [nvarchar](50) NULL,
	[NEIGHBOURS_VISIBLE] [nchar](1) NULL,
	[OCCUPIED_DAILY] [nchar](1) NULL,
	[NO_WEEKS_RENTED] [smallint] NULL,
	[IS_ACTIVE] [nchar](1) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[COMMENTDWELLINGOWNED] [nvarchar](100) NULL,
	[REPAIR_COST] [decimal](10, 0) NULL,
	[DETACHED_OTHER_STRUCTURES] [nvarchar](5) NULL,
	[MONTHS_RENTED] [int] NULL,
	[REPLACEMENTCOST_COVA] [nvarchar](20) NULL,
	[PREMIER_DISCOUNT] [int] NOT NULL,
 CONSTRAINT [PK_APP_DWELLINGS_INFO_CUSTOMER_ID_APP_ID_VERSION_ID_DWELING_ID] PRIMARY KEY CLUSTERED 
(
	[CUSTOMER_ID] ASC,
	[APP_ID] ASC,
	[APP_VERSION_ID] ASC,
	[DWELLING_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO




