/****** Object:  Table [dbo].[APP_GEN_PRO_LOCATIONS]    Script Date: 02/08/2012 16:22:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_GEN_PRO_LOCATIONS](
	[CUSTOMER_ID] [int] NOT NULL,
	[APP_ID] [int] NOT NULL,
	[APP_VERSION_ID] [smallint] NOT NULL,
	[LOB_ID] [smallint] NOT NULL,
	[LOCATION_ID] [smallint] NOT NULL,
	[LOC_NUM] [int] NULL,
	[IS_PRIMARY] [nchar](1) NULL,
	[LOC_ADD1] [nvarchar](75) NULL,
	[LOC_ADD2] [nvarchar](75) NULL,
	[LOC_CITY] [nvarchar](75) NULL,
	[LOC_COUNTY] [nvarchar](75) NULL,
	[LOC_STATE] [nvarchar](5) NULL,
	[LOC_ZIP] [nvarchar](11) NULL,
	[LOC_COUNTRY] [nvarchar](5) NULL,
	[IS_ACTIVE] [nchar](1) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[LOC_TERRITORY] [nvarchar](5) NULL,
	[LOCATION_TYPE] [int] NULL,
 CONSTRAINT [PK_APP_GEN_PRO_LOCATIONS_CUSTOMER_ID_APP_ID_VERSION_ID_LOB_ID_LOCATION_ID] PRIMARY KEY NONCLUSTERED 
(
	[CUSTOMER_ID] ASC,
	[APP_ID] ASC,
	[APP_VERSION_ID] ASC,
	[LOB_ID] ASC,
	[LOCATION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO


