
/****** Object:  Table [dbo].[APP_LOCATIONS]    Script Date: 02/08/2012 16:20:36 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO
--drop table APP_LOCATIONS
CREATE TABLE [dbo].[APP_LOCATIONS](
	[CUSTOMER_ID] [int] NOT NULL,
	[APP_ID] [int] NOT NULL,
	[APP_VERSION_ID] [smallint] NOT NULL,
	[LOCATION_ID] [smallint] NOT NULL,
	[LOC_NUM] [int] NULL,
	[IS_PRIMARY] [nchar](1) NULL,
	[LOC_ADD1] [nvarchar](75) NULL,
	[LOC_ADD2] [nvarchar](75) NULL,
	[LOC_CITY] [nvarchar](75) NULL,
	[LOC_COUNTY] [nvarchar](75) NULL,
	[LOC_STATE] [nvarchar](5) NULL,
	[LOC_ZIP] [nvarchar](11) NULL,
	[LOC_COUNTRY] [nvarchar](5) NULL,
	[PHONE_NUMBER] [nvarchar](20) NULL,
	[FAX_NUMBER] [nvarchar](20) NULL,
	[DEDUCTIBLE] [nvarchar](20) NULL,
	[NAMED_PERILL] [int] NULL,
	[DESCRIPTION] [varchar](1000) NULL,
	[IS_ACTIVE] [nchar](1) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL,
	[LOC_TERRITORY] [nvarchar](5) NULL,
	[LOCATION_TYPE] [int] NULL,
	[RENTED_WEEKLY] [varchar](10) NULL,
	[WEEKS_RENTED] [varchar](10) NULL,
	[LOSSREPORT_ORDER] [int] NULL,
	[LOSSREPORT_DATETIME] [datetime] NULL,
	[REPORT_STATUS] [char](1) NULL,
 CONSTRAINT [PK_APP_LOCATIONS_CUSTOMER_ID_APP_ID_VERSION_ID_LOCATION_ID] PRIMARY KEY NONCLUSTERED 
(
	[CUSTOMER_ID] ASC,
	[APP_ID] ASC,
	[APP_VERSION_ID] ASC,
	[LOCATION_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON, FILLFACTOR = 90) ON [PRIMARY]
) ON [PRIMARY]

GO





