USE [EBX-ADV-DEV-SINGAPORE]
GO

/****** Object:  Table [dbo].[POL_MARINECARGO_VOYAGE_INFORMATION]    Script Date: 03/21/2012 14:17:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[POL_MARINECARGO_VOYAGE_INFORMATION](
	[VOYAGE_INFO_ID] [int] NOT NULL,
	[RISK_ID] [int] NULL,
	[CUSTOMER_ID] [int] NULL,
	[POLICY_ID] [int] NULL,
	[POLICY_VERSION_ID] [int] NULL,
	[VOYAGE_FROM] [int] NULL,
	[VOYAGE_TO] [int] NULL,
	[THENCE_TO] [int] NULL,
	[QUANTITY_DESCRIPTION] [nvarchar](2000) NULL,
	[IS_ACTIVE] [nchar](2) NULL,
	[CREATED_BY] [int] NULL,
	[CREATED_DATETIME] [datetime] NULL,
	[MODIFIED_BY] [int] NULL,
	[LAST_UPDATED_DATETIME] [datetime] NULL
) ON [PRIMARY]

GO


