go

INSERT INTO POL_RISK_DETAIL
SELECT 38,'0531','RISK.INSURED_VEH_NUMBER',
'POL_VEHICLES RISK WITH(NOLOCK) LEFT OUTER JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID',
'VEHICLE_ID'

go

ALTER TABLE POL_REINSURANCE_INFO ADD COMM_AMOUNT DECIMAL(18,2)
ALTER TABLE POL_REINSURANCE_INFO ADD REIN_PREMIUM DECIMAL(18,2)

