--SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_ID = 1058
--SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID = 1058
--SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID = 1126
--SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_ID = 1126
--SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID = 1452
--SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_ID = 1452
--SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID = 1453
--SELECT * FROM MNT_LOOKUP_VALUES WHERE LOOKUP_ID = 1453

GO
ALTER TABLE MNT_LOOKUP_TABLES ALTER COLUMN LOOKUP_NAME NVARCHAR(80)

GO
DECLARE @LOOKUP_ID INT
SELECT @LOOKUP_ID = MAX(LOOKUP_ID) + 1 from MNT_LOOKUP_TABLES 

DECLARE @LOOKUP_UNIQUE_ID INT
SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID = @LOOKUP_ID)
BEGIN
INSERT INTO MNT_LOOKUP_TABLES (LOOKUP_ID,LOOKUP_NAME,LOOKUP_DESC,LOOKUP_TYPE,LOOKUP_TBL_EDIT,LOOKUP_CODE_WIDTH,LOOKUP_DISPLAY_FORMAT,LOOKUP_DESC_WIDTH,LOOKUP_LEVEL) VALUES
(@LOOKUP_ID,'CLASSUNCLASS','UNCLASS/CLASS VALUES','H','Y',4,'N',255,'D')
END

INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,1,1,'Class',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,2,0,'Unclass',1,'Y','','','','')

GO


DECLARE @LOOKUP_ID INT
SELECT @LOOKUP_ID = MAX(LOOKUP_ID) + 1 from MNT_LOOKUP_TABLES 
DECLARE @LOOKUP_UNIQUE_ID INT

IF NOT EXISTS(SELECT * FROM MNT_LOOKUP_TABLES WHERE LOOKUP_ID = @LOOKUP_ID)
BEGIN
INSERT INTO MNT_LOOKUP_TABLES (LOOKUP_ID,LOOKUP_NAME,LOOKUP_DESC,LOOKUP_TYPE,LOOKUP_TBL_EDIT,LOOKUP_CODE_WIDTH,LOOKUP_DISPLAY_FORMAT,LOOKUP_DESC_WIDTH,LOOKUP_LEVEL) VALUES
(@LOOKUP_ID,'TypeOfVessel','Type of Vessel','H','Y',4,'N',255,'D')
END

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,1,1,'Barge',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,2,2,'Bulk and/or Combination',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,3,3,'Containership',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,4,4,'Conventional',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,5,5,'Vessel',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,6,6,'Landing Craft',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,7,7,'OHGC',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,8,8,'TUG',1,'Y','','','','')

SELECT @LOOKUP_UNIQUE_ID = MAX(LOOKUP_UNIQUE_ID) + 1 from MNT_LOOKUP_VALUES WHERE LOOKUP_UNIQUE_ID < 114301
INSERT INTO MNT_LOOKUP_VALUES (LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC,LOOKUP_SYS_DEF,IS_ACTIVE,LAST_UPDATED_DATETIME,LOOKUP_FRAME_OR_MASONRY,Type,NSS_VALUE_CODE)
VALUES
(@LOOKUP_UNIQUE_ID,@LOOKUP_ID,9,9,'Vehicle Carrier',1,'Y','','','','')

GO
















