
--For Activities
--11109 Corporates
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Supply of Semi Conductor Chips',11109,'Y')
GO

INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Manufacture of Textile Products',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Wholesale Service for Good',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'IT Services',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Construction of Roadworks',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Housing Developer',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Accounting Services',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Legal',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Frame Manufacturers',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Ship Building',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Freighforwarding Agent',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Courier Services',11109,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Others',11109,'Y')
GO

---for Individual 
--11110

INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Accountant',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Businessman',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Director',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Lawyer',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Salesman',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Architect',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Conductor',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Journalists',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Teacher',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Doctor',11110,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Dentist',11110,'Y')
GO

--For Government
--14725
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Minstry of Health',14725,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Minstry of Manpower',14725,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'LTA',14725,'Y')
GO
INSERT INTO [dbo].[MNT_ACTIVITY_MASTER]    ([ACTIVITY_ID],[ACTIVITY_DESC],[TYPE],[IS_ACTIVE])VALUES  
((SELECT MAX(ACTIVITY_ID)+1 FROM MNT_ACTIVITY_MASTER),'Traffic Police',14725,'Y')
GO

--BUSINESS TYPES
DELETE FROM MNT_BUSINESS_TYPES 

INSERT INTO MNT_BUSINESS_TYPES VALUES('Manufacturing')
INSERT INTO MNT_BUSINESS_TYPES VALUES('IT Services')
INSERT INTO MNT_BUSINESS_TYPES VALUES('Contstruction of rails and roadworks')
INSERT INTO MNT_BUSINESS_TYPES VALUES('Professional Services')
INSERT INTO MNT_BUSINESS_TYPES VALUES('Logistics')
INSERT INTO MNT_BUSINESS_TYPES VALUES('Ship Building')

--for User Types
UPDATE  MNT_USER_TYPES SET IS_ACTIVE='N' where USER_TYPE_DESC not in(
'ACCOUNT EXECUTIVE',
'UNDERWRITER',
'SERVICER',
'DIRECTOR',
'UNDERWRITER MANAGER',
'SUPPORT',
'CLAIMS MANAGER',
'CLAIMS ADJUSTER',
'SYSTEM ADMIN',
'USER',
'AGENCY MANAGER',
'AGENT',
'MARKETING',
'OTHERS'
)
--NEW USER TYPES TO BE ADDED FROM SCREEN MARKETING,OTHERS AND PRODUCER \

