IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[MNT_VESSEL_MASTER]') AND type in (N'U'))
DROP TABLE [dbo].[MNT_VESSEL_MASTER]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[MNT_VESSEL_MASTER](
	[VESSEL_ID] [int] NOT NULL,
	[VESSEL_NAME] [VARCHAR](40) NOT NULL,
	[GRT] [varchar](10) NOT NULL,
	[IMO] [varchar](10) NULL,
	[NRT] [VARCHAR](10) NULL,
	[FLAG] [VARCHAR](20) NULL,
	[CLASSIFICATION] [VARCHAR] (10) NULL,
	[YEAR_BUILT] [INT] NOT NULL,
	[LINER] [INT] NOT NULL,
	[TYPE_OF_VESSEL] [INT] NOT NULL,
	[CLASS_TYPE] [INT] NOT NULL,
	[CLASS] [VARCHAR] (5) NOT NULL,
	[DAY_PRIOR_TO_SAILING_DATE] [VARCHAR] (10) NULL,
	[TOTAL_SHIPMENT_DAY] [VARCHAR] (10) NULL,
	[IS_ACTIVE] [NCHAR] (2) NULL
 CONSTRAINT [PK_MNT_VESSEL_MASTER_VESSEL_ID] PRIMARY KEY CLUSTERED 
(
	[VESSEL_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO
