
INSERT INTO POL_RISK_DETAIL 
VALUES(1,0531,'RISK.DWELLING_ID','POL_DWELLINGS_INFO RISK WITH(NOLOCK) LEFT OUTER JOIN POL_LOCATIONS PL WITH(NOLOCK) ON PL.CUSTOMER_ID = RISK.CUSTOMER_ID AND PL.POLICY_ID = RISK.POLICY_ID AND PL.POLICY_VERSION_ID = RISK.POLICY_VERSION_ID and PL.LOCATION_ID = RISK.LOCATION_ID','DWELLING_ID')


