


insert into MNT_LOOKUP_TABLES(LOOKUP_ID, LOOKUP_NAME, LOOKUP_DESC,LOOKUP_CODE_WIDTH, LOOKUP_DESC_WIDTH ) values((select max(LOOKUP_ID)+ 1 from mnt_lookup_tables),'SNat','Singapore Nationality',5,255)

insert into MNT_LOOKUP_VALUES(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC, IS_ACTIVE)
values((select max(LOOKUP_UNIQUE_ID)+ 1 from MNT_LOOKUP_VALUES),1450,1,'SGPRN','Singaporean','Y')


insert into MNT_LOOKUP_VALUES(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC, IS_ACTIVE)
values((select max(LOOKUP_UNIQUE_ID)+ 1 from MNT_LOOKUP_VALUES),1450,2,'SGPR','Singapore PR','Y')

insert into MNT_LOOKUP_VALUES(LOOKUP_UNIQUE_ID,LOOKUP_ID,LOOKUP_VALUE_ID,LOOKUP_VALUE_CODE,LOOKUP_VALUE_DESC, IS_ACTIVE)
values((select max(LOOKUP_UNIQUE_ID)+ 1 from MNT_LOOKUP_VALUES),1450,3,'SGOTH','Others','Y')


