update mnt_agency_list set TERMINATION_DATE = DATEADD(YEAR,+5,GETDATE()) where AGENCY_ID != 32814
update mnt_agency_list set TERMINATION_DATE_RENEW = DATEADD(YEAR,+5,GETDATE()) where AGENCY_ID != 32814
DELETE FROM MNT_AGENCY_STATE_LOB_ASSOC
